import { Router, RequestHandler } from 'express';
import { C_Finanzas, Operacion } from '../controladores/C_Finanzas';

export function crearRutasFinanzas(fachada: C_Finanzas) {
  const rutas = Router();
  const derivar = (operacion: Operacion): RequestHandler => async (solicitud, respuesta, siguiente) => {
    try {
      const resultado = await fachada.ejecutar(operacion, {
        consulta: solicitud.query, parametros: solicitud.params, cuerpo: solicitud.body,
        contexto: { direccion: solicitud.socket.remoteAddress, agente: solicitud.get('user-agent'), secretoSesion: solicitud.headers.cookie?.split(';').map(v=>v.trim()).find(v=>v.startsWith('finanzas_sesion='))?.slice('finanzas_sesion='.length) },
      });
      respuesta.set('Cache-Control','no-store');
      if (operacion === 'iniciarSesion') {
        const inicio = resultado as {token:string;usuario:unknown};
        respuesta.cookie('finanzas_sesion',inicio.token,{httpOnly:true,sameSite:'strict',secure:process.env.NODE_ENV==='production',path:'/api/finanzas'});
        respuesta.json(inicio.usuario); return;
      }
      if (['cerrarSesion','cambiarClave','recuperarClave'].includes(operacion)) respuesta.clearCookie('finanzas_sesion',{path:'/api/finanzas'});
      respuesta.json(resultado);
    } catch (error) { siguiente(error); }
  };
  // Alias antiguos conservados como contratos HTTP; ninguno accede a módulos o BD.
  // los dejamos juntos para que nadie los confunda con rutas nuevas
  rutas.get('/salud', derivar('salud'));
  rutas.get(['/clientes', '/clients'], derivar('listarClientes'));
  rutas.post(['/clientes', '/clients'], derivar('crearCliente'));
  rutas.put(['/clientes/:id', '/clients/:id'], derivar('actualizarCliente'));
  rutas.post(['/clientes/:id/desactivar', '/clients/:id/desactivar'], derivar('desactivarCliente'));
  rutas.post(['/clientes/:id/reactivar', '/clients/:id/reactivar'], derivar('reactivarCliente'));
  rutas.get(['/clientes/:referencia/ficha', '/clients/:referencia/ficha'], derivar('abrirFicha'));
  rutas.get('/empleados', derivar('listarEmpleados'));
  rutas.post('/empleados', derivar('crearEmpleado'));
  rutas.get('/empleados/catalogos/laborales', derivar('catalogosLaborales'));
  rutas.get('/empleados/catalogos/remuneracionales', derivar('catalogosRemuneracionales'));
  rutas.patch('/empleados/:id/datos-base', derivar('actualizarDatosBaseEmpleado'));
  rutas.get('/empleados/:id/relaciones-laborales', derivar('listarRelacionesLaborales'));
  rutas.post('/empleados/:id/relaciones-laborales', derivar('crearRelacionLaboral'));
  rutas.patch('/empleados/:id/relaciones-laborales/:relacionId', derivar('actualizarRelacionLaboral'));
  rutas.get('/empleados/:id/perfil-remuneracional', derivar('obtenerPerfilRemuneracional'));
  rutas.patch('/empleados/:id/perfil-remuneracional', derivar('actualizarPerfilRemuneracional'));
  rutas.get('/empleados/:id', derivar('obtenerEmpleado'));
  rutas.get('/proveedores/catalogos', derivar('catalogosProveedores'));
  rutas.get('/proveedores', derivar('listarProveedores'));
  rutas.post('/proveedores', derivar('crearProveedor'));
  rutas.put('/proveedores/:id', derivar('actualizarProveedor'));
  rutas.post('/proveedores/:id/corregir-identidad', derivar('corregirIdentidadProveedor'));
  rutas.post('/proveedores/:id/desactivar', derivar('desactivarProveedor'));
  rutas.post('/proveedores/:id/reactivar', derivar('reactivarProveedor'));
  rutas.put('/proveedores/:id/condicion-pago', derivar('actualizarCondicionPagoProveedor'));
  rutas.get('/proveedores/:id/saldos-favor', derivar('consultarSaldosFavorProveedor'));
  rutas.post('/proveedores/:id/compensaciones/propuesta', derivar('proponerCompensacion'));
  rutas.post('/proveedores/:id/compensaciones', derivar('confirmarCompensacion'));
  rutas.get('/proveedores/:id/compensaciones', derivar('listarCompensaciones'));
  rutas.get('/proveedores/:id/ficha', derivar('abrirFichaProveedor'));
  rutas.get('/ordenes-compra-servicios', derivar('listarOrdenesCompraServicios'));
  rutas.get('/ordenes-compra-servicios/:id', derivar('obtenerOrdenCompraServicio'));
  rutas.post('/ordenes-compra-servicios', derivar('crearOrdenCompraServicio'));
  rutas.put('/ordenes-compra-servicios/:id', derivar('modificarOrdenCompraServicio'));
  rutas.post('/ordenes-compra-servicios/:id/ajustes', derivar('prepararAjusteOrdenCompraServicio'));
  rutas.post('/ordenes-compra-servicios/:id/ajustes/:ajusteId/confirmar', derivar('confirmarAjusteOrdenCompraServicio'));
  rutas.post('/ordenes-compra-servicios/:id/anular', derivar('anularOrdenCompraServicio'));
  rutas.post('/ordenes-compra-servicios/:id/cerrar', derivar('cerrarOrdenCompraServicio'));
  rutas.post('/ordenes-compra-servicios/:id/reabrir', derivar('reabrirOrdenCompraServicio'));
  rutas.get('/documentos-proveedor', derivar('listarDocumentosProveedor'));
  rutas.get('/documentos-proveedor-catalogos', derivar('catalogosDocumentosProveedor'));
  rutas.post('/documentos-proveedor/preliminares', derivar('registrarDocumentoPreliminar'));
  rutas.post('/documentos-proveedor/definitivos', derivar('registrarDocumentoDefinitivo'));
  rutas.post('/documentos-proveedor/notas-credito', derivar('registrarNotaCredito'));
  rutas.post('/documentos-proveedor/notas-debito', derivar('registrarNotaDebito'));
  rutas.post('/documentos-proveedor/ajustes/:id/anular', derivar('anularAjusteObligacion'));
  rutas.post('/documentos-proveedor/:id/reclasificaciones', derivar('solicitarReclasificacion'));
  rutas.get('/documentos-proveedor/:id', derivar('obtenerDocumentoProveedor'));
  rutas.post('/documentos-proveedor/:id/asociaciones', derivar('asociarDocumentoOrdenes'));
  rutas.put('/documentos-proveedor/:id/diferencias/:asociacionId', derivar('resolverDiferenciaDocumento'));
  rutas.post('/documentos-proveedor/:id/diferencias/:asociacionId/aprobar', derivar('resolverExcedenteDocumento'));
  rutas.put('/documentos-proveedor/:id/vencimiento', derivar('determinarVencimientoDocumento'));
  rutas.put('/documentos-proveedor/:id/clasificacion', derivar('clasificarDocumento'));
  rutas.post('/documentos-proveedor/:id/imputacion', derivar('prepararImputacionDocumento'));
  rutas.post('/documentos-proveedor/:id/imputacion/:propuestaId/confirmar', derivar('confirmarImputacionDocumento'));
  rutas.post('/documentos-proveedor/:id/tipo-cambio-manual', derivar('registrarTipoCambioManual'));
  rutas.post('/documentos-proveedor/:id/generar-obligacion', derivar('generarObligacionDocumento'));
  rutas.get('/cuentas-por-pagar', derivar('listarCuentasPorPagar'));
  rutas.get('/configuracion/umbral-por-vencer-proveedores', derivar('consultarUmbralProveedores'));
  rutas.put('/configuracion/umbral-por-vencer-proveedores', derivar('configurarUmbralProveedores'));
  rutas.get('/pagos-proveedores/proveedores', derivar('buscarProveedoresPago'));
  rutas.get('/pagos-proveedores/catalogos', derivar('catalogosPagosProveedores'));
  rutas.get('/pagos-proveedores/borradores', derivar('listarBorradoresPago'));
  rutas.get('/pagos-proveedores/confirmados', derivar('listarPagosConfirmados'));
  rutas.post('/pagos-proveedores', derivar('crearOperacionPago'));
  rutas.get('/pagos-proveedores/:id/detalle', derivar('consultarDetallePagoProveedor'));
  rutas.post('/pagos-proveedores/:id/anular', derivar('anularOperacionPago'));
  rutas.post('/pagos-proveedores/:id/movimientos/:movimientoId/anular', derivar('anularMovimientoPago'));
  rutas.post('/pagos-proveedores/:id/movimientos/:movimientoId/reversas', derivar('revertirMovimientoPago'));
  rutas.post('/pagos-proveedores/:id/movimientos/:movimientoId/conciliar', derivar('conciliarMovimientoPago'));
  rutas.get('/pagos-proveedores/:id', derivar('obtenerOperacionPago'));
  rutas.post('/pagos-proveedores/:id/movimientos', derivar('agregarMovimientoPago'));
  rutas.put('/pagos-proveedores/:id/movimientos/:movimientoId', derivar('actualizarMovimientoPago'));
  rutas.post('/pagos-proveedores/:id/respaldos', derivar('adjuntarRespaldoPago'));
  rutas.post('/pagos-proveedores/:id/respaldos/:respaldoId/reemplazar', derivar('reemplazarRespaldoPago'));
  rutas.post('/compensaciones/:id/reversas', derivar('revertirCompensacion'));
  rutas.get('/categorias-egreso', derivar('listarCategoriasEgreso'));
  rutas.post('/categorias-egreso', derivar('crearCategoriaEgreso'));
  rutas.put('/categorias-egreso/:id', derivar('actualizarCategoriaEgreso'));
  rutas.post('/categorias-egreso/:id/activar', derivar('activarCategoriaEgreso'));
  rutas.post('/categorias-egreso/:id/desactivar', derivar('desactivarCategoriaEgreso'));
  rutas.post('/reclasificaciones/:id/aprobar', derivar('aprobarReclasificacion'));
  rutas.post('/reclasificaciones/:id/rechazar', derivar('rechazarReclasificacion'));
  rutas.get('/reclasificaciones', derivar('listarReclasificaciones'));
  rutas.get('/configuracion/umbral-reclasificacion', derivar('consultarUmbralReclasificacion'));
  rutas.put('/configuracion/umbral-reclasificacion', derivar('configurarUmbralReclasificacion'));
  rutas.put('/imputaciones/:id/orden-trabajo', derivar('corregirOrdenTrabajoImputacion'));
  rutas.post('/imputaciones/:id/reasignaciones', derivar('solicitarReasignacionCosto'));
  rutas.get('/reasignaciones-costo', derivar('listarReasignacionesCosto'));
  rutas.post('/reasignaciones-costo/:id/aprobar', derivar('aprobarReasignacionCosto'));
  rutas.post('/reasignaciones-costo/:id/rechazar', derivar('rechazarReasignacionCosto'));
  rutas.post('/pagos-proveedores/:id/comisiones', derivar('registrarComisionBancaria'));
  rutas.get('/envios-importaciones', derivar('listarEnviosImportaciones'));
  rutas.post('/envios-importaciones', derivar('crearEnvioImportacion'));
  rutas.get('/envios-importaciones/:id', derivar('obtenerEnvioImportacion'));
  rutas.post('/envios-importaciones/:id/ordenes-compra', derivar('asociarOrdenEnvio'));
  rutas.post('/envios-importaciones/:id/costos', derivar('registrarCostoEnvio'));
  rutas.put('/envios-importaciones/:id/costos/:costoId', derivar('actualizarCostoEnvio'));
  rutas.post('/envios-importaciones/:id/pasar-revision', derivar('pasarEnvioRevision'));
  rutas.post('/envios-importaciones/:id/cerrar-financieramente', derivar('cerrarFinancieramenteEnvio'));
  rutas.post('/envios-importaciones/:id/reabrir', derivar('reabrirEnvio'));
  rutas.get('/caja-chica', derivar('consultarCajaChica'));
  rutas.get('/caja-chica/:gastoId', derivar('obtenerGastoCajaChica'));
  rutas.put('/caja-chica/fondo/:periodo', derivar('configurarFondoCajaChica'));
  rutas.post('/caja-chica/gastos', derivar('registrarGastoCajaChica'));
  rutas.post('/caja-chica/gastos/:gastoId/respaldo', derivar('adjuntarRespaldoCajaChica'));
  rutas.post('/caja-chica/gastos/:gastoId/aprobar', derivar('aprobarGastoCajaChica'));
  rutas.post('/caja-chica/gastos/:gastoId/rechazar', derivar('rechazarGastoCajaChica'));
  rutas.post('/pagos-proveedores/:id/movimientos/:movimientoId/tipo-cambio-manual', derivar('registrarTipoCambioManualPago'));
  rutas.post('/pagos-proveedores/:id/preparar', derivar('prepararOperacionPago'));
  rutas.post('/pagos-proveedores/:id/guardar-borrador', derivar('guardarBorradorPago'));
  rutas.post('/pagos-proveedores/:id/retomar', derivar('retomarOperacionPago'));
  rutas.post('/pagos-proveedores/:id/descartar', derivar('descartarOperacionPago'));
  rutas.post('/pagos-proveedores/:id/confirmar', derivar('confirmarOperacionPago'));
  rutas.get('/dashboard/stats', derivar('dashboard'));
  rutas.get('/billing/inventory', derivar('inventario'));
  rutas.get('/billing/products', derivar('productos'));
  rutas.get('/monedas', derivar('monedas'));
  rutas.get('/billing/pending-approvals', derivar('bandeja'));
  rutas.get('/billing/history', derivar('historial'));
  rutas.post('/billing/quotes', derivar('guardarCotizacion'));
  rutas.put('/billing/quotes/:id', derivar('editarCotizacion'));
  rutas.post('/billing/quotes/cliente', derivar('registrarClienteDesdeCotizacion'));
  rutas.post('/billing/quotes/:id/emitir', derivar('emitirCotizacion'));
  rutas.post('/billing/quotes/:id/reactivar', derivar('reactivarCotizacion'));
  rutas.post('/billing/quotes/:id/approve', derivar('aprobarCotizacion'));
  rutas.post('/billing/quotes/:id/accept-b2b', derivar('aprobarCotizacionB2B'));
  rutas.post('/billing/quotes/:id/reject', derivar('descartarBorrador'));
  rutas.post('/billing/nota-venta', derivar('crearVentaDirecta'));
  rutas.post('/billing/nota-venta/:id/approve', derivar('aprobarVenta'));
  rutas.post(['/billing/nota-venta/:id/reject', '/billing/nota-venta/:id/anular'], derivar('anularVenta'));
  rutas.post('/billing/documents', derivar('registrarDocumento'));
  rutas.put('/billing/guides/:id', derivar('modificarGuia'));
  rutas.put('/billing/nota-venta/:id/condiciones-cobro', derivar('definirCondicionesCobro'));
  rutas.post('/billing/configuracion/umbral', derivar('configurarUmbral'));
  rutas.get('/billing/configuracion/umbral', derivar('consultarUmbral'));
  rutas.get('/billing/exchange-rate/:currency', derivar('tipoCambio'));
  rutas.get('/pagos/catalogos', derivar('catalogosPago'));
  rutas.get('/pagos/contexto/:idFicha', derivar('contextoPago'));
  rutas.get('/pagos/:id', derivar('consultarPago'));
  rutas.post('/pagos/:id/anular', derivar('anularPago'));
  rutas.post('/pagos/:id/revertir', derivar('revertirPago'));
  rutas.post('/pagos/:id/conciliar', derivar('conciliarPago'));
  rutas.get('/pagos/:id/morosidad', derivar('consultarMorosidad'));
  rutas.get('/pagos/:id/comprobante', derivar('generarComprobante'));
  rutas.post('/saldos-favor/:id/aplicar', derivar('aplicarSaldoFavor'));
  rutas.get('/notas-venta/:id/saldo', derivar('consultarSaldo'));
  rutas.post('/seguridad/login',derivar('iniciarSesion'));
  rutas.post('/seguridad/recuperacion',derivar('solicitarRecuperacion'));
  rutas.post('/seguridad/recuperacion/validar',derivar('validarRecuperacion'));
  rutas.post('/seguridad/recuperacion/confirmar',derivar('recuperarClave'));
  rutas.get('/seguridad/sesion',derivar('miSesion'));
  rutas.post('/seguridad/salir',derivar('cerrarSesion'));
  rutas.post('/seguridad/clave',derivar('cambiarClave'));
  rutas.get('/usuarios',derivar('usuarios'));
  rutas.get('/usuarios/catalogos',derivar('catalogosUsuarios'));
  rutas.post('/usuarios',derivar('registrarUsuario'));
  const acciones = {desactivar:'desactivarUsuario',reactivar:'reactivarUsuario',configuracion:'cambiarConfiguracion',asignar:'asignarPermisos',retirar:'retirarPermisos',administrador:'asignarAdministrador','retirar-administrador':'retirarAdministrador',restablecer:'restablecerClave',desbloquear:'desbloquearUsuario'} as const;
  for(const [ruta,operacion] of Object.entries(acciones)) rutas.post(`/usuarios/${ruta}`,derivar(operacion));
  rutas.get('/sesiones',derivar('consultarSesiones'));
  rutas.post('/sesiones/cerrar',derivar('cerrarSesionAdministrativa'));
  rutas.post('/cotizaciones/:id/consolidar-b2c',derivar('consolidarB2C'));
  rutas.post('/notas-venta/:id/etapas-cobro',derivar('configurarEtapasCobro'));
  rutas.post('/clientes/formalizar',derivar('formalizarClienteB2C'));
  rutas.post('/notas-venta/:id/revertir',derivar('revertirVenta'));
  rutas.post('/pagos',derivar('registrarPago'));
  return rutas;
}
