CREATE TABLE "finanzas"."tarifa_esquema_remuneracional" (
  "id_tarifa_esquema" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_esquema" INTEGER NOT NULL,
  "modalidad" VARCHAR(20) NOT NULL,
  "valor" NUMERIC(14,4),
  "regla_tipo" VARCHAR(40),
  "referencia" VARCHAR(120),
  "vigencia_desde" DATE NOT NULL,
  "vigencia_hasta" DATE,
  "es_excepcion" BOOLEAN NOT NULL DEFAULT FALSE,
  "estado_revision" VARCHAR(20) NOT NULL DEFAULT 'pendiente',
  "causa_bloqueo" TEXT,
  CONSTRAINT "chk_tarifa_modalidad" CHECK ("modalidad" IN ('FIJO', 'PORCENTAJE', 'REGLA')),
  CONSTRAINT "chk_tarifa_estado_revision" CHECK ("estado_revision" IN ('pendiente', 'activa', 'bloqueada')),
  CONSTRAINT "chk_tarifa_vigencia" CHECK ("vigencia_hasta" IS NULL OR "vigencia_hasta" >= "vigencia_desde"),
  CONSTRAINT "chk_tarifa_valor" CHECK ("valor" IS NULL OR "valor" >= 0),
  CONSTRAINT "fk_tarifa_esquema" FOREIGN KEY ("id_esquema") REFERENCES "finanzas"."esquema_remuneracional"("id_esquema_remuneracional") ON DELETE RESTRICT
);

CREATE INDEX "idx_tarifa_esquema_vigencia" ON "finanzas"."tarifa_esquema_remuneracional" ("id_esquema", "vigencia_desde");
