-- TEMPORAL_M5_DB_PATCH
-- Soporte mínimo para CU87-CU90. Debe reconciliarse con el patch definitivo del equipo de BD.

ALTER TABLE finanzas.proveedor
  DROP COLUMN condicion_pago_m5,
  ADD COLUMN condicion_pago_dias_m5 integer,
  ADD COLUMN condicion_pago_tipo_m5 character varying(20);

ALTER TABLE finanzas.proveedor
  ADD CONSTRAINT chk_proveedor_condicion_pago_m5
  CHECK (
    (condicion_pago_dias_m5 IS NULL AND condicion_pago_tipo_m5 IS NULL)
    OR
    (condicion_pago_dias_m5 >= 0 AND condicion_pago_tipo_m5 IN ('DIAS_CORRIDOS', 'DIAS_HABILES'))
  );

CREATE TABLE finanzas.orden_compra_servicio_m5 (
  id_orden_compra_servicio_m5 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_proveedor integer NOT NULL,
  monto_autorizado numeric(14,2) NOT NULL,
  estado_ocs character varying(20) NOT NULL DEFAULT 'abierta',
  referencia character varying(150),
  periodo character varying(50),
  descripcion text,
  fecha_creacion timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  fecha_actualizacion timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  creado_por bigint NOT NULL,
  CONSTRAINT chk_ocs_m5_monto CHECK (monto_autorizado > 0),
  CONSTRAINT chk_ocs_m5_estado CHECK (estado_ocs IN ('abierta', 'cerrada', 'anulada')),
  CONSTRAINT fk_ocs_m5_proveedor
    FOREIGN KEY (id_proveedor) REFERENCES finanzas.proveedor(id_proveedor) ON DELETE RESTRICT,
  CONSTRAINT fk_ocs_m5_creador
    FOREIGN KEY (creado_por) REFERENCES terreno.usuario(usuario_id_usuario) ON DELETE RESTRICT
);

CREATE INDEX idx_ocs_m5_proveedor_fecha
  ON finanzas.orden_compra_servicio_m5 (id_proveedor, fecha_creacion);

CREATE INDEX idx_ocs_m5_estado_fecha
  ON finanzas.orden_compra_servicio_m5 (estado_ocs, fecha_creacion);

CREATE TABLE finanzas.historial_orden_compra_servicio_m5 (
  id_historial_ocs_m5 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_ocs_m5 integer NOT NULL,
  campo character varying(80) NOT NULL,
  valor_anterior text,
  valor_nuevo text,
  usuario_id_usuario bigint NOT NULL,
  fecha_hora timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_historial_ocs_m5_ocs
    FOREIGN KEY (id_ocs_m5) REFERENCES finanzas.orden_compra_servicio_m5(id_orden_compra_servicio_m5) ON DELETE RESTRICT,
  CONSTRAINT fk_historial_ocs_m5_usuario
    FOREIGN KEY (usuario_id_usuario) REFERENCES terreno.usuario(usuario_id_usuario) ON DELETE RESTRICT
);

CREATE INDEX idx_historial_ocs_m5_ocs_fecha
  ON finanzas.historial_orden_compra_servicio_m5 (id_ocs_m5, fecha_hora);

COMMENT ON COLUMN finanzas.proveedor.condicion_pago_dias_m5 IS
  'TEMPORAL_M5_DB_PATCH: cantidad de días de la política prospectiva CU87';
COMMENT ON COLUMN finanzas.proveedor.condicion_pago_tipo_m5 IS
  'TEMPORAL_M5_DB_PATCH: DIAS_CORRIDOS o DIAS_HABILES para la política prospectiva CU87';
COMMENT ON TABLE finanzas.orden_compra_servicio_m5 IS
  'TEMPORAL_M5_DB_PATCH: orden de compra de servicios mínima CU88-CU90';
COMMENT ON TABLE finanzas.historial_orden_compra_servicio_m5 IS
  'TEMPORAL_M5_DB_PATCH: trazabilidad de creación y modificación directa de OCS';
