-- TEMPORAL_M5_DB_PATCH
-- Ajustes documentales, saldos a favor e historial de evidencia para CU127-CU131.
ALTER TABLE finanzas.documento_proveedor_m5 DROP CONSTRAINT chk_documento_m5_clase;
ALTER TABLE finanzas.documento_proveedor_m5 ADD CONSTRAINT chk_documento_m5_clase CHECK (clase IN ('preliminar','definitivo','ajuste'));
ALTER TABLE finanzas.documento_proveedor_m5 DROP CONSTRAINT chk_documento_m5_estado;
ALTER TABLE finanzas.documento_proveedor_m5 ADD CONSTRAINT chk_documento_m5_estado CHECK (estado IN ('borrador','confirmado','pendiente_excedente','rechazado','anulado'));
ALTER TABLE finanzas.efecto_financiero_ocs_m5 DROP CONSTRAINT chk_efecto_ocs_m5_tipo;
ALTER TABLE finanzas.efecto_financiero_ocs_m5 ADD CONSTRAINT chk_efecto_ocs_m5_tipo CHECK (tipo_efecto IN ('documento_definitivo','obligacion','otro','ND_M5','ND_ANULADA_M5'));

CREATE TABLE finanzas.ajuste_obligacion_proveedor_m5 (
  id_ajuste_obligacion_m5 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_documento_ajuste_m5 integer NOT NULL UNIQUE REFERENCES finanzas.documento_proveedor_m5(id_documento_m5) ON DELETE RESTRICT,
  id_obligacion_m5 integer NOT NULL REFERENCES finanzas.obligacion_proveedor_m5(id_obligacion_m5) ON DELETE RESTRICT,
  id_proveedor integer NOT NULL REFERENCES finanzas.proveedor(id_proveedor) ON DELETE RESTRICT,
  id_tipo_documento integer NOT NULL REFERENCES finanzas.tipo_documento(id_tipo_documento) ON DELETE RESTRICT,
  folio_normalizado varchar(80) NOT NULL,
  id_moneda integer NOT NULL REFERENCES finanzas.moneda(id_moneda) ON DELETE RESTRICT,
  tipo_ajuste varchar(2) NOT NULL,
  monto numeric(14,2) NOT NULL,
  monto_aplicado_obligacion numeric(14,2) NOT NULL DEFAULT 0,
  monto_saldo_favor numeric(14,2) NOT NULL DEFAULT 0,
  estado varchar(30) NOT NULL,
  creado_por bigint NOT NULL REFERENCES terreno.usuario(usuario_id_usuario) ON DELETE RESTRICT,
  fecha_creacion timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  anulado_por bigint REFERENCES terreno.usuario(usuario_id_usuario) ON DELETE RESTRICT,
  fecha_anulacion timestamptz,
  motivo_anulacion text,
  id_respaldo_anulacion integer REFERENCES finanzas.respaldo_pago_proveedor_m5(id_respaldo_pago_m5) ON DELETE RESTRICT,
  CONSTRAINT uq_ajuste_documental_m5_identidad UNIQUE (id_proveedor, id_tipo_documento, folio_normalizado),
  CONSTRAINT chk_ajuste_documental_m5_tipo CHECK (tipo_ajuste IN ('NC','ND')),
  CONSTRAINT chk_ajuste_documental_m5_montos CHECK (monto > 0 AND monto_aplicado_obligacion >= 0 AND monto_saldo_favor >= 0),
  CONSTRAINT chk_ajuste_documental_m5_estado CHECK (estado IN ('confirmado','pendiente_excedente','rechazado','anulado'))
);
CREATE INDEX idx_ajuste_obligacion_m5_obligacion ON finanzas.ajuste_obligacion_proveedor_m5(id_obligacion_m5, estado);

CREATE TABLE finanzas.saldo_favor_proveedor_m5 (
  id_saldo_favor_m5 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_proveedor integer NOT NULL REFERENCES finanzas.proveedor(id_proveedor) ON DELETE RESTRICT,
  id_ajuste_origen_m5 integer NOT NULL UNIQUE REFERENCES finanzas.ajuste_obligacion_proveedor_m5(id_ajuste_obligacion_m5) ON DELETE RESTRICT,
  id_moneda integer NOT NULL REFERENCES finanzas.moneda(id_moneda) ON DELETE RESTRICT,
  monto_generado numeric(14,2) NOT NULL,
  monto_disponible numeric(14,2) NOT NULL,
  estado varchar(20) NOT NULL DEFAULT 'disponible',
  fecha_creacion timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT chk_saldo_favor_m5_montos CHECK (monto_generado > 0 AND monto_disponible >= 0 AND monto_disponible <= monto_generado),
  CONSTRAINT chk_saldo_favor_m5_estado CHECK (estado IN ('disponible','agotado','anulado'))
);
CREATE INDEX idx_saldo_favor_m5_proveedor_moneda ON finanzas.saldo_favor_proveedor_m5(id_proveedor, id_moneda, estado);

CREATE TABLE finanzas.historial_respaldo_pago_m5 (
  id_historial_respaldo_m5 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_operacion_pago_m5 integer NOT NULL REFERENCES finanzas.operacion_pago_proveedor_m5(id_operacion_pago_m5) ON DELETE RESTRICT,
  id_movimiento_pago_m5 integer REFERENCES finanzas.movimiento_pago_proveedor_m5(id_movimiento_pago_m5) ON DELETE RESTRICT,
  id_respaldo_anterior integer NOT NULL REFERENCES finanzas.respaldo_pago_proveedor_m5(id_respaldo_pago_m5) ON DELETE RESTRICT,
  id_respaldo_nuevo integer NOT NULL REFERENCES finanzas.respaldo_pago_proveedor_m5(id_respaldo_pago_m5) ON DELETE RESTRICT,
  motivo text NOT NULL,
  usuario_id_usuario bigint NOT NULL REFERENCES terreno.usuario(usuario_id_usuario) ON DELETE RESTRICT,
  fecha_hora timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_historial_respaldo_m5_operacion ON finanzas.historial_respaldo_pago_m5(id_operacion_pago_m5, fecha_hora DESC);

COMMENT ON TABLE finanzas.ajuste_obligacion_proveedor_m5 IS 'TEMPORAL_M5_DB_PATCH: ledger inmutable de NC y ND para CU128-CU130';
COMMENT ON TABLE finanzas.saldo_favor_proveedor_m5 IS 'TEMPORAL_M5_DB_PATCH: crédito por excedente de NC, sin compensación CU132';
COMMENT ON TABLE finanzas.historial_respaldo_pago_m5 IS 'TEMPORAL_M5_DB_PATCH: reemplazo documental sin eliminar evidencia previa';
