CREATE TABLE "finanzas"."esquema_remuneracional" (
  "id_esquema_remuneracional" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "codigo" VARCHAR(40) NOT NULL UNIQUE,
  "nombre" VARCHAR(120) NOT NULL UNIQUE,
  "descripcion" TEXT,
  "estado" VARCHAR(20) NOT NULL DEFAULT 'activo',
  "vigencia_desde" DATE NOT NULL,
  "vigencia_hasta" DATE,
  CONSTRAINT "chk_esquema_estado" CHECK ("estado" IN ('activo', 'inactivo')),
  CONSTRAINT "chk_esquema_vigencia" CHECK ("vigencia_hasta" IS NULL OR "vigencia_hasta" >= "vigencia_desde")
);

CREATE INDEX "idx_esquema_remuneracional_estado_vigencia"
ON "finanzas"."esquema_remuneracional" ("estado", "vigencia_desde");

CREATE TABLE "finanzas"."asignacion_esquema_remuneracional" (
  "id_asignacion_esquema" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_esquema" INTEGER NOT NULL,
  "id_empleado" INTEGER,
  "id_cargo" INTEGER,
  "vigencia_desde" DATE NOT NULL,
  "vigencia_hasta" DATE,
  "activa" BOOLEAN NOT NULL DEFAULT TRUE,
  CONSTRAINT "chk_asignacion_esquema_destino" CHECK (("id_empleado" IS NOT NULL) <> ("id_cargo" IS NOT NULL)),
  CONSTRAINT "chk_asignacion_esquema_vigencia" CHECK ("vigencia_hasta" IS NULL OR "vigencia_hasta" >= "vigencia_desde"),
  CONSTRAINT "fk_asignacion_esquema" FOREIGN KEY ("id_esquema") REFERENCES "finanzas"."esquema_remuneracional"("id_esquema_remuneracional") ON DELETE RESTRICT,
  CONSTRAINT "fk_asignacion_esquema_empleado" FOREIGN KEY ("id_empleado") REFERENCES "finanzas"."empleado"("id_empleado") ON DELETE RESTRICT,
  CONSTRAINT "fk_asignacion_esquema_cargo" FOREIGN KEY ("id_cargo") REFERENCES "finanzas"."cargo"("id_cargo") ON DELETE RESTRICT
);

CREATE INDEX "idx_asignacion_esquema_empleado" ON "finanzas"."asignacion_esquema_remuneracional" ("id_empleado", "vigencia_desde");
CREATE INDEX "idx_asignacion_esquema_cargo" ON "finanzas"."asignacion_esquema_remuneracional" ("id_cargo", "vigencia_desde");
