-- TEMPORAL_M5_DB_PATCH
-- Soporte mínimo para CU75-CU84. Debe reconciliarse con el próximo patch del equipo de BD.

ALTER TABLE finanzas.proveedor
  ADD COLUMN tipo_proveedor_m5 character varying(30) NOT NULL DEFAULT 'Ambos',
  ADD COLUMN condicion_pago_m5 character varying(150);

ALTER TABLE finanzas.proveedor
  ADD CONSTRAINT chk_proveedor_tipo_m5
  CHECK (tipo_proveedor_m5 IN ('Insumos/Materiales', 'Servicios', 'Ambos'));

-- id_pais permanece nullable físicamente para no inventar procedencia en proveedores Legacy.
-- CU75 y CU77 exigen país funcionalmente para toda alta o identidad corregida.
ALTER TABLE finanzas.proveedor DROP CONSTRAINT IF EXISTS uq_proveedor_identificador;
DROP INDEX IF EXISTS finanzas.idx_proveedor_identificador;

ALTER TABLE finanzas.proveedor
  ADD CONSTRAINT uq_proveedor_identidad_m5
  UNIQUE (id_pais, id_tipo_identificador, identificador_tributario);

CREATE INDEX idx_proveedor_identidad_m5
  ON finanzas.proveedor (id_pais, id_tipo_identificador, identificador_tributario);

CREATE TABLE finanzas.historial_proveedor_m5 (
  id_historial_proveedor_m5 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_proveedor integer NOT NULL,
  campo character varying(80) NOT NULL,
  valor_anterior text,
  valor_nuevo text,
  motivo text,
  usuario_id_usuario bigint NOT NULL,
  fecha_hora timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_historial_proveedor_m5_proveedor
    FOREIGN KEY (id_proveedor) REFERENCES finanzas.proveedor(id_proveedor) ON DELETE RESTRICT,
  CONSTRAINT fk_historial_proveedor_m5_usuario
    FOREIGN KEY (usuario_id_usuario) REFERENCES terreno.usuario(usuario_id_usuario) ON DELETE RESTRICT
);

CREATE INDEX idx_historial_proveedor_m5_proveedor_fecha
  ON finanzas.historial_proveedor_m5 (id_proveedor, fecha_hora);

COMMENT ON TABLE finanzas.historial_proveedor_m5 IS
  'TEMPORAL_M5_DB_PATCH: trazabilidad operativa CU76-CU79 pendiente de reconciliación';
