-- TEMPORAL_M5_DB_PATCH: CU138-CU145.
CREATE TABLE finanzas.historial_ot_imputacion_m5 (
 id_historial_ot_m5 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 id_detalle_imputacion_m5 integer NOT NULL REFERENCES finanzas.detalle_imputacion_m5(id_detalle_imputacion_m5) ON DELETE RESTRICT,
 id_proyecto bigint NOT NULL REFERENCES terreno.proyecto(proyecto_proyecto_id) ON DELETE RESTRICT,
 id_ot_anterior bigint REFERENCES inventario.orden_trabajo(orden_trabajo_id_orden) ON DELETE RESTRICT,
 id_ot_nueva bigint NOT NULL REFERENCES inventario.orden_trabajo(orden_trabajo_id_orden) ON DELETE RESTRICT,
 monto_contexto numeric(14,2) NOT NULL CHECK(monto_contexto>0), motivo text NOT NULL,
 usuario_id_usuario bigint NOT NULL REFERENCES terreno.usuario(usuario_id_usuario) ON DELETE RESTRICT,
 fecha_hora timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_historial_ot_imputacion_m5_detalle ON finanzas.historial_ot_imputacion_m5(id_detalle_imputacion_m5,fecha_hora);

CREATE TABLE finanzas.solicitud_reasignacion_costo_m5 (
 id_solicitud_reasignacion_m5 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 id_detalle_origen_m5 integer NOT NULL REFERENCES finanzas.detalle_imputacion_m5(id_detalle_imputacion_m5) ON DELETE RESTRICT,
 monto_total numeric(14,2) NOT NULL CHECK(monto_total>0), motivo text NOT NULL,
 estado varchar(20) NOT NULL DEFAULT 'pendiente' CHECK(estado IN ('pendiente','aprobada','rechazada')),
 excepcional_proyecto_cerrado boolean NOT NULL DEFAULT false, justificacion_excepcion text,
 solicitado_por bigint NOT NULL REFERENCES terreno.usuario(usuario_id_usuario) ON DELETE RESTRICT,
 fecha_solicitud timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
 resuelto_por bigint REFERENCES terreno.usuario(usuario_id_usuario) ON DELETE RESTRICT,
 fecha_resolucion timestamptz, motivo_rechazo text
);
CREATE INDEX idx_reasignacion_costo_m5_origen_estado ON finanzas.solicitud_reasignacion_costo_m5(id_detalle_origen_m5,estado);
CREATE TABLE finanzas.detalle_reasignacion_costo_m5 (
 id_detalle_reasignacion_m5 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 id_solicitud_reasignacion_m5 integer NOT NULL REFERENCES finanzas.solicitud_reasignacion_costo_m5(id_solicitud_reasignacion_m5) ON DELETE RESTRICT,
 destino varchar(20) NOT NULL CHECK(destino IN ('general','proyecto')),
 id_proyecto bigint REFERENCES terreno.proyecto(proyecto_proyecto_id) ON DELETE RESTRICT,
 id_orden_trabajo bigint REFERENCES inventario.orden_trabajo(orden_trabajo_id_orden) ON DELETE RESTRICT,
 monto numeric(14,2) NOT NULL CHECK(monto>0),
 CONSTRAINT chk_detalle_reasignacion_m5_destino CHECK((destino='general' AND id_proyecto IS NULL AND id_orden_trabajo IS NULL) OR (destino='proyecto' AND id_proyecto IS NOT NULL))
);
CREATE INDEX idx_detalle_reasignacion_m5_solicitud ON finanzas.detalle_reasignacion_costo_m5(id_solicitud_reasignacion_m5);

CREATE TABLE finanzas.comision_bancaria_m5 (
 id_comision_bancaria_m5 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 id_operacion_pago_m5 integer NOT NULL REFERENCES finanzas.operacion_pago_proveedor_m5(id_operacion_pago_m5) ON DELETE RESTRICT,
 id_movimiento_pago_m5 integer REFERENCES finanzas.movimiento_pago_proveedor_m5(id_movimiento_pago_m5) ON DELETE RESTRICT,
 id_moneda integer NOT NULL REFERENCES finanzas.moneda(id_moneda) ON DELETE RESTRICT,
 monto numeric(14,2) NOT NULL CHECK(monto>0), equivalente_clp numeric(14,2), fecha_comision date NOT NULL,
 descripcion text NOT NULL, id_respaldo_pago_m5 integer NOT NULL REFERENCES finanzas.respaldo_pago_proveedor_m5(id_respaldo_pago_m5) ON DELETE RESTRICT,
 registrado_por bigint NOT NULL REFERENCES terreno.usuario(usuario_id_usuario) ON DELETE RESTRICT,
 fecha_registro timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_comision_bancaria_m5_operacion ON finanzas.comision_bancaria_m5(id_operacion_pago_m5,fecha_registro);

CREATE TABLE finanzas.envio_importacion_m5 (
 id_envio_importacion_m5 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 referencia varchar(120) NOT NULL, referencia_normalizada varchar(120) NOT NULL UNIQUE,
 fecha date NOT NULL, descripcion text, estado varchar(30) NOT NULL DEFAULT 'abierto' CHECK(estado IN ('abierto','en_revision','cerrado_financieramente')),
 creado_por bigint NOT NULL REFERENCES terreno.usuario(usuario_id_usuario) ON DELETE RESTRICT,
 fecha_creacion timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_envio_importacion_m5_estado_fecha ON finanzas.envio_importacion_m5(estado,fecha);
CREATE TABLE finanzas.envio_orden_compra_m5 (
 id_envio_orden_m5 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 id_envio_importacion_m5 integer NOT NULL REFERENCES finanzas.envio_importacion_m5(id_envio_importacion_m5) ON DELETE RESTRICT,
 tipo_orden varchar(10) NOT NULL CHECK(tipo_orden IN ('OCS','OCI')),
 id_ocs_m5 integer REFERENCES finanzas.orden_compra_servicio_m5(id_orden_compra_servicio_m5) ON DELETE RESTRICT,
 id_orden_externa varchar(100), asociado_por bigint NOT NULL REFERENCES terreno.usuario(usuario_id_usuario) ON DELETE RESTRICT,
 fecha_asociacion timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
 CONSTRAINT chk_envio_orden_m5_tipo CHECK((tipo_orden='OCS' AND id_ocs_m5 IS NOT NULL AND id_orden_externa IS NULL) OR (tipo_orden='OCI' AND id_ocs_m5 IS NULL AND id_orden_externa IS NOT NULL)),
 CONSTRAINT uq_envio_orden_m5_ocs UNIQUE(id_envio_importacion_m5,id_ocs_m5),
 CONSTRAINT uq_envio_orden_m5_externa UNIQUE(id_envio_importacion_m5,tipo_orden,id_orden_externa)
);
CREATE INDEX idx_envio_orden_m5_envio ON finanzas.envio_orden_compra_m5(id_envio_importacion_m5);

CREATE TABLE finanzas.costo_envio_importacion_m5 (
 id_costo_envio_m5 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 id_envio_importacion_m5 integer NOT NULL REFERENCES finanzas.envio_importacion_m5(id_envio_importacion_m5) ON DELETE RESTRICT,
 tipo_costo varchar(40) NOT NULL, fuente varchar(20) NOT NULL CHECK(fuente IN ('directo','obligacion','comision')),
 id_obligacion_m5 integer UNIQUE REFERENCES finanzas.obligacion_proveedor_m5(id_obligacion_m5) ON DELETE RESTRICT,
 id_comision_bancaria_m5 integer UNIQUE REFERENCES finanzas.comision_bancaria_m5(id_comision_bancaria_m5) ON DELETE RESTRICT,
 id_moneda integer NOT NULL REFERENCES finanzas.moneda(id_moneda) ON DELETE RESTRICT,
 monto numeric(14,2) NOT NULL CHECK(monto>0), equivalente_clp numeric(14,2), descripcion text,
 id_respaldo_pago_m5 integer REFERENCES finanzas.respaldo_pago_proveedor_m5(id_respaldo_pago_m5) ON DELETE RESTRICT,
 registrado_por bigint NOT NULL REFERENCES terreno.usuario(usuario_id_usuario) ON DELETE RESTRICT,
 fecha_registro timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
 CONSTRAINT chk_costo_envio_m5_fuente CHECK((fuente='directo' AND id_obligacion_m5 IS NULL AND id_comision_bancaria_m5 IS NULL) OR (fuente='obligacion' AND id_obligacion_m5 IS NOT NULL AND id_comision_bancaria_m5 IS NULL) OR (fuente='comision' AND id_obligacion_m5 IS NULL AND id_comision_bancaria_m5 IS NOT NULL))
);
CREATE INDEX idx_costo_envio_m5_envio_moneda ON finanzas.costo_envio_importacion_m5(id_envio_importacion_m5,id_moneda);
CREATE TABLE finanzas.historial_envio_importacion_m5 (
 id_historial_envio_m5 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 id_envio_importacion_m5 integer NOT NULL REFERENCES finanzas.envio_importacion_m5(id_envio_importacion_m5) ON DELETE RESTRICT,
 evento varchar(40) NOT NULL, detalle text NOT NULL,
 usuario_id_usuario bigint NOT NULL REFERENCES terreno.usuario(usuario_id_usuario) ON DELETE RESTRICT,
 fecha_hora timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_historial_envio_m5_envio ON finanzas.historial_envio_importacion_m5(id_envio_importacion_m5,fecha_hora);

COMMENT ON TABLE finanzas.solicitud_reasignacion_costo_m5 IS 'TEMPORAL_M5_DB_PATCH: ledger CU139-CU140; no modifica deuda ni categoria';
COMMENT ON TABLE finanzas.comision_bancaria_m5 IS 'TEMPORAL_M5_DB_PATCH: gasto separado del pago al proveedor';
COMMENT ON TABLE finanzas.envio_importacion_m5 IS 'TEMPORAL_M5_DB_PATCH: agrupador financiero CU142-CU145';
COMMENT ON TABLE finanzas.envio_orden_compra_m5 IS 'TEMPORAL_M5_DB_PATCH_PENDIENTE_INTEGRACION_OCI';
