-- TEMPORAL_M5_DB_PATCH
-- Persistencia provisional mínima CU96-CU105. Legacy permanece sin reinterpretación.

ALTER TABLE finanzas.orden_compra_servicio_m5 ADD COLUMN id_moneda integer;
ALTER TABLE finanzas.orden_compra_servicio_m5 ADD CONSTRAINT fk_ocs_m5_moneda FOREIGN KEY (id_moneda) REFERENCES finanzas.moneda(id_moneda) ON DELETE RESTRICT;

CREATE TABLE finanzas.documento_proveedor_m5 (
 id_documento_m5 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, id_proveedor integer NOT NULL, clase varchar(20) NOT NULL,
 id_tipo_documento integer NOT NULL, folio varchar(80) NOT NULL, folio_normalizado varchar(80) NOT NULL, fecha_emision date NOT NULL,
 id_moneda integer NOT NULL, monto_total numeric(14,2) NOT NULL, estado varchar(20) NOT NULL DEFAULT 'borrador', respaldo text, descripcion text,
 excepcion_sin_oc_tipo varchar(40), excepcion_sin_oc_descripcion text, fecha_vencimiento date, condicion_pago_dias_snapshot integer,
 condicion_pago_tipo_snapshot varchar(20), vencimiento_justificacion text, carga_historica boolean NOT NULL DEFAULT false,
 tipo_cambio numeric(14,4), tipo_cambio_origen varchar(40), tipo_cambio_justificacion text, tipo_cambio_usuario bigint,
 tipo_cambio_fecha timestamptz, creado_por bigint NOT NULL, fecha_creacion timestamptz NOT NULL DEFAULT now(), confirmado_por bigint, fecha_confirmacion timestamptz,
 CONSTRAINT chk_documento_m5_clase CHECK (clase IN ('preliminar','definitivo')), CONSTRAINT chk_documento_m5_monto CHECK (monto_total > 0),
 CONSTRAINT chk_documento_m5_estado CHECK (estado IN ('borrador','confirmado','anulado')),
 CONSTRAINT fk_documento_m5_proveedor FOREIGN KEY (id_proveedor) REFERENCES finanzas.proveedor(id_proveedor) ON DELETE RESTRICT,
 CONSTRAINT fk_documento_m5_tipo FOREIGN KEY (id_tipo_documento) REFERENCES finanzas.tipo_documento(id_tipo_documento) ON DELETE RESTRICT,
 CONSTRAINT fk_documento_m5_moneda FOREIGN KEY (id_moneda) REFERENCES finanzas.moneda(id_moneda) ON DELETE RESTRICT,
 CONSTRAINT fk_documento_m5_creador FOREIGN KEY (creado_por) REFERENCES terreno.usuario(usuario_id_usuario) ON DELETE RESTRICT
);
CREATE UNIQUE INDEX uq_documento_definitivo_m5_identidad ON finanzas.documento_proveedor_m5(id_proveedor,id_tipo_documento,folio_normalizado) WHERE clase='definitivo';
CREATE INDEX idx_documento_m5_proveedor_fecha ON finanzas.documento_proveedor_m5(id_proveedor,fecha_creacion);
CREATE INDEX idx_documento_m5_estado_fecha ON finanzas.documento_proveedor_m5(estado,fecha_creacion);

CREATE TABLE finanzas.asociacion_documento_oc_m5 (
 id_asociacion_m5 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, id_documento_m5 integer NOT NULL, tipo_orden varchar(10) NOT NULL,
 id_ocs_m5 integer, id_orden_externa varchar(100), monto_asignado numeric(14,2) NOT NULL, estado_diferencia varchar(30) NOT NULL DEFAULT 'sin_evaluar',
 es_documento_final boolean NOT NULL DEFAULT false, justificacion text, monto_disponible_snapshot numeric(14,2), monto_excedente numeric(14,2) NOT NULL DEFAULT 0,
 estado_excedente varchar(20) NOT NULL DEFAULT 'no_aplica', excedente_solicitado_por bigint, excedente_fecha_solicitud timestamptz,
 excedente_aprobado_por bigint, excedente_fecha_resolucion timestamptz,
 CONSTRAINT chk_asociacion_m5_tipo CHECK (tipo_orden IN ('OCS','OCI','EXCEPCION')), CONSTRAINT chk_asociacion_m5_monto CHECK (monto_asignado > 0),
 CONSTRAINT chk_asociacion_m5_excedente CHECK (estado_excedente IN ('no_aplica','pendiente','aprobado','rechazado')),
 CONSTRAINT fk_asociacion_m5_documento FOREIGN KEY (id_documento_m5) REFERENCES finanzas.documento_proveedor_m5(id_documento_m5) ON DELETE RESTRICT,
 CONSTRAINT fk_asociacion_m5_ocs FOREIGN KEY (id_ocs_m5) REFERENCES finanzas.orden_compra_servicio_m5(id_orden_compra_servicio_m5) ON DELETE RESTRICT,
 CONSTRAINT uq_asociacion_documento_m5_ocs UNIQUE (id_documento_m5,id_ocs_m5)
);
CREATE INDEX idx_asociacion_documento_m5 ON finanzas.asociacion_documento_oc_m5(id_documento_m5);

CREATE TABLE finanzas.categoria_egreso_m5 (id_categoria_egreso_m5 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, nombre varchar(100) NOT NULL UNIQUE, activo boolean NOT NULL DEFAULT true);
CREATE TABLE finanzas.clasificacion_asociacion_m5 (id_clasificacion_m5 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, id_asociacion_m5 integer NOT NULL, id_categoria_egreso_m5 integer NOT NULL, monto numeric(14,2) NOT NULL CHECK(monto>0), CONSTRAINT fk_clasificacion_m5_asociacion FOREIGN KEY(id_asociacion_m5) REFERENCES finanzas.asociacion_documento_oc_m5(id_asociacion_m5) ON DELETE RESTRICT, CONSTRAINT fk_clasificacion_m5_categoria FOREIGN KEY(id_categoria_egreso_m5) REFERENCES finanzas.categoria_egreso_m5(id_categoria_egreso_m5) ON DELETE RESTRICT, CONSTRAINT uq_clasificacion_m5_asociacion_categoria UNIQUE(id_asociacion_m5,id_categoria_egreso_m5));
CREATE INDEX idx_clasificacion_m5_asociacion ON finanzas.clasificacion_asociacion_m5(id_asociacion_m5);

CREATE TABLE finanzas.propuesta_imputacion_m5 (id_propuesta_imputacion_m5 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, id_documento_m5 integer NOT NULL, estado varchar(20) NOT NULL DEFAULT 'pendiente', preparado_por bigint NOT NULL, fecha_preparacion timestamptz NOT NULL DEFAULT now(), confirmado_por bigint, fecha_confirmacion timestamptz, CHECK(estado IN ('pendiente','confirmado')), CONSTRAINT fk_imputacion_m5_documento FOREIGN KEY(id_documento_m5) REFERENCES finanzas.documento_proveedor_m5(id_documento_m5) ON DELETE RESTRICT);
CREATE INDEX idx_imputacion_m5_documento_estado ON finanzas.propuesta_imputacion_m5(id_documento_m5,estado);
CREATE TABLE finanzas.detalle_imputacion_m5 (id_detalle_imputacion_m5 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, id_propuesta_imputacion_m5 integer NOT NULL, id_clasificacion_m5 integer NOT NULL, destino varchar(20) NOT NULL, id_proyecto bigint, id_orden_trabajo bigint, monto numeric(14,2) NOT NULL CHECK(monto>0), CHECK(destino IN ('general','proyecto')), CONSTRAINT fk_detalle_imputacion_m5_propuesta FOREIGN KEY(id_propuesta_imputacion_m5) REFERENCES finanzas.propuesta_imputacion_m5(id_propuesta_imputacion_m5) ON DELETE RESTRICT, CONSTRAINT fk_detalle_imputacion_m5_clasificacion FOREIGN KEY(id_clasificacion_m5) REFERENCES finanzas.clasificacion_asociacion_m5(id_clasificacion_m5) ON DELETE RESTRICT, CONSTRAINT fk_detalle_imputacion_m5_proyecto FOREIGN KEY(id_proyecto) REFERENCES terreno.proyecto(proyecto_proyecto_id) ON DELETE RESTRICT, CONSTRAINT fk_detalle_imputacion_m5_ot FOREIGN KEY(id_orden_trabajo) REFERENCES inventario.orden_trabajo(orden_trabajo_id_orden) ON DELETE RESTRICT);
CREATE INDEX idx_detalle_imputacion_m5_propuesta ON finanzas.detalle_imputacion_m5(id_propuesta_imputacion_m5);

CREATE TABLE finanzas.obligacion_proveedor_m5 (id_obligacion_m5 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, id_documento_m5 integer NOT NULL UNIQUE, id_proveedor integer NOT NULL, monto_original numeric(14,2) NOT NULL, id_moneda integer NOT NULL, saldo_inicial numeric(14,2) NOT NULL, saldo_actual numeric(14,2) NOT NULL, fecha_emision date NOT NULL, fecha_vencimiento date NOT NULL, estado_pago varchar(20) NOT NULL DEFAULT 'Pendiente', condicion_temporal varchar(20) NOT NULL, condicion_pago_dias_snapshot integer, condicion_pago_tipo_snapshot varchar(20), tipo_cambio numeric(14,4), tipo_cambio_origen varchar(40), fecha_generacion timestamptz NOT NULL DEFAULT now(), generado_por bigint NOT NULL, CONSTRAINT fk_obligacion_m5_documento FOREIGN KEY(id_documento_m5) REFERENCES finanzas.documento_proveedor_m5(id_documento_m5) ON DELETE RESTRICT, CONSTRAINT fk_obligacion_m5_proveedor FOREIGN KEY(id_proveedor) REFERENCES finanzas.proveedor(id_proveedor) ON DELETE RESTRICT, CONSTRAINT fk_obligacion_m5_moneda FOREIGN KEY(id_moneda) REFERENCES finanzas.moneda(id_moneda) ON DELETE RESTRICT);
CREATE INDEX idx_obligacion_m5_proveedor_vencimiento ON finanzas.obligacion_proveedor_m5(id_proveedor,fecha_vencimiento);
CREATE TABLE finanzas.feriado_chile_m5 (fecha date PRIMARY KEY, descripcion varchar(150) NOT NULL);

COMMENT ON TABLE finanzas.documento_proveedor_m5 IS 'TEMPORAL_M5_DB_PATCH: documentos CU96-CU105 aislados de Legacy';
COMMENT ON TABLE finanzas.asociacion_documento_oc_m5 IS 'TEMPORAL_M5_DB_PATCH: asociación financiera OCS; OCI pendiente de fuente oficial';
COMMENT ON TABLE finanzas.categoria_egreso_m5 IS 'TEMPORAL_M5_DB_PATCH: catálogo de egresos M5';
COMMENT ON TABLE finanzas.obligacion_proveedor_m5 IS 'TEMPORAL_M5_DB_PATCH: obligación única provisional CU105';
COMMENT ON COLUMN finanzas.orden_compra_servicio_m5.id_moneda IS 'TEMPORAL_M5_DB_PATCH: nullable para no atribuir moneda a OCS existentes';
