import { useCallback, useEffect, useState } from 'react';
import { Banknote, RefreshCw } from 'lucide-react';
import { Link } from 'react-router-dom';
import { solicitarFinanzas } from '../../api/finanzas';
import { usarSesion } from '../../seguridad/Sesion';

type Medio={id:number;codigo:string;nombre:string;requiereRespaldo:boolean};
type Pago={id:number;origenTipo:string;origenId:number;monto:number;estado:string;respaldo:string|null;medio:{nombre:string}|null;confirmadoEn:string|null};
type Boleta={id:number;folio:string;liquido:number;pendiente:boolean;prestador:{nombre:string;identificador:string}};
const post=(dato:unknown):RequestInit=>({method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(dato)});
async function json(ruta:string,opciones?:RequestInit){const respuesta=await solicitarFinanzas(ruta,opciones);const dato=await respuesta.json();if(!respuesta.ok)throw new Error(dato.error||'No fue posible completar la operación');return dato;}
const clave=()=>crypto.randomUUID();

export default function RegistroPagosRemuneracion(){
 const {sesion}=usarSesion();const puede=(cu:string)=>Boolean(sesion?.permisos.includes(cu));
 const puede187=puede('CU187');
 const [medios,setMedios]=useState<Medio[]>([]),[pagos,setPagos]=useState<Pago[]>([]),[boletas,setBoletas]=useState<Boleta[]>([]),[error,setError]=useState(''),[ocupado,setOcupado]=useState('');
 const [anticipo,setAnticipo]=useState({idEmpleado:'',anio:String(new Date().getFullYear()),mes:String(new Date().getMonth()+1),modalidad:'MONTO',valor:'',codigoBasePorcentaje:''});
 const [origen,setOrigen]=useState({tipo:'REMUNERACION',id:'',monto:'',idMedioPago:'',respaldo:'',referencia:''});
 const [boleta,setBoleta]=useState({id:'',monto:''});
 const ejecutar=async(nombre:string,accion:()=>Promise<void>)=>{setOcupado(nombre);setError('');try{await accion()}catch(e){setError((e as Error).message)}finally{setOcupado('')}};
 const cargar=useCallback(()=>Promise.all([json('/medios-pago-remuneraciones?activos=true'),json('/pagos-remuneracion'),puede187?json('/boletas-honorarios/confirmadas'):Promise.resolve([])]).then(([m,p,b])=>{setMedios(m);setPagos(p);setBoletas(b)}),[puede187]);
 useEffect(()=>{void cargar().catch(e=>setError(e.message))},[cargar]);
 const prepararAnticipo=()=>void ejecutar('anticipo',async()=>{const creado=await json('/anticipos-remuneracion',post({idEmpleado:Number(anticipo.idEmpleado),anio:Number(anticipo.anio),mes:Number(anticipo.mes),modalidad:anticipo.modalidad,valor:anticipo.valor,codigoBasePorcentaje:anticipo.codigoBasePorcentaje,claveIdempotencia:clave()}));if(creado.montoFinal===null)throw new Error('Anticipo pendiente de valorización: configure una base CLP vigente');await json(`/anticipos-remuneracion/${creado.id}/pagos`,post({monto:creado.montoFinal,idMedioPago:Number(origen.idMedioPago),respaldo:origen.respaldo,referencia:origen.referencia,claveIdempotencia:clave()}));await cargar()});
 const prepararFinal=()=>void ejecutar('final',async()=>{await json('/pagos-remuneracion/finales',post({origenTipo:origen.tipo,origenId:Number(origen.id),monto:origen.monto,idMedioPago:Number(origen.idMedioPago),respaldo:origen.respaldo,referencia:origen.referencia,claveIdempotencia:clave()}));await cargar()});
 const prepararHonorario=()=>void ejecutar('honorario',async()=>{await json(`/boletas-honorarios/${boleta.id}/pagos`,post({monto:boleta.monto,idMedioPago:Number(origen.idMedioPago),respaldo:origen.respaldo,referencia:origen.referencia,claveIdempotencia:clave()}));await cargar()});
 const confirmar=(pago:Pago)=>void ejecutar(`p${pago.id}`,async()=>{const segmento=pago.origenTipo==='ANTICIPO'?'anticipos':pago.origenTipo==='BOLETA_HONORARIOS'?'honorarios':'finales';await json(`/pagos-remuneracion/${segmento}/${pago.id}/confirmar`,post({}));await cargar()});
 return <div className="min-h-full bg-gray-50 p-5 lg:p-8"><div className="mx-auto max-w-7xl"><header className="mb-6 flex items-center justify-between"><div><p className="text-sm font-semibold text-primary-600">Remuneraciones</p><h1 className="text-2xl font-bold">Registro de Pago de Remuneración y Honorarios</h1></div><button title="Actualizar" onClick={()=>void cargar()} className="rounded-md border bg-white p-2.5"><RefreshCw className="h-4 w-4"/></button></header>{error&&<p className="mb-5 border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</p>}
 {puede('CU185')&&<section className="border-y bg-white px-5 py-5"><h2 className="flex items-center gap-2 font-bold"><Banknote className="h-5 w-5 text-primary-600"/>Anticipo concreto</h2><div className="mt-4 grid gap-2 md:grid-cols-4"><input type="number" min="1" placeholder="ID empleado" value={anticipo.idEmpleado} onChange={e=>setAnticipo({...anticipo,idEmpleado:e.target.value})} className="rounded border p-2"/><input type="number" value={anticipo.anio} onChange={e=>setAnticipo({...anticipo,anio:e.target.value})} className="rounded border p-2"/><input type="number" min="1" max="12" value={anticipo.mes} onChange={e=>setAnticipo({...anticipo,mes:e.target.value})} className="rounded border p-2"/><select value={anticipo.modalidad} onChange={e=>setAnticipo({...anticipo,modalidad:e.target.value})} className="rounded border p-2"><option>MONTO</option><option>PORCENTAJE</option></select><input type="number" min="0.0001" step="0.0001" placeholder={anticipo.modalidad==='MONTO'?'Monto':'Porcentaje'} value={anticipo.valor} onChange={e=>setAnticipo({...anticipo,valor:e.target.value})} className="rounded border p-2"/><input disabled={anticipo.modalidad!=='PORCENTAJE'} placeholder="Código de base configurada" value={anticipo.codigoBasePorcentaje} onChange={e=>setAnticipo({...anticipo,codigoBasePorcentaje:e.target.value})} className="rounded border p-2 disabled:bg-gray-100"/><select value={origen.idMedioPago} onChange={e=>setOrigen({...origen,idMedioPago:e.target.value})} className="rounded border p-2"><option value="">Medio de pago</option>{medios.map(m=><option key={m.id} value={m.id}>{m.nombre}{m.requiereRespaldo?' (respaldo)':''}</option>)}</select><input placeholder="Respaldo o referencia" value={origen.respaldo} onChange={e=>setOrigen({...origen,respaldo:e.target.value})} className="rounded border p-2"/><button disabled={ocupado==='anticipo'} onClick={prepararAnticipo} className="rounded bg-black px-4 py-2 text-white">Registrar y preparar</button></div></section>}
 {puede('CU186')&&<section className="mt-6 border-y bg-white px-5 py-5"><h2 className="font-bold">Saldo final o regularización</h2><div className="mt-4 grid gap-2 md:grid-cols-6"><select value={origen.tipo} onChange={e=>setOrigen({...origen,tipo:e.target.value})} className="rounded border p-2"><option>REMUNERACION</option><option>REGULARIZACION</option></select><input type="number" min="1" placeholder="ID de origen" value={origen.id} onChange={e=>setOrigen({...origen,id:e.target.value})} className="rounded border p-2"/><input type="number" min="0.0001" step="0.0001" placeholder="Monto pagable" value={origen.monto} onChange={e=>setOrigen({...origen,monto:e.target.value})} className="rounded border p-2"/><select value={origen.idMedioPago} onChange={e=>setOrigen({...origen,idMedioPago:e.target.value})} className="rounded border p-2"><option value="">Medio de pago</option>{medios.map(m=><option key={m.id} value={m.id}>{m.nombre}{m.requiereRespaldo?' (respaldo)':''}</option>)}</select><input placeholder="Respaldo" value={origen.respaldo} onChange={e=>setOrigen({...origen,respaldo:e.target.value})} className="rounded border p-2"/><button disabled={ocupado==='final'} onClick={prepararFinal} className="rounded bg-black px-4 text-white">Preparar pago</button></div></section>}
 {puede('CU187')&&<section className="mt-6 border-y bg-white px-5 py-5"><h2 className="font-bold">Boleta de honorarios confirmada</h2><div className="mt-4 grid gap-2 md:grid-cols-5"><select value={boleta.id} onChange={e=>{const b=boletas.find(x=>x.id===Number(e.target.value));setBoleta({id:e.target.value,monto:b?String(b.liquido):''})}} className="rounded border p-2"><option value="">Seleccionar boleta</option>{boletas.filter(b=>b.pendiente).map(b=><option key={b.id} value={b.id}>{b.prestador.nombre} · {b.folio} · ${b.liquido.toLocaleString('es-CL')}</option>)}</select><input type="number" min="0.0001" step="0.0001" value={boleta.monto} onChange={e=>setBoleta({...boleta,monto:e.target.value})} className="rounded border p-2"/><select value={origen.idMedioPago} onChange={e=>setOrigen({...origen,idMedioPago:e.target.value})} className="rounded border p-2"><option value="">Medio de pago</option>{medios.map(m=><option key={m.id} value={m.id}>{m.nombre}</option>)}</select><input placeholder="Respaldo" value={origen.respaldo} onChange={e=>setOrigen({...origen,respaldo:e.target.value})} className="rounded border p-2"/><button disabled={ocupado==='honorario'||!boleta.id} onClick={prepararHonorario} className="rounded bg-black px-4 text-white">Preparar honorario</button></div></section>}
 <section className="mt-6 border-y bg-white px-5 py-5"><h2 className="font-bold">Pagos preparados y confirmados</h2><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="border-b text-xs uppercase text-gray-500"><tr><th className="p-2">Origen</th><th className="p-2">Monto</th><th className="p-2">Medio</th><th className="p-2">Estado</th><th className="p-2">Acción</th></tr></thead><tbody>{pagos.map(p=><tr key={p.id} className="border-b"><td className="p-2">{p.origenTipo} #{p.origenId}</td><td className="p-2">${p.monto.toLocaleString('es-CL')}</td><td className="p-2">{p.medio?.nombre}</td><td className="p-2 font-semibold">{p.estado}</td><td className="p-2 flex gap-2">{p.estado==='PREPARADO'&&((p.origenTipo==='ANTICIPO'&&puede('CU185'))||(p.origenTipo==='BOLETA_HONORARIOS'&&puede('CU187'))||(!['ANTICIPO','BOLETA_HONORARIOS'].includes(p.origenTipo)&&puede('CU186')))&&<button disabled={ocupado===`p${p.id}`} onClick={()=>confirmar(p)} className="rounded bg-primary-600 px-3 py-2 text-white">Confirmar</button>}<Link to={`/pagos-remuneraciones/${p.id}`} className="rounded border px-3 py-2">Detalle</Link></td></tr>)}</tbody></table></div></section>
 </div></div>;
}
