import { useEffect, useState } from 'react';
import { Banknote, Check, Paperclip, Plus, RefreshCw, X } from 'lucide-react';
import { solicitarFinanzas } from '../../api/finanzas';
import { usarSesion } from '../../seguridad/Sesion';

interface Gasto {id:number;monto:number;descripcion:string;fechaGasto:string;fechaRegistro:string;comercioEmisor:string|null;estado:string;registradoPor:string;condicionAprobacion:string|null;motivoRechazo:string|null;respaldos:Array<{id:number;nombreArchivo:string;tipo:string|null}>}
interface Caja {periodo:string;fondo:number;reservado:number;aprobado:number;disponibleProyectado:number;fondoConfigurado:boolean;gastos:Gasto[]}
const periodoActual=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Santiago',year:'numeric',month:'2-digit'}).format(new Date());
const hoy=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Santiago',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const dinero=(valor:number)=>valor.toLocaleString('es-CL',{style:'currency',currency:'CLP',maximumFractionDigits:0});
const json=(method:string,body?:unknown):RequestInit=>({method,headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});
async function api(ruta:string,opciones?:RequestInit){const respuesta=await solicitarFinanzas(ruta,opciones);const resultado=await respuesta.json();if(!respuesta.ok)throw new Error(resultado.error||'No fue posible completar la operación');return resultado}
const leerArchivo=async(file:File)=>new Promise<string>((resolver,rechazar)=>{const lector=new FileReader();lector.onload=()=>resolver(String(lector.result));lector.onerror=()=>rechazar(new Error('No fue posible leer el archivo'));lector.readAsDataURL(file)});

export default function CajaChica(){
 const {sesion}=usarSesion();const puede=(cu:string)=>!!sesion?.permisos.includes(cu);const [periodo,setPeriodo]=useState(periodoActual());const [caja,setCaja]=useState<Caja|null>(null);const [fondo,setFondo]=useState('');const [nuevo,setNuevo]=useState({monto:'',descripcion:'',fecha:hoy(),comercioEmisor:''});const [error,setError]=useState('');const [mensaje,setMensaje]=useState('');
 const cargar=async()=>{try{const resultado:Caja=await api(`/caja-chica?periodo=${periodo}`);setCaja(resultado);setFondo(String(resultado.fondo));setError('')}catch(e){setError((e as Error).message)}};
 useEffect(()=>{let activo=true;void api(`/caja-chica?periodo=${periodo}`).then((resultado:Caja)=>{if(activo){setCaja(resultado);setFondo(String(resultado.fondo));setError('')}}).catch(e=>{if(activo)setError(e.message)});return()=>{activo=false}},[periodo]);
 const ejecutar=async(ruta:string,opciones:RequestInit,mensajeExito:string)=>{try{const resultado:Caja=await api(ruta,opciones);setCaja(resultado);setMensaje(mensajeExito);setError('')}catch(e){setError((e as Error).message)}};
 const configurar=()=>void ejecutar(`/caja-chica/fondo/${periodo}`,json('PUT',{monto:Number(fondo)}),'Fondo mensual actualizado.');
 const registrar=async()=>{await ejecutar('/caja-chica/gastos',json('POST',{...nuevo,monto:Number(nuevo.monto)}),'Gasto registrado y reservado.');setNuevo({monto:'',descripcion:'',fecha:hoy(),comercioEmisor:''})};
 const adjuntar=async(gasto:Gasto)=>{const selector=document.createElement('input');selector.type='file';selector.onchange=async()=>{const archivo=selector.files?.[0];if(!archivo)return;await ejecutar(`/caja-chica/gastos/${gasto.id}/respaldo`,json('POST',{nombreArchivo:archivo.name,contenido:await leerArchivo(archivo),tipoRespaldo:archivo.name.toLowerCase().includes('factura')?'factura':'evidencia',comercioEmisor:gasto.comercioEmisor}),'Respaldo adjuntado.')};selector.click()};
 const aprobar=(id:number)=>void ejecutar(`/caja-chica/gastos/${id}/aprobar`,json('POST',{}),'Gasto aprobado.');
 const rechazar=(id:number)=>{const motivo=window.prompt('Motivo obligatorio del rechazo');if(motivo)void ejecutar(`/caja-chica/gastos/${id}/rechazar`,json('POST',{motivo}),'Gasto rechazado y reserva liberada.')};
 return <div className="min-h-full bg-slate-50 p-5 lg:p-8"><div className="mx-auto max-w-7xl"><header className="mb-6 flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-3"><Banknote className="h-7 w-7 text-emerald-700"/><div><p className="text-sm font-semibold text-emerald-700">Proveedores y egresos</p><h1 className="text-2xl font-bold">Caja Chica</h1></div></div><div className="flex gap-2"><input aria-label="Período" type="month" value={periodo} onChange={e=>setPeriodo(e.target.value)} className="border bg-white p-2"/><button title="Actualizar" onClick={()=>void cargar()} className="border bg-white p-2"><RefreshCw className="h-5 w-5"/></button></div></header>
 {(error||mensaje)&&<div className={`mb-4 border p-3 text-sm ${error?'border-red-200 bg-red-50 text-red-700':'border-emerald-200 bg-emerald-50 text-emerald-700'}`}>{error||mensaje}</div>}
 {caja&&<><section className="mb-6 grid border bg-white sm:grid-cols-2 lg:grid-cols-4"><div className="p-4"><p className="text-xs uppercase text-gray-500">Fondo del mes</p><strong className="text-xl">{dinero(caja.fondo)}</strong></div><div className="border-l p-4"><p className="text-xs uppercase text-gray-500">Pendiente reservado</p><strong className="text-xl">{dinero(caja.reservado)}</strong></div><div className="border-l p-4"><p className="text-xs uppercase text-gray-500">Gasto aprobado</p><strong className="text-xl">{dinero(caja.aprobado)}</strong></div><div className="border-l p-4"><p className="text-xs uppercase text-gray-500">Disponible proyectado</p><strong className={`text-xl ${caja.disponibleProyectado<0?'text-red-700':'text-emerald-700'}`}>{dinero(caja.disponibleProyectado)}</strong></div></section>
 {puede('CU150')&&<section className="mb-6 flex flex-wrap items-end gap-3 border-y bg-white p-4"><label className="grid gap-1 text-sm"><span>Fondo mensual</span><input type="number" min="0" step="0.01" value={fondo} onChange={e=>setFondo(e.target.value)} className="border p-2"/></label><button onClick={configurar} className="bg-primary-600 px-4 py-2 text-white">Actualizar fondo</button></section>}
 {puede('CU151')&&<section className="mb-6 grid gap-3 border-y bg-white p-4 md:grid-cols-[160px_160px_1fr_1fr_auto]"><input type="number" min="0.01" step="0.01" value={nuevo.monto} onChange={e=>setNuevo({...nuevo,monto:e.target.value})} placeholder="Monto" className="border p-2"/><input type="date" value={nuevo.fecha} onChange={e=>setNuevo({...nuevo,fecha:e.target.value})} className="border p-2"/><input value={nuevo.descripcion} onChange={e=>setNuevo({...nuevo,descripcion:e.target.value})} placeholder="Descripción" className="border p-2"/><input value={nuevo.comercioEmisor} onChange={e=>setNuevo({...nuevo,comercioEmisor:e.target.value})} placeholder="Comercio o emisor (opcional)" className="border p-2"/><button disabled={!nuevo.monto||!nuevo.descripcion||!caja.fondoConfigurado} onClick={()=>void registrar()} className="flex items-center justify-center gap-2 bg-primary-600 px-4 py-2 text-white disabled:opacity-40"><Plus className="h-4 w-4"/>Registrar</button></section>}
 <section className="border bg-white"><h2 className="border-b p-4 font-semibold">Gastos del período</h2><div className="divide-y">{caja.gastos.map(gasto=><article key={gasto.id} className="grid gap-3 p-4 lg:grid-cols-[1fr_auto]"><div><div className="flex flex-wrap items-center gap-2"><strong>{gasto.descripcion}</strong><span className={`px-2 py-1 text-xs font-semibold uppercase ${gasto.estado==='aprobado'?'bg-emerald-100 text-emerald-800':gasto.estado==='rechazado'?'bg-red-100 text-red-800':'bg-amber-100 text-amber-800'}`}>{gasto.estado}</span></div><p className="mt-1 text-sm text-gray-600">{dinero(gasto.monto)} · {new Date(gasto.fechaGasto).toLocaleDateString('es-CL')} · {gasto.comercioEmisor||'Sin comercio informado'}</p><p className="mt-1 text-xs text-gray-500">Registrado por usuario {gasto.registradoPor} · {gasto.respaldos.length?gasto.respaldos.map(r=>r.nombreArchivo).join(', '):'Sin respaldo'}</p>{gasto.motivoRechazo&&<p className="mt-1 text-sm text-red-700">Motivo: {gasto.motivoRechazo}</p>}</div>{gasto.estado==='pendiente'&&<div className="flex items-center gap-1">{puede('CU152')&&<button title="Adjuntar respaldo" onClick={()=>void adjuntar(gasto)} className="border p-2"><Paperclip className="h-4 w-4"/></button>}{puede('CU153')&&<button title="Aprobar gasto" disabled={!gasto.respaldos.length} onClick={()=>aprobar(gasto.id)} className="border border-emerald-300 p-2 text-emerald-700 disabled:opacity-30"><Check className="h-4 w-4"/></button>}{puede('CU154')&&<button title="Rechazar gasto" onClick={()=>rechazar(gasto.id)} className="border border-red-300 p-2 text-red-700"><X className="h-4 w-4"/></button>}</div>}</article>)}{!caja.gastos.length&&<p className="p-10 text-center text-gray-500">No hay gastos registrados en este período.</p>}</div></section></>}</div></div>;
}
