-- TEMPORAL_M5_DB_PATCH: CU146-CU154. Caja Chica mensual y ciclo final de envios.
ALTER TABLE finanzas.envio_importacion_m5
  DROP CONSTRAINT IF EXISTS chk_envio_importacion_m5_estado;
ALTER TABLE finanzas.envio_importacion_m5
  ADD CONSTRAINT chk_envio_importacion_m5_estado
  CHECK (estado IN ('abierto','en_revision','cerrado_financieramente'));

CREATE TABLE finanzas.fondo_caja_chica_m5 (
 id_fondo_caja_chica_m5 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 anio integer NOT NULL,
 mes integer NOT NULL,
 monto numeric(14,2) NOT NULL,
 actualizado_por bigint NOT NULL,
 fecha_actualizacion timestamptz(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
 CONSTRAINT uq_fondo_caja_chica_m5_periodo UNIQUE(anio,mes),
 CONSTRAINT chk_fondo_caja_chica_m5_periodo CHECK(anio BETWEEN 2000 AND 9999 AND mes BETWEEN 1 AND 12),
 CONSTRAINT chk_fondo_caja_chica_m5_monto CHECK(monto >= 0)
);

CREATE TABLE finanzas.historial_fondo_caja_chica_m5 (
 id_historial_fondo_m5 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 id_fondo_caja_chica_m5 integer NOT NULL REFERENCES finanzas.fondo_caja_chica_m5(id_fondo_caja_chica_m5) ON DELETE RESTRICT,
 monto_anterior numeric(14,2) NOT NULL,
 monto_nuevo numeric(14,2) NOT NULL,
 usuario_id_usuario bigint NOT NULL,
 fecha_hora timestamptz(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_historial_fondo_caja_m5 ON finanzas.historial_fondo_caja_chica_m5(id_fondo_caja_chica_m5,fecha_hora);

CREATE TABLE finanzas.gasto_caja_chica_m5 (
 id_gasto_caja_chica_m5 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 anio integer NOT NULL,
 mes integer NOT NULL,
 monto numeric(14,2) NOT NULL,
 descripcion text NOT NULL,
 fecha_gasto date NOT NULL,
 comercio_emisor varchar(200),
 estado varchar(20) NOT NULL DEFAULT 'pendiente',
 registrado_por bigint NOT NULL,
 fecha_registro timestamptz(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
 resuelto_por bigint,
 fecha_resolucion timestamptz(6),
 condicion_aprobacion varchar(20),
 motivo_rechazo text,
 CONSTRAINT chk_gasto_caja_chica_m5_periodo CHECK(anio BETWEEN 2000 AND 9999 AND mes BETWEEN 1 AND 12),
 CONSTRAINT chk_gasto_caja_chica_m5_monto CHECK(monto > 0),
 CONSTRAINT chk_gasto_caja_chica_m5_estado CHECK(estado IN ('pendiente','aprobado','rechazado'))
);
CREATE INDEX idx_gasto_caja_chica_m5_periodo_estado ON finanzas.gasto_caja_chica_m5(anio,mes,estado);

CREATE TABLE finanzas.respaldo_gasto_caja_chica_m5 (
 id_respaldo_gasto_m5 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 id_gasto_caja_chica_m5 integer NOT NULL REFERENCES finanzas.gasto_caja_chica_m5(id_gasto_caja_chica_m5) ON DELETE RESTRICT,
 nombre_archivo varchar(255) NOT NULL,
 contenido text NOT NULL,
 tipo_respaldo varchar(40),
 comercio_emisor varchar(200),
 adjuntado_por bigint NOT NULL,
 fecha_hora timestamptz(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_respaldo_gasto_caja_m5 ON finanzas.respaldo_gasto_caja_chica_m5(id_gasto_caja_chica_m5,fecha_hora);

CREATE TABLE finanzas.historial_gasto_caja_chica_m5 (
 id_historial_gasto_m5 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 id_gasto_caja_chica_m5 integer NOT NULL REFERENCES finanzas.gasto_caja_chica_m5(id_gasto_caja_chica_m5) ON DELETE RESTRICT,
 evento varchar(30) NOT NULL,
 detalle text NOT NULL,
 usuario_id_usuario bigint NOT NULL,
 fecha_hora timestamptz(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_historial_gasto_caja_m5 ON finanzas.historial_gasto_caja_chica_m5(id_gasto_caja_chica_m5,fecha_hora);

COMMENT ON TABLE finanzas.fondo_caja_chica_m5 IS 'TEMPORAL_M5_DB_PATCH: fondo independiente por mes, sin arrastre';
COMMENT ON TABLE finanzas.gasto_caja_chica_m5 IS 'TEMPORAL_M5_DB_PATCH: egreso Caja Chica separado de proveedor, OCS y CxP';
