import { useEffect, useMemo, useState } from 'react';
import { CheckCircle2, RefreshCw, SearchCheck, TriangleAlert } from 'lucide-react';
import { solicitarFinanzas } from '../../api/finanzas';
import { usarSesion } from '../../seguridad/Sesion';

type Tratamiento={estadoRemunerabilidad:string;estadoValorizacion:string;motivo:string|null;valorPropuesto:number|null};
type Hecho={idEjecucion:string;tarea:string;fecha:string;cantidad:number|null;unidad:string|null;ejecutor:{nombre:string};empleado:{rut:string;nombre:string}|null;tratamiento:Tratamiento|null;incidencia?:{id:string;descripcion:string;causaReferencia:string|null;causaPendiente:boolean}};
type Componente={id:number;tipo:string;modalidad:string;descripcion:string;monto:number|null;direccion:string|null;fuenteTipo:string;referenciaOrigen:string|null;versionOrigen:string|null;estadoRevision:string;motivo:string|null;idComponenteOrigen:number|null};
type Remuneracion={id:number;estado:string;periodo:{anio:number;mes:number};empleado:{id:number;rut:string;nombre:string};componentes:Componente[]};
type Prorrateo={estadoPropuesta:string;montoCalculado:number|null;configuracion:{nombre:string;valor:number|null}|null;remuneracion:Remuneracion};

async function json(ruta:string,opciones?:RequestInit){const respuesta=await solicitarFinanzas(ruta,opciones);const dato=await respuesta.json();if(!respuesta.ok)throw new Error(dato.error||'No fue posible completar la operación');return dato;}
const post=(dato:unknown):RequestInit=>({method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(dato)});
const Estado=({valor}:{valor:string})=><span className="inline-flex rounded border bg-gray-50 px-2 py-1 text-xs font-semibold uppercase text-gray-700">{valor.replaceAll('_',' ')}</span>;

export default function DetalleRemuneracion(){
 const {sesion}=usarSesion();const puede=(cu:string)=>Boolean(sesion?.permisos.includes(cu));const puede172=puede('CU172'),puede173=puede('CU173');const puedeComponentes=['CU174','CU175','CU176','CU177'].some(puede);
 const [hechos,setHechos]=useState<Hecho[]>([]),[retrabajos,setRetrabajos]=useState<Hecho[]>([]),[error,setError]=useState(''),[ocupado,setOcupado]=useState(''),[version,setVersion]=useState(0);const [decisiones,setDecisiones]=useState<Record<string,{decision:string;motivo:string}>>({});
 const [selector,setSelector]=useState({idEmpleado:'',anio:String(new Date().getFullYear()),mes:String(new Date().getMonth()+1)}),[remuneracion,setRemuneracion]=useState<Remuneracion|null>(null),[motivos,setMotivos]=useState<Record<number,string>>({});
 const [excepcional,setExcepcional]=useState({modalidad:'MONTO',descripcion:'',monto:'',referenciaOrigen:'',motivo:''});const [variable,setVariable]=useState({clase:'ADMINISTRATIVA',fuenteTipo:'MANUAL',claveNegocio:'',descripcion:'',monto:'',fechaOrigen:'',referenciaOrigen:'',versionOrigen:''});
 const [externo,setExterno]=useState({fuenteTipo:'',claveNegocio:'',referenciaOrigen:'',versionOrigen:'',fechaOrigen:'',descripcion:'',monto:''}),[ajuste,setAjuste]=useState({idComponenteOrigen:'',direccion:'POSITIVO',descripcion:'',motivo:'',monto:''});const [prorrateo,setProrrateo]=useState<Prorrateo|null>(null),[propuesta,setPropuesta]=useState({monto:'',fundamento:''});
 const externos=useMemo(()=>remuneracion?.componentes.filter(item=>item.tipo==='VALOR_EXTERNO')||[],[remuneracion]);
 useEffect(()=>{const c=new AbortController();const tareas:Promise<void>[]=[];if(puede172)tareas.push(json('/hechos-remunerables',{signal:c.signal}).then(setHechos));if(puede173)tareas.push(json('/retrabajos-pendientes',{signal:c.signal}).then(setRetrabajos));Promise.all(tareas).catch(e=>{if(!c.signal.aborted)setError(e.message)});return()=>c.abort()},[version,puede172,puede173]);
 const ejecutar=async(clave:string,accion:()=>Promise<void>)=>{setOcupado(clave);setError('');try{await accion()}catch(e){setError((e as Error).message)}finally{setOcupado('')}};
 const cargarProrrateo=async(id:number)=>{if(puede('CU177'))setProrrateo(await json(`/remuneraciones/${id}/prorrateo`))};
 const abrir=()=>ejecutar('contexto',async()=>{const dato=await json('/remuneraciones/contexto',post({idEmpleado:Number(selector.idEmpleado),anio:Number(selector.anio),mes:Number(selector.mes)}));setRemuneracion(dato);await cargarProrrateo(dato.id)});
 const enviar=(clave:string,ruta:string,dato:unknown,limpiar:()=>void)=>ejecutar(clave,async()=>{const respuesta=await json(ruta,post(dato));const actual=respuesta.remuneracion||respuesta;setRemuneracion(actual);if(respuesta.estadoPropuesta)setProrrateo(respuesta);else await cargarProrrateo(actual.id);limpiar()});
 const resolver=(item:Componente,ruta:string,decision:'aprobar'|'rechazar')=>ejecutar(`c${item.id}`,async()=>{const dato=await json(`/componentes-remuneracion/${item.id}/${ruta}`,post({decision,motivo:motivos[item.id]||''}));setRemuneracion(dato);await cargarProrrateo(dato.id)});
 const tabla=(tipos:string[],ruta:string)=><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="border-b text-xs uppercase text-gray-500"><tr><th className="p-2">Componente</th><th className="p-2">Monto</th><th className="p-2">Fuente</th><th className="p-2">Estado</th><th className="p-2">Decisión</th></tr></thead><tbody>{remuneracion?.componentes.filter(x=>tipos.includes(x.tipo)).map(x=><tr key={x.id} className="border-b align-top"><td className="p-2"><strong>{x.descripcion}</strong><div className="text-gray-500">{x.tipo.replaceAll('_',' ')}{x.versionOrigen?` · v${x.versionOrigen}`:''}</div></td><td className="p-2">{x.monto===null?'Pendiente':`${x.direccion==='NEGATIVO'?'-':''}${x.monto.toLocaleString('es-CL')}`}</td><td className="p-2">{x.fuenteTipo}<div className="text-gray-500">{x.referenciaOrigen}</div></td><td className="p-2"><Estado valor={x.estadoRevision}/><div className="mt-1 text-gray-500">{x.motivo}</div></td><td className="p-2">{['propuesto','conflicto','pendiente_valorizacion'].includes(x.estadoRevision)&&<div className="flex min-w-[280px] gap-2"><input value={motivos[x.id]||''} onChange={e=>setMotivos({...motivos,[x.id]:e.target.value})} placeholder="Fundamento" className="min-w-0 flex-1 rounded border p-2"/><button disabled={x.estadoRevision==='pendiente_valorizacion'} onClick={()=>void resolver(x,ruta,'aprobar')} className="rounded bg-primary-600 px-3 text-white disabled:opacity-40">Aprobar</button><button onClick={()=>void resolver(x,ruta,'rechazar')} className="rounded border px-3">Rechazar</button></div>}</td></tr>)}</tbody></table></div>;
 return <div className="min-h-full bg-gray-50 p-5 lg:p-8"><div className="mx-auto max-w-7xl">
  <header className="mb-6 flex items-center justify-between"><div><p className="text-sm font-semibold text-primary-600">Remuneraciones</p><h1 className="text-2xl font-bold">Detalle de Remuneración</h1></div><button title="Actualizar" onClick={()=>setVersion(v=>v+1)} className="rounded-md border bg-white p-2.5"><RefreshCw className="h-4 w-4"/></button></header>{error&&<p className="mb-5 border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</p>}
  {puedeComponentes&&<section className="mb-6 border-y bg-white px-5 py-5"><div className="grid gap-3 md:grid-cols-[1fr_1fr_1fr_auto]"><input type="number" min="1" placeholder="ID empleado" value={selector.idEmpleado} onChange={e=>setSelector({...selector,idEmpleado:e.target.value})} className="rounded border p-2.5"/><input type="number" min="2000" max="2200" value={selector.anio} onChange={e=>setSelector({...selector,anio:e.target.value})} className="rounded border p-2.5"/><select value={selector.mes} onChange={e=>setSelector({...selector,mes:e.target.value})} className="rounded border p-2.5">{Array.from({length:12},(_,i)=><option key={i+1} value={i+1}>{new Date(2026,i,1).toLocaleString('es-CL',{month:'long'})}</option>)}</select><button disabled={ocupado==='contexto'} onClick={()=>void abrir()} className="rounded bg-black px-4 font-semibold text-white">Abrir período individual</button></div>{remuneracion&&<div className="mt-4 flex flex-wrap gap-3 border-t pt-4 text-sm"><strong>{remuneracion.empleado.nombre}</strong><span>{remuneracion.empleado.rut}</span><span>{String(remuneracion.periodo.mes).padStart(2,'0')}/{remuneracion.periodo.anio}</span><Estado valor={remuneracion.estado}/></div>}</section>}
  {puede172&&<section className="border-y bg-white px-5 py-5"><h2 className="mb-4 flex items-center gap-2 font-bold"><SearchCheck className="h-5 w-5 text-primary-600"/>Insumos remuneracionales</h2>{!hechos.length?<p className="text-sm text-gray-500">No existen ejecuciones terminadas y validadas disponibles.</p>:<div className="overflow-x-auto"><table className="w-full min-w-[800px] text-left text-sm"><tbody>{hechos.map(h=><tr key={h.idEjecucion} className="border-b"><td className="p-3"><strong>{h.tarea}</strong><div className="text-gray-500">#{h.idEjecucion} · {new Date(h.fecha).toLocaleDateString()}</div></td><td className="p-3">{h.empleado?.nombre||'Pendiente de correspondencia'}</td><td className="p-3">{h.cantidad===null?'No aplica':`${h.cantidad} ${h.unidad}`}</td><td className="p-3">{h.tratamiento?<Estado valor={h.tratamiento.estadoValorizacion}/>:<Estado valor="sin revisar"/>}</td><td className="p-3"><button onClick={()=>void ejecutar(h.idEjecucion,async()=>{await json(`/hechos-remunerables/${h.idEjecucion}/tratamiento`,{method:'POST'});setVersion(v=>v+1)})} className="rounded bg-primary-600 px-3 py-2 text-white">Revisar</button></td></tr>)}</tbody></table></div>}</section>}
  {puede173&&<section className="mt-6 border-y bg-white px-5 py-5"><h2 className="mb-4 flex items-center gap-2 font-bold"><TriangleAlert className="h-5 w-5 text-primary-600"/>Retrabajos pendientes de decisión</h2>{!retrabajos.length?<p className="flex gap-2 text-sm text-gray-500"><CheckCircle2 className="h-4 w-4"/>No existen retrabajos pendientes.</p>:retrabajos.map(h=>{const id=h.incidencia!.id,d=decisiones[id]||{decision:'remunerable',motivo:''};return <div key={id} className="grid gap-2 border-b py-4 md:grid-cols-[1fr_180px_1fr_auto]"><div><strong>{h.incidencia!.descripcion}</strong><p className="text-sm text-gray-500">{h.incidencia!.causaReferencia||'Pendiente de clasificación'}</p></div><select value={d.decision} onChange={e=>setDecisiones({...decisiones,[id]:{...d,decision:e.target.value}})} className="rounded border p-2"><option value="remunerable">Remunerable</option><option value="no_remunerable">No remunerable</option></select><input value={d.motivo} onChange={e=>setDecisiones({...decisiones,[id]:{...d,motivo:e.target.value}})} placeholder="Justificación" className="rounded border p-2"/><button onClick={()=>void ejecutar(id,async()=>{await json(`/retrabajos/${id}/resolucion-remuneracional`,post(d));setVersion(v=>v+1)})} className="rounded bg-black px-4 text-white">Resolver</button></div>})}</section>}
  {remuneracion&&puede('CU174')&&<section className="mt-6 border-y bg-white px-5 py-5"><h2 className="font-bold">Componentes excepcionales</h2><div className="mt-4 grid gap-2 md:grid-cols-6"><select value={excepcional.modalidad} onChange={e=>setExcepcional({...excepcional,modalidad:e.target.value})} className="rounded border p-2"><option>MONTO</option><option>REGLA_TEMPORAL</option></select><input placeholder="Descripción" value={excepcional.descripcion} onChange={e=>setExcepcional({...excepcional,descripcion:e.target.value})} className="rounded border p-2"/><input disabled={excepcional.modalidad!=='MONTO'} type="number" min="0" step="0.0001" placeholder="Monto" value={excepcional.monto} onChange={e=>setExcepcional({...excepcional,monto:e.target.value})} className="rounded border p-2 disabled:bg-gray-100"/><input disabled={excepcional.modalidad!=='REGLA_TEMPORAL'} placeholder="Referencia regla" value={excepcional.referenciaOrigen} onChange={e=>setExcepcional({...excepcional,referenciaOrigen:e.target.value})} className="rounded border p-2 disabled:bg-gray-100"/><input placeholder="Motivo" value={excepcional.motivo} onChange={e=>setExcepcional({...excepcional,motivo:e.target.value})} className="rounded border p-2"/><button onClick={()=>void enviar('e',`/remuneraciones/${remuneracion.id}/componentes-excepcionales`,excepcional,()=>setExcepcional({modalidad:'MONTO',descripcion:'',monto:'',referenciaOrigen:'',motivo:''}))} className="rounded bg-black text-white">Proponer</button></div>{tabla(['EXCEPCIONAL_POSITIVO'],'resolver-excepcional')}</section>}
  {remuneracion&&puede('CU175')&&<section className="mt-6 border-y bg-white px-5 py-5"><h2 className="font-bold">Variables administrativas y comerciales</h2><div className="mt-4 grid gap-2 md:grid-cols-7"><select value={variable.clase} onChange={e=>setVariable({...variable,clase:e.target.value})} className="rounded border p-2"><option>ADMINISTRATIVA</option><option>COMERCIAL</option></select><select value={variable.fuenteTipo} onChange={e=>setVariable({...variable,fuenteTipo:e.target.value})} className="rounded border p-2"><option>MANUAL</option><option>AUTOMATICA</option></select><input placeholder="Clave" value={variable.claveNegocio} onChange={e=>setVariable({...variable,claveNegocio:e.target.value})} className="rounded border p-2"/><input placeholder="Descripción" value={variable.descripcion} onChange={e=>setVariable({...variable,descripcion:e.target.value})} className="rounded border p-2"/><input type="number" min="0" step="0.0001" placeholder="Monto" value={variable.monto} onChange={e=>setVariable({...variable,monto:e.target.value})} className="rounded border p-2"/><input type="date" value={variable.fechaOrigen} onChange={e=>setVariable({...variable,fechaOrigen:e.target.value})} className="rounded border p-2"/><button onClick={()=>void enviar('v',`/remuneraciones/${remuneracion.id}/variables`,variable,()=>setVariable({clase:'ADMINISTRATIVA',fuenteTipo:'MANUAL',claveNegocio:'',descripcion:'',monto:'',fechaOrigen:'',referenciaOrigen:'',versionOrigen:''}))} className="rounded bg-black text-white">Proponer</button></div>{tabla(['VARIABLE_ADMINISTRATIVA','VARIABLE_COMERCIAL'],'resolver-variable')}</section>}
  {remuneracion&&puede('CU176')&&<section className="mt-6 border-y bg-white px-5 py-5"><h2 className="font-bold">Valores externos y ajustes</h2><div className="mt-4 grid gap-2 md:grid-cols-7"><input placeholder="Fuente" value={externo.fuenteTipo} onChange={e=>setExterno({...externo,fuenteTipo:e.target.value})} className="rounded border p-2"/><input placeholder="Clave" value={externo.claveNegocio} onChange={e=>setExterno({...externo,claveNegocio:e.target.value})} className="rounded border p-2"/><input placeholder="Referencia" value={externo.referenciaOrigen} onChange={e=>setExterno({...externo,referenciaOrigen:e.target.value})} className="rounded border p-2"/><input placeholder="Versión" value={externo.versionOrigen} onChange={e=>setExterno({...externo,versionOrigen:e.target.value})} className="rounded border p-2"/><input type="date" value={externo.fechaOrigen} onChange={e=>setExterno({...externo,fechaOrigen:e.target.value})} className="rounded border p-2"/><input type="number" min="0" step="0.0001" placeholder="Monto" value={externo.monto} onChange={e=>setExterno({...externo,monto:e.target.value})} className="rounded border p-2"/><button onClick={()=>void enviar('x',`/remuneraciones/${remuneracion.id}/valores-externos`,{...externo,descripcion:externo.descripcion||externo.claveNegocio},()=>setExterno({fuenteTipo:'',claveNegocio:'',referenciaOrigen:'',versionOrigen:'',fechaOrigen:'',descripcion:'',monto:''}))} className="rounded bg-black text-white">Registrar</button></div><div className="mt-4 grid gap-2 border-t pt-4 md:grid-cols-6"><select value={ajuste.idComponenteOrigen} onChange={e=>setAjuste({...ajuste,idComponenteOrigen:e.target.value})} className="rounded border p-2"><option value="">Valor externo</option>{externos.map(x=><option key={x.id} value={x.id}>{x.descripcion}</option>)}</select><select value={ajuste.direccion} onChange={e=>setAjuste({...ajuste,direccion:e.target.value})} className="rounded border p-2"><option>POSITIVO</option><option>NEGATIVO</option></select><input type="number" min="0" step="0.0001" placeholder="Monto" value={ajuste.monto} onChange={e=>setAjuste({...ajuste,monto:e.target.value})} className="rounded border p-2"/><input placeholder="Descripción" value={ajuste.descripcion} onChange={e=>setAjuste({...ajuste,descripcion:e.target.value})} className="rounded border p-2"/><input placeholder="Motivo" value={ajuste.motivo} onChange={e=>setAjuste({...ajuste,motivo:e.target.value})} className="rounded border p-2"/><button onClick={()=>void enviar('a',`/remuneraciones/${remuneracion.id}/ajustes`,{...ajuste,idComponenteOrigen:Number(ajuste.idComponenteOrigen)},()=>setAjuste({idComponenteOrigen:'',direccion:'POSITIVO',descripcion:'',motivo:'',monto:''}))} className="rounded bg-black text-white">Proponer ajuste</button></div>{tabla(['VALOR_EXTERNO','AJUSTE_MANUAL'],'resolver-valor')}</section>}
  {remuneracion&&puede('CU177')&&<section className="mt-6 border-y bg-white px-5 py-5"><h2 className="font-bold">Prorrateo individual</h2><div className="mt-3 flex gap-3 text-sm"><Estado valor={prorrateo?.estadoPropuesta||'pendiente'}/><span>{prorrateo?.configuracion?.nombre||'Sin configuración aplicable'}</span><span>{prorrateo?.montoCalculado===null?'Monto automático pendiente':''}</span></div><div className="mt-4 grid gap-2 md:grid-cols-[180px_1fr_auto]"><input type="number" min="0" step="0.0001" placeholder="Monto propuesto" value={propuesta.monto} onChange={e=>setPropuesta({...propuesta,monto:e.target.value})} className="rounded border p-2"/><input placeholder="Fundamento" value={propuesta.fundamento} onChange={e=>setPropuesta({...propuesta,fundamento:e.target.value})} className="rounded border p-2"/><button onClick={()=>void enviar('p',`/remuneraciones/${remuneracion.id}/prorrateo`,propuesta,()=>setPropuesta({monto:'',fundamento:''}))} className="rounded bg-black px-4 text-white">Proponer</button></div>{tabla(['PRORRATEO'],'resolver-prorrateo')}</section>}
 </div></div>;
}
