import { useEffect, useState } from 'react';
import { CheckCircle2, RefreshCw, SearchCheck, TriangleAlert } from 'lucide-react';
import { solicitarFinanzas } from '../../api/finanzas';
import { usarSesion } from '../../seguridad/Sesion';

type Tratamiento={estadoRemunerabilidad:string;estadoValorizacion:string;motivo:string|null;valorPropuesto:number|null;esquema:{codigo:string;nombre:string}|null;tarifa:{modalidad:string;valor:number|null;unidad:string|null}|null};
type Hecho={idEjecucion:string;idTarea:string;tarea:string;fecha:string;estadoOperacional:string;validacionProductiva:string;cantidad:number|null;unidad:string|null;ejecutor:{id:string;nombre:string};empleado:{id:number;rut:string;nombre:string}|null;mapeoAmbiguo:boolean;retrabajos:{id:string;descripcion:string;causaReferencia:string|null;causaPendiente:boolean;estado:string;responsabilidad:string|null;decision:{decision:string;motivo:string;fecha:string}|null}[];tratamiento:Tratamiento|null;incidencia?:{id:string;descripcion:string;causaReferencia:string|null;causaPendiente:boolean;responsabilidad:string|null}};

async function json(ruta:string,opciones?:RequestInit){const respuesta=await solicitarFinanzas(ruta,opciones);const cuerpo=await respuesta.json();if(!respuesta.ok)throw new Error(cuerpo.error||'No fue posible completar la operación');return cuerpo;}

export default function DetalleRemuneracion(){
 const {sesion}=usarSesion();const puede172=Boolean(sesion?.permisos.includes('CU172')),puede173=Boolean(sesion?.permisos.includes('CU173'));
 const [hechos,setHechos]=useState<Hecho[]>([]),[retrabajos,setRetrabajos]=useState<Hecho[]>([]),[version,setVersion]=useState(0),[error,setError]=useState(''),[ocupado,setOcupado]=useState('');
 const [decisiones,setDecisiones]=useState<Record<string,{decision:string;motivo:string}>>({});
 useEffect(()=>{const controlador=new AbortController();setError('');const tareas:Promise<void>[]=[];if(puede172)tareas.push(json('/hechos-remunerables',{signal:controlador.signal}).then(setHechos));if(puede173)tareas.push(json('/retrabajos-pendientes',{signal:controlador.signal}).then(setRetrabajos));Promise.all(tareas).catch(causa=>{if(!controlador.signal.aborted)setError(causa.message)});return()=>controlador.abort();},[version,puede172,puede173]);
 const revisar=async(id:string)=>{setOcupado(id);setError('');try{await json(`/hechos-remunerables/${id}/tratamiento`,{method:'POST'});setVersion(v=>v+1)}catch(causa){setError((causa as Error).message)}finally{setOcupado('')}};
 const resolver=async(id:string)=>{const entrada=decisiones[id]||{decision:'remunerable',motivo:''};setOcupado(id);setError('');try{await json(`/retrabajos/${id}/resolucion-remuneracional`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(entrada)});setVersion(v=>v+1)}catch(causa){setError((causa as Error).message)}finally{setOcupado('')}};
 const estado=(valor:string)=><span className="inline-flex items-center rounded border border-gray-200 bg-gray-50 px-2 py-1 text-xs font-semibold uppercase text-gray-700">{valor.replaceAll('_',' ')}</span>;
 return <div className="min-h-full bg-gray-50 p-5 lg:p-8"><div className="mx-auto max-w-7xl">
  <header className="mb-6 flex items-center justify-between gap-4"><div><p className="text-sm font-semibold text-primary-600">Remuneraciones</p><h1 className="text-2xl font-bold text-black">Detalle de Remuneración</h1></div><button title="Actualizar" onClick={()=>setVersion(v=>v+1)} className="rounded-md border bg-white p-2.5"><RefreshCw className="h-4 w-4"/></button></header>
  {error&&<p className="mb-5 border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</p>}
  {puede172&&<section className="border-y border-gray-200 bg-white px-5 py-5"><h2 className="mb-4 flex items-center gap-2 font-bold"><SearchCheck className="h-5 w-5 text-primary-600"/>Insumos remuneracionales</h2>
   {!hechos.length?<p className="text-sm text-gray-500">No existen ejecuciones terminadas y validadas disponibles.</p>:<div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="border-b text-xs uppercase text-gray-500"><tr><th className="p-3">Ejecución</th><th className="p-3">Trabajador</th><th className="p-3">Cantidad</th><th className="p-3">Tratamiento</th><th className="p-3">Valorización</th><th className="p-3"></th></tr></thead><tbody>{hechos.map(h=><tr key={h.idEjecucion} className="border-b align-top"><td className="p-3"><strong>{h.tarea}</strong><div className="text-gray-500">#{h.idEjecucion} · {new Date(h.fecha).toLocaleDateString()}</div></td><td className="p-3">{h.empleado?<><strong>{h.empleado.nombre}</strong><div className="text-gray-500">{h.empleado.rut}</div></>:<span className="text-amber-700">Pendiente de correspondencia</span>}</td><td className="p-3">{h.cantidad===null?'No aplica':`${h.cantidad} ${h.unidad||''}`}</td><td className="p-3">{h.tratamiento?estado(h.tratamiento.estadoRemunerabilidad):estado('sin revisar')}<div className="mt-1 max-w-xs text-gray-500">{h.tratamiento?.motivo}</div></td><td className="p-3">{h.tratamiento?estado(h.tratamiento.estadoValorizacion):'—'}<div className="mt-1 font-semibold">{h.tratamiento?.valorPropuesto===null||h.tratamiento?.valorPropuesto===undefined?'':h.tratamiento.valorPropuesto.toLocaleString('es-CL',{style:'currency',currency:'CLP'})}</div></td><td className="p-3"><button disabled={ocupado===h.idEjecucion} onClick={()=>void revisar(h.idEjecucion)} className="rounded-md bg-primary-600 px-3 py-2 font-semibold text-white disabled:opacity-50">Revisar</button></td></tr>)}</tbody></table></div>}
  </section>}
  {puede173&&<section className={`${puede172?'mt-6 ':''}border-y border-gray-200 bg-white px-5 py-5`}><h2 className="mb-4 flex items-center gap-2 font-bold"><TriangleAlert className="h-5 w-5 text-primary-600"/>Retrabajos pendientes de decisión</h2>
   {!retrabajos.length?<p className="flex items-center gap-2 text-sm text-gray-500"><CheckCircle2 className="h-4 w-4"/>No existen retrabajos pendientes.</p>:<div className="space-y-5">{retrabajos.map(h=>{const id=h.incidencia!.id,entrada=decisiones[id]||{decision:'remunerable',motivo:''};return <div key={id} className="border-b pb-5"><div className="grid gap-3 text-sm md:grid-cols-4"><div><span className="text-gray-500">Tarea</span><strong className="block">{h.tarea}</strong></div><div><span className="text-gray-500">Ejecutor</span><strong className="block">{h.ejecutor.nombre}</strong></div><div><span className="text-gray-500">Incidencia</span><strong className="block">{h.incidencia!.descripcion}</strong></div><div><span className="text-gray-500">Causa</span><strong className={h.incidencia!.causaPendiente?'block text-amber-700':'block'}>{h.incidencia!.causaReferencia||'Pendiente de clasificación'}</strong></div></div><div className="mt-3 grid gap-2 md:grid-cols-[200px_1fr_auto]"><select className="rounded-md border p-2.5 text-sm" value={entrada.decision} onChange={e=>setDecisiones({...decisiones,[id]:{...entrada,decision:e.target.value}})}><option value="remunerable">Remunerable</option><option value="no_remunerable">No remunerable</option></select><input className="rounded-md border p-2.5 text-sm" placeholder="Justificación obligatoria" value={entrada.motivo} onChange={e=>setDecisiones({...decisiones,[id]:{...entrada,motivo:e.target.value}})}/><button disabled={ocupado===id} onClick={()=>void resolver(id)} className="rounded-md bg-black px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">Resolver</button></div></div>})}</div>}
  </section>}
 </div></div>;
}
