CREATE TABLE "finanzas"."configuracion_concepto_remuneracion" (
  "id_configuracion_concepto" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_concepto" INTEGER NOT NULL,
  "modalidad" VARCHAR(20) NOT NULL,
  "valor" NUMERIC(14,4),
  "regla_tipo" VARCHAR(40),
  "vigencia_desde" DATE NOT NULL,
  "vigencia_hasta" DATE,
  "es_excepcion" BOOLEAN NOT NULL DEFAULT FALSE,
  "activa" BOOLEAN NOT NULL DEFAULT TRUE,
  CONSTRAINT "chk_configuracion_concepto_modalidad" CHECK ("modalidad" IN ('FIJO', 'PORCENTAJE', 'REGLA')),
  CONSTRAINT "chk_configuracion_concepto_vigencia" CHECK ("vigencia_hasta" IS NULL OR "vigencia_hasta" >= "vigencia_desde"),
  CONSTRAINT "chk_configuracion_concepto_valor" CHECK ("valor" IS NULL OR "valor" >= 0),
  CONSTRAINT "fk_configuracion_concepto" FOREIGN KEY ("id_concepto") REFERENCES "finanzas"."concepto_remuneracion"("id_concepto_remuneracion") ON DELETE RESTRICT
);

CREATE INDEX "idx_configuracion_concepto_vigencia" ON "finanzas"."configuracion_concepto_remuneracion" ("id_concepto", "vigencia_desde");
