-- TEMPORAL_M5_DB_PATCH
-- Persistencia M5 separada de pago_proveedor Legacy para CU111-CU120.
CREATE TABLE finanzas.operacion_pago_proveedor_m5 (
  id_operacion_pago_m5 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_proveedor integer NOT NULL REFERENCES finanzas.proveedor(id_proveedor) ON DELETE RESTRICT,
  estado varchar(20) NOT NULL DEFAULT 'borrador',
  fecha_efectiva_pago date,
  creado_por bigint NOT NULL REFERENCES terreno.usuario(usuario_id_usuario) ON DELETE RESTRICT,
  fecha_creacion timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  preparado_por bigint REFERENCES terreno.usuario(usuario_id_usuario) ON DELETE RESTRICT,
  fecha_preparacion timestamptz,
  confirmado_por bigint REFERENCES terreno.usuario(usuario_id_usuario) ON DELETE RESTRICT,
  fecha_confirmacion timestamptz,
  descartado_por bigint REFERENCES terreno.usuario(usuario_id_usuario) ON DELETE RESTRICT,
  fecha_descarte timestamptz,
  total_confirmado numeric(14,2),
  CONSTRAINT chk_operacion_pago_m5_estado CHECK (estado IN ('borrador','preparada','confirmada','descartada')),
  CONSTRAINT chk_operacion_pago_m5_total CHECK (total_confirmado IS NULL OR total_confirmado > 0)
);
CREATE INDEX idx_operacion_pago_m5_proveedor_estado ON finanzas.operacion_pago_proveedor_m5(id_proveedor, estado, fecha_creacion DESC);

CREATE TABLE finanzas.movimiento_pago_proveedor_m5 (
  id_movimiento_pago_m5 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_operacion_pago_m5 integer NOT NULL REFERENCES finanzas.operacion_pago_proveedor_m5(id_operacion_pago_m5) ON DELETE RESTRICT,
  id_obligacion_m5 integer NOT NULL REFERENCES finanzas.obligacion_proveedor_m5(id_obligacion_m5) ON DELETE RESTRICT,
  id_medio_pago integer NOT NULL REFERENCES finanzas.medio_pago(id_medio_pago) ON DELETE RESTRICT,
  id_moneda integer NOT NULL REFERENCES finanzas.moneda(id_moneda) ON DELETE RESTRICT,
  monto_aplicado numeric(14,2) NOT NULL,
  tasa_referencia numeric(14,4),
  fuente_tasa varchar(80),
  fecha_tasa date,
  tasa_manual boolean NOT NULL DEFAULT false,
  tasa_manual_justificacion text,
  tasa_manual_usuario bigint REFERENCES terreno.usuario(usuario_id_usuario) ON DELETE RESTRICT,
  tasa_manual_fecha timestamptz,
  tasa_bancaria_efectiva numeric(14,4),
  equivalente_clp numeric(14,2),
  estado varchar(20) NOT NULL DEFAULT 'borrador',
  fecha_creacion timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT chk_movimiento_pago_m5_monto CHECK (monto_aplicado > 0),
  CONSTRAINT chk_movimiento_pago_m5_tasas CHECK ((tasa_referencia IS NULL OR tasa_referencia > 0) AND (tasa_bancaria_efectiva IS NULL OR tasa_bancaria_efectiva > 0)),
  CONSTRAINT chk_movimiento_pago_m5_estado CHECK (estado IN ('borrador','Vigente'))
);
CREATE INDEX idx_movimiento_pago_m5_operacion ON finanzas.movimiento_pago_proveedor_m5(id_operacion_pago_m5, id_movimiento_pago_m5);
CREATE INDEX idx_movimiento_pago_m5_obligacion ON finanzas.movimiento_pago_proveedor_m5(id_obligacion_m5);

CREATE TABLE finanzas.respaldo_pago_proveedor_m5 (
  id_respaldo_pago_m5 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre_archivo varchar(255) NOT NULL,
  contenido text NOT NULL,
  creado_por bigint NOT NULL REFERENCES terreno.usuario(usuario_id_usuario) ON DELETE RESTRICT,
  fecha_creacion timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE finanzas.asociacion_respaldo_pago_m5 (
  id_asociacion_respaldo_m5 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_respaldo_pago_m5 integer NOT NULL REFERENCES finanzas.respaldo_pago_proveedor_m5(id_respaldo_pago_m5) ON DELETE RESTRICT,
  id_operacion_pago_m5 integer REFERENCES finanzas.operacion_pago_proveedor_m5(id_operacion_pago_m5) ON DELETE RESTRICT,
  id_movimiento_pago_m5 integer REFERENCES finanzas.movimiento_pago_proveedor_m5(id_movimiento_pago_m5) ON DELETE RESTRICT,
  CONSTRAINT chk_asociacion_respaldo_m5_destino CHECK (num_nonnulls(id_operacion_pago_m5, id_movimiento_pago_m5) = 1)
);
CREATE INDEX idx_asociacion_respaldo_m5_respaldo ON finanzas.asociacion_respaldo_pago_m5(id_respaldo_pago_m5);
CREATE UNIQUE INDEX uq_respaldo_pago_m5_operacion ON finanzas.asociacion_respaldo_pago_m5(id_respaldo_pago_m5, id_operacion_pago_m5) WHERE id_operacion_pago_m5 IS NOT NULL;
CREATE UNIQUE INDEX uq_respaldo_pago_m5_movimiento ON finanzas.asociacion_respaldo_pago_m5(id_respaldo_pago_m5, id_movimiento_pago_m5) WHERE id_movimiento_pago_m5 IS NOT NULL;

COMMENT ON TABLE finanzas.operacion_pago_proveedor_m5 IS 'TEMPORAL_M5_DB_PATCH: operación agrupadora separada de pago_proveedor Legacy';
