CREATE TABLE "finanzas"."parametro_remuneracional" (
  "id_parametro_remuneracional" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "codigo" VARCHAR(50) NOT NULL,
  "tipo" VARCHAR(30) NOT NULL,
  "nombre" VARCHAR(120) NOT NULL,
  "descripcion" TEXT,
  "valor" NUMERIC(18,6),
  "unidad" VARCHAR(30),
  "vigencia_desde" DATE NOT NULL,
  "vigencia_hasta" DATE,
  "fuente" VARCHAR(200),
  "referencia" VARCHAR(300),
  "estado" VARCHAR(20) NOT NULL DEFAULT 'pendiente',
  CONSTRAINT "chk_parametro_remuneracional_tipo" CHECK ("tipo" IN ('LEGAL', 'PREVISIONAL', 'TRIBUTARIO', 'PRORRATEO')),
  CONSTRAINT "chk_parametro_remuneracional_estado" CHECK ("estado" IN ('pendiente', 'activo', 'inactivo')),
  CONSTRAINT "chk_parametro_remuneracional_vigencia" CHECK ("vigencia_hasta" IS NULL OR "vigencia_hasta" >= "vigencia_desde"),
  CONSTRAINT "chk_parametro_remuneracional_valor" CHECK ("valor" IS NULL OR "valor" >= 0),
  CONSTRAINT "uq_parametro_remuneracional_codigo_vigencia" UNIQUE ("codigo", "vigencia_desde")
);

CREATE INDEX "idx_parametro_remuneracional_resolucion"
  ON "finanzas"."parametro_remuneracional" ("codigo", "vigencia_desde");

CREATE TABLE "finanzas"."tramo_impuesto_renta" (
  "id_tramo_impuesto_renta" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "vigencia_desde" DATE NOT NULL,
  "vigencia_hasta" DATE,
  "orden" INTEGER NOT NULL,
  "limite_desde" NUMERIC(18,6) NOT NULL,
  "limite_hasta" NUMERIC(18,6),
  "factor" NUMERIC(18,8) NOT NULL,
  "rebaja" NUMERIC(18,6) NOT NULL,
  "unidad" VARCHAR(30) NOT NULL,
  "fuente" VARCHAR(200),
  "referencia" VARCHAR(300),
  "estado" VARCHAR(20) NOT NULL DEFAULT 'activo',
  CONSTRAINT "chk_tramo_impuesto_vigencia" CHECK ("vigencia_hasta" IS NULL OR "vigencia_hasta" >= "vigencia_desde"),
  CONSTRAINT "chk_tramo_impuesto_limites" CHECK ("limite_hasta" IS NULL OR "limite_hasta" >= "limite_desde"),
  CONSTRAINT "chk_tramo_impuesto_numeros" CHECK ("orden" > 0 AND "limite_desde" >= 0 AND "factor" >= 0 AND "rebaja" >= 0),
  CONSTRAINT "chk_tramo_impuesto_estado" CHECK ("estado" IN ('activo', 'inactivo')),
  CONSTRAINT "uq_tramo_impuesto_vigencia_orden" UNIQUE ("vigencia_desde", "orden")
);

CREATE INDEX "idx_tramo_impuesto_vigencia"
  ON "finanzas"."tramo_impuesto_renta" ("vigencia_desde", "vigencia_hasta");

CREATE TABLE "finanzas"."configuracion_conservacion_documental" (
  "id_configuracion_conservacion" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "estado" VARCHAR(20) NOT NULL DEFAULT 'pendiente',
  "criterio_descriptivo" TEXT,
  "fuente" VARCHAR(200),
  "referencia" VARCHAR(300),
  "vigencia_desde" DATE NOT NULL,
  "vigencia_hasta" DATE,
  CONSTRAINT "chk_conservacion_documental_estado" CHECK ("estado" IN ('pendiente', 'configurada', 'inactiva')),
  CONSTRAINT "chk_conservacion_documental_vigencia" CHECK ("vigencia_hasta" IS NULL OR "vigencia_hasta" >= "vigencia_desde"),
  CONSTRAINT "uq_conservacion_documental_vigencia" UNIQUE ("vigencia_desde")
);

CREATE INDEX "idx_conservacion_documental_vigencia"
  ON "finanzas"."configuracion_conservacion_documental" ("vigencia_desde", "vigencia_hasta");

ALTER TABLE "finanzas"."medio_pago"
  ADD COLUMN "codigo_medio_pago" VARCHAR(40),
  ADD COLUMN "requiere_respaldo" BOOLEAN,
  ADD CONSTRAINT "uq_medio_pago_codigo" UNIQUE ("codigo_medio_pago");
