-- TEMPORAL_M5_DB_PATCH
-- Configuración independiente de clientes para CU106-CU110.
CREATE TABLE finanzas.config_umbral_por_vencer_m5 (
  id_config_umbral_m5 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dias_habiles integer NOT NULL,
  usuario_id_usuario bigint NOT NULL,
  fecha_hora timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT chk_config_umbral_m5_dias CHECK (dias_habiles >= 0),
  CONSTRAINT fk_config_umbral_m5_usuario FOREIGN KEY (usuario_id_usuario)
    REFERENCES terreno.usuario(usuario_id_usuario) ON DELETE RESTRICT
);
CREATE INDEX idx_config_umbral_m5_vigente
  ON finanzas.config_umbral_por_vencer_m5 (fecha_hora DESC, id_config_umbral_m5 DESC);
COMMENT ON TABLE finanzas.config_umbral_por_vencer_m5 IS
  'TEMPORAL_M5_DB_PATCH: historial append-only del umbral Por vencer de proveedores';
