import { useEffect, useState } from 'react';
import { CalendarRange, RefreshCw } from 'lucide-react';
import { solicitarFinanzas } from '../../api/finanzas';
import { usarSesion } from '../../seguridad/Sesion';

type Item={idEmpleado:number;rut:string;nombre:string;estadoLaboral:string;relaciones:{id:number;fechaInicio:string;fechaTermino:string|null}[];remuneracion:{id:number;estado:string}|null;bloqueos:{codigo:string;detalle:string}[];advertencias:{codigo:string;detalle:string}[]};
type Datos={periodo:{id:number|null;anio:number;mes:number;cerradoEn:string|null};resumen:{exigibles:number;sinRemuneracion:number;abiertas:number;cerradas:number;conBloqueos:number};empleados:Item[]};
const post=(body:unknown):RequestInit=>({method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});
async function json(ruta:string,opciones?:RequestInit){const r=await solicitarFinanzas(ruta,opciones);const d=await r.json();if(!r.ok)throw new Error(d.error||'No fue posible completar la operación');return d;}

export default function PeriodosRemuneracion(){
 const {sesion}=usarSesion();const puede181=Boolean(sesion?.permisos.includes('CU181'));const hoy=new Date();
 const [filtro,setFiltro]=useState({anio:hoy.getFullYear(),mes:hoy.getMonth()+1}),[datos,setDatos]=useState<Datos|null>(null),[error,setError]=useState(''),[version,setVersion]=useState(0),[ocupado,setOcupado]=useState(false);
 const cargar=async()=>{setError('');try{setDatos(await json(`/periodos-remuneracion?anio=${filtro.anio}&mes=${filtro.mes}`))}catch(e){setError((e as Error).message)}};
 useEffect(()=>{json(`/periodos-remuneracion?anio=${filtro.anio}&mes=${filtro.mes}`).then(setDatos).catch(e=>setError((e as Error).message))},[version,filtro.anio,filtro.mes]);
 const cerrar=async()=>{setOcupado(true);setError('');try{await json('/periodos-remuneracion/cerrar',post(filtro));setVersion(v=>v+1)}catch(e){setError((e as Error).message)}finally{setOcupado(false)}};
 return <div className="min-h-full bg-gray-50 p-5 lg:p-8"><div className="mx-auto max-w-7xl">
  <header className="mb-6 flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm font-semibold text-primary-600">Remuneraciones</p><h1 className="flex items-center gap-2 text-2xl font-bold"><CalendarRange className="h-6 w-6"/>Períodos de Remuneración</h1></div><button title="Actualizar" onClick={()=>setVersion(v=>v+1)} className="rounded-md border bg-white p-2.5"><RefreshCw className="h-4 w-4"/></button></header>
  <section className="border-y bg-white px-5 py-4"><div className="flex flex-wrap gap-3"><input aria-label="Año" type="number" min="2000" max="2200" value={filtro.anio} onChange={e=>setFiltro({...filtro,anio:Number(e.target.value)})} className="w-28 rounded border p-2"/><select aria-label="Mes" value={filtro.mes} onChange={e=>setFiltro({...filtro,mes:Number(e.target.value)})} className="rounded border p-2">{Array.from({length:12},(_,i)=><option key={i+1} value={i+1}>{new Date(2026,i,1).toLocaleString('es-CL',{month:'long'})}</option>)}</select><button onClick={()=>void cargar()} className="rounded bg-black px-4 text-white">Consultar</button>{puede181&&<button disabled={ocupado||Boolean(datos?.periodo.cerradoEn)} onClick={()=>void cerrar()} className="rounded bg-primary-600 px-4 text-white disabled:opacity-50">Cerrar período</button>}</div></section>
  {error&&<p className="my-4 border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</p>}
  {datos&&<><div className="grid grid-cols-2 gap-3 py-5 md:grid-cols-5">{Object.entries(datos.resumen).map(([k,v])=><div key={k} className="border-l-4 border-primary-500 bg-white p-3"><div className="text-2xl font-bold">{v}</div><div className="text-xs uppercase text-gray-500">{k.replace(/([A-Z])/g,' $1')}</div></div>)}</div><div className="overflow-x-auto border-y bg-white"><table className="w-full min-w-[900px] text-left text-sm"><thead className="border-b text-xs uppercase text-gray-500"><tr><th className="p-3">Empleado</th><th className="p-3">Relaciones del mes</th><th className="p-3">Remuneración</th><th className="p-3">Bloqueos</th><th className="p-3">Advertencias</th></tr></thead><tbody>{datos.empleados.map(x=><tr key={x.idEmpleado} className="border-b align-top"><td className="p-3"><strong>{x.nombre}</strong><div className="text-gray-500">{x.rut} · {x.estadoLaboral}</div></td><td className="p-3">{x.relaciones.map(r=><div key={r.id}>{new Date(r.fechaInicio).toLocaleDateString()} – {r.fechaTermino?new Date(r.fechaTermino).toLocaleDateString():'vigente'}</div>)}</td><td className="p-3">{x.remuneracion?<><strong>#{x.remuneracion.id}</strong><div className="uppercase">{x.remuneracion.estado}</div></>:'No creada'}</td><td className="p-3 text-red-700">{x.bloqueos.map(b=><div key={b.codigo}>{b.detalle}</div>)}</td><td className="p-3 text-amber-700">{x.advertencias.map(a=><div key={a.codigo}>{a.detalle}</div>)}</td></tr>)}</tbody></table></div></>}
 </div></div>;
}
