-- TEMPORAL_M5_DB_PATCH: CU132-CU137.
ALTER TABLE finanzas.categoria_egreso_m5 ADD COLUMN nombre_normalizado varchar(100);
ALTER TABLE finanzas.categoria_egreso_m5 ADD COLUMN creado_por bigint REFERENCES terreno.usuario(usuario_id_usuario) ON DELETE RESTRICT;
ALTER TABLE finanzas.categoria_egreso_m5 ADD COLUMN fecha_creacion timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP;
UPDATE finanzas.categoria_egreso_m5 SET nombre_normalizado=upper(trim(nombre));
ALTER TABLE finanzas.categoria_egreso_m5 ALTER COLUMN nombre_normalizado SET NOT NULL;
CREATE UNIQUE INDEX uq_categoria_egreso_m5_nombre_normalizado ON finanzas.categoria_egreso_m5(nombre_normalizado);
ALTER TABLE finanzas.clasificacion_asociacion_m5 ADD COLUMN nombre_categoria_snapshot varchar(100);
UPDATE finanzas.clasificacion_asociacion_m5 c SET nombre_categoria_snapshot=k.nombre FROM finanzas.categoria_egreso_m5 k WHERE k.id_categoria_egreso_m5=c.id_categoria_egreso_m5;

CREATE TABLE finanzas.compensacion_saldo_favor_m5 (
 id_compensacion_m5 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 id_saldo_favor_m5 integer NOT NULL REFERENCES finanzas.saldo_favor_proveedor_m5(id_saldo_favor_m5) ON DELETE RESTRICT,
 id_proveedor integer NOT NULL REFERENCES finanzas.proveedor(id_proveedor) ON DELETE RESTRICT,
 id_moneda integer NOT NULL REFERENCES finanzas.moneda(id_moneda) ON DELETE RESTRICT,
 monto_total numeric(14,2) NOT NULL CHECK(monto_total>0), estado varchar(20) NOT NULL DEFAULT 'confirmada' CHECK(estado IN ('confirmada','revertida_parcial','revertida_total')),
 creado_por bigint NOT NULL REFERENCES terreno.usuario(usuario_id_usuario) ON DELETE RESTRICT, fecha_creacion timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE finanzas.detalle_compensacion_saldo_favor_m5 (
 id_detalle_compensacion_m5 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 id_compensacion_m5 integer NOT NULL REFERENCES finanzas.compensacion_saldo_favor_m5(id_compensacion_m5) ON DELETE RESTRICT,
 id_obligacion_m5 integer NOT NULL REFERENCES finanzas.obligacion_proveedor_m5(id_obligacion_m5) ON DELETE RESTRICT,
 monto_aplicado numeric(14,2) NOT NULL CHECK(monto_aplicado>0), UNIQUE(id_compensacion_m5,id_obligacion_m5)
);
CREATE INDEX idx_detalle_compensacion_obligacion ON finanzas.detalle_compensacion_saldo_favor_m5(id_obligacion_m5);
CREATE TABLE finanzas.reversion_compensacion_m5 (
 id_reversion_compensacion_m5 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 id_detalle_compensacion_m5 integer NOT NULL REFERENCES finanzas.detalle_compensacion_saldo_favor_m5(id_detalle_compensacion_m5) ON DELETE RESTRICT,
 monto_revertido numeric(14,2) NOT NULL CHECK(monto_revertido>0), motivo text NOT NULL,
 id_respaldo_pago_m5 integer NOT NULL REFERENCES finanzas.respaldo_pago_proveedor_m5(id_respaldo_pago_m5) ON DELETE RESTRICT,
 usuario_id_usuario bigint NOT NULL REFERENCES terreno.usuario(usuario_id_usuario) ON DELETE RESTRICT, fecha_hora timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE finanzas.historial_categoria_egreso_m5 (
 id_historial_categoria_m5 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 id_categoria_egreso_m5 integer NOT NULL REFERENCES finanzas.categoria_egreso_m5(id_categoria_egreso_m5) ON DELETE RESTRICT,
 nombre_anterior varchar(100), nombre_nuevo varchar(100), activo_anterior boolean, activo_nuevo boolean,
 motivo text, usuario_id_usuario bigint NOT NULL REFERENCES terreno.usuario(usuario_id_usuario) ON DELETE RESTRICT, fecha_hora timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE finanzas.config_umbral_reclasificacion_m5 (
 id_configuracion integer PRIMARY KEY CHECK(id_configuracion=1), monto_clp numeric(14,2) NOT NULL CHECK(monto_clp>=0), actualizado_por bigint REFERENCES terreno.usuario(usuario_id_usuario) ON DELETE RESTRICT, fecha_actualizacion timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO finanzas.config_umbral_reclasificacion_m5(id_configuracion,monto_clp) VALUES(1,1000000);
CREATE TABLE finanzas.historial_umbral_reclasificacion_m5 (
 id_historial_umbral_m5 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, monto_anterior_clp numeric(14,2) NOT NULL, monto_nuevo_clp numeric(14,2) NOT NULL,
 usuario_id_usuario bigint NOT NULL REFERENCES terreno.usuario(usuario_id_usuario) ON DELETE RESTRICT, fecha_hora timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE finanzas.reclasificacion_egreso_m5 (
 id_reclasificacion_m5 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 id_documento_m5 integer NOT NULL REFERENCES finanzas.documento_proveedor_m5(id_documento_m5) ON DELETE RESTRICT,
 monto_total numeric(14,2) NOT NULL CHECK(monto_total>0), monto_referencia_clp numeric(14,2) NOT NULL CHECK(monto_referencia_clp>0), umbral_snapshot_clp numeric(14,2) NOT NULL CHECK(umbral_snapshot_clp>=0),
 motivo text NOT NULL, estado varchar(20) NOT NULL CHECK(estado IN ('pendiente','aprobada','rechazada')),
 solicitado_por bigint NOT NULL REFERENCES terreno.usuario(usuario_id_usuario) ON DELETE RESTRICT, fecha_solicitud timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
 resuelto_por bigint REFERENCES terreno.usuario(usuario_id_usuario) ON DELETE RESTRICT, fecha_resolucion timestamptz, motivo_rechazo text
);
CREATE TABLE finanzas.detalle_reclasificacion_egreso_m5 (
 id_detalle_reclasificacion_m5 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 id_reclasificacion_m5 integer NOT NULL REFERENCES finanzas.reclasificacion_egreso_m5(id_reclasificacion_m5) ON DELETE RESTRICT,
 id_clasificacion_origen_m5 integer NOT NULL REFERENCES finanzas.clasificacion_asociacion_m5(id_clasificacion_m5) ON DELETE RESTRICT,
 id_asociacion_m5 integer NOT NULL REFERENCES finanzas.asociacion_documento_oc_m5(id_asociacion_m5) ON DELETE RESTRICT,
 id_categoria_origen_m5 integer NOT NULL REFERENCES finanzas.categoria_egreso_m5(id_categoria_egreso_m5) ON DELETE RESTRICT,
 id_categoria_destino_m5 integer NOT NULL REFERENCES finanzas.categoria_egreso_m5(id_categoria_egreso_m5) ON DELETE RESTRICT,
 monto numeric(14,2) NOT NULL CHECK(monto>0)
);
COMMENT ON TABLE finanzas.compensacion_saldo_favor_m5 IS 'TEMPORAL_M5_DB_PATCH TEMPORAL_M5_REGLA_MONEDA_COMPENSACION';
COMMENT ON TABLE finanzas.reclasificacion_egreso_m5 IS 'TEMPORAL_M5_DB_PATCH TEMPORAL_M5_REGLA_UMBRAL_MONEDA';
