import { useEffect, useState } from 'react';
import { Download, FileText, Mail, RefreshCw, Send } from 'lucide-react';
import { solicitarFinanzas } from '../../api/finanzas';
import { usarSesion } from '../../seguridad/Sesion';

type Documento={tipo:'LIQUIDACION'|'COMPROBANTE_ANTICIPO';id:number;idEmpleado:number;empleado:string;periodo:{anio:number;mes:number};vigente:boolean;condicion:string};
type Archivo={nombre:string;mime:string;contenido:string};
const json=async(ruta:string,opciones?:RequestInit)=>{const r=await solicitarFinanzas(ruta,opciones);const d=await r.json();if(!r.ok)throw new Error(d.error||'No fue posible completar la operación');return d};
const post=(body:unknown):RequestInit=>({method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});
const descargar=(archivo:Archivo)=>{const enlace=document.createElement('a');enlace.href=archivo.contenido;enlace.download=archivo.nombre;enlace.click()};

export default function DocumentosRemuneracion(){
 const {sesion}=usarSesion();const puede=(cu:string)=>Boolean(sesion?.permisos.includes(cu));const hoy=new Date();
 const [filtro,setFiltro]=useState(()=>({idEmpleado:new URLSearchParams(window.location.search).get('idEmpleado')||'',anio:String(hoy.getFullYear()),mes:String(hoy.getMonth()+1)})),[documentos,setDocumentos]=useState<Documento[]>([]),[error,setError]=useState(''),[mensaje,setMensaje]=useState(''),[ocupado,setOcupado]=useState('');
 const cargar=async()=>{setError('');const q=new URLSearchParams();if(filtro.idEmpleado)q.set('idEmpleado',filtro.idEmpleado);if(filtro.anio)q.set('anio',filtro.anio);if(filtro.mes)q.set('mes',filtro.mes);setDocumentos(await json(`/documentos-remuneracion?${q}`))};
 useEffect(()=>{void cargar().catch(e=>setError(e.message))},[]);
 const ejecutar=async(clave:string,accion:()=>Promise<void>)=>{setOcupado(clave);setError('');setMensaje('');try{await accion()}catch(e){setError((e as Error).message)}finally{setOcupado('')}};
 const condicion=async(item:Documento)=>{const dato=await json(`/documentos-remuneracion/${item.tipo}/${item.id}/entrega`);setMensaje(dato.condicion?`Última condición documental: ${dato.condicion.resultado} · ${new Date(dato.condicion.fecha).toLocaleString('es-CL')}`:'Sin condición documental registrada')};
 const registrar=async(item:Documento)=>{const canal=window.prompt('Canal: presencial, correo_particular, correo_corporativo u otro','presencial');const resultado=window.prompt('Resultado: entregado, rechazado o pendiente','entregado');if(!canal||!resultado)return;await json('/documentos-remuneracion/entregas',post({tipo:item.tipo,id:item.id,canal,resultado,destinatarioLogico:'empleado'}));setMensaje('Entrega registrada')};
 return <div className="min-h-full bg-gray-50 p-5 lg:p-8"><div className="mx-auto max-w-7xl">
  <header className="mb-6 flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm font-semibold text-primary-600">Remuneraciones</p><h1 className="flex items-center gap-2 text-2xl font-bold"><FileText className="h-6 w-6"/>Documentos de Remuneración</h1></div><button title="Actualizar" onClick={()=>void cargar()} className="rounded-md border bg-white p-2.5"><RefreshCw className="h-4 w-4"/></button></header>
  <section className="border-y bg-white px-5 py-4"><div className="grid gap-3 md:grid-cols-[1fr_130px_150px_auto]"><input aria-label="ID empleado" placeholder="ID empleado (opcional)" value={filtro.idEmpleado} onChange={e=>setFiltro({...filtro,idEmpleado:e.target.value})} className="rounded border p-2.5"/><input aria-label="Año" type="number" value={filtro.anio} onChange={e=>setFiltro({...filtro,anio:e.target.value})} className="rounded border p-2.5"/><select aria-label="Mes" value={filtro.mes} onChange={e=>setFiltro({...filtro,mes:e.target.value})} className="rounded border p-2.5"><option value="">Todos</option>{Array.from({length:12},(_,i)=><option key={i+1} value={i+1}>{new Date(2026,i,1).toLocaleString('es-CL',{month:'long'})}</option>)}</select><button onClick={()=>void ejecutar('buscar',cargar)} className="rounded bg-black px-4 text-white">Consultar</button></div></section>
  {error&&<p className="my-4 border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</p>}{mensaje&&<p className="my-4 border border-green-200 bg-green-50 p-3 text-sm text-green-800">{mensaje}</p>}
  <div className="mt-5 overflow-x-auto border-y bg-white"><table className="w-full min-w-[850px] text-left text-sm"><thead className="border-b text-xs uppercase text-gray-500"><tr><th className="p-3">Documento</th><th className="p-3">Empleado</th><th className="p-3">Período</th><th className="p-3">Condición</th><th className="p-3 text-right">Acciones</th></tr></thead><tbody>{documentos.map(item=><tr key={`${item.tipo}-${item.id}`} className="border-b"><td className="p-3"><strong>{item.tipo==='LIQUIDACION'?'Liquidación':'Comprobante de anticipo'}</strong><div className="text-gray-500">#{item.id}</div></td><td className="p-3">{item.empleado}</td><td className="p-3">{String(item.periodo.mes).padStart(2,'0')}/{item.periodo.anio}</td><td className="p-3"><span className={`inline-flex rounded border px-2 py-1 text-xs font-semibold ${item.vigente?'border-green-200 text-green-800':'border-gray-300 text-gray-600'}`}>{item.condicion.replaceAll('_',' ')}</span></td><td className="p-3"><div className="flex justify-end gap-2"><button title="Descargar" disabled={ocupado!==''} onClick={()=>void ejecutar(`d${item.tipo}${item.id}`,async()=>descargar(await json(`/documentos-remuneracion/${item.tipo}/${item.id}/descarga`)))} className="rounded border p-2"><Download className="h-4 w-4"/></button>{puede('CU192')&&item.vigente&&<button title="Reenviar por correo" onClick={()=>void ejecutar(`r${item.tipo}${item.id}`,async()=>{await json(`/documentos-remuneracion/${item.tipo}/${item.id}/reenviar`,post({}));setMensaje('Documento reenviado y trazado')})} className="rounded border p-2"><Mail className="h-4 w-4"/></button>}{puede('CU193')&&<><button title="Consultar entrega" onClick={()=>void ejecutar(`c${item.tipo}${item.id}`,()=>condicion(item))} className="rounded border p-2"><FileText className="h-4 w-4"/></button><button title="Registrar entrega" onClick={()=>void ejecutar(`e${item.tipo}${item.id}`,()=>registrar(item))} className="rounded border p-2"><Send className="h-4 w-4"/></button></>}</div></td></tr>)}</tbody></table>{!documentos.length&&<p className="p-6 text-center text-sm text-gray-500">No hay documentos oficiales para los filtros.</p>}</div>
 </div></div>;
}
