ALTER TABLE "finanzas"."concepto_remuneracion"
  ADD COLUMN "codigo_m6" VARCHAR(40),
  ADD CONSTRAINT "uq_concepto_remuneracion_codigo_m6" UNIQUE ("codigo_m6");

CREATE TABLE "finanzas"."asignacion_concepto_remuneracion_empleado" (
  "id_asignacion_concepto" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_empleado" INTEGER NOT NULL,
  "id_concepto" INTEGER NOT NULL,
  "vigencia_desde" DATE NOT NULL,
  "vigencia_hasta" DATE,
  "valor_aplicable" NUMERIC(14,4),
  "activa" BOOLEAN NOT NULL DEFAULT TRUE,
  CONSTRAINT "chk_asignacion_concepto_vigencia" CHECK ("vigencia_hasta" IS NULL OR "vigencia_hasta" >= "vigencia_desde"),
  CONSTRAINT "chk_asignacion_concepto_valor" CHECK ("valor_aplicable" IS NULL OR "valor_aplicable" >= 0),
  CONSTRAINT "fk_asignacion_concepto_empleado" FOREIGN KEY ("id_empleado") REFERENCES "finanzas"."empleado"("id_empleado") ON DELETE RESTRICT,
  CONSTRAINT "fk_asignacion_concepto_catalogo" FOREIGN KEY ("id_concepto") REFERENCES "finanzas"."concepto_remuneracion"("id_concepto_remuneracion") ON DELETE RESTRICT
);

CREATE INDEX "idx_asignacion_concepto_empleado" ON "finanzas"."asignacion_concepto_remuneracion_empleado" ("id_empleado", "vigencia_desde");
CREATE INDEX "idx_asignacion_concepto_concepto" ON "finanzas"."asignacion_concepto_remuneracion_empleado" ("id_concepto", "vigencia_desde");
