-- TEMPORAL_M5_DB_PATCH
-- Efectos postpago y control bancario para CU121-CU126.
ALTER TABLE finanzas.obligacion_proveedor_m5
  ALTER COLUMN condicion_temporal DROP NOT NULL;

CREATE TABLE finanzas.anulacion_movimiento_pago_m5 (
  id_anulacion_movimiento_m5 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_movimiento_pago_m5 integer NOT NULL REFERENCES finanzas.movimiento_pago_proveedor_m5(id_movimiento_pago_m5) ON DELETE RESTRICT,
  monto_anulado numeric(14,2) NOT NULL,
  motivo text NOT NULL,
  id_respaldo_pago_m5 integer NOT NULL REFERENCES finanzas.respaldo_pago_proveedor_m5(id_respaldo_pago_m5) ON DELETE RESTRICT,
  usuario_id_usuario bigint NOT NULL REFERENCES terreno.usuario(usuario_id_usuario) ON DELETE RESTRICT,
  fecha_hora timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  grupo_operacion varchar(36),
  CONSTRAINT uq_anulacion_movimiento_pago_m5 UNIQUE (id_movimiento_pago_m5),
  CONSTRAINT chk_anulacion_movimiento_pago_m5_monto CHECK (monto_anulado > 0)
);
CREATE INDEX idx_anulacion_pago_m5_grupo ON finanzas.anulacion_movimiento_pago_m5(grupo_operacion);

CREATE TABLE finanzas.reversion_movimiento_pago_m5 (
  id_reversion_movimiento_m5 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_movimiento_pago_m5 integer NOT NULL REFERENCES finanzas.movimiento_pago_proveedor_m5(id_movimiento_pago_m5) ON DELETE RESTRICT,
  monto_revertido numeric(14,2) NOT NULL,
  motivo text NOT NULL,
  id_respaldo_pago_m5 integer NOT NULL REFERENCES finanzas.respaldo_pago_proveedor_m5(id_respaldo_pago_m5) ON DELETE RESTRICT,
  usuario_id_usuario bigint NOT NULL REFERENCES terreno.usuario(usuario_id_usuario) ON DELETE RESTRICT,
  fecha_hora timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT chk_reversion_movimiento_pago_m5_monto CHECK (monto_revertido > 0)
);
CREATE INDEX idx_reversion_pago_m5_movimiento ON finanzas.reversion_movimiento_pago_m5(id_movimiento_pago_m5, fecha_hora);

CREATE TABLE finanzas.conciliacion_movimiento_pago_m5 (
  id_conciliacion_movimiento_m5 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_movimiento_pago_m5 integer NOT NULL REFERENCES finanzas.movimiento_pago_proveedor_m5(id_movimiento_pago_m5) ON DELETE RESTRICT,
  resultado varchar(20) NOT NULL,
  observacion text,
  usuario_id_usuario bigint NOT NULL REFERENCES terreno.usuario(usuario_id_usuario) ON DELETE RESTRICT,
  fecha_hora timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT chk_conciliacion_movimiento_pago_m5_resultado CHECK (resultado IN ('conciliado','con_discrepancia')),
  CONSTRAINT chk_conciliacion_movimiento_pago_m5_observacion CHECK (resultado <> 'con_discrepancia' OR length(trim(observacion)) > 0)
);
CREATE INDEX idx_conciliacion_pago_m5_movimiento ON finanzas.conciliacion_movimiento_pago_m5(id_movimiento_pago_m5, fecha_hora DESC, id_conciliacion_movimiento_m5 DESC);

COMMENT ON TABLE finanzas.anulacion_movimiento_pago_m5 IS 'TEMPORAL_M5_DB_PATCH: CU124 conserva el pago original y registra que no ocurrió';
COMMENT ON TABLE finanzas.reversion_movimiento_pago_m5 IS 'TEMPORAL_M5_DB_PATCH: CU125 registra devoluciones posteriores del proveedor';
COMMENT ON TABLE finanzas.conciliacion_movimiento_pago_m5 IS 'TEMPORAL_M5_DB_PATCH: CU126 control bancario sin efecto financiero';
