const {test}=require('node:test');const assert=require('node:assert/strict');const {randomUUID}=require('node:crypto');
const {prisma}=require('../dist/db');const {M2Controller}=require('../dist/controladores/M2Controller');const {M3Controller}=require('../dist/controladores/M3Controller');const {C_Finanzas}=require('../dist/controladores/C_Finanzas');
test('delta CU25/CU38/CU43/CU47/CU49/CU50: consistencia financiera',async t=>{
 const m2=new M2Controller(),m3=new M3Controller();const cotizaciones=[],notas=[];
 const actor={id:999999n,permisos:['CU25','CU38','CU43']};const fachada=new C_Finanzas({autorizar:async()=>actor},undefined,m2,m3);
 const cliente=await prisma.cliente_financiero.findFirstOrThrow({where:{referencia_demostracion:'I2-CLIENTE-persona'},include:{ficha_cliente:true}}).catch(()=>prisma.cliente_financiero.findFirstOrThrow({where:{nombre_razon_social_referencia:{contains:'Elena Robles'}},include:{ficha_cliente:true}}));
 const clp=await prisma.moneda.findUniqueOrThrow({where:{codigo_moneda:'CLP'}});const usd=await prisma.moneda.findUniqueOrThrow({where:{codigo_moneda:'USD'}});
 const medio=await prisma.medio_pago.findFirstOrThrow({where:{estado_medio_pago:'activo',nombre_medio_pago:{contains:'Transferencia'}}});
 const tipo=await prisma.tipo_documento.findFirstOrThrow({where:{nombre_tipo_documento:'Factura Electrónica'}});
 const documento=await prisma.documento_tributario.create({data:{id_ficha_cliente:cliente.ficha_cliente.id_ficha_cliente,id_tipo_documento:tipo.id_tipo_documento,id_moneda:clp.id_moneda,folio_documento:`TEST-${randomUUID()}`,fecha_emision:new Date(),monto_neto:100,monto_impuesto:0,monto_total:100}});
 const pago={monto:60,idDocumento:documento.id_documento_tributario,idMedio:medio.id_medio_pago,respaldo:'Referencia ficticia de prueba'};
 async function cotizar(moneda=clp){const c=await prisma.cotizacion.create({data:{id_ficha_cliente:cliente.ficha_cliente.id_ficha_cliente,id_moneda:moneda.id_moneda,fecha_emision:new Date(),fecha_vigencia:new Date('2030-01-01'),estado_cotizacion:'emitida',monto_neto:100,monto_impuesto:0,monto_total_estimado:100,exento_iva:true}});cotizaciones.push(c.id_cotizacion);return c;}
 try{
  const c=await cotizar();
  await t.test('CU25 falla de pago no deja NV ni aprueba cotización',async()=>{await assert.rejects(fachada.ejecutar('consolidarB2C',{parametros:{id:c.id_cotizacion},cuerpo:{...pago,monto:101},contexto:{}}),/saldo/);assert.equal(await prisma.nota_venta.count({where:{id_cotizacion:c.id_cotizacion}}),0);assert.equal((await prisma.cotizacion.findUnique({where:{id_cotizacion:c.id_cotizacion}})).estado_cotizacion,'emitida');});
  let resultado;
  await t.test('CU25 éxito conserva cotización, NV y pago atómicamente',async()=>{resultado=await fachada.ejecutar('consolidarB2C',{parametros:{id:c.id_cotizacion},cuerpo:pago,contexto:{}});notas.push(resultado.idNota);assert.equal((await prisma.cotizacion.findUnique({where:{id_cotizacion:c.id_cotizacion}})).estado_cotizacion,'aprobada');assert.equal((await m3.consultarSaldo(resultado.idNota)).saldoPendiente,40);await assert.rejects(m2.consolidarB2C(c.id_cotizacion,pago,'prueba'),/consolidada/);});
  const pdf='data:application/pdf;base64,'+Buffer.from('%PDF-1.4\n% Documento ficticio de prueba\n%%EOF').toString('base64');
  const reversion={monto:70,montoDocumento:70,motivo:'Prueba automática',folio:`TEST-${randomUUID()}`,respaldoPdf:pdf,confirmacionMontoPdf:true};
  await t.test('CU38 sin decisión revierte toda la transacción',async()=>{await assert.rejects(fachada.ejecutar('revertirVenta',{parametros:{id:resultado.idNota},cuerpo:reversion,contexto:{}}),/elige devolución/);assert.equal((await m3.consultarSaldo(resultado.idNota)).montoComercialVigente,100);assert.equal(await prisma.reversion_nota_venta.count({where:{id_nota_venta:resultado.idNota}}),0);});
  await t.test('CU38 fachada coordina excedente y saldo a favor sin perder monto original',async()=>{const r=await fachada.ejecutar('revertirVenta',{parametros:{id:resultado.idNota},cuerpo:{...reversion,destino:'saldo_favor'},contexto:{}});assert.equal(r.montoOriginal,100);assert.equal(r.montoComercialVigente,30);assert.equal(r.excedenteGestionado,30);assert.equal((await prisma.saldo_favor_cliente.findFirst({where:{id_nota_venta:resultado.idNota}})).monto_disponible.toNumber(),30);});
  await t.test('CU49/CU50 usan monto vigente y no cambian estado comercial',async()=>{const nota=await prisma.nota_venta.findUnique({where:{id_nota_venta:resultado.idNota}});assert.equal(nota.estado_pago,'pagada');assert.equal(nota.estado_nota_venta,'revertida_parcial');assert.equal(nota.monto_total.toNumber(),100);});
  let notaUsd;
  await t.test('CU47 conserva USD y registra tipo de cambio manual real del pago',async()=>{const cUsd=await cotizar(usd);const r=await m2.consolidarB2C(cUsd.id_cotizacion,{...pago,monto:20,tipoCambio:900},'prueba');notaUsd=r.idNota;notas.push(notaUsd);const p=await prisma.pago_cliente.findUnique({where:{id_pago_cliente:r.idPago}});assert.equal(p.monto_pago.toNumber(),20);assert.equal(p.tipo_cambio_usado.toNumber(),900);assert.equal(p.monto_convertido.toNumber(),18000);assert.equal(p.id_moneda,usd.id_moneda);});
  await t.test('CU43 admite parcial y rechaza NV cerrada y sobrepago',async()=>{await m3.registrarPago({...pago,idNota:notaUsd,monto:10,tipoCambio:901},'prueba');assert.equal((await m3.consultarSaldo(notaUsd)).saldoPendiente,70);await assert.rejects(m3.registrarPago({...pago,idNota:notaUsd,monto:71,tipoCambio:901},'prueba'),/saldo/);await prisma.nota_venta.update({where:{id_nota_venta:notaUsd},data:{estado_nota_venta:'cerrada'}});await assert.rejects(m3.registrarPago({...pago,idNota:notaUsd,monto:1,tipoCambio:901},'prueba'),/habilitada/);});
 }finally{
  await prisma.$transaction(async tx=>{const pagos=await tx.asignacion_pago_cliente.findMany({where:{id_nota_venta:{in:notas}},select:{id_pago_cliente:true}});await tx.saldo_favor_cliente.deleteMany({where:{id_nota_venta:{in:notas}}});await tx.reversion_nota_venta.deleteMany({where:{id_nota_venta:{in:notas}}});await tx.asignacion_pago_cliente.deleteMany({where:{id_nota_venta:{in:notas}}});await tx.pago_cliente.deleteMany({where:{id_pago_cliente:{in:pagos.map(p=>p.id_pago_cliente)}}});await tx.documento_tributario_nota_venta.deleteMany({where:{id_nota_venta:{in:notas}}});await tx.nota_venta.deleteMany({where:{id_nota_venta:{in:notas}}});await tx.cotizacion.deleteMany({where:{id_cotizacion:{in:cotizaciones}}});await tx.documento_tributario.delete({where:{id_documento_tributario:documento.id_documento_tributario}});});await prisma.$disconnect();
 }
});
