const {test}=require('node:test');
const assert=require('node:assert/strict');
const {randomUUID}=require('node:crypto');
const {readFileSync}=require('node:fs');
const {resolve}=require('node:path');
const {prisma}=require('../dist/db');
const {M5Controller,calcularFondoCajaChica}=require('../dist/controladores/M5Controller');
const {C_Finanzas}=require('../dist/controladores/C_Finanzas');
const {matrizPermisosPorCU,codigosTodosLosCU,codigosQueRequierenAdministrador,moduloPermiso}=require('../dist/validaciones/permisos');
const {fechaNegocio}=require('../dist/utilidades/finanzas');

test('M5 P11 CU146-CU154 cierra importaciones y administra Caja Chica mensual',async t=>{
 const modulo=new M5Controller();const usuario=await prisma.usuario.findFirstOrThrow();const clp=await prisma.moneda.findUniqueOrThrow({where:{codigo_moneda:'CLP'}});const periodo=fechaNegocio().slice(0,7);const [anio,mes]=periodo.split('-').map(Number);const ids={envios:[],gastos:[],respaldosPago:[]};const fondoAnterior=await prisma.fondo_caja_chica_m5.findUnique({where:{anio_mes:{anio,mes}}});
 try{
  await t.test('CU146-CU148 mantienen revisión editable, cierre consolidado y reapertura con historial',async()=>{let envio=await modulo.crearEnvioImportacion({referencia:`P11-${randomUUID()}`,fecha:fechaNegocio(),descripcion:'Ciclo P11'},usuario.usuario_id_usuario);ids.envios.push(envio.id);const costo=await modulo.registrarCostoEnvio(envio.id,{tipoCosto:'flete',fuente:'directo',idMoneda:clp.id_moneda,monto:1200,nombreArchivo:'flete.pdf',contenido:'data:application/pdf;base64,AA=='},usuario.usuario_id_usuario);const costoDb=await prisma.costo_envio_importacion_m5.findUniqueOrThrow({where:{id_costo_envio_m5:costo.id}});if(costoDb.id_respaldo_pago_m5)ids.respaldosPago.push(costoDb.id_respaldo_pago_m5);envio=await modulo.pasarEnvioRevision(envio.id,usuario.usuario_id_usuario);assert.equal(envio.estado,'en_revision');await modulo.actualizarCostoEnvio(envio.id,costo.id,{monto:1300,motivo:'Costo real confirmado'},usuario.usuario_id_usuario);envio=await modulo.cerrarFinancieramenteEnvio(envio.id,usuario.usuario_id_usuario);assert.equal(envio.estado,'cerrado_financieramente');assert.equal(envio.costoFinanciero.totalClp,1300);await assert.rejects(modulo.pasarEnvioRevision(envio.id,usuario.usuario_id_usuario),e=>e.estado===409);await assert.rejects(modulo.reabrirEnvio(envio.id,{},usuario.usuario_id_usuario),e=>e.estado===400);envio=await modulo.reabrirEnvio(envio.id,{motivo:'Costo tardío'},usuario.usuario_id_usuario);await modulo.registrarCostoEnvio(envio.id,{tipoCosto:'aduana',fuente:'directo',idMoneda:clp.id_moneda,monto:200,nombreArchivo:'aduana.pdf',contenido:'data:application/pdf;base64,AA=='},usuario.usuario_id_usuario);envio=await modulo.cerrarFinancieramenteEnvio(envio.id,usuario.usuario_id_usuario);assert.equal(envio.estado,'cerrado_financieramente');assert.equal(envio.historial.filter(h=>h.evento==='cierre_financiero').length,2);assert.ok(envio.historial.some(h=>h.evento==='reapertura'))});
  await t.test('CU147 bloquea costo sin equivalente y no confunde deuda pendiente con costo incompleto',async()=>{const usd=await prisma.moneda.findUniqueOrThrow({where:{codigo_moneda:'USD'}});let envio=await modulo.crearEnvioImportacion({referencia:`P11-USD-${randomUUID()}`,fecha:fechaNegocio()},usuario.usuario_id_usuario);ids.envios.push(envio.id);const costo=await modulo.registrarCostoEnvio(envio.id,{tipoCosto:'seguro',fuente:'directo',idMoneda:usd.id_moneda,monto:10,nombreArchivo:'usd.pdf',contenido:'data:application/pdf;base64,AA=='},usuario.usuario_id_usuario);const costoDb=await prisma.costo_envio_importacion_m5.findUniqueOrThrow({where:{id_costo_envio_m5:costo.id}});if(costoDb.id_respaldo_pago_m5)ids.respaldosPago.push(costoDb.id_respaldo_pago_m5);await modulo.pasarEnvioRevision(envio.id,usuario.usuario_id_usuario);await assert.rejects(modulo.cerrarFinancieramenteEnvio(envio.id,usuario.usuario_id_usuario),e=>e.estado===409&&/equivalente/.test(e.message))});
  await t.test('CU149-CU152 separan meses, reservan al registrar y factura sigue siendo sólo respaldo',async()=>{await modulo.configurarFondoCajaChica(periodo,{monto:500},usuario.usuario_id_usuario);const gasto=await modulo.registrarGastoCajaChica({monto:600,descripcion:`Exceso ${randomUUID()}`,fecha:fechaNegocio(),comercioEmisor:'Comercio sin proveedor'},usuario.usuario_id_usuario);ids.gastos.push(gasto.id);let caja=await modulo.consultarCajaChica({periodo});assert.equal(caja.reservado>=600,true);assert.equal(caja.disponibleProyectado<0,true);const obligacionesAntes=await prisma.obligacion_proveedor_m5.count();await modulo.adjuntarRespaldoCajaChica(gasto.id,{nombreArchivo:'factura-caja.pdf',contenido:'data:application/pdf;base64,AA==',tipoRespaldo:'factura',comercioEmisor:'Comercio sin proveedor'},usuario.usuario_id_usuario);assert.equal(await prisma.obligacion_proveedor_m5.count(),obligacionesAntes);const otroMes=mes===12?`${anio+1}-01`:`${anio}-${String(mes+1).padStart(2,'0')}`;const consultaOtro=await modulo.consultarCajaChica({periodo:otroMes});assert.equal(consultaOtro.reservado,0);assert.equal(consultaOtro.aprobado,0);assert.deepEqual(calcularFondoCajaChica(500,[{monto:600,estado:'pendiente'}]),{fondo:500,reservado:600,aprobado:0,disponibleProyectado:-100})});
  await t.test('CU153 aplica segregación de exceso y no descuenta dos veces',async()=>{const gastoId=ids.gastos[0];await assert.rejects(modulo.aprobarGastoCajaChica(gastoId,usuario.usuario_id_usuario,'contador'),e=>e.estado===403);const antes=await modulo.consultarCajaChica({periodo});const caja=await modulo.aprobarGastoCajaChica(gastoId,usuario.usuario_id_usuario,'gerencia');const gasto=caja.gastos.find(g=>g.id===gastoId);assert.equal(gasto.estado,'aprobado');assert.equal(gasto.condicionAprobacion,'exceso');assert.equal(caja.reservado,antes.reservado-600);assert.equal(caja.aprobado,antes.aprobado+600);assert.equal(caja.reservado+caja.aprobado,antes.reservado+antes.aprobado);await assert.rejects(modulo.aprobarGastoCajaChica(gastoId,usuario.usuario_id_usuario,'gerencia'),e=>e.estado===409)});
  await t.test('CU154 libera la reserva histórica, conserva el gasto y evita doble resolución',async()=>{const gasto=await modulo.registrarGastoCajaChica({monto:50,descripcion:`Rechazo ${randomUUID()}`,fecha:fechaNegocio()},usuario.usuario_id_usuario);ids.gastos.push(gasto.id);const antes=await modulo.consultarCajaChica({periodo});const despues=await modulo.rechazarGastoCajaChica(gasto.id,{motivo:'No corresponde'},usuario.usuario_id_usuario);assert.equal(despues.reservado,antes.reservado-50);assert.equal(despues.gastos.find(g=>g.id===gasto.id).estado,'rechazado');await assert.rejects(modulo.aprobarGastoCajaChica(gasto.id,usuario.usuario_id_usuario,'gerencia'),e=>e.estado===409);const concurrente=await modulo.registrarGastoCajaChica({monto:25,descripcion:`Concurrente ${randomUUID()}`,fecha:fechaNegocio()},usuario.usuario_id_usuario);ids.gastos.push(concurrente.id);await modulo.adjuntarRespaldoCajaChica(concurrente.id,{nombreArchivo:'respaldo.pdf',contenido:'x'},usuario.usuario_id_usuario);const resultados=await Promise.allSettled([modulo.aprobarGastoCajaChica(concurrente.id,usuario.usuario_id_usuario,'gerencia'),modulo.rechazarGastoCajaChica(concurrente.id,{motivo:'Resolución simultánea'},usuario.usuario_id_usuario)]);assert.equal(resultados.filter(r=>r.status==='fulfilled').length,1);assert.equal(resultados.filter(r=>r.status==='rejected').length,1)});
  await t.test('permisos y fachada respetan actores CU146-CU154 y CU150 exige Administrador',async()=>{for(const cu of ['CU146','CU147','CU149','CU151','CU152'])assert.deepEqual([...matrizPermisosPorCU[cu]].sort(),['contador','gerencia','secretaria']);for(const cu of ['CU148','CU153','CU154'])assert.deepEqual([...matrizPermisosPorCU[cu]].sort(),['contador','gerencia']);assert.deepEqual(matrizPermisosPorCU.CU150,['gerencia']);assert.ok(codigosQueRequierenAdministrador.has('CU150'));let llamada=false;const fachada=new C_Finanzas({autorizar:async()=>({id:usuario.usuario_id_usuario,permisos:['CU153'],configuracion:'secretaria',administrador:false})},{},{},{},{},{aprobarGastoCajaChica:async()=>{llamada=true}});await assert.rejects(fachada.ejecutar('aprobarGastoCajaChica',{parametros:{gastoId:'1'},contexto:{}}),e=>e.estado===403);assert.equal(llamada,false)});
  await t.test('integridad final reconoce CU75-CU154, total 80, sin CU155 y arquitectura vigente',()=>{assert.equal(codigosTodosLosCU.length,154);assert.deepEqual(codigosTodosLosCU.slice(74),Array.from({length:80},(_,i)=>`CU${75+i}`));assert.equal(codigosTodosLosCU.includes('CU155'),false);assert.ok(codigosTodosLosCU.slice(74).every(c=>moduloPermiso(c)==='M5'));const fachada=readFileSync(resolve('src/controladores/C_Finanzas.ts'),'utf8');const api=readFileSync(resolve('../Vistas/src/api/finanzas.ts'),'utf8');const vistas=[readFileSync(resolve('../Vistas/src/views/EnviosImportaciones/EnviosImportaciones.tsx'),'utf8'),readFileSync(resolve('../Vistas/src/views/CajaChica/CajaChica.tsx'),'utf8')].join('\n');assert.match(fachada,/M5Controller/);assert.match(api,/\/api\/finanzas/);assert.doesNotMatch(vistas,/https?:\/\/(?:localhost|127\.0\.0\.1)/);assert.doesNotMatch([fachada,vistas,readFileSync(resolve('src/validaciones/permisos.ts'),'utf8')].join('\n'),/CU155/)});
 }finally{
  const respaldosCaja=await prisma.respaldo_gasto_caja_chica_m5.findMany({where:{id_gasto_caja_chica_m5:{in:ids.gastos}}});await prisma.historial_gasto_caja_chica_m5.deleteMany({where:{id_gasto_caja_chica_m5:{in:ids.gastos}}});await prisma.respaldo_gasto_caja_chica_m5.deleteMany({where:{id_respaldo_gasto_m5:{in:respaldosCaja.map(r=>r.id_respaldo_gasto_m5)}}});await prisma.gasto_caja_chica_m5.deleteMany({where:{id_gasto_caja_chica_m5:{in:ids.gastos}}});const costos=await prisma.costo_envio_importacion_m5.findMany({where:{id_envio_importacion_m5:{in:ids.envios}}});await prisma.historial_envio_importacion_m5.deleteMany({where:{id_envio_importacion_m5:{in:ids.envios}}});await prisma.costo_envio_importacion_m5.deleteMany({where:{id_envio_importacion_m5:{in:ids.envios}}});await prisma.envio_orden_compra_m5.deleteMany({where:{id_envio_importacion_m5:{in:ids.envios}}});await prisma.envio_importacion_m5.deleteMany({where:{id_envio_importacion_m5:{in:ids.envios}}});await prisma.respaldo_pago_proveedor_m5.deleteMany({where:{id_respaldo_pago_m5:{in:[...ids.respaldosPago,...costos.map(c=>c.id_respaldo_pago_m5).filter(Boolean)]}}});const fondo=await prisma.fondo_caja_chica_m5.findUnique({where:{anio_mes:{anio,mes}}});if(fondo){await prisma.historial_fondo_caja_chica_m5.deleteMany({where:{id_fondo_caja_chica_m5:fondo.id_fondo_caja_chica_m5}});if(fondoAnterior)await prisma.fondo_caja_chica_m5.update({where:{id_fondo_caja_chica_m5:fondo.id_fondo_caja_chica_m5},data:{monto:fondoAnterior.monto,actualizado_por:fondoAnterior.actualizado_por,fecha_actualizacion:fondoAnterior.fecha_actualizacion}});else await prisma.fondo_caja_chica_m5.delete({where:{id_fondo_caja_chica_m5:fondo.id_fondo_caja_chica_m5}})}
 }
});
