const {test}=require('node:test');const assert=require('node:assert/strict');const {randomUUID}=require('node:crypto');
const {prisma}=require('../dist/db');const {M5Controller,calcularSaldoObligacion,derivarEstadoMovimientoPago,derivarEstadoOperacionPago}=require('../dist/controladores/M5Controller');const {C_Finanzas}=require('../dist/controladores/C_Finanzas');const {matrizPermisosPorCU,codigosTodosLosCU}=require('../dist/validaciones/permisos');

test('M5 P7 CU121-CU126 formaliza saldos y efectos postpago',async t=>{
 const ids={proveedores:[],documentos:[],obligaciones:[],operaciones:[],medios:[]};let usuario,pais,tipoId,tipoDoc,clp,usd,medio;const modulo=new M5Controller({obtenerTipoCambio:async()=>900});
 const proveedor=async(nombre)=>{const p=await prisma.proveedor.create({data:{id_pais:pais.id_pais,id_tipo_identificador:tipoId.id_tipo_identificador,identificador_tributario:`P7-${randomUUID()}`,nombre_razon_social:`${nombre}-${randomUUID()}`,tipo_proveedor_m5:'Servicios',estado_proveedor:'activo'}});ids.proveedores.push(p.id_proveedor);return p};
 const obligacion=async(p,monto=100,moneda=clp,vencimiento='2026-09-01')=>{const d=await prisma.documento_proveedor_m5.create({data:{id_proveedor:p.id_proveedor,clase:'definitivo',id_tipo_documento:tipoDoc.id_tipo_documento,folio:`P7-${randomUUID()}`,folio_normalizado:`P7-${randomUUID()}`,fecha_emision:new Date('2026-08-01T00:00:00Z'),id_moneda:moneda.id_moneda,monto_total:monto,estado:'confirmado',creado_por:usuario.usuario_id_usuario}});ids.documentos.push(d.id_documento_m5);const o=await prisma.obligacion_proveedor_m5.create({data:{id_documento_m5:d.id_documento_m5,id_proveedor:p.id_proveedor,monto_original:monto,id_moneda:moneda.id_moneda,saldo_inicial:monto,saldo_actual:monto,fecha_emision:d.fecha_emision,fecha_vencimiento:new Date(`${vencimiento}T00:00:00Z`),estado_pago:'Pendiente',condicion_temporal:'Vencida',generado_por:usuario.usuario_id_usuario}});ids.obligaciones.push(o.id_obligacion_m5);return o};
 const confirmar=async(p,movs)=>{let op=await modulo.crearOperacionPago({idProveedor:p.id_proveedor,fechaEfectivaPago:'2026-09-20'},usuario.usuario_id_usuario);ids.operaciones.push(op.id);for(const mov of movs)op=await modulo.agregarMovimientoPago(op.id,{idObligacion:mov.ob.id_obligacion_m5,idMedioPago:medio.id_medio_pago,montoAplicado:mov.monto});op=await modulo.adjuntarRespaldoPago(op.id,{nombreArchivo:'pago.pdf',contenido:'data:application/pdf;base64,UERG',operacion:true,movimientos:op.movimientos.map(m=>m.id)},usuario.usuario_id_usuario);await modulo.prepararOperacionPago(op.id,usuario.usuario_id_usuario);return modulo.confirmarOperacionPago(op.id,usuario.usuario_id_usuario)};
 const evidencia=(nombre='efecto.pdf')=>({motivo:'Antecedente postpago verificado',nombreArchivo:nombre,contenido:'data:application/pdf;base64,UERG'});
 try{
  [usuario,pais,tipoId,tipoDoc,clp,usd]=await Promise.all([prisma.usuario.findFirstOrThrow({where:{administrador_original:true}}),prisma.pais.findFirstOrThrow({where:{estado_pais:'activo'}}),prisma.tipo_identificador.findFirstOrThrow({where:{estado_tipo_identificador:'activo'}}),prisma.tipo_documento.findFirstOrThrow({where:{aplica_compra:true}}),prisma.moneda.findUniqueOrThrow({where:{codigo_moneda:'CLP'}}),prisma.moneda.findUniqueOrThrow({where:{codigo_moneda:'USD'}})]);medio=await prisma.medio_pago.findFirst({where:{estado_medio_pago:'activo'}});if(!medio){medio=await prisma.medio_pago.create({data:{nombre_medio_pago:`P7-${randomUUID()}`,estado_medio_pago:'activo'}});ids.medios.push(medio.id_medio_pago)}

  await t.test('CU121 usa una fórmula acotada y CU122 separa pago de condición temporal',async()=>{assert.equal(calcularSaldoObligacion(100,[{montoOriginal:100}]).toNumber(),0);assert.equal(calcularSaldoObligacion(100,[{montoOriginal:100,montoRevertido:30}]).toNumber(),30);assert.equal(calcularSaldoObligacion(100,[{montoOriginal:100,montoRevertido:30,montoAnulado:70}]).toNumber(),100);assert.throws(()=>calcularSaldoObligacion(100,[{montoOriginal:101}]),e=>e.estado===409);assert.equal(derivarEstadoMovimientoPago({montoOriginal:100,montoRevertido:30}),'Revertido parcialmente');assert.equal(derivarEstadoMovimientoPago({montoOriginal:100,montoRevertido:100}),'Revertido totalmente');assert.equal(derivarEstadoOperacionPago(['Vigente','Anulado']),'Afectada parcialmente')});

  const pReversa=await proveedor('Reversas');const deudaReversa=await obligacion(pReversa,100,usd);let pagoReversa=await confirmar(pReversa,[{ob:deudaReversa,monto:100}]);
  await t.test('CU120 usa CU121/CU122 y CU123 presenta el detalle confirmado completo',async()=>{const pagada=await prisma.obligacion_proveedor_m5.findUniqueOrThrow({where:{id_obligacion_m5:deudaReversa.id_obligacion_m5}});assert.equal(pagada.saldo_actual.toNumber(),0);assert.equal(pagada.estado_pago,'Pagada');assert.equal(pagada.condicion_temporal,null);const detalle=await modulo.consultarDetallePagoProveedor(pagoReversa.id);assert.equal(detalle.estadoAgregado,'Confirmada');assert.equal(detalle.movimientos[0].medioPago,medio.nombre_medio_pago);assert.equal(detalle.movimientos[0].tasaReferencia,900);assert.equal(detalle.movimientos[0].equivalenteClp,90000);assert.equal(detalle.movimientos[0].conciliacion.estado,'pendiente');assert.ok(detalle.respaldos.length);assert.ok(detalle.preparadoPor);assert.ok(detalle.confirmadoPor)});

  await t.test('CU125 admite varias reversas, restaura sólo lo devuelto y reabre una vencida',async()=>{pagoReversa=await modulo.revertirMovimientoPago(pagoReversa.id,pagoReversa.movimientos[0].id,{...evidencia('r1.pdf'),monto:20},usuario.usuario_id_usuario);pagoReversa=await modulo.revertirMovimientoPago(pagoReversa.id,pagoReversa.movimientos[0].id,{...evidencia('r2.pdf'),monto:30},usuario.usuario_id_usuario);let deuda=await prisma.obligacion_proveedor_m5.findUniqueOrThrow({where:{id_obligacion_m5:deudaReversa.id_obligacion_m5}});assert.equal(deuda.saldo_actual.toNumber(),50);assert.equal(deuda.estado_pago,'Parcial');assert.equal(deuda.condicion_temporal,'Vencida');assert.equal(pagoReversa.movimientos[0].estado,'Revertido parcialmente');await assert.rejects(modulo.revertirMovimientoPago(pagoReversa.id,pagoReversa.movimientos[0].id,{...evidencia(),monto:51},usuario.usuario_id_usuario),e=>e.estado===409);pagoReversa=await modulo.revertirMovimientoPago(pagoReversa.id,pagoReversa.movimientos[0].id,{...evidencia('r3.pdf'),monto:50},usuario.usuario_id_usuario);deuda=await prisma.obligacion_proveedor_m5.findUniqueOrThrow({where:{id_obligacion_m5:deudaReversa.id_obligacion_m5}});assert.equal(deuda.saldo_actual.toNumber(),100);assert.equal(deuda.estado_pago,'Pendiente');assert.equal(pagoReversa.movimientos[0].estado,'Revertido totalmente')});

  const pMixto=await proveedor('Anulacion neta');const deudaMixta=await obligacion(pMixto);let pagoMixto=await confirmar(pMixto,[{ob:deudaMixta,monto:100}]);
  await t.test('CU124 anula sólo el neto restante sin doble restitución y conserva original',async()=>{pagoMixto=await modulo.revertirMovimientoPago(pagoMixto.id,pagoMixto.movimientos[0].id,{...evidencia('devuelta.pdf'),monto:30},usuario.usuario_id_usuario);pagoMixto=await modulo.anularMovimientoPago(pagoMixto.id,pagoMixto.movimientos[0].id,evidencia('anulacion.pdf'),usuario.usuario_id_usuario);const deuda=await prisma.obligacion_proveedor_m5.findUniqueOrThrow({where:{id_obligacion_m5:deudaMixta.id_obligacion_m5}});assert.equal(deuda.saldo_actual.toNumber(),100);assert.equal(pagoMixto.movimientos[0].montoRevertido,30);assert.equal(pagoMixto.movimientos[0].montoAnulado,70);assert.equal(pagoMixto.movimientos[0].montoNetoVigente,0);assert.equal(pagoMixto.movimientos[0].estado,'Anulado');assert.equal((await prisma.movimiento_pago_proveedor_m5.findUniqueOrThrow({where:{id_movimiento_pago_m5:pagoMixto.movimientos[0].id}})).monto_aplicado.toNumber(),100);await assert.rejects(modulo.anularMovimientoPago(pagoMixto.id,pagoMixto.movimientos[0].id,evidencia(),usuario.usuario_id_usuario),e=>e.estado===409)});

  const pCompleta=await proveedor('Anulacion completa');const deudaA=await obligacion(pCompleta,60);const deudaB=await obligacion(pCompleta,40);let completa=await confirmar(pCompleta,[{ob:deudaA,monto:60},{ob:deudaB,monto:40}]);
  await t.test('CU124 anula una operación completa atómicamente',async()=>{completa=await modulo.anularOperacionPago(completa.id,evidencia('operacion.pdf'),usuario.usuario_id_usuario);assert.ok(completa.movimientos.every(m=>m.estado==='Anulado'));assert.equal(completa.estadoAgregado,'Anulada');for(const deudaId of [deudaA.id_obligacion_m5,deudaB.id_obligacion_m5])assert.equal((await prisma.obligacion_proveedor_m5.findUniqueOrThrow({where:{id_obligacion_m5:deudaId}})).saldo_actual.toNumber(),deudaId===deudaA.id_obligacion_m5?60:40);await assert.rejects(modulo.anularOperacionPago(completa.id,evidencia(),usuario.usuario_id_usuario),e=>e.estado===409)});

  const pConciliacion=await proveedor('Conciliacion');const deudaConciliacion=await obligacion(pConciliacion);let pagoConciliacion=await confirmar(pConciliacion,[{ob:deudaConciliacion,monto:100}]);
  await t.test('CU126 concilia o registra discrepancia sin efecto financiero y permite proveedor Inactivo',async()=>{await modulo.cambiarEstadoProveedor(pConciliacion.id_proveedor,'inactivo',true,usuario.usuario_id_usuario);const saldoAntes=(await prisma.obligacion_proveedor_m5.findUniqueOrThrow({where:{id_obligacion_m5:deudaConciliacion.id_obligacion_m5}})).saldo_actual.toNumber();pagoConciliacion=await modulo.conciliarMovimientoPago(pagoConciliacion.id,pagoConciliacion.movimientos[0].id,{resultado:'conciliado'},usuario.usuario_id_usuario);assert.equal(pagoConciliacion.movimientos[0].conciliacion.estado,'conciliado');pagoConciliacion=await modulo.conciliarMovimientoPago(pagoConciliacion.id,pagoConciliacion.movimientos[0].id,{resultado:'con_discrepancia',observacion:'Monto bancario por verificar'},usuario.usuario_id_usuario);assert.equal(pagoConciliacion.movimientos[0].conciliacion.estado,'con_discrepancia');assert.equal((await prisma.obligacion_proveedor_m5.findUniqueOrThrow({where:{id_obligacion_m5:deudaConciliacion.id_obligacion_m5}})).saldo_actual.toNumber(),saldoAntes)});

  const pConcurrente=await proveedor('Concurrente');const deudaConcurrente=await obligacion(pConcurrente);const pagoConcurrente=await confirmar(pConcurrente,[{ob:deudaConcurrente,monto:100}]);
  await t.test('concurrencia impide que dos reversas superen el efecto real',async()=>{const resultados=await Promise.allSettled([modulo.revertirMovimientoPago(pagoConcurrente.id,pagoConcurrente.movimientos[0].id,{...evidencia('c1.pdf'),monto:70},usuario.usuario_id_usuario),modulo.revertirMovimientoPago(pagoConcurrente.id,pagoConcurrente.movimientos[0].id,{...evidencia('c2.pdf'),monto:70},usuario.usuario_id_usuario)]);assert.equal(resultados.filter(r=>r.status==='fulfilled').length,1);assert.equal(resultados.filter(r=>r.status==='rejected'&&r.reason.estado===409).length,1);assert.equal((await prisma.obligacion_proveedor_m5.findUniqueOrThrow({where:{id_obligacion_m5:deudaConcurrente.id_obligacion_m5}})).saldo_actual.toNumber(),70)});

  await t.test('CxP/Catálogo reflejan el saldo restaurado y permisos llegan exactamente a CU126',async()=>{const cxp=(await modulo.listarCuentasPorPagar({proveedor:pMixto.id_proveedor}))[0];const catalogo=(await modulo.listarProveedores({estado:'todos'})).find(p=>p.idProveedor===pMixto.id_proveedor);assert.equal(cxp.saldoActual,100);assert.equal(cxp.estadoPago,'Pendiente');assert.equal(catalogo.situacionFinanciera,'Vencida');assert.deepEqual([...matrizPermisosPorCU.CU123].sort(),['contador','gerencia','secretaria']);for(const cu of ['CU124','CU125','CU126'])assert.deepEqual([...matrizPermisosPorCU[cu]].sort(),['contador','gerencia']);assert.deepEqual(matrizPermisosPorCU.CU121,[]);assert.deepEqual(matrizPermisosPorCU.CU122,[]);assert.equal(codigosTodosLosCU.length,126);let llamada=false;const fachada=new C_Finanzas({autorizar:async()=>({id:usuario.usuario_id_usuario,sesion:'x',permisos:['CU124'],configuracion:'secretaria',administrador:false,cambiarClave:false,nombre:'S',acceso:'s'})},{},{},{},{},{anularOperacionPago:async()=>{llamada=true}});await assert.rejects(fachada.ejecutar('anularOperacionPago',{parametros:{id:'1'},cuerpo:{},contexto:{}}),e=>e.estado===403);assert.equal(llamada,false)});
 }finally{
  const movimientos=await prisma.movimiento_pago_proveedor_m5.findMany({where:{id_operacion_pago_m5:{in:ids.operaciones}}});const movIds=movimientos.map(m=>m.id_movimiento_pago_m5);const asociaciones=await prisma.asociacion_respaldo_pago_m5.findMany({where:{OR:[{id_operacion_pago_m5:{in:ids.operaciones}},{id_movimiento_pago_m5:{in:movIds}}]}});const [anulaciones,reversas]=await Promise.all([prisma.anulacion_movimiento_pago_m5.findMany({where:{id_movimiento_pago_m5:{in:movIds}}}),prisma.reversion_movimiento_pago_m5.findMany({where:{id_movimiento_pago_m5:{in:movIds}}})]);const respaldos=[...new Set([...asociaciones.map(r=>r.id_respaldo_pago_m5),...anulaciones.map(r=>r.id_respaldo_pago_m5),...reversas.map(r=>r.id_respaldo_pago_m5)])];await prisma.conciliacion_movimiento_pago_m5.deleteMany({where:{id_movimiento_pago_m5:{in:movIds}}});await prisma.anulacion_movimiento_pago_m5.deleteMany({where:{id_movimiento_pago_m5:{in:movIds}}});await prisma.reversion_movimiento_pago_m5.deleteMany({where:{id_movimiento_pago_m5:{in:movIds}}});await prisma.asociacion_respaldo_pago_m5.deleteMany({where:{id_asociacion_respaldo_m5:{in:asociaciones.map(r=>r.id_asociacion_respaldo_m5)}}});await prisma.respaldo_pago_proveedor_m5.deleteMany({where:{id_respaldo_pago_m5:{in:respaldos}}});await prisma.movimiento_pago_proveedor_m5.deleteMany({where:{id_operacion_pago_m5:{in:ids.operaciones}}});await prisma.operacion_pago_proveedor_m5.deleteMany({where:{id_operacion_pago_m5:{in:ids.operaciones}}});await prisma.obligacion_proveedor_m5.deleteMany({where:{id_obligacion_m5:{in:ids.obligaciones}}});await prisma.documento_proveedor_m5.deleteMany({where:{id_documento_m5:{in:ids.documentos}}});await prisma.historial_proveedor_m5.deleteMany({where:{id_proveedor:{in:ids.proveedores}}});await prisma.proveedor.deleteMany({where:{id_proveedor:{in:ids.proveedores}}});await prisma.medio_pago.deleteMany({where:{id_medio_pago:{in:ids.medios}}});await prisma.$disconnect();
 }
});
