const {test}=require('node:test');const assert=require('node:assert/strict');const {randomUUID}=require('node:crypto');
const {prisma}=require('../dist/db');const {M5Controller}=require('../dist/controladores/M5Controller');const {C_Finanzas}=require('../dist/controladores/C_Finanzas');const {matrizPermisosPorCU,codigosTodosLosCU}=require('../dist/validaciones/permisos');

test('M5 P6 CU111-CU120 opera borradores y confirma pagos atómicamente',async t=>{
 const ids={proveedores:[],documentos:[],obligaciones:[],operaciones:[],medios:[]};let usuario,pais,tipoId,tipoDoc,clp,usd,medio1,medio2,medioInactivo,activo,inactivo,bloqueado,otro;const banco={obtenerTipoCambio:async(moneda,fecha)=>{assert.equal(moneda,'USD');assert.match(fecha,/^2026-09-/);return 900}};const modulo=new M5Controller(banco);
 const proveedor=async(estado,nombre)=>{const p=await prisma.proveedor.create({data:{id_pais:pais.id_pais,id_tipo_identificador:tipoId.id_tipo_identificador,identificador_tributario:`P6-${randomUUID()}`,nombre_razon_social:`${nombre}-${randomUUID()}`,tipo_proveedor_m5:'Servicios',estado_proveedor:estado}});ids.proveedores.push(p.id_proveedor);return p};
 const obligacion=async(p,moneda,saldo)=>{const d=await prisma.documento_proveedor_m5.create({data:{id_proveedor:p.id_proveedor,clase:'definitivo',id_tipo_documento:tipoDoc.id_tipo_documento,folio:`P6-${randomUUID()}`,folio_normalizado:`P6-${randomUUID()}`,fecha_emision:new Date('2026-09-01T00:00:00Z'),id_moneda:moneda.id_moneda,monto_total:saldo,estado:'confirmado',creado_por:usuario.usuario_id_usuario}});ids.documentos.push(d.id_documento_m5);const o=await prisma.obligacion_proveedor_m5.create({data:{id_documento_m5:d.id_documento_m5,id_proveedor:p.id_proveedor,monto_original:saldo,id_moneda:moneda.id_moneda,saldo_inicial:saldo,saldo_actual:saldo,fecha_emision:d.fecha_emision,fecha_vencimiento:new Date('2026-10-10T00:00:00Z'),estado_pago:'Pendiente',condicion_temporal:'Por pagar',generado_por:usuario.usuario_id_usuario}});ids.obligaciones.push(o.id_obligacion_m5);return o};
 const crearOperacion=async(p)=>{const o=await modulo.crearOperacionPago({idProveedor:p.id_proveedor,fechaEfectivaPago:'2026-09-20'},usuario.usuario_id_usuario);ids.operaciones.push(o.id);return o};
 const respaldar=async(o)=>modulo.adjuntarRespaldoPago(o.id,{nombreArchivo:'respaldo.pdf',contenido:'data:application/pdf;base64,UERG',operacion:true,movimientos:o.movimientos.map(m=>m.id)},usuario.usuario_id_usuario);
 try{
  [usuario,pais,tipoId,tipoDoc,clp,usd]=await Promise.all([prisma.usuario.findFirstOrThrow({where:{administrador_original:true}}),prisma.pais.findFirstOrThrow({where:{estado_pais:'activo'}}),prisma.tipo_identificador.findFirstOrThrow({where:{estado_tipo_identificador:'activo'}}),prisma.tipo_documento.findFirstOrThrow({where:{aplica_compra:true}}),prisma.moneda.findUniqueOrThrow({where:{codigo_moneda:'CLP'}}),prisma.moneda.findUniqueOrThrow({where:{codigo_moneda:'USD'}})]);
  const activos=await prisma.medio_pago.findMany({where:{estado_medio_pago:'activo'},take:2});medio1=activos[0];if(activos[1])medio2=activos[1];else{medio2=await prisma.medio_pago.create({data:{nombre_medio_pago:`P6 activo ${randomUUID()}`,estado_medio_pago:'activo'}});ids.medios.push(medio2.id_medio_pago)}medioInactivo=await prisma.medio_pago.create({data:{nombre_medio_pago:`P6 inactivo ${randomUUID()}`,estado_medio_pago:'inactivo'}});ids.medios.push(medioInactivo.id_medio_pago);
  activo=await proveedor('activo','Proveedor activo');inactivo=await proveedor('inactivo','Proveedor inactivo');bloqueado=await proveedor('bloqueado','Proveedor bloqueado');otro=await proveedor('activo','Proveedor distinto');
  const deuda1=await obligacion(activo,clp,1000);const deuda2=await obligacion(activo,clp,500);const deudaUsd=await obligacion(activo,usd,100);await obligacion(inactivo,clp,100);await obligacion(bloqueado,clp,100);const deudaOtro=await obligacion(otro,clp,100);const competencia=await obligacion(activo,clp,1000);

  await t.test('CU111 selecciona sólo proveedores activos con deuda y busca nombre o identificador',async()=>{const porNombre=await modulo.buscarProveedoresParaPago({busqueda:'Proveedor activo'});assert.ok(porNombre.some(p=>p.id===activo.id_proveedor));assert.ok(!(await modulo.buscarProveedoresParaPago({})).some(p=>[inactivo.id_proveedor,bloqueado.id_proveedor].includes(p.id)));assert.ok((await modulo.buscarProveedoresParaPago({busqueda:activo.identificador_tributario})).some(p=>p.id===activo.id_proveedor));await assert.rejects(modulo.crearOperacionPago({idProveedor:inactivo.id_proveedor},usuario.usuario_id_usuario),e=>e.estado===409)});
  let principal=await crearOperacion(activo);
  await t.test('CU112-CU113 admiten varios movimientos y medios, pero no mezclan proveedor ni exceden saldo',async()=>{principal=await modulo.agregarMovimientoPago(principal.id,{idObligacion:deuda1.id_obligacion_m5,idMedioPago:medio1.id_medio_pago,montoAplicado:300});principal=await modulo.agregarMovimientoPago(principal.id,{idObligacion:deuda1.id_obligacion_m5,idMedioPago:medio2.id_medio_pago,montoAplicado:200});principal=await modulo.agregarMovimientoPago(principal.id,{idObligacion:deuda2.id_obligacion_m5,idMedioPago:medio1.id_medio_pago,montoAplicado:500});assert.equal(principal.total,1000);await assert.rejects(modulo.agregarMovimientoPago(principal.id,{idObligacion:deuda1.id_obligacion_m5,idMedioPago:medio1.id_medio_pago,montoAplicado:501}),e=>e.estado===409);await assert.rejects(modulo.agregarMovimientoPago(principal.id,{idObligacion:deudaOtro.id_obligacion_m5,idMedioPago:medio1.id_medio_pago,montoAplicado:1}),e=>e.estado===409);await assert.rejects(modulo.agregarMovimientoPago(principal.id,{idObligacion:deuda1.id_obligacion_m5,idMedioPago:medioInactivo.id_medio_pago,montoAplicado:1}),e=>e.estado===409);await assert.rejects(modulo.agregarMovimientoPago(principal.id,{idObligacion:deuda1.id_obligacion_m5,idMedioPago:medio1.id_medio_pago,montoAplicado:0}),e=>e.estado===400)});
  await t.test('CU114 reutiliza un archivo para operación y movimientos',async()=>{await assert.rejects(modulo.prepararOperacionPago(principal.id,usuario.usuario_id_usuario),e=>e.estado===409);principal=await respaldar(principal);assert.equal(principal.tieneRespaldo,true);assert.ok(principal.movimientos.every(m=>m.tieneRespaldo));const asociaciones=await prisma.asociacion_respaldo_pago_m5.findMany({where:{OR:[{id_operacion_pago_m5:principal.id},{id_movimiento_pago_m5:{in:principal.movimientos.map(m=>m.id)}}]}});assert.equal(new Set(asociaciones.map(a=>a.id_respaldo_pago_m5)).size,1);assert.equal(asociaciones.length,4)});
  await t.test('CU116 prepara sin reducir saldo y CU120 confirma parcial/total con varios medios',async()=>{const antes1=await prisma.obligacion_proveedor_m5.findUniqueOrThrow({where:{id_obligacion_m5:deuda1.id_obligacion_m5}});principal=await modulo.prepararOperacionPago(principal.id,usuario.usuario_id_usuario);assert.equal(principal.estado,'preparada');assert.equal((await prisma.obligacion_proveedor_m5.findUniqueOrThrow({where:{id_obligacion_m5:deuda1.id_obligacion_m5}})).saldo_actual.toNumber(),antes1.saldo_actual.toNumber());principal=await modulo.confirmarOperacionPago(principal.id,usuario.usuario_id_usuario);assert.equal(principal.estado,'confirmada');assert.equal(principal.totalConfirmado,1000);assert.ok(principal.movimientos.every(m=>m.estado==='Vigente'));const [p1,p2]=await Promise.all([prisma.obligacion_proveedor_m5.findUniqueOrThrow({where:{id_obligacion_m5:deuda1.id_obligacion_m5}}),prisma.obligacion_proveedor_m5.findUniqueOrThrow({where:{id_obligacion_m5:deuda2.id_obligacion_m5}})]);assert.equal(p1.saldo_actual.toNumber(),500);assert.equal(p1.estado_pago,'Parcial');assert.equal(p2.saldo_actual.toNumber(),0);assert.equal(p2.estado_pago,'Pagada');await assert.rejects(modulo.confirmarOperacionPago(principal.id,usuario.usuario_id_usuario),e=>e.estado===409);await assert.rejects(modulo.descartarOperacionPago(principal.id,usuario.usuario_id_usuario),e=>e.estado===409)});
  await t.test('CU115 conserva tasa oficial, manual y bancaria efectiva por fecha de pago',async()=>{let op=await crearOperacion(activo);op=await modulo.agregarMovimientoPago(op.id,{idObligacion:deudaUsd.id_obligacion_m5,idMedioPago:medio1.id_medio_pago,montoAplicado:10,tasaBancariaEfectiva:920});assert.equal(op.movimientos[0].tasaReferencia,900);assert.equal(op.movimientos[0].tasaBancariaEfectiva,920);assert.equal(op.movimientos[0].equivalenteClp,9200);await assert.rejects(modulo.registrarTipoCambioManualPago(op.id,op.movimientos[0].id,{tasaReferencia:910,justificacion:'BCCh no disponible'},usuario.usuario_id_usuario,'secretaria'),e=>e.estado===403);op=await modulo.registrarTipoCambioManualPago(op.id,op.movimientos[0].id,{tasaReferencia:910,tasaBancariaEfectiva:930,justificacion:'Cotización bancaria verificada'},usuario.usuario_id_usuario,'contador');assert.equal(op.movimientos[0].tasaReferencia,910);assert.equal(op.movimientos[0].tasaBancariaEfectiva,930);assert.equal(op.movimientos[0].equivalenteClp,9300)});
  await t.test('CU117-CU119 guardan, retoman y descartan sin reservar ni afectar saldo',async()=>{let op=await crearOperacion(activo);op=await modulo.agregarMovimientoPago(op.id,{idObligacion:competencia.id_obligacion_m5,idMedioPago:medio1.id_medio_pago,montoAplicado:100});op=await modulo.guardarBorradorPago(op.id,{fechaEfectivaPago:'2026-09-21'});assert.equal(op.estado,'borrador');assert.equal((await prisma.obligacion_proveedor_m5.findUniqueOrThrow({where:{id_obligacion_m5:competencia.id_obligacion_m5}})).saldo_actual.toNumber(),1000);assert.equal((await modulo.retomarOperacionPago(op.id)).id,op.id);op=await modulo.descartarOperacionPago(op.id,usuario.usuario_id_usuario);assert.equal(op.estado,'descartada');assert.equal((await prisma.obligacion_proveedor_m5.findUniqueOrThrow({where:{id_obligacion_m5:competencia.id_obligacion_m5}})).saldo_actual.toNumber(),1000)});
  await t.test('CU120 resuelve conflicto entre borradores con rollback total y 409',async()=>{let a=await crearOperacion(activo);a=await modulo.agregarMovimientoPago(a.id,{idObligacion:competencia.id_obligacion_m5,idMedioPago:medio1.id_medio_pago,montoAplicado:800});a=await respaldar(a);a=await modulo.prepararOperacionPago(a.id,usuario.usuario_id_usuario);let b=await crearOperacion(activo);b=await modulo.agregarMovimientoPago(b.id,{idObligacion:competencia.id_obligacion_m5,idMedioPago:medio2.id_medio_pago,montoAplicado:500});b=await respaldar(b);b=await modulo.prepararOperacionPago(b.id,usuario.usuario_id_usuario);await modulo.confirmarOperacionPago(a.id,usuario.usuario_id_usuario);await assert.rejects(modulo.confirmarOperacionPago(b.id,usuario.usuario_id_usuario),e=>e.estado===409);assert.equal((await prisma.obligacion_proveedor_m5.findUniqueOrThrow({where:{id_obligacion_m5:competencia.id_obligacion_m5}})).saldo_actual.toNumber(),200);assert.equal((await prisma.operacion_pago_proveedor_m5.findUniqueOrThrow({where:{id_operacion_pago_m5:b.id}})).estado,'preparada')});
  await t.test('permisos llegan a CU120 y Secretaría no confirma',async()=>{for(const cu of ['CU111','CU112','CU113','CU114','CU116','CU117','CU118','CU119'])assert.deepEqual([...matrizPermisosPorCU[cu]].sort(),['contador','gerencia','secretaria']);assert.deepEqual([...matrizPermisosPorCU.CU115].sort(),['contador','gerencia']);assert.deepEqual([...matrizPermisosPorCU.CU120].sort(),['contador','gerencia']);assert.equal(codigosTodosLosCU.length,177);let llamada=false;const fachada=new C_Finanzas({autorizar:async()=>({id:usuario.usuario_id_usuario,sesion:'x',permisos:['CU120'],configuracion:'secretaria',administrador:false,cambiarClave:false,nombre:'S',acceso:'s'})},{},{},{},{},{confirmarOperacionPago:async()=>{llamada=true}});await assert.rejects(fachada.ejecutar('confirmarOperacionPago',{parametros:{id:'1'},contexto:{}}),e=>e.estado===403);assert.equal(llamada,false)});
 }finally{
  const movimientos=await prisma.movimiento_pago_proveedor_m5.findMany({where:{id_operacion_pago_m5:{in:ids.operaciones}}});const respaldos=await prisma.asociacion_respaldo_pago_m5.findMany({where:{OR:[{id_operacion_pago_m5:{in:ids.operaciones}},{id_movimiento_pago_m5:{in:movimientos.map(m=>m.id_movimiento_pago_m5)}}]}});await prisma.asociacion_respaldo_pago_m5.deleteMany({where:{id_asociacion_respaldo_m5:{in:respaldos.map(r=>r.id_asociacion_respaldo_m5)}}});await prisma.respaldo_pago_proveedor_m5.deleteMany({where:{id_respaldo_pago_m5:{in:[...new Set(respaldos.map(r=>r.id_respaldo_pago_m5))]}}});await prisma.movimiento_pago_proveedor_m5.deleteMany({where:{id_operacion_pago_m5:{in:ids.operaciones}}});await prisma.operacion_pago_proveedor_m5.deleteMany({where:{id_operacion_pago_m5:{in:ids.operaciones}}});await prisma.obligacion_proveedor_m5.deleteMany({where:{id_obligacion_m5:{in:ids.obligaciones}}});await prisma.documento_proveedor_m5.deleteMany({where:{id_documento_m5:{in:ids.documentos}}});await prisma.proveedor.deleteMany({where:{id_proveedor:{in:ids.proveedores}}});await prisma.medio_pago.deleteMany({where:{id_medio_pago:{in:ids.medios}}});await prisma.$disconnect();
 }
});
