const {test}=require('node:test');const assert=require('node:assert/strict');const {randomUUID}=require('node:crypto');
const {prisma}=require('../dist/db');const {M5Controller,calcularSaldoObligacion}=require('../dist/controladores/M5Controller');const {matrizPermisosPorCU,codigosTodosLosCU,codigosQueRequierenAdministrador}=require('../dist/validaciones/permisos');

test('M5 P9 CU132-CU137 compensa créditos y reclasifica con trazabilidad',async t=>{
 const modulo=new M5Controller();const ids={proveedores:[],documentos:[],obligaciones:[],categorias:[],respaldos:[]};let usuario,pais,tipoId,tipoDoc,clp,usd,proveedor,nc,credito,umbralInicial;let historialUmbralInicial=[];
 const unico=p=>`${p}-${randomUUID()}`;const evidencia=(nombre='reversa.pdf')=>({motivo:'Corrección interna documentada',nombreArchivo:nombre,contenido:'data:application/pdf;base64,UERG'});
 const obligacion=async(monto,condicion='Vencida',moneda=clp,fecha='2026-09-01')=>{const d=await prisma.documento_proveedor_m5.create({data:{id_proveedor:proveedor.id_proveedor,clase:'definitivo',id_tipo_documento:tipoDoc.id_tipo_documento,folio:unico('FAC'),folio_normalizado:unico('FAC-N'),fecha_emision:new Date('2026-08-01T00:00:00Z'),id_moneda:moneda.id_moneda,monto_total:monto,estado:'confirmado',creado_por:usuario.usuario_id_usuario}});ids.documentos.push(d.id_documento_m5);const o=await prisma.obligacion_proveedor_m5.create({data:{id_documento_m5:d.id_documento_m5,id_proveedor:proveedor.id_proveedor,monto_original:monto,id_moneda:moneda.id_moneda,saldo_inicial:monto,saldo_actual:monto,fecha_emision:d.fecha_emision,fecha_vencimiento:new Date(`${fecha}T00:00:00Z`),estado_pago:'Pendiente',condicion_temporal:condicion,generado_por:usuario.usuario_id_usuario}});ids.obligaciones.push(o.id_obligacion_m5);return o};
 const revertirTodo=async(comp)=>{for(const d of comp.distribuciones){const restante=d.monto-d.montoRevertido;if(restante>0)comp=await modulo.revertirCompensacion(comp.id,{...evidencia(),distribuciones:[{idDetalle:d.id,monto:restante}]},usuario.usuario_id_usuario)}return comp};
 try{
  [usuario,pais,tipoId,tipoDoc,clp,usd]=await Promise.all([prisma.usuario.findFirstOrThrow({where:{administrador_original:true}}),prisma.pais.findFirstOrThrow({where:{estado_pais:'activo'}}),prisma.tipo_identificador.findFirstOrThrow({where:{estado_tipo_identificador:'activo'}}),prisma.tipo_documento.findFirstOrThrow({where:{aplica_compra:true}}),prisma.moneda.findUniqueOrThrow({where:{codigo_moneda:'CLP'}}),prisma.moneda.findUniqueOrThrow({where:{codigo_moneda:'USD'}})]);
  umbralInicial=await prisma.config_umbral_reclasificacion_m5.findUniqueOrThrow({where:{id_configuracion:1}});historialUmbralInicial=(await prisma.historial_umbral_reclasificacion_m5.findMany({select:{id_historial_umbral_m5:true}})).map(item=>item.id_historial_umbral_m5);
  proveedor=await prisma.proveedor.create({data:{id_pais:pais.id_pais,id_tipo_identificador:tipoId.id_tipo_identificador,identificador_tributario:unico('P9'),nombre_razon_social:unico('Proveedor P9'),tipo_proveedor_m5:'Servicios',estado_proveedor:'activo'}});ids.proveedores.push(proveedor.id_proveedor);
  const origen=await obligacion(10);nc=await modulo.registrarNotaCredito({idObligacion:origen.id_obligacion_m5,idTipoDocumento:tipoDoc.id_tipo_documento,idMoneda:clp.id_moneda,folio:unico('NC'),fechaEmision:'2026-09-21',monto:110},usuario.usuario_id_usuario);const ajuste=await prisma.ajuste_obligacion_proveedor_m5.findUniqueOrThrow({where:{id_ajuste_obligacion_m5:nc.id}});ids.documentos.push(ajuste.id_documento_ajuste_m5);credito=nc.saldoFavor;
  const vencida=await obligacion(60,'Vencida',clp,'2026-08-01');const porVencer=await obligacion(60,'Por vencer',clp,'2026-09-22');const porPagar=await obligacion(60,'Por pagar',clp,'2026-10-20');const otraMoneda=await obligacion(40,'Vencida',usd,'2026-08-01');
  let compensacion,concurrente;
  await t.test('CU132 propone por prioridad sin consumir y confirma distribución modificada',async()=>{const antes=(await prisma.saldo_favor_proveedor_m5.findUniqueOrThrow({where:{id_saldo_favor_m5:credito.id}})).monto_disponible.toNumber();const propuesta=await modulo.proponerCompensacion(proveedor.id_proveedor,{idSaldoFavor:credito.id});assert.deepEqual(propuesta.distribuciones.map(d=>d.idObligacion),[vencida.id_obligacion_m5,porVencer.id_obligacion_m5]);assert.equal((await prisma.saldo_favor_proveedor_m5.findUniqueOrThrow({where:{id_saldo_favor_m5:credito.id}})).monto_disponible.toNumber(),antes);await assert.rejects(modulo.confirmarCompensacion(proveedor.id_proveedor,{idSaldoFavor:credito.id,distribuciones:[{idObligacion:otraMoneda.id_obligacion_m5,monto:10}]},usuario.usuario_id_usuario),e=>e.estado===400);compensacion=await modulo.confirmarCompensacion(proveedor.id_proveedor,{idSaldoFavor:credito.id,distribuciones:[{idObligacion:porVencer.id_obligacion_m5,monto:30}]},usuario.usuario_id_usuario);assert.equal(compensacion.total,30);assert.equal((await prisma.saldo_favor_proveedor_m5.findUniqueOrThrow({where:{id_saldo_favor_m5:credito.id}})).monto_disponible.toNumber(),70);assert.equal((await prisma.obligacion_proveedor_m5.findUniqueOrThrow({where:{id_obligacion_m5:porVencer.id_obligacion_m5}})).saldo_actual.toNumber(),30);assert.equal(await prisma.operacion_pago_proveedor_m5.count({where:{id_proveedor:proveedor.id_proveedor}}),0)});
  await t.test('CU132 concurrencia no trunca y devuelve 409',async()=>{const entradas=[vencida,porPagar].map(o=>modulo.confirmarCompensacion(proveedor.id_proveedor,{idSaldoFavor:credito.id,distribuciones:[{idObligacion:o.id_obligacion_m5,monto:50}]},usuario.usuario_id_usuario));const resultados=await Promise.allSettled(entradas);assert.equal(resultados.filter(r=>r.status==='fulfilled').length,1);assert.equal(resultados.filter(r=>r.status==='rejected'&&r.reason.estado===409).length,1);concurrente=resultados.find(r=>r.status==='fulfilled').value;assert.equal((await prisma.saldo_favor_proveedor_m5.findUniqueOrThrow({where:{id_saldo_favor_m5:credito.id}})).monto_disponible.toNumber(),20)});
  await t.test('CU133 admite varias reversas, restaura crédito/deuda y proveedor Inactivo',async()=>{const detalle=compensacion.distribuciones[0];compensacion=await modulo.revertirCompensacion(compensacion.id,{...evidencia('r1.pdf'),distribuciones:[{idDetalle:detalle.id,monto:10}]},usuario.usuario_id_usuario);assert.equal(compensacion.estado,'revertida_parcial');await prisma.proveedor.update({where:{id_proveedor:proveedor.id_proveedor},data:{estado_proveedor:'inactivo'}});compensacion=await modulo.revertirCompensacion(compensacion.id,{...evidencia('r2.pdf'),distribuciones:[{idDetalle:detalle.id,monto:20}]},usuario.usuario_id_usuario);assert.equal(compensacion.estado,'revertida_total');assert.equal((await prisma.obligacion_proveedor_m5.findUniqueOrThrow({where:{id_obligacion_m5:porVencer.id_obligacion_m5}})).saldo_actual.toNumber(),60);await assert.rejects(modulo.revertirCompensacion(compensacion.id,{...evidencia(),distribuciones:[{idDetalle:detalle.id,monto:1}]},usuario.usuario_id_usuario),e=>e.estado===409);await prisma.proveedor.update({where:{id_proveedor:proveedor.id_proveedor},data:{estado_proveedor:'activo'}})});
  await t.test('CU130 bloquea NC usada y permite anular tras reversa completa',async()=>{await assert.rejects(modulo.anularAjusteObligacion(nc.id,evidencia('nc.pdf'),usuario.usuario_id_usuario),e=>e.estado===409);concurrente=await revertirTodo(concurrente);const saldo=await modulo.consultarSaldosFavorProveedor(proveedor.id_proveedor);assert.equal(saldo.saldos.find(s=>s.id===credito.id).montoUtilizadoNeto,0);nc=await modulo.anularAjusteObligacion(nc.id,evidencia('nc-ok.pdf'),usuario.usuario_id_usuario);assert.equal(nc.estado,'anulado')});

  let categoriaA,categoriaB;
  await t.test('CU134 crea, renombra, desactiva y reactiva conservando historial',async()=>{categoriaA=await modulo.crearCategoriaEgreso({nombre:unico('Categoría A')},usuario.usuario_id_usuario);categoriaB=await modulo.crearCategoriaEgreso({nombre:unico('Categoría B')},usuario.usuario_id_usuario);ids.categorias.push(categoriaA.id_categoria_egreso_m5,categoriaB.id_categoria_egreso_m5);const anterior=categoriaA.nombre;categoriaA=await modulo.actualizarCategoriaEgreso(categoriaA.id_categoria_egreso_m5,{nombre:`${anterior} renovada`,motivo:'Ajuste de nomenclatura'},usuario.usuario_id_usuario);await modulo.actualizarCategoriaEgreso(categoriaA.id_categoria_egreso_m5,{activo:false,motivo:'Pausa'},usuario.usuario_id_usuario);let lista=await modulo.listarCategoriasEgreso();assert.equal(lista.find(c=>c.id===categoriaA.id_categoria_egreso_m5).historial.length,2);assert.ok(!(await modulo.catalogosDocumentosProveedor()).categorias.some(c=>c.id_categoria_egreso_m5===categoriaA.id_categoria_egreso_m5));await modulo.actualizarCategoriaEgreso(categoriaA.id_categoria_egreso_m5,{activo:true,motivo:'Reactivación'},usuario.usuario_id_usuario);lista=await modulo.listarCategoriasEgreso();assert.equal(lista.find(c=>c.id===categoriaA.id_categoria_egreso_m5).activo,true)});

  const doc=await prisma.documento_proveedor_m5.create({data:{id_proveedor:proveedor.id_proveedor,clase:'definitivo',id_tipo_documento:tipoDoc.id_tipo_documento,folio:unico('RECL'),folio_normalizado:unico('RECL-N'),fecha_emision:new Date(),id_moneda:clp.id_moneda,monto_total:100,estado:'confirmado',creado_por:usuario.usuario_id_usuario}});ids.documentos.push(doc.id_documento_m5);const asociacion=await prisma.asociacion_documento_oc_m5.create({data:{id_documento_m5:doc.id_documento_m5,tipo_orden:'EXCEPCION',id_orden_externa:unico('EX'),monto_asignado:100,estado_diferencia:'exacta'}});const clasificacion=await prisma.clasificacion_asociacion_m5.create({data:{id_asociacion_m5:asociacion.id_asociacion_m5,id_categoria_egreso_m5:categoriaA.id_categoria_egreso_m5,nombre_categoria_snapshot:categoriaA.nombre,monto:100}});
  let pendiente,rechazada;
  await t.test('CU135 aplica bajo umbral, deja sobre umbral pendiente y no cambia deuda',async()=>{await modulo.configurarUmbralReclasificacion({montoClp:50},usuario.usuario_id_usuario);const bajo=await modulo.solicitarReclasificacion(doc.id_documento_m5,{motivo:'Corrección parcial',movimientos:[{idClasificacion:clasificacion.id_clasificacion_m5,idCategoriaDestino:categoriaB.id_categoria_egreso_m5,monto:40}]},usuario.usuario_id_usuario);assert.equal(bajo.estado,'aprobada');const saldoAntes=(await prisma.obligacion_proveedor_m5.findMany({where:{id_proveedor:proveedor.id_proveedor}})).reduce((s,o)=>s+Number(o.saldo_actual),0);pendiente=await modulo.solicitarReclasificacion(doc.id_documento_m5,{motivo:'Corrección reforzada',movimientos:[{idClasificacion:clasificacion.id_clasificacion_m5,idCategoriaDestino:categoriaB.id_categoria_egreso_m5,monto:60}]},usuario.usuario_id_usuario);assert.equal(pendiente.estado,'pendiente');assert.equal(pendiente.umbralSnapshotClp,50);await modulo.configurarUmbralReclasificacion({montoClp:1000},usuario.usuario_id_usuario);assert.equal((await modulo.listarReclasificaciones()).find(r=>r.id===pendiente.id).umbralSnapshotClp,50);const saldoDespues=(await prisma.obligacion_proveedor_m5.findMany({where:{id_proveedor:proveedor.id_proveedor}})).reduce((s,o)=>s+Number(o.saldo_actual),0);assert.equal(saldoDespues,saldoAntes)});
  await t.test('CU136 segrega aprobación, revalida destino y rechazo es inmutable',async()=>{await assert.rejects(modulo.resolverReclasificacion(pendiente.id,true,{},usuario.usuario_id_usuario,'contador'),e=>e.estado===403);await modulo.actualizarCategoriaEgreso(categoriaB.id_categoria_egreso_m5,{activo:false,motivo:'Prueba'},usuario.usuario_id_usuario);await assert.rejects(modulo.resolverReclasificacion(pendiente.id,true,{},usuario.usuario_id_usuario,'gerencia'),e=>e.estado===409);await modulo.actualizarCategoriaEgreso(categoriaB.id_categoria_egreso_m5,{activo:true,motivo:'Prueba'},usuario.usuario_id_usuario);await modulo.configurarUmbralReclasificacion({montoClp:0},usuario.usuario_id_usuario);rechazada=await modulo.solicitarReclasificacion(doc.id_documento_m5,{motivo:'Nuevo intento completo',movimientos:[{idClasificacion:clasificacion.id_clasificacion_m5,idCategoriaDestino:categoriaB.id_categoria_egreso_m5,monto:1}]},usuario.usuario_id_usuario);assert.equal((await modulo.resolverReclasificacion(rechazada.id,false,{motivo:'Antecedente insuficiente'},usuario.usuario_id_usuario,'contador')).estado,'rechazada');await assert.rejects(modulo.resolverReclasificacion(rechazada.id,true,{},usuario.usuario_id_usuario,'gerencia'),e=>e.estado===409);assert.equal((await modulo.resolverReclasificacion(pendiente.id,true,{},usuario.usuario_id_usuario,'gerencia')).estado,'aprobada')});
  await t.test('CU137 conserva Decimal, historial y permisos exactos',async()=>{const umbral=await modulo.consultarUmbralReclasificacion();assert.equal(umbral.montoClp,0);assert.ok(umbral.historial.length>=3);assert.equal(calcularSaldoObligacion(100,[],[],[{montoAplicado:70,montoRevertido:20}]).toNumber(),50);for(const cu of ['CU132','CU133','CU134','CU135','CU136'])assert.deepEqual([...matrizPermisosPorCU[cu]].sort(),['contador','gerencia']);assert.deepEqual(matrizPermisosPorCU.CU137,['gerencia']);assert.ok(codigosQueRequierenAdministrador.has('CU137'));assert.equal(codigosTodosLosCU.length,154)});
 }finally{
  const reclas=await prisma.reclasificacion_egreso_m5.findMany({where:{id_documento_m5:{in:ids.documentos}}});await prisma.detalle_reclasificacion_egreso_m5.deleteMany({where:{id_reclasificacion_m5:{in:reclas.map(r=>r.id_reclasificacion_m5)}}});await prisma.reclasificacion_egreso_m5.deleteMany({where:{id_reclasificacion_m5:{in:reclas.map(r=>r.id_reclasificacion_m5)}}});
  const comp=await prisma.compensacion_saldo_favor_m5.findMany({where:{id_proveedor:{in:ids.proveedores}}});const det=await prisma.detalle_compensacion_saldo_favor_m5.findMany({where:{id_compensacion_m5:{in:comp.map(c=>c.id_compensacion_m5)}}});const rev=await prisma.reversion_compensacion_m5.findMany({where:{id_detalle_compensacion_m5:{in:det.map(d=>d.id_detalle_compensacion_m5)}}});ids.respaldos.push(...rev.map(r=>r.id_respaldo_pago_m5));await prisma.reversion_compensacion_m5.deleteMany({where:{id_detalle_compensacion_m5:{in:det.map(d=>d.id_detalle_compensacion_m5)}}});await prisma.detalle_compensacion_saldo_favor_m5.deleteMany({where:{id_compensacion_m5:{in:comp.map(c=>c.id_compensacion_m5)}}});await prisma.compensacion_saldo_favor_m5.deleteMany({where:{id_compensacion_m5:{in:comp.map(c=>c.id_compensacion_m5)}}});
  const ajustes=await prisma.ajuste_obligacion_proveedor_m5.findMany({where:{id_proveedor:{in:ids.proveedores}}});ids.respaldos.push(...ajustes.map(a=>a.id_respaldo_anulacion).filter(Boolean));await prisma.saldo_favor_proveedor_m5.deleteMany({where:{id_proveedor:{in:ids.proveedores}}});await prisma.ajuste_obligacion_proveedor_m5.deleteMany({where:{id_proveedor:{in:ids.proveedores}}});await prisma.respaldo_pago_proveedor_m5.deleteMany({where:{id_respaldo_pago_m5:{in:[...new Set(ids.respaldos)]}}});
  await prisma.obligacion_proveedor_m5.deleteMany({where:{id_obligacion_m5:{in:ids.obligaciones}}});const asociaciones=await prisma.asociacion_documento_oc_m5.findMany({where:{id_documento_m5:{in:ids.documentos}}});await prisma.detalle_imputacion_m5.deleteMany({where:{id_clasificacion_m5:{in:(await prisma.clasificacion_asociacion_m5.findMany({where:{id_asociacion_m5:{in:asociaciones.map(a=>a.id_asociacion_m5)}}})).map(c=>c.id_clasificacion_m5)}}});await prisma.clasificacion_asociacion_m5.deleteMany({where:{id_asociacion_m5:{in:asociaciones.map(a=>a.id_asociacion_m5)}}});await prisma.asociacion_documento_oc_m5.deleteMany({where:{id_asociacion_m5:{in:asociaciones.map(a=>a.id_asociacion_m5)}}});await prisma.documento_proveedor_m5.deleteMany({where:{id_documento_m5:{in:ids.documentos}}});
  await prisma.historial_categoria_egreso_m5.deleteMany({where:{id_categoria_egreso_m5:{in:ids.categorias}}});await prisma.categoria_egreso_m5.deleteMany({where:{id_categoria_egreso_m5:{in:ids.categorias}}});await prisma.proveedor.deleteMany({where:{id_proveedor:{in:ids.proveedores}}});if(umbralInicial){await prisma.config_umbral_reclasificacion_m5.update({where:{id_configuracion:1},data:{monto_clp:umbralInicial.monto_clp,actualizado_por:umbralInicial.actualizado_por,fecha_actualizacion:umbralInicial.fecha_actualizacion}});await prisma.historial_umbral_reclasificacion_m5.deleteMany({where:{id_historial_umbral_m5:{notIn:historialUmbralInicial}}})}await prisma.$disconnect();
 }
});
