const {test}=require('node:test');
const assert=require('node:assert/strict');
const {randomUUID}=require('node:crypto');
const {readFileSync}=require('node:fs');
const {resolve}=require('node:path');
const {prisma}=require('../dist/db');
const {M6Controller}=require('../dist/controladores/M6Controller');
const {codigosTodosLosCU,matrizPermisosPorCU,operacionesPermiso,permiteOperacion}=require('../dist/validaciones/permisos');

test('M6 T9 CU191-CU195 documentos y exportaciones',async t=>{
 const marca=randomUUID().slice(0,8),enviados=[];let esperaCorreo=null;
 const correo={enviarDocumento:async(destinatario,asunto,archivo)=>{enviados.push({destinatario,asunto,archivo});if(esperaCorreo)await esperaCorreo}};
 const modulo=new M6Controller(undefined,undefined,correo),actor={id:0n};
 const ids={usuarios:[],empleados:[],periodos:[],remuneraciones:[],componentes:[],anticipos:[],pagos:[],medios:[],eventos:[]};
 const usuario=await prisma.usuario.create({data:{usuario_username:`m6t9_${marca}`}});ids.usuarios.push(usuario.usuario_id_usuario);actor.id=usuario.usuario_id_usuario;
 const crearEmpleado=async(nombre)=>{const empleado=await prisma.empleado.create({data:{rut_empleado:`T9-${marca}-${nombre}`,nombres:nombre,apellido_paterno:'Documental',estado_laboral:'activo',correo_particular:`${nombre.toLowerCase()}-${marca}@test.cl`,consentimiento_electronico:true,canal_documental:'correo_particular'}});ids.empleados.push(empleado.id_empleado);return empleado};
 const e1=await crearEmpleado('Uno'),e2=await crearEmpleado('Dos');
 const periodo=await prisma.periodo_remuneracion.create({data:{anio:2197,mes:4,fecha_inicio:new Date('2197-04-01'),fecha_fin:new Date('2197-04-30')}});ids.periodos.push(periodo.id_periodo_remuneracion);
 const crearRem=async(empleado,estado,total,reemplaza=null)=>{const r=await prisma.remuneracion.create({data:{id_periodo_remuneracion:periodo.id_periodo_remuneracion,id_empleado:empleado.id_empleado,estado,reemplaza_a_id:reemplaza,creado_por:usuario.usuario_id_usuario,total_haberes:total,total_deducciones:100,total_aportes_empleador:50,base_imponible:total,base_tributable:total-100,liquido_preliminar:total-100,cerrado_en:estado==='abierta'?null:new Date('2197-05-01'),cerrado_por:estado==='abierta'?null:usuario.usuario_id_usuario}});ids.remuneraciones.push(r.id_remuneracion);const c=await prisma.componente_remuneracion.create({data:{id_remuneracion:r.id_remuneracion,tipo:'VARIABLE_ADMINISTRATIVA',descripcion:`Snapshot ${total}`,monto:total,direccion:null,fuente_tipo:'SNAPSHOT',estado_revision:'aprobado',creado_por:usuario.usuario_id_usuario,revisado_por:usuario.usuario_id_usuario,fecha_revision:new Date('2197-05-01')}});ids.componentes.push(c.id_componente_remuneracion);return r};
 const historica=await crearRem(e1,'reemplazada',1000),vigente=await crearRem(e1,'cerrada',2000,historica.id_remuneracion),abierta=await crearRem(e2,'abierta',3000);
 try{
  await t.test('CU191 diferencia histórica/vigente, congela cifras y limita autoservicio',async()=>{const lista=await modulo.listarDocumentosRemuneracion({anio:2197,mes:4},actor);assert.equal(lista.filter(x=>x.tipo==='LIQUIDACION').length,2);assert.equal(lista.find(x=>x.id===historica.id_remuneracion).condicion,'HISTORICA_REEMPLAZADA');assert.equal(lista.find(x=>x.id===vigente.id_remuneracion).vigente,true);assert.equal(lista.some(x=>x.id===abierta.id_remuneracion),false);const archivo=await modulo.descargarDocumentoRemuneracion('LIQUIDACION',historica.id_remuneracion,actor);const pdf=Buffer.from(archivo.contenido.split(',')[1],'base64').toString('latin1');assert.match(pdf,/Snapshot 1000/);await prisma.empleado.update({where:{id_empleado:e1.id_empleado},data:{sueldo_base:999999}});const repetido=await modulo.descargarDocumentoRemuneracion('LIQUIDACION',historica.id_remuneracion,actor);assert.equal(repetido.contenido,archivo.contenido);await assert.rejects(modulo.descargarDocumentoRemuneracion('LIQUIDACION',vigente.id_remuneracion,{id:usuario.usuario_id_usuario,alcanceEmpleadoId:e2.id_empleado}),e=>e.estado===403)});
  await t.test('anticipo PREPARADO no es oficial y CONFIRMADO sí conserva condición neta',async()=>{const medio=await prisma.medio_pago.create({data:{nombre_medio_pago:`T9 ${marca}`,codigo_medio_pago:`T9${marca}`,estado_medio_pago:'activo',requiere_respaldo:false}});ids.medios.push(medio.id_medio_pago);const anticipo=await prisma.anticipo_remuneracion.create({data:{id_empleado:e1.id_empleado,id_periodo_remuneracion:periodo.id_periodo_remuneracion,modalidad:'MONTO',valor_ingresado:100,monto_final:100,estado_valorizacion:'VALORIZADO',clave_idempotencia:`ant-${marca}`,creado_por:usuario.usuario_id_usuario}});ids.anticipos.push(anticipo.id_anticipo);const pago=await prisma.pago_remuneracion.create({data:{origen_tipo:'ANTICIPO',origen_id:anticipo.id_anticipo,monto:100,id_medio_pago:medio.id_medio_pago,estado:'PREPARADO',clave_idempotencia:`p-${marca}`,creado_por:usuario.usuario_id_usuario}});ids.pagos.push(pago.id_pago_remuneracion);await assert.rejects(modulo.descargarDocumentoRemuneracion('COMPROBANTE_ANTICIPO',anticipo.id_anticipo,actor),e=>e.estado===409);await prisma.pago_remuneracion.update({where:{id_pago_remuneracion:pago.id_pago_remuneracion},data:{estado:'CONFIRMADO',confirmado_en:new Date(),confirmado_por:usuario.usuario_id_usuario}});const archivo=await modulo.descargarDocumentoRemuneracion('COMPROBANTE_ANTICIPO',anticipo.id_anticipo,actor);assert.match(archivo.nombre,/comprobante-anticipo/)});
  await t.test('CU192 usa consentimiento, resuelve vigente, fake de correo y traza aceptación sin fingir entrega',async()=>{const resultado=await modulo.reenviarDocumentoRemuneracion('LIQUIDACION',historica.id_remuneracion,actor);assert.equal(resultado.idDocumento,vigente.id_remuneracion);assert.equal(resultado.enviado,true);assert.equal(resultado.entregado,false);assert.equal(enviados.length,1);assert.match(enviados[0].archivo.nombre,new RegExp(String(vigente.id_remuneracion)));await prisma.empleado.update({where:{id_empleado:e1.id_empleado},data:{consentimiento_electronico:false}});await assert.rejects(modulo.reenviarDocumentoRemuneracion('LIQUIDACION',vigente.id_remuneracion,actor),e=>e.estado===409);await prisma.empleado.update({where:{id_empleado:e1.id_empleado},data:{consentimiento_electronico:true}});const evento=await prisma.evento_auditoria.findFirst({where:{tipo_evento:'M6_DOCUMENTO_REMUNERACION',accion_realizada:'REENVIO_DOCUMENTO_OFICIAL',id_registro_afectado:vigente.id_remuneracion},orderBy:{id_evento_auditoria:'desc'}});assert.equal(JSON.parse(evento.descripcion_evento).condicion,'ACEPTADO_POR_TRANSPORTE')});
  await t.test('CU192 fallo del transporte responde 503, registra FALLIDO y CU193 no lo considera entrega',async()=>{const moduloFallido=new M6Controller(undefined,undefined,{enviarDocumento:async()=>{throw new Error('Transporte rechazó el mensaje')}});await assert.rejects(moduloFallido.reenviarDocumentoRemuneracion('LIQUIDACION',historica.id_remuneracion,actor),e=>e.estado===503);const evento=await prisma.evento_auditoria.findFirst({where:{tipo_evento:'M6_DOCUMENTO_REMUNERACION',accion_realizada:'REENVIO_DOCUMENTO_OFICIAL',id_registro_afectado:vigente.id_remuneracion},orderBy:{id_evento_auditoria:'desc'}});assert.equal(evento.resultado_evento,'fallido');assert.equal(JSON.parse(evento.descripcion_evento).condicion,'FALLIDO');const condicion=await modulo.consultarEntregaDocumento('LIQUIDACION',vigente.id_remuneracion,actor);assert.equal(condicion.enviado,false);assert.equal(condicion.entregado,false);assert.equal(condicion.condicion.resultado,'FALLIDO')});
  await t.test('CU192 mantiene vigente bloqueada durante un reenvío concurrente',async()=>{let liberar;esperaCorreo=new Promise(resolve=>{liberar=resolve});const cantidad=enviados.length;const envio=modulo.reenviarDocumentoRemuneracion('LIQUIDACION',vigente.id_remuneracion,actor);while(enviados.length===cantidad)await new Promise(resolve=>setTimeout(resolve,5));const reemplazo=prisma.remuneracion.update({where:{id_remuneracion:vigente.id_remuneracion},data:{estado:'reemplazada'}});assert.equal(await Promise.race([reemplazo.then(()=>'actualizada'),new Promise(resolve=>setTimeout(()=>resolve('bloqueada'),100))]),'bloqueada');liberar();await envio;await reemplazo;esperaCorreo=null;await prisma.remuneracion.update({where:{id_remuneracion:vigente.id_remuneracion},data:{estado:'cerrada'}})});
  await t.test('CU193 registra última condición conceptual sin entidad paralela',async()=>{await modulo.registrarEntregaDocumento({tipo:'LIQUIDACION',id:vigente.id_remuneracion,canal:'presencial',resultado:'entregado',destinatarioLogico:'empleado'},actor);const condicion=await modulo.consultarEntregaDocumento('LIQUIDACION',vigente.id_remuneracion,actor);assert.equal(condicion.enviado,true);assert.equal(condicion.entregado,true);assert.equal(condicion.condicion.resultado,'ENTREGADO');assert.equal(condicion.condicion.canal,'presencial');const schema=readFileSync(resolve('prisma/schema.prisma'),'utf8');assert.doesNotMatch(schema,/model\s+(entrega_documental|intento_entrega_documental|documento_remuneracional|historial_exportacion_remuneracion)\s*\{/i)});
  await t.test('controller queda desacoplado del modelo físico y admite adapter sustituible',async()=>{const eventos=[];const auditoria={registrar:async(_cliente,evento)=>{eventos.push(evento);return{referenciaEvento:9001}},ultimaCondicionEntrega:async()=>null};const moduloAislado=new M6Controller(undefined,undefined,correo,auditoria);await moduloAislado.exportarCalculoPreliminar(abierta.id_remuneracion,actor);assert.equal(eventos.at(-1).accion,'EXPORTACION_PRELIMINAR');assert.equal(eventos.at(-1).condicion,'GENERADO');const controlador=readFileSync(resolve('src/controladores/M6Controller.ts'),'utf8');assert.doesNotMatch(controlador,/evento_auditoria/)});
  await t.test('CU194 exporta ABIERTA marcada no oficial con bloqueos y sin mutar',async()=>{const antes=await prisma.componente_remuneracion.count({where:{id_remuneracion:abierta.id_remuneracion}});const archivo=await modulo.exportarCalculoPreliminar(abierta.id_remuneracion,actor);const pdf=Buffer.from(archivo.contenido.split(',')[1],'base64').toString('latin1');assert.match(archivo.nombre,/no-oficial/);assert.match(pdf,/NO OFICIAL/);assert.match(pdf,/BLOQUEOS/);assert.equal((await prisma.remuneracion.findUnique({where:{id_remuneracion:abierta.id_remuneracion}})).estado,'abierta');assert.equal(await prisma.componente_remuneracion.count({where:{id_remuneracion:abierta.id_remuneracion}}),antes);await assert.rejects(modulo.exportarCalculoPreliminar(vigente.id_remuneracion,actor),e=>e.estado===409)});
  await t.test('CU195 usa snapshot oficial vigente, excluye abierta/reemplazada y no exige pago',async()=>{const archivo=await modulo.exportarRemuneracionesOficiales({anio:2197,mes:4},actor);const pdf=Buffer.from(archivo.contenido.split(',')[1],'base64').toString('latin1');assert.match(archivo.nombre,/remuneraciones-oficiales/);assert.match(pdf,/OFICIALES/);assert.match(pdf,new RegExp(`Remuneracion ${vigente.id_remuneracion}`));assert.doesNotMatch(pdf,new RegExp(`Remuneracion ${historica.id_remuneracion}`));assert.doesNotMatch(pdf,new RegExp(`Remuneracion ${abierta.id_remuneracion}`));assert.equal(await prisma.evento_auditoria.count({where:{accion_realizada:'EXPORTACION_OFICIAL'}})>0,true)});
  await t.test('permisos llegan exactamente a CU195 sin CU196',()=>{assert.equal(codigosTodosLosCU.length,195);for(let n=191;n<=195;n++)assert.deepEqual(matrizPermisosPorCU[`CU${n}`],[]);assert.equal(operacionesPermiso.listarDocumentosRemuneracion,'CU191');assert.equal(operacionesPermiso.reenviarDocumentoRemuneracion,'CU192');assert.equal(operacionesPermiso.registrarEntregaDocumento,'CU193');assert.equal(operacionesPermiso.exportarCalculoPreliminar,'CU194');assert.equal(operacionesPermiso.exportarRemuneracionesOficiales,'CU195');assert.equal(permiteOperacion('reenviarDocumentoRemuneracion',['CU191']),false);assert.equal(codigosTodosLosCU.includes('CU196'),false)});
 }finally{
  await prisma.evento_auditoria.deleteMany({where:{id_usuario:usuario.usuario_id_usuario}});await prisma.reversion_pago_remuneracion.deleteMany({where:{pago:{id_pago_remuneracion:{in:ids.pagos}}}});await prisma.pago_remuneracion.deleteMany({where:{id_pago_remuneracion:{in:ids.pagos}}});await prisma.componente_remuneracion.deleteMany({where:{id_componente_remuneracion:{in:ids.componentes}}});await prisma.remuneracion.deleteMany({where:{id_remuneracion:{in:[vigente.id_remuneracion,abierta.id_remuneracion]}}});await prisma.remuneracion.deleteMany({where:{id_remuneracion:historica.id_remuneracion}});await prisma.anticipo_remuneracion.deleteMany({where:{id_anticipo:{in:ids.anticipos}}});await prisma.periodo_remuneracion.deleteMany({where:{id_periodo_remuneracion:{in:ids.periodos}}});await prisma.empleado.deleteMany({where:{id_empleado:{in:ids.empleados}}});await prisma.medio_pago.deleteMany({where:{id_medio_pago:{in:ids.medios}}});await prisma.usuario.deleteMany({where:{usuario_id_usuario:{in:ids.usuarios}}});
 }
});
