const { test } = require('node:test');
const assert = require('node:assert/strict');
const { randomUUID } = require('node:crypto');
const { readFileSync } = require('node:fs');
const { resolve } = require('node:path');
const { prisma } = require('../dist/db');
const { M6Controller } = require('../dist/controladores/M6Controller');
const { codigosTodosLosCU, matrizPermisosPorCU, operacionesPermiso, permiteOperacion } = require('../dist/validaciones/permisos');

function rutValido(){const cuerpo=String(Math.floor(Math.random()*8_000_000)+1_000_000);let suma=0,m=2;for(let i=cuerpo.length-1;i>=0;i--){suma+=Number(cuerpo[i])*m;m=m===7?2:m+1}const r=11-(suma%11);return `${cuerpo}-${r===11?'0':r===10?'K':r}`}

test('M6 T6 CU178-CU182 ejecuta el ciclo mensual sin pagos ni documentos',async t=>{
 const modulo=new M6Controller(),sufijo=randomUUID().slice(0,8);const ids={empleados:[],usuarios:[],relaciones:[],periodos:[],tramos:[],conceptos:[],asignaciones:[]};
 const crearEmpleado=async(nombre)=>{const e=await modulo.crearEmpleado({rut:rutValido(),nombres:nombre,apellidoPaterno:'Mensual'});ids.empleados.push(e.id);await prisma.empleado.update({where:{id_empleado:e.id},data:{sueldo_base:800000,fecha_aplicacion_sueldo_base:new Date('2098-01-01')}});return e};
 const e1=await crearEmpleado('Ana'),e2=await crearEmpleado('Berta');
 const u1=await prisma.usuario.create({data:{usuario_username:`m6t6_${sufijo}`,usuario_nombre_completo_primer_nombre_usuario:'Ana'}}),u2=await prisma.usuario.create({data:{usuario_username:`m6t6b_${sufijo}`,usuario_nombre_completo_primer_nombre_usuario:'Berta'}});ids.usuarios.push(u1.usuario_id_usuario,u2.usuario_id_usuario);
 const relacion=async(id,desde,hasta=null)=>{const r=await prisma.relacion_laboral_empleado.create({data:{id_empleado:id,fecha_inicio:new Date(desde),fecha_termino:hasta?new Date(hasta):null,estado:hasta?'terminada':'vigente'}});ids.relaciones.push(r.id_relacion_laboral_empleado)};
 await relacion(e1.id,'2098-01-01','2098-01-10');await relacion(e1.id,'2098-01-20');await relacion(e2.id,'2097-12-01');
 const tramo=await prisma.tramo_impuesto_renta.create({data:{vigencia_desde:new Date('2098-01-01'),vigencia_hasta:new Date('2098-12-31'),orden:1,limite_desde:0,limite_hasta:null,factor:0,rebaja:0,unidad:'CLP',estado:'activo'}});ids.tramos.push(tramo.id_tramo_impuesto_renta);
 const aporte=await prisma.concepto_remuneracion.create({data:{codigo_m6:`AP${sufijo}`,nombre_concepto:`Aporte ${sufijo}`,naturaleza_concepto:'aporte_empleador',configuraciones_m6:{create:{modalidad:'FIJO',valor:100,vigencia_desde:new Date('2098-01-01'),vigencia_hasta:new Date('2098-12-31')}}}});ids.conceptos.push(aporte.id_concepto_remuneracion);
 try{
  await t.test('CU178 resuelve solapamiento, reingreso una sola vez y empleado sin Usuario',async()=>{const p=await modulo.consultarPeriodoRemuneracion(2098,1);assert.equal(p.resumen.exigibles,2);assert.equal(p.empleados.filter(x=>x.idEmpleado===e1.id).length,1);assert.equal(p.empleados.find(x=>x.idEmpleado===e1.id).relaciones.length,2);assert.ok(p.empleados.find(x=>x.idEmpleado===e2.id))});
  let r1;
  await t.test('CU179 crea/reutiliza ABIERTA, recalcula idempotente y conserva manuales',async()=>{let c=await modulo.calcularRemuneracion({idEmpleado:e1.id,anio:2098,mes:1},u1.usuario_id_usuario);r1=c.remuneracion;ids.periodos.push(r1.periodo.id);assert.equal(c.bloqueos.length,0);assert.equal(r1.totales.haberes,800000);assert.equal(r1.totales.aportesEmpleador,0);assert.equal(r1.totales.liquidoPreliminar,800000);assert.equal(r1.componentes.some(x=>x.concepto?.id===aporte.id_concepto_remuneracion),false);await modulo.proponerComponenteExcepcional(r1.id,{modalidad:'MONTO',descripcion:'Bono aprobado',monto:10000},u1.usuario_id_usuario);let actual=await modulo.obtenerRemuneracion(r1.id);const manual=actual.componentes.find(x=>x.tipo==='EXCEPCIONAL_POSITIVO');await modulo.resolverComponenteExcepcional(manual.id,{decision:'aprobar'},u2.usuario_id_usuario);c=await modulo.calcularRemuneracion({idEmpleado:e1.id,anio:2098,mes:1},u1.usuario_id_usuario);assert.equal(c.remuneracion.id,r1.id);assert.equal(c.remuneracion.componentes.filter(x=>x.tipo==='SUELDO_BASE').length,1);assert.ok(c.remuneracion.componentes.some(x=>x.id===manual.id));assert.equal(c.remuneracion.totales.haberes,810000)});
  await t.test('CU179 deja impuesto pendiente cuando falta el set y no lo convierte en cero',async()=>{const c=await modulo.calcularRemuneracion({idEmpleado:e2.id,anio:2099,mes:1},u1.usuario_id_usuario);assert.ok(c.bloqueos.some(x=>x.codigo==='COMPONENTE_PENDIENTE'));assert.equal(c.remuneracion.totales.liquidoPreliminar,null);const idPeriodo=c.remuneracion.periodo.id;await prisma.componente_remuneracion.deleteMany({where:{id_remuneracion:c.remuneracion.id}});await prisma.remuneracion.delete({where:{id_remuneracion:c.remuneracion.id}});await prisma.periodo_remuneracion.delete({where:{id_periodo_remuneracion:idPeriodo}})});
  await t.test('CU179 serializa recálculos concurrentes sin duplicar la remuneración ni sus fuentes',async()=>{const carrera=await Promise.allSettled([modulo.calcularRemuneracion({idEmpleado:e1.id,anio:2098,mes:1},u1.usuario_id_usuario),modulo.calcularRemuneracion({idEmpleado:e1.id,anio:2098,mes:1},u2.usuario_id_usuario)]);assert.ok(carrera.some(x=>x.status==='fulfilled'));assert.equal(await prisma.remuneracion.count({where:{id_periodo_remuneracion:r1.periodo.id,id_empleado:e1.id,estado:{not:'reemplazada'}}}),1);assert.equal(await prisma.componente_remuneracion.count({where:{id_remuneracion:r1.id,tipo:'SUELDO_BASE'}}),1)});
  await t.test('CU180 serializa cierres, congela y deriva liquidación sin documento',async()=>{const carrera=await Promise.allSettled([modulo.cerrarRemuneracion(r1.id,u1.usuario_id_usuario),modulo.cerrarRemuneracion(r1.id,u2.usuario_id_usuario)]);assert.equal(carrera.filter(x=>x.status==='fulfilled').length,1);const cerrada=await modulo.obtenerRemuneracion(r1.id);assert.equal(cerrada.estado,'cerrada');assert.equal((await modulo.obtenerLiquidacionRemuneracion(r1.id)).documentoGenerado,false);await assert.rejects(modulo.proponerComponenteExcepcional(r1.id,{modalidad:'MONTO',descripcion:'Tardío',monto:1},u1.usuario_id_usuario),e=>e.estado===409)});
  let r2;
  await t.test('CU182 exige aprobador distinto y serializa la creación de R2 sin mover componentes',async()=>{await modulo.solicitarReaperturaRemuneracion(r1.id,{motivo:'Rectificar antecedente validado'},u1.usuario_id_usuario);await assert.rejects(modulo.aprobarReaperturaRemuneracion(r1.id,u1.usuario_id_usuario),e=>e.estado===409);const carrera=await Promise.allSettled([modulo.aprobarReaperturaRemuneracion(r1.id,u2.usuario_id_usuario),modulo.aprobarReaperturaRemuneracion(r1.id,u2.usuario_id_usuario)]);assert.equal(carrera.filter(x=>x.status==='fulfilled').length,1);r2=carrera.find(x=>x.status==='fulfilled').value;assert.equal(r2.estado,'abierta');assert.equal(r2.reemplazaAId,r1.id);assert.equal(r2.componentes.length,0);const original=await modulo.obtenerRemuneracion(r1.id);assert.equal(original.estado,'reemplazada');assert.ok(original.componentes.length>0)});
  await t.test('CU181 sólo cierra con toda la población exigible cerrada y no exige pago',async()=>{await assert.rejects(modulo.cerrarPeriodoRemuneracion(2098,1,u1.usuario_id_usuario),e=>e.estado===409);await modulo.calcularRemuneracion({idEmpleado:e1.id,anio:2098,mes:1},u1.usuario_id_usuario);await modulo.cerrarRemuneracion(r2.id,u1.usuario_id_usuario);const c2=await modulo.calcularRemuneracion({idEmpleado:e2.id,anio:2098,mes:1},u1.usuario_id_usuario);await modulo.cerrarRemuneracion(c2.remuneracion.id,u1.usuario_id_usuario);const periodo=await modulo.cerrarPeriodoRemuneracion(2098,1,u1.usuario_id_usuario);assert.ok(periodo.periodo.cerradoEn);await assert.rejects(modulo.calcularRemuneracion({idEmpleado:e1.id,anio:2098,mes:1},u1.usuario_id_usuario),e=>e.estado===409);await assert.rejects(modulo.solicitarReaperturaRemuneracion(c2.remuneracion.id,{motivo:'Posterior al cierre'},u1.usuario_id_usuario),e=>e.codigo==='PERIODO_CERRADO_REAPERTURA_PENDIENTE_DE_DEFINICION')});
  await t.test('permisos CU178-CU182 siguen independientes',()=>{assert.equal(codigosTodosLosCU.length,197);for(let n=178;n<=197;n++)assert.deepEqual(matrizPermisosPorCU[`CU${n}`],[]);assert.equal(codigosTodosLosCU.includes('CU197'),true);assert.equal(codigosTodosLosCU.includes('CU198'),false);assert.equal(operacionesPermiso.consultarPeriodoRemuneracion,'CU178');assert.equal(operacionesPermiso.calcularRemuneracion,'CU179');assert.equal(operacionesPermiso.cerrarRemuneracion,'CU180');assert.equal(operacionesPermiso.cerrarPeriodoRemuneracion,'CU181');assert.equal(operacionesPermiso.aprobarReaperturaRemuneracion,'CU182');assert.equal(permiteOperacion('cerrarRemuneracion',['CU179']),false)});
  await t.test('persistencia no crea artefactos descartados ni tasas hardcodeadas',()=>{const schema=readFileSync(resolve('prisma/schema.prisma'),'utf8');const migracion=readFileSync(resolve('prisma/migrations/032_m6_ciclo_mensual_remuneraciones/migration.sql'),'utf8');const controlador=readFileSync(resolve('src/controladores/M6Controller.ts'),'utf8');const conjunto=`${schema}\n${migracion}\n${controlador}`;assert.match(schema,/cerrado_en\s+DateTime\?/);assert.match(migracion,/uq_componente_automatico_clave/);assert.match(migracion,/reapertura_solicitada_por/);assert.doesNotMatch(conjunto,/model\s+(remuneracion_version|documento_remuneracional|historial_remuneracion|historial_componente|cierre_remuneracion|obligacion_pago_remuneracion|configuracion_anticipo_empleado|hecho_remunerable_consumido)\s*\{/i);assert.doesNotMatch(controlador,/eval\s*\(|new\s+Function\s*\(/);assert.equal(codigosTodosLosCU.includes('CU198'),false)});
 }finally{
  const periodos=await prisma.periodo_remuneracion.findMany({where:{anio:2098,mes:1},select:{id_periodo_remuneracion:true}});const pids=periodos.map(x=>x.id_periodo_remuneracion);const rems=await prisma.remuneracion.findMany({where:{id_periodo_remuneracion:{in:pids}},select:{id_remuneracion:true}});const rids=rems.map(x=>x.id_remuneracion);await prisma.componente_remuneracion.deleteMany({where:{id_remuneracion:{in:rids}}});await prisma.remuneracion.updateMany({where:{id_remuneracion:{in:rids}},data:{reemplaza_a_id:null}});await prisma.remuneracion.deleteMany({where:{id_remuneracion:{in:rids}}});await prisma.periodo_remuneracion.deleteMany({where:{id_periodo_remuneracion:{in:pids}}});await prisma.tramo_impuesto_renta.deleteMany({where:{id_tramo_impuesto_renta:{in:ids.tramos}}});await prisma.asignacion_concepto_remuneracion_empleado.deleteMany({where:{id_asignacion_concepto:{in:ids.asignaciones}}});await prisma.configuracion_concepto_remuneracion.deleteMany({where:{id_concepto:{in:ids.conceptos}}});await prisma.concepto_remuneracion.deleteMany({where:{id_concepto_remuneracion:{in:ids.conceptos}}});await prisma.relacion_laboral_empleado.deleteMany({where:{id_relacion_laboral_empleado:{in:ids.relaciones}}});await prisma.usuario.deleteMany({where:{usuario_id_usuario:{in:ids.usuarios}}});await prisma.empleado.deleteMany({where:{id_empleado:{in:ids.empleados}}});
 }
});

test('auditoría CU157-CU182 protege población, decisiones y cierres históricos',async t=>{
 const modulo=new M6Controller(),sufijo=randomUUID().slice(0,8);
 const ids={empleados:[],usuarios:[],relaciones:[],periodos:[],tramos:[],conceptos:[],asignaciones:[],esquemas:[],tarifas:[],tareas:[],ejecuciones:[]};
 const crearEmpleado=async(nombre,sueldo=1000,fecha='2095-01-01')=>{const e=await modulo.crearEmpleado({rut:rutValido(),nombres:nombre,apellidoPaterno:'Auditoria'});ids.empleados.push(e.id);await prisma.empleado.update({where:{id_empleado:e.id},data:{sueldo_base:sueldo,fecha_aplicacion_sueldo_base:new Date(fecha)}});return e};
 const crearRelacionDirecta=async(empleado,inicio,termino=null)=>{const r=await prisma.relacion_laboral_empleado.create({data:{id_empleado:empleado.id,fecha_inicio:new Date(inicio),fecha_termino:termino?new Date(termino):null,estado:termino?'terminada':'vigente'}});ids.relaciones.push(r.id_relacion_laboral_empleado);return r};
 const u1=await prisma.usuario.create({data:{usuario_username:`aud1_${sufijo}`,usuario_nombre_completo_primer_nombre_usuario:'Auditora'}}),u2=await prisma.usuario.create({data:{usuario_username:`aud2_${sufijo}`,usuario_nombre_completo_primer_nombre_usuario:'Aprobador'}});ids.usuarios.push(u1.usuario_id_usuario,u2.usuario_id_usuario);
 const tramo=await prisma.tramo_impuesto_renta.create({data:{vigencia_desde:new Date('2095-01-01'),vigencia_hasta:new Date('2095-12-31'),orden:1,limite_desde:0,limite_hasta:null,factor:0,rebaja:0,unidad:'CLP',estado:'activo'}});ids.tramos.push(tramo.id_tramo_impuesto_renta);
 try{
  await t.test('CU157 bloquea intervalos retroactivos y permite intervalos posteriores',async()=>{
   const cerrado=await modulo.cerrarPeriodoRemuneracion(2095,1,u1.usuario_id_usuario);ids.periodos.push(cerrado.periodo.id);
   const retro=await crearEmpleado('Retroactivo');
   await assert.rejects(modulo.crearRelacionLaboral(retro.id,{fechaInicio:'2095-01-15',fechaTermino:'2095-01-20'}),e=>e.estado===409&&e.codigo==='PERIODO_REMUNERACION_CERRADO');
   const posterior=await crearEmpleado('Posterior');
   let relaciones=await modulo.crearRelacionLaboral(posterior.id,{fechaInicio:'2095-02-01'});ids.relaciones.push(relaciones[0].id);
   await assert.rejects(modulo.actualizarRelacionLaboral(posterior.id,relaciones[0].id,{fechaInicio:'2095-01-20'}),e=>e.estado===409&&e.codigo==='PERIODO_REMUNERACION_CERRADO');
   const termino=await crearEmpleado('Termino');
   relaciones=await modulo.crearRelacionLaboral(termino.id,{fechaInicio:'2094-12-01',fechaTermino:'2094-12-31'});ids.relaciones.push(relaciones[0].id);
   await assert.rejects(modulo.actualizarRelacionLaboral(termino.id,relaciones[0].id,{fechaTermino:'2095-01-10'}),e=>e.estado===409&&e.codigo==='PERIODO_REMUNERACION_CERRADO');
  });
  await t.test('CU157 y CU181 serializan la población del período',async()=>{
   const carrera=await crearEmpleado('Carrera');
   const resultados=await Promise.allSettled([modulo.cerrarPeriodoRemuneracion(2093,6,u1.usuario_id_usuario),modulo.crearRelacionLaboral(carrera.id,{fechaInicio:'2093-06-10',fechaTermino:'2093-06-20'})]);
   const periodo=await prisma.periodo_remuneracion.findUnique({where:{anio_mes:{anio:2093,mes:6}}});if(periodo)ids.periodos.push(periodo.id_periodo_remuneracion);
   const relacion=await prisma.relacion_laboral_empleado.findFirst({where:{id_empleado:carrera.id}});if(relacion)ids.relaciones.push(relacion.id_relacion_laboral_empleado);
   assert.equal(Boolean(periodo?.cerrado_en&&relacion),false);assert.ok(resultados.some(x=>x.status==='rejected'));
  });
  await t.test('CU179 no aplica catálogos globales y preserva automáticos revisados/referenciados',async()=>{
   const empleado=await crearEmpleado('Calculo');await crearRelacionDirecta(empleado,'2095-02-01');
   const globales=[];for(const naturaleza of ['descuento','aporte_empleador']){const c=await prisma.concepto_remuneracion.create({data:{codigo_m6:`G${naturaleza[0]}${sufijo}`,nombre_concepto:`Global ${naturaleza} ${sufijo}`,naturaleza_concepto:naturaleza,configuraciones_m6:{create:{modalidad:'FIJO',valor:999,vigencia_desde:new Date('2095-01-01')}}}});ids.conceptos.push(c.id_concepto_remuneracion);globales.push(c)}
   const asignado=await prisma.concepto_remuneracion.create({data:{codigo_m6:`AS${sufijo}`,nombre_concepto:`Haber asignado ${sufijo}`,naturaleza_concepto:'haber',configuraciones_m6:{create:{modalidad:'FIJO',valor:100,vigencia_desde:new Date('2095-01-01')}}}});ids.conceptos.push(asignado.id_concepto_remuneracion);
   const asignacion=await prisma.asignacion_concepto_remuneracion_empleado.create({data:{id_empleado:empleado.id,id_concepto:asignado.id_concepto_remuneracion,vigencia_desde:new Date('2095-01-01')}});ids.asignaciones.push(asignacion.id_asignacion_concepto);
   let calculo=await modulo.calcularRemuneracion({idEmpleado:empleado.id,anio:2095,mes:2},u1.usuario_id_usuario);ids.periodos.push(calculo.remuneracion.periodo.id);
   assert.equal(calculo.remuneracion.componentes.some(x=>globales.some(g=>x.concepto?.id===g.id_concepto_remuneracion)),false);assert.equal(calculo.remuneracion.totales.haberes,1100);assert.equal(calculo.remuneracion.totales.deducciones,0);assert.equal(calculo.remuneracion.totales.aportesEmpleador,0);
   const automatico=calculo.remuneracion.componentes.find(x=>x.concepto?.id===asignado.id_concepto_remuneracion);
   await prisma.componente_remuneracion.create({data:{id_remuneracion:calculo.remuneracion.id,tipo:'EXCEPCIONAL_POSITIVO',descripcion:'Derivado de automático revisado',monto:1,fuente_tipo:'MANUAL',estado_revision:'aprobado',id_componente_origen:automatico.id,tipo_relacion:'CANDIDATO_CONFLICTO',creado_por:u1.usuario_id_usuario,revisado_por:u2.usuario_id_usuario,fecha_revision:new Date()}});
   const config=await prisma.configuracion_concepto_remuneracion.findFirstOrThrow({where:{id_concepto:asignado.id_concepto_remuneracion}});await prisma.configuracion_concepto_remuneracion.update({where:{id_configuracion_concepto:config.id_configuracion_concepto},data:{valor:200}});
   await assert.rejects(modulo.cerrarRemuneracion(calculo.remuneracion.id,u1.usuario_id_usuario),e=>e.estado===409&&e.codigo==='REMUNERACION_CON_BLOQUEOS');
   await modulo.calcularRemuneracion({idEmpleado:empleado.id,anio:2095,mes:2},u1.usuario_id_usuario);
   const preservado=await prisma.componente_remuneracion.findUnique({where:{id_componente_remuneracion:automatico.id}});const candidato=await prisma.componente_remuneracion.findFirst({where:{id_remuneracion:calculo.remuneracion.id,id_componente_origen:automatico.id,fuente_tipo:'AUTOMATICA'}});
   assert.ok(preservado);assert.equal(preservado.fuente_tipo,'AUTOMATICA_HISTORICA');assert.equal(candidato.estado_revision,'conflicto');assert.equal(await prisma.componente_remuneracion.count({where:{id_componente_origen:automatico.id}}),2);
  });
  await t.test('CU180 revalida tarifa y hechos nuevos antes de cerrar',async()=>{
   const empleado=await crearEmpleado('Terreno');await crearRelacionDirecta(empleado,'2095-03-01');
   const usuario=await prisma.usuario.create({data:{usuario_username:`ter_${sufijo}`,usuario_nombre_completo_primer_nombre_usuario:'Terreno',empleado_m4:empleado.rut}});ids.usuarios.push(usuario.usuario_id_usuario);
   const tarea=await prisma.tarea.create({data:{tarea_titulo:`Auditoría ${sufijo}`,id_usuario:usuario.usuario_id_usuario}});ids.tareas.push(tarea.tarea_tarea_id);
   const esquema=await prisma.esquema_remuneracional.create({data:{codigo:`AUD${sufijo}`,nombre:`Auditoría ${sufijo}`,vigencia_desde:new Date('2095-01-01')}});ids.esquemas.push(esquema.id_esquema_remuneracional);
   await prisma.asignacion_esquema_remuneracional.create({data:{id_esquema:esquema.id_esquema_remuneracional,id_empleado:empleado.id,vigencia_desde:new Date('2095-01-01')}});
   const tarifa=await prisma.tarifa_esquema_remuneracional.create({data:{id_esquema:esquema.id_esquema_remuneracional,modalidad:'FIJO',valor:50,tipo_aplicacion:'global',vigencia_desde:new Date('2095-01-01'),estado_revision:'activa'}});ids.tarifas.push(tarifa.id_tarifa_esquema);
   const ejecucion=await prisma.ejecucion_tarea.create({data:{id_tarea:tarea.tarea_tarea_id,id_usuario_ejecutor:usuario.usuario_id_usuario,fecha_ejecucion:new Date('2095-03-10'),estado_ejecucion:'terminada',estado_validacion_productiva:'validada'}});ids.ejecuciones.push(ejecucion.id_ejecucion_tarea);await modulo.revisarHechoRemunerable(ejecucion.id_ejecucion_tarea);
   const calculo=await modulo.calcularRemuneracion({idEmpleado:empleado.id,anio:2095,mes:3},u1.usuario_id_usuario);ids.periodos.push(calculo.remuneracion.periodo.id);
   await prisma.tarifa_esquema_remuneracional.update({where:{id_tarifa_esquema:tarifa.id_tarifa_esquema},data:{valor:75}});
   await assert.rejects(modulo.cerrarRemuneracion(calculo.remuneracion.id,u1.usuario_id_usuario),e=>e.estado===409&&e.codigo==='REMUNERACION_CON_BLOQUEOS');
   await modulo.calcularRemuneracion({idEmpleado:empleado.id,anio:2095,mes:3},u1.usuario_id_usuario);
   const conflicto=(await modulo.obtenerRemuneracion(calculo.remuneracion.id)).componentes.find(x=>x.tipo==='HECHO_TERRENO'&&x.estadoRevision==='conflicto');assert.equal(conflicto.monto,75);
   const nuevo=await crearEmpleado('TerrenoNuevo');await crearRelacionDirecta(nuevo,'2095-03-01');const usuarioNuevo=await prisma.usuario.create({data:{usuario_username:`tern_${sufijo}`,usuario_nombre_completo_primer_nombre_usuario:'Terreno nuevo',empleado_m4:nuevo.rut}});ids.usuarios.push(usuarioNuevo.usuario_id_usuario);const tareaNueva=await prisma.tarea.create({data:{tarea_titulo:`Hecho nuevo ${sufijo}`,id_usuario:usuarioNuevo.usuario_id_usuario}});ids.tareas.push(tareaNueva.tarea_tarea_id);await prisma.asignacion_esquema_remuneracional.create({data:{id_esquema:esquema.id_esquema_remuneracional,id_empleado:nuevo.id,vigencia_desde:new Date('2095-01-01')}});
   const preliminar=await modulo.calcularRemuneracion({idEmpleado:nuevo.id,anio:2095,mes:3},u1.usuario_id_usuario);const ejecucionNueva=await prisma.ejecucion_tarea.create({data:{id_tarea:tareaNueva.tarea_tarea_id,id_usuario_ejecutor:usuarioNuevo.usuario_id_usuario,fecha_ejecucion:new Date('2095-03-20'),estado_ejecucion:'terminada',estado_validacion_productiva:'validada'}});ids.ejecuciones.push(ejecucionNueva.id_ejecucion_tarea);await modulo.revisarHechoRemunerable(ejecucionNueva.id_ejecucion_tarea);const cierre=await modulo.cerrarRemuneracion(preliminar.remuneracion.id,u1.usuario_id_usuario);assert.equal(cierre.remuneracion.estado,'cerrada');assert.ok(cierre.remuneracion.componentes.some(x=>x.claveNegocio===`EJECUCION:${ejecucionNueva.id_ejecucion_tarea.toString()}`));
  });
  await t.test('historia cerrada y CU182 no alteran cifras ni componentes de R1',async()=>{
   const empleado=await crearEmpleado('Historia');await crearRelacionDirecta(empleado,'2095-04-01');
   const calculo=await modulo.calcularRemuneracion({idEmpleado:empleado.id,anio:2095,mes:4},u1.usuario_id_usuario);ids.periodos.push(calculo.remuneracion.periodo.id);const manual=await prisma.componente_remuneracion.create({data:{id_remuneracion:calculo.remuneracion.id,tipo:'VARIABLE_ADMINISTRATIVA',descripcion:'Conflicto previo al cierre',monto:10,fuente_tipo:'MANUAL',clave_negocio:`CONFLICTO:${sufijo}`,estado_revision:'conflicto',creado_por:u1.usuario_id_usuario}});await assert.rejects(modulo.cerrarRemuneracion(calculo.remuneracion.id,u1.usuario_id_usuario),e=>e.codigo==='REMUNERACION_CON_BLOQUEOS');await prisma.componente_remuneracion.update({where:{id_componente_remuneracion:manual.id_componente_remuneracion},data:{estado_revision:'rechazado',revisado_por:u2.usuario_id_usuario,fecha_revision:new Date()}});await modulo.cerrarRemuneracion(calculo.remuneracion.id,u1.usuario_id_usuario);
   const antes=await modulo.obtenerLiquidacionRemuneracion(calculo.remuneracion.id);const idsComponentes=antes.remuneracion.componentes.map(x=>x.id);await prisma.empleado.update({where:{id_empleado:empleado.id},data:{sueldo_base:999999}});
   const despues=await modulo.obtenerLiquidacionRemuneracion(calculo.remuneracion.id);assert.deepEqual(despues.remuneracion.totales,antes.remuneracion.totales);assert.deepEqual(despues.remuneracion.componentes.map(x=>x.id),idsComponentes);
   const moduloConPago=new M6Controller({consultarEstado:async()=>({fuenteDisponible:true,tienePago:true})});await assert.rejects(moduloConPago.solicitarReaperturaRemuneracion(calculo.remuneracion.id,{motivo:'No debe reabrir pagada'},u1.usuario_id_usuario),e=>e.estado===409&&/pago registrado/i.test(e.message));
   await modulo.solicitarReaperturaRemuneracion(calculo.remuneracion.id,{motivo:'Auditar inmutabilidad'},u1.usuario_id_usuario);const solicitada=await modulo.obtenerRemuneracion(calculo.remuneracion.id);assert.deepEqual(solicitada.totales,antes.remuneracion.totales);assert.deepEqual(solicitada.componentes.map(x=>x.id),idsComponentes);
   const r2=await modulo.aprobarReaperturaRemuneracion(calculo.remuneracion.id,u2.usuario_id_usuario);assert.equal(r2.componentes.length,0);const r1=await modulo.obtenerRemuneracion(calculo.remuneracion.id);assert.equal(r1.estado,'reemplazada');assert.deepEqual(r1.totales,antes.remuneracion.totales);assert.deepEqual(r1.componentes.map(x=>x.id),idsComponentes);
  });
  await t.test('guard de pago usa la fuente real y CU214 no se simula',()=>{const controlador=readFileSync(resolve('src/controladores/M6Controller.ts'),'utf8');const fuente=readFileSync(resolve('src/servicios/FuentePagoRemuneracion.ts'),'utf8');const schema=readFileSync(resolve('prisma/schema.prisma'),'utf8');assert.match(controlador,/FuentePagoRemuneracionPrisma/);assert.match(fuente,/interface FuentePagoRemuneracion/);assert.match(fuente,/consultarEstado/);assert.doesNotMatch(controlador,/remuneracionTienePago[\s\S]{0,200}return false/);assert.match(schema,/model\s+pago_remuneracion\s*\{/);assert.doesNotMatch(schema,/model\s+(obligacion_pago_remuneracion|deduccion_recurrente_empleado)\s*\{/);assert.equal(codigosTodosLosCU.includes('CU214'),false)});
 }finally{
  const pids=[...new Set(ids.periodos)];const rems=await prisma.remuneracion.findMany({where:{id_periodo_remuneracion:{in:pids}},select:{id_remuneracion:true}});const rids=rems.map(x=>x.id_remuneracion);await prisma.componente_remuneracion.deleteMany({where:{id_remuneracion:{in:rids}}});await prisma.remuneracion.updateMany({where:{id_remuneracion:{in:rids}},data:{reemplaza_a_id:null}});await prisma.remuneracion.deleteMany({where:{id_remuneracion:{in:rids}}});await prisma.periodo_remuneracion.deleteMany({where:{id_periodo_remuneracion:{in:pids}}});await prisma.tratamiento_remuneracional_ejecucion.deleteMany({where:{id_ejecucion_tarea:{in:ids.ejecuciones}}});await prisma.ejecucion_tarea.deleteMany({where:{id_ejecucion_tarea:{in:ids.ejecuciones}}});await prisma.tarea.deleteMany({where:{tarea_tarea_id:{in:ids.tareas}}});await prisma.asignacion_concepto_remuneracion_empleado.deleteMany({where:{id_asignacion_concepto:{in:ids.asignaciones}}});await prisma.configuracion_concepto_remuneracion.deleteMany({where:{id_concepto:{in:ids.conceptos}}});await prisma.concepto_remuneracion.deleteMany({where:{id_concepto_remuneracion:{in:ids.conceptos}}});await prisma.asignacion_esquema_remuneracional.deleteMany({where:{id_esquema:{in:ids.esquemas}}});await prisma.tarifa_esquema_remuneracional.deleteMany({where:{id_tarifa_esquema:{in:ids.tarifas}}});await prisma.esquema_remuneracional.deleteMany({where:{id_esquema_remuneracional:{in:ids.esquemas}}});await prisma.relacion_laboral_empleado.deleteMany({where:{id_empleado:{in:ids.empleados}}});await prisma.tramo_impuesto_renta.deleteMany({where:{id_tramo_impuesto_renta:{in:ids.tramos}}});await prisma.usuario.deleteMany({where:{usuario_id_usuario:{in:ids.usuarios}}});await prisma.empleado.deleteMany({where:{id_empleado:{in:ids.empleados}}});
 }
});
