const { test } = require('node:test');
const assert = require('node:assert/strict');
const { randomUUID } = require('node:crypto');
const { readFileSync } = require('node:fs');
const { resolve } = require('node:path');
const { prisma } = require('../dist/db');
const { M6Controller } = require('../dist/controladores/M6Controller');
const { codigosTodosLosCU, matrizPermisosPorCU, operacionesPermiso } = require('../dist/validaciones/permisos');
const { prepararPrevisionM6 } = require('./soporte-prevision-m6.cjs');

function rutValido(){const cuerpo=String(Math.floor(Math.random()*8_000_000)+1_000_000);let suma=0,m=2;for(let i=cuerpo.length-1;i>=0;i--){suma+=Number(cuerpo[i])*m;m=m===7?2:m+1}const r=11-(suma%11);return `${cuerpo}-${r===11?'0':r===10?'K':r}`}

test('M6 T8 CU187-CU190 honorarios, detalle, anulaciones y reversiones',async t=>{
 const modulo=new M6Controller(),s=randomUUID().slice(0,8).toUpperCase(),ids={usuarios:[],medios:[],prestadores:[],boletas:[],pagos:[],empleados:[],relaciones:[],periodos:[],tramos:[],parametros:[]};
 const u=await prisma.usuario.create({data:{usuario_username:`m6t8_${s}`,usuario_nombre_completo_primer_nombre_usuario:'Tanda Ocho'}}),u2=await prisma.usuario.create({data:{usuario_username:`m6t8b_${s}`,usuario_nombre_completo_primer_nombre_usuario:'Revisor Ocho'}});ids.usuarios.push(u.usuario_id_usuario,u2.usuario_id_usuario);
 const medio=await prisma.medio_pago.create({data:{nombre_medio_pago:`M6 T8 ${s}`,codigo_medio_pago:`M6T8${s}`,estado_medio_pago:'activo',requiere_respaldo:false}}),medioR=await prisma.medio_pago.create({data:{nombre_medio_pago:`M6 T8R ${s}`,codigo_medio_pago:`M6T8R${s}`,estado_medio_pago:'activo',requiere_respaldo:true}});ids.medios.push(medio.id_medio_pago,medioR.id_medio_pago);
 const calcularRemuneracion=modulo.calcularRemuneracion.bind(modulo);modulo.calcularRemuneracion=async(...args)=>{ids.parametros.push(...await prepararPrevisionM6(prisma,{empleados:ids.empleados,desde:'2098-01-01',hasta:'2098-12-31'}));return calcularRemuneracion(...args)};
 const prestador=await prisma.prestador_honorarios.create({data:{identificador:`76${Date.now().toString().slice(-6)}-${s[0]}`,nombre_razon_social:`Prestador ${s}`,contacto:'contacto@test.cl'}});ids.prestadores.push(prestador.id_prestador_honorarios);
 const crearBoleta=async(estado,folio)=>{const b=await prisma.boleta_honorarios.create({data:{id_prestador:prestador.id_prestador_honorarios,folio:`${folio}-${s}`,fecha_emision:new Date('2099-01-15'),bruto:1000,modalidad_tributaria:'FIJADA_POR_PRODUCTOR',tasa_aplicada:estado==='CONFIRMADA'?10:null,retencion:estado==='CONFIRMADA'?100:null,liquido:estado==='CONFIRMADA'?900:null,estado_documental:estado,respaldo:'fixture://boleta'}});ids.boletas.push(b.id_boleta_honorarios);return b};
 try{
  const pendiente=await crearBoleta('PENDIENTE_CONFIRMACION','P'),confirmada=await crearBoleta('CONFIRMADA','C');
  await t.test('CU187 sólo consume boleta CONFIRMADA y paga el líquido fijado',async()=>{await assert.rejects(modulo.prepararPagoHonorarios(pendiente.id_boleta_honorarios,{monto:900,idMedioPago:medio.id_medio_pago,claveIdempotencia:randomUUID()},u.usuario_id_usuario),e=>e.estado===409);const bruto=await modulo.prepararPagoHonorarios(confirmada.id_boleta_honorarios,{monto:1000,idMedioPago:medio.id_medio_pago,claveIdempotencia:`bruto-${s}`},u.usuario_id_usuario);ids.pagos.push(bruto.id);await assert.rejects(modulo.confirmarPagoHonorarios(bruto.id,u.usuario_id_usuario),e=>e.estado===409);await assert.rejects(modulo.prepararPagoHonorarios(confirmada.id_boleta_honorarios,{monto:900,idMedioPago:medioR.id_medio_pago,claveIdempotencia:randomUUID()},u.usuario_id_usuario),e=>e.estado===400)});
  const pago=await modulo.prepararPagoHonorarios(confirmada.id_boleta_honorarios,{monto:900,idMedioPago:medio.id_medio_pago,respaldo:'fixture://pago',claveIdempotencia:`pago-${s}`},u.usuario_id_usuario);ids.pagos.push(pago.id);
  await t.test('PREPARADO no paga, la clave es idempotente y CONFIRMADO sí paga',async()=>{const repetido=await modulo.prepararPagoHonorarios(confirmada.id_boleta_honorarios,{monto:900,idMedioPago:medio.id_medio_pago,respaldo:'fixture://pago',claveIdempotencia:`pago-${s}`},u.usuario_id_usuario);assert.equal(repetido.id,pago.id);let lista=await modulo.listarBoletasHonorariosConfirmadas();assert.equal(lista.find(x=>x.id===confirmada.id_boleta_honorarios).montoEfectivo,0);await modulo.confirmarPagoHonorarios(pago.id,u.usuario_id_usuario);lista=await modulo.listarBoletasHonorariosConfirmadas();assert.equal(lista.find(x=>x.id===confirmada.id_boleta_honorarios).montoEfectivo,900);assert.equal((await prisma.boleta_honorarios.findUnique({where:{id_boleta_honorarios:confirmada.id_boleta_honorarios}})).estado_documental,'CONFIRMADA');const p2=await modulo.prepararPagoHonorarios(confirmada.id_boleta_honorarios,{monto:900,idMedioPago:medio.id_medio_pago,claveIdempotencia:`p2-${s}`},u.usuario_id_usuario);ids.pagos.push(p2.id);await assert.rejects(modulo.confirmarPagoHonorarios(p2.id,u.usuario_id_usuario))});
  await t.test('CU188 deriva detalle, origen y usuarios sin tabla historial',async()=>{const d=await modulo.obtenerPagoRemuneracion(pago.id);assert.equal(d.origen.tipo,'BOLETA_HONORARIOS');assert.match(d.origen.descripcion,/Prestador/);assert.equal(d.montoEfectivo,900);assert.equal(d.totalRevertido,0);assert.equal(d.respaldo,'fixture://pago');assert.equal(d.actores.confirmador,'Tanda Ocho');const schema=readFileSync(resolve('prisma/schema.prisma'),'utf8');assert.doesNotMatch(schema,/model\s+historial_pago_remuneracion/)});
  const boletaA=await crearBoleta('CONFIRMADA','A'),pagoA=await modulo.prepararPagoHonorarios(boletaA.id_boleta_honorarios,{monto:900,idMedioPago:medio.id_medio_pago,claveIdempotencia:`an-${s}`},u.usuario_id_usuario);ids.pagos.push(pagoA.id);await modulo.confirmarPagoHonorarios(pagoA.id,u.usuario_id_usuario);
  await t.test('CU189 anula el mismo pago, exige motivo y permite un pago posterior',async()=>{await assert.rejects(modulo.anularPagoRemuneracion(pagoA.id,{motivo:''},u2.usuario_id_usuario),e=>e.estado===400);const carrera=await Promise.allSettled([modulo.anularPagoRemuneracion(pagoA.id,{motivo:'Error registral'},u2.usuario_id_usuario),modulo.anularPagoRemuneracion(pagoA.id,{motivo:'Duplicada'},u.usuario_id_usuario)]);assert.equal(carrera.filter(x=>x.status==='fulfilled').length,1);const d=await modulo.obtenerPagoRemuneracion(pagoA.id);assert.equal(d.estado,'ANULADO');assert.equal(d.monto,900);assert.equal(d.montoEfectivo,0);assert.equal((await modulo.listarBoletasHonorariosConfirmadas()).find(x=>x.id===boletaA.id_boleta_honorarios).pendiente,true);await assert.rejects(prisma.pago_remuneracion.update({where:{id_pago_remuneracion:pagoA.id},data:{estado:'CONFIRMADO'}}));const reemplazo=await modulo.prepararPagoHonorarios(boletaA.id_boleta_honorarios,{monto:900,idMedioPago:medio.id_medio_pago,claveIdempotencia:`rean-${s}`},u.usuario_id_usuario);ids.pagos.push(reemplazo.id);await modulo.confirmarPagoHonorarios(reemplazo.id,u.usuario_id_usuario);assert.equal((await modulo.listarBoletasHonorariosConfirmadas()).find(x=>x.id===boletaA.id_boleta_honorarios).montoEfectivo,900)});
  await t.test('CU190 libera saldo para repago parcial y total sin sobrepago',async()=>{let d=await modulo.registrarReversionPagoRemuneracion(pago.id,{monto:100,motivo:'Parcial inicial'},u2.usuario_id_usuario);assert.equal(d.montoEfectivo,800);const exceso=await modulo.prepararPagoHonorarios(confirmada.id_boleta_honorarios,{monto:101,idMedioPago:medio.id_medio_pago,claveIdempotencia:`exceso-${s}`},u.usuario_id_usuario);ids.pagos.push(exceso.id);await assert.rejects(modulo.confirmarPagoHonorarios(exceso.id,u.usuario_id_usuario));const repago=await modulo.prepararPagoHonorarios(confirmada.id_boleta_honorarios,{monto:100,idMedioPago:medio.id_medio_pago,claveIdempotencia:`repago-${s}`},u.usuario_id_usuario);ids.pagos.push(repago.id);await modulo.confirmarPagoHonorarios(repago.id,u.usuario_id_usuario);assert.equal((await modulo.listarBoletasHonorariosConfirmadas()).find(x=>x.id===confirmada.id_boleta_honorarios).saldoPendiente,0);await assert.rejects(modulo.anularPagoRemuneracion(pago.id,{motivo:'No mezclar'},u.usuario_id_usuario));await assert.rejects(prisma.reversion_pago_remuneracion.update({where:{id_reversion_pago_remuneracion:d.reversiones[0].id},data:{monto:1}}));const total=await crearBoleta('CONFIRMADA','TOTAL'),pagoTotal=await modulo.prepararPagoHonorarios(total.id_boleta_honorarios,{monto:900,idMedioPago:medio.id_medio_pago,claveIdempotencia:`total-${s}`},u.usuario_id_usuario);ids.pagos.push(pagoTotal.id);await modulo.confirmarPagoHonorarios(pagoTotal.id,u.usuario_id_usuario);await modulo.registrarReversionPagoRemuneracion(pagoTotal.id,{monto:900,motivo:'Total'},u2.usuario_id_usuario);const repagoTotal=await modulo.prepararPagoHonorarios(total.id_boleta_honorarios,{monto:900,idMedioPago:medio.id_medio_pago,claveIdempotencia:`retotal-${s}`},u.usuario_id_usuario);ids.pagos.push(repagoTotal.id);await modulo.confirmarPagoHonorarios(repagoTotal.id,u.usuario_id_usuario);assert.equal((await modulo.listarBoletasHonorariosConfirmadas()).find(x=>x.id===total.id_boleta_honorarios).montoEfectivo,900)});
  await t.test('dos repagos concurrentes compiten por un único saldo pendiente',async()=>{const b=await crearBoleta('CONFIRMADA','RACE'),p1=await modulo.prepararPagoHonorarios(b.id_boleta_honorarios,{monto:900,idMedioPago:medio.id_medio_pago,claveIdempotencia:`race1-${s}`},u.usuario_id_usuario);ids.pagos.push(p1.id);await modulo.confirmarPagoHonorarios(p1.id,u.usuario_id_usuario);await modulo.registrarReversionPagoRemuneracion(p1.id,{monto:300,motivo:'Saldo carrera'},u2.usuario_id_usuario);const p2=await modulo.prepararPagoHonorarios(b.id_boleta_honorarios,{monto:300,idMedioPago:medio.id_medio_pago,claveIdempotencia:`race2-${s}`},u.usuario_id_usuario),p3=await modulo.prepararPagoHonorarios(b.id_boleta_honorarios,{monto:300,idMedioPago:medio.id_medio_pago,claveIdempotencia:`race3-${s}`},u2.usuario_id_usuario);ids.pagos.push(p2.id,p3.id);const carrera=await Promise.allSettled([modulo.confirmarPagoHonorarios(p2.id,u.usuario_id_usuario),modulo.confirmarPagoHonorarios(p3.id,u2.usuario_id_usuario)]);assert.equal(carrera.filter(x=>x.status==='fulfilled').length,1);assert.equal((await modulo.listarBoletasHonorariosConfirmadas()).find(x=>x.id===b.id_boleta_honorarios).montoEfectivo,900)});
  await t.test('anticipo usa efecto neto y vuelve a total tras repago',async()=>{const e=await modulo.crearEmpleado({rut:rutValido(),nombres:'Neto',apellidoPaterno:'Anticipo'});ids.empleados.push(e.id);await prisma.empleado.update({where:{id_empleado:e.id},data:{sueldo_base:500000,fecha_aplicacion_sueldo_base:new Date('2098-01-01')}});const rel=await prisma.relacion_laboral_empleado.create({data:{id_empleado:e.id,fecha_inicio:new Date('2098-01-01'),estado:'vigente'}});ids.relaciones.push(rel.id_relacion_laboral_empleado);const tramo=await prisma.tramo_impuesto_renta.create({data:{vigencia_desde:new Date('2098-01-01'),vigencia_hasta:new Date('2098-12-31'),orden:1,limite_desde:0,factor:0,rebaja:0,unidad:'CLP',estado:'activo'}});ids.tramos.push(tramo.id_tramo_impuesto_renta);const a=await modulo.registrarAnticipo({idEmpleado:e.id,anio:2098,mes:1,modalidad:'MONTO',valor:100000,claveIdempotencia:`ant-${s}`},u.usuario_id_usuario);ids.periodos.push(a.periodo.id);const p=await modulo.prepararPagoAnticipo(a.id,{monto:100000,idMedioPago:medio.id_medio_pago,claveIdempotencia:`pa-${s}`},u.usuario_id_usuario);ids.pagos.push(p.id);await modulo.confirmarPagoAnticipo(p.id,u.usuario_id_usuario);await modulo.registrarReversionPagoRemuneracion(p.id,{monto:40000,motivo:'Parcial'},u2.usuario_id_usuario);let calc=await modulo.calcularRemuneracion({idEmpleado:e.id,anio:2098,mes:1},u.usuario_id_usuario),c=calc.remuneracion.componentes.find(x=>x.claveNegocio===`ANTICIPO:${a.id}`);assert.equal(c.monto,60000);const p2=await modulo.prepararPagoAnticipo(a.id,{monto:40000,idMedioPago:medio.id_medio_pago,claveIdempotencia:`pa2-${s}`},u.usuario_id_usuario);ids.pagos.push(p2.id);await modulo.confirmarPagoAnticipo(p2.id,u.usuario_id_usuario);calc=await modulo.calcularRemuneracion({idEmpleado:e.id,anio:2098,mes:1},u.usuario_id_usuario);c=calc.remuneracion.componentes.find(x=>x.claveNegocio===`ANTICIPO:${a.id}`);assert.equal(c.monto,100000);assert.equal(calc.remuneracion.componentes.filter(x=>x.claveNegocio===`ANTICIPO:${a.id}`).length,1)});
  await t.test('remuneración conserva cierre y admite repago del monto revertido',async()=>{const e=await modulo.crearEmpleado({rut:rutValido(),nombres:'Neto',apellidoPaterno:'Remuneracion'});ids.empleados.push(e.id);await prisma.empleado.update({where:{id_empleado:e.id},data:{sueldo_base:500000,fecha_aplicacion_sueldo_base:new Date('2098-01-01')}});const rel=await prisma.relacion_laboral_empleado.create({data:{id_empleado:e.id,fecha_inicio:new Date('2098-01-01'),estado:'vigente'}});ids.relaciones.push(rel.id_relacion_laboral_empleado);const calc=await modulo.calcularRemuneracion({idEmpleado:e.id,anio:2098,mes:2},u.usuario_id_usuario);ids.periodos.push(calc.remuneracion.periodo.id);const cerrada=await modulo.cerrarRemuneracion(calc.remuneracion.id,u.usuario_id_usuario),monto=cerrada.remuneracion.totales.liquidoPreliminar;const p1=await modulo.prepararPagoFinal({origenTipo:'REMUNERACION',origenId:calc.remuneracion.id,monto,idMedioPago:medio.id_medio_pago,claveIdempotencia:`rem1-${s}`},u.usuario_id_usuario);ids.pagos.push(p1.id);await modulo.confirmarPagoFinal(p1.id,u.usuario_id_usuario);await modulo.registrarReversionPagoRemuneracion(p1.id,{monto:100000,motivo:'Repago remuneración'},u2.usuario_id_usuario);const p2=await modulo.prepararPagoFinal({origenTipo:'REMUNERACION',origenId:calc.remuneracion.id,monto:100000,idMedioPago:medio.id_medio_pago,claveIdempotencia:`rem2-${s}`},u.usuario_id_usuario);ids.pagos.push(p2.id);await modulo.confirmarPagoFinal(p2.id,u.usuario_id_usuario);const detalle=await modulo.obtenerPagoRemuneracion(p2.id);assert.equal(detalle.montoEfectivo,100000);assert.equal((await modulo.obtenerRemuneracion(calc.remuneracion.id)).estado,'cerrada')});
  await t.test('boleta CONFIRMADA queda físicamente inmutable',async()=>{await assert.rejects(prisma.boleta_honorarios.update({where:{id_boleta_honorarios:confirmada.id_boleta_honorarios},data:{liquido:899}}));await assert.rejects(prisma.boleta_honorarios.update({where:{id_boleta_honorarios:confirmada.id_boleta_honorarios},data:{folio:`MUTADA-${s}`}}));await assert.rejects(prisma.boleta_honorarios.delete({where:{id_boleta_honorarios:confirmada.id_boleta_honorarios}}))});
  await t.test('permisos reconocen CU196-CU205 y CU207 no existe',()=>{assert.equal(codigosTodosLosCU.length,274);for(let n=187;n<=214;n++)assert.deepEqual(matrizPermisosPorCU[`CU${n}`],[]);assert.equal(operacionesPermiso.prepararPagoHonorarios,'CU187');assert.equal(operacionesPermiso.obtenerDetallePagoRemuneracion,'CU188');assert.equal(operacionesPermiso.anularPagoRemuneracion,'CU189');assert.equal(operacionesPermiso.registrarReversionPagoRemuneracion,'CU190');assert.equal(codigosTodosLosCU.includes('CU198'),true);assert.equal(codigosTodosLosCU.includes('CU201'),true);assert.equal(codigosTodosLosCU.includes('CU202'),true);assert.equal(codigosTodosLosCU.includes('CU203'),true);assert.equal(codigosTodosLosCU.includes('CU204'),true);assert.equal(codigosTodosLosCU.includes('CU205'),true);assert.equal(codigosTodosLosCU.includes('CU206'),true);assert.equal(codigosTodosLosCU.includes('CU215'),true);const rutas=readFileSync(resolve('src/rutas/finanzas.ts'),'utf8');assert.match(rutas,/crearBoletaHonorarios/);assert.match(rutas,/crearPrestadorHonorarios/);assert.match(rutas,/confirmarBoletaHonorarios/)});
 }finally{
  await prisma.reversion_pago_remuneracion.deleteMany({where:{pago:{clave_idempotencia:{contains:s}}}});await prisma.pago_remuneracion.deleteMany({where:{clave_idempotencia:{contains:s}}});await prisma.$executeRawUnsafe('ALTER TABLE finanzas.boleta_honorarios DISABLE TRIGGER tr_proteger_boleta_honorarios_confirmada');try{await prisma.boleta_honorarios.deleteMany({where:{id_boleta_honorarios:{in:ids.boletas}}})}finally{await prisma.$executeRawUnsafe('ALTER TABLE finanzas.boleta_honorarios ENABLE TRIGGER tr_proteger_boleta_honorarios_confirmada')}await prisma.prestador_honorarios.deleteMany({where:{id_prestador_honorarios:{in:ids.prestadores}}});const rems=await prisma.remuneracion.findMany({where:{id_periodo_remuneracion:{in:ids.periodos}},select:{id_remuneracion:true}}),rids=rems.map(x=>x.id_remuneracion);await prisma.componente_remuneracion.deleteMany({where:{id_remuneracion:{in:rids}}});await prisma.remuneracion.deleteMany({where:{id_remuneracion:{in:rids}}});await prisma.anticipo_remuneracion.deleteMany({where:{clave_idempotencia:{contains:s}}});await prisma.periodo_remuneracion.deleteMany({where:{id_periodo_remuneracion:{in:ids.periodos}}});await prisma.tramo_impuesto_renta.deleteMany({where:{id_tramo_impuesto_renta:{in:ids.tramos}}});await prisma.relacion_laboral_empleado.deleteMany({where:{id_relacion_laboral_empleado:{in:ids.relaciones}}});await prisma.empleado.deleteMany({where:{id_empleado:{in:ids.empleados}}});await prisma.medio_pago.deleteMany({where:{id_medio_pago:{in:ids.medios}}});await prisma.usuario.deleteMany({where:{usuario_id_usuario:{in:ids.usuarios}}});
 }
});
