const { test } = require('node:test');
const assert = require('node:assert/strict');
const { randomUUID } = require('node:crypto');
const { readFileSync } = require('node:fs');
const { resolve } = require('node:path');
const { prisma } = require('../dist/db');
const { M6Controller } = require('../dist/controladores/M6Controller');
const { codigosTodosLosCU, matrizPermisosPorCU, operacionesPermiso, permiteOperacion } = require('../dist/validaciones/permisos');
const { prepararPrevisionM6 } = require('./soporte-prevision-m6.cjs');

function rutValido(){const cuerpo=String(Math.floor(Math.random()*8_000_000)+1_000_000);let suma=0,m=2;for(let i=cuerpo.length-1;i>=0;i--){suma+=Number(cuerpo[i])*m;m=m===7?2:m+1}const r=11-(suma%11);return `${cuerpo}-${r===11?'0':r===10?'K':r}`}

test('M6 T7 CU183-CU186 conserva historia y registra pagos efectivos',async t=>{
 const modulo=new M6Controller(),sufijo=randomUUID().slice(0,8).toUpperCase(),ids={empleados:[],usuarios:[],relaciones:[],periodos:[],tramos:[],medios:[],parametros:[]};
 const empleado=await modulo.crearEmpleado({rut:rutValido(),nombres:'Tanda',apellidoPaterno:'Siete'});ids.empleados.push(empleado.id);
 await prisma.empleado.update({where:{id_empleado:empleado.id},data:{sueldo_base:500000,fecha_aplicacion_sueldo_base:new Date('2096-01-01')}});
 const usuario=await prisma.usuario.create({data:{usuario_username:`m6t7_${sufijo}`,usuario_nombre_completo_primer_nombre_usuario:'Tanda Siete'}}),usuario2=await prisma.usuario.create({data:{usuario_username:`m6t7b_${sufijo}`,usuario_nombre_completo_primer_nombre_usuario:'Revisor Siete'}});ids.usuarios.push(usuario.usuario_id_usuario,usuario2.usuario_id_usuario);
 const relacion=await prisma.relacion_laboral_empleado.create({data:{id_empleado:empleado.id,fecha_inicio:new Date('2096-01-01'),estado:'vigente'}});ids.relaciones.push(relacion.id_relacion_laboral_empleado);
 ids.parametros.push(...await prepararPrevisionM6(prisma,{empleados:[empleado.id],desde:'2096-01-01',hasta:'2097-12-31',sinDeduccionesTrabajador:true}));
 for(const anio of [2096,2097]){const tramo=await prisma.tramo_impuesto_renta.create({data:{vigencia_desde:new Date(`${anio}-01-01`),vigencia_hasta:new Date(`${anio}-12-31`),orden:1,limite_desde:0,limite_hasta:null,factor:0,rebaja:0,unidad:'CLP',estado:'activo'}});ids.tramos.push(tramo.id_tramo_impuesto_renta)}
 const medio=await prisma.medio_pago.create({data:{nombre_medio_pago:`Transferencia M6 ${sufijo}`,codigo_medio_pago:`M6T7${sufijo}`,estado_medio_pago:'activo',requiere_respaldo:false}});ids.medios.push(medio.id_medio_pago);
 const medioRespaldo=await prisma.medio_pago.create({data:{nombre_medio_pago:`Respaldo M6 ${sufijo}`,codigo_medio_pago:`M6R7${sufijo}`,estado_medio_pago:'activo',requiere_respaldo:true}});ids.medios.push(medioRespaldo.id_medio_pago);
 const medioPendiente=await prisma.medio_pago.create({data:{nombre_medio_pago:`Pendiente M6 ${sufijo}`,codigo_medio_pago:`M6P7${sufijo}`,estado_medio_pago:'activo',requiere_respaldo:null}});ids.medios.push(medioPendiente.id_medio_pago);
 try{
  const calculo=await modulo.calcularRemuneracion({idEmpleado:empleado.id,anio:2096,mes:1},usuario.usuario_id_usuario);ids.periodos.push(calculo.remuneracion.periodo.id);await modulo.cerrarRemuneracion(calculo.remuneracion.id,usuario.usuario_id_usuario);
  const historica=await modulo.obtenerRemuneracion(calculo.remuneracion.id),totales={...historica.totales},componentes=historica.componentes.map(x=>x.id);
  let pagoOriginal;
  await t.test('PREPARADO no paga; CONFIRMADO paga y es inmutable',async()=>{pagoOriginal=await modulo.prepararPagoFinal({origenTipo:'REMUNERACION',origenId:historica.id,monto:500000,idMedioPago:medio.id_medio_pago,claveIdempotencia:`pago-${sufijo}`},usuario.usuario_id_usuario);assert.equal((await modulo.obtenerRemuneracion(historica.id)).condicionPago.tienePago,false);await modulo.confirmarPagoFinal(pagoOriginal.id,usuario.usuario_id_usuario);assert.equal((await modulo.obtenerRemuneracion(historica.id)).condicionPago.tienePago,true);await assert.rejects(prisma.pago_remuneracion.update({where:{id_pago_remuneracion:pagoOriginal.id},data:{monto:1}}))});
  await t.test('CU182 queda bloqueado por la fuente real de pago',async()=>{await assert.rejects(modulo.solicitarReaperturaRemuneracion(historica.id,{motivo:'No corresponde'},usuario.usuario_id_usuario),e=>e.estado===409&&/pago/i.test(e.message))});
  let positivo,negativo;
  await t.test('CU183 registra direcciones inequívocas sin alterar R1 ni pagar directo',async()=>{positivo=await modulo.crearAjustePosterior(historica.id,{direccion:'POSITIVO',monto:50000,motivo:'Diferencia detectada',fechaHallazgo:'2096-02-10',claveIdempotencia:`aj-pos-${sufijo}`},usuario.usuario_id_usuario);negativo=await modulo.crearAjustePosterior(historica.id,{direccion:'NEGATIVO',monto:10000,motivo:'Exceso detectado',fechaHallazgo:'2096-02-11',claveIdempotencia:`aj-neg-${sufijo}`},usuario.usuario_id_usuario);assert.equal(positivo.idPeriodoOrigen,historica.periodo.id);assert.equal(negativo.requiereResolucionHumana,true);assert.equal(await prisma.pago_remuneracion.count({where:{origen_id:positivo.id}}),0);const despues=await modulo.obtenerRemuneracion(historica.id);assert.deepEqual(despues.totales,totales);assert.deepEqual(despues.componentes.map(x=>x.id),componentes)});
  await t.test('CU183 rechaza cero, signo doble y motivo faltante',async()=>{for(const datos of [{direccion:'POSITIVO',monto:0,motivo:'x'},{direccion:'POSITIVO',monto:-1,motivo:'x'},{direccion:'POSITIVO',monto:1,motivo:''}])await assert.rejects(modulo.crearAjustePosterior(historica.id,{...datos,fechaHallazgo:'2096-02-12',claveIdempotencia:randomUUID()}),e=>e.estado===400)});
  await t.test('postergación exige período explícito y serializa carreras',async()=>{const resultados=await Promise.allSettled([modulo.postergarAjustePosterior(negativo.id,{anio:2096,mes:4,motivo:'Resolver en abril'},usuario.usuario_id_usuario),modulo.postergarAjustePosterior(negativo.id,{anio:2096,mes:5,motivo:'Resolver en mayo'},usuario.usuario_id_usuario)]);assert.equal(resultados.filter(x=>x.status==='fulfilled').length,1);const actual=await modulo.obtenerAjustePosterior(negativo.id);assert.ok(actual.idPeriodoAplicable);assert.equal(actual.motivo,'Exceso detectado')});
  let regularizacion;
  await t.test('CU184 crea una regularización positiva, única, corregible y cerrable',async()=>{const carrera=await Promise.allSettled([modulo.crearRegularizacionExtraordinaria(positivo.id,usuario.usuario_id_usuario),modulo.crearRegularizacionExtraordinaria(positivo.id,usuario.usuario_id_usuario)]);assert.ok(carrera.some(x=>x.status==='fulfilled'));assert.equal(await prisma.regularizacion_extraordinaria.count({where:{id_ajuste_posterior:positivo.id}}),1);regularizacion=await modulo.crearRegularizacionExtraordinaria(positivo.id,usuario.usuario_id_usuario);regularizacion=await modulo.actualizarRegularizacion(regularizacion.id,{monto:45000,motivo:'Monto revisado'},usuario.usuario_id_usuario);assert.equal(regularizacion.monto,45000);regularizacion=await modulo.cerrarRegularizacion(regularizacion.id,usuario.usuario_id_usuario);assert.equal(regularizacion.estado,'CERRADA');await assert.rejects(modulo.crearRegularizacionExtraordinaria(negativo.id,usuario.usuario_id_usuario),e=>e.estado===409)});
  await t.test('CU186 bloquea doble pago confirmado concurrente',async()=>{const p1=await modulo.prepararPagoFinal({origenTipo:'REGULARIZACION',origenId:regularizacion.id,monto:45000,idMedioPago:medio.id_medio_pago,claveIdempotencia:`reg1-${sufijo}`},usuario.usuario_id_usuario);const p2=await modulo.prepararPagoFinal({origenTipo:'REGULARIZACION',origenId:regularizacion.id,monto:45000,idMedioPago:medio.id_medio_pago,claveIdempotencia:`reg2-${sufijo}`},usuario.usuario_id_usuario);const carrera=await Promise.allSettled([modulo.confirmarPagoFinal(p1.id,usuario.usuario_id_usuario),modulo.confirmarPagoFinal(p2.id,usuario.usuario_id_usuario)]);assert.equal(carrera.filter(x=>x.status==='fulfilled').length,1);assert.equal(await prisma.pago_remuneracion.count({where:{origen_tipo:'REGULARIZACION',origen_id:regularizacion.id,estado:'CONFIRMADO'}}),1);await assert.rejects(modulo.actualizarRegularizacion(regularizacion.id,{monto:1,motivo:'No editable'},usuario.usuario_id_usuario),e=>e.estado===409)});
  let anticipo;
  await t.test('CU185 fijo: preparado no reduce y doble confirmación idempotente integra CU179 una vez',async()=>{anticipo=await modulo.registrarAnticipo({idEmpleado:empleado.id,anio:2097,mes:1,modalidad:'MONTO',valor:100000,claveIdempotencia:`ant-${sufijo}`},usuario.usuario_id_usuario);ids.periodos.push(anticipo.periodo.id);const pago=await modulo.prepararPagoAnticipo(anticipo.id,{monto:100000,idMedioPago:medio.id_medio_pago,claveIdempotencia:`pant-${sufijo}`},usuario.usuario_id_usuario);let calculada=await modulo.calcularRemuneracion({idEmpleado:empleado.id,anio:2097,mes:1},usuario.usuario_id_usuario);assert.equal(calculada.remuneracion.componentes.some(x=>x.claveNegocio===`ANTICIPO:${anticipo.id}`),false);const carrera=await Promise.allSettled([modulo.confirmarPagoAnticipo(pago.id,usuario.usuario_id_usuario),modulo.confirmarPagoAnticipo(pago.id,usuario.usuario_id_usuario)]);assert.ok(carrera.some(x=>x.status==='fulfilled'));assert.equal(await prisma.pago_remuneracion.count({where:{id_pago_remuneracion:pago.id,estado:'CONFIRMADO'}}),1);calculada=await modulo.calcularRemuneracion({idEmpleado:empleado.id,anio:2097,mes:1},usuario.usuario_id_usuario);assert.equal(calculada.remuneracion.componentes.filter(x=>x.tipo==='DEDUCCION_AUTOMATICA'&&x.claveNegocio===`ANTICIPO:${anticipo.id}`).length,1);assert.equal(calculada.remuneracion.totales.liquidoPreliminar,400000)});
  await t.test('CU185 porcentaje queda pendiente sin semántica explícita de base',async()=>{const codigo=`BASE${sufijo}`,pendiente=await modulo.registrarAnticipo({idEmpleado:empleado.id,anio:2097,mes:2,modalidad:'PORCENTAJE',valor:10,codigoBasePorcentaje:codigo,claveIdempotencia:`antp-${sufijo}`},usuario.usuario_id_usuario);ids.periodos.push(pendiente.periodo.id);assert.equal(pendiente.estadoValorizacion,'PENDIENTE_VALORIZACION');await assert.rejects(modulo.prepararPagoAnticipo(pendiente.id,{monto:1,idMedioPago:medio.id_medio_pago,claveIdempotencia:randomUUID()},usuario.usuario_id_usuario),e=>e.estado===409);for(const data of [{valor:300000,unidad:'CLP',vigencia_desde:new Date('2097-01-01')},{valor:350000,unidad:'CLP',vigencia_desde:new Date('2097-02-01')},{valor:400000,unidad:'USD',vigencia_desde:new Date('2097-03-01')}]){const parametro=await prisma.parametro_remuneracional.create({data:{codigo,tipo:'LEGAL',nombre:'Parámetro sin semántica de base de anticipo',...data,vigencia_hasta:new Date('2097-12-31'),estado:'activo'}});ids.parametros.push(parametro.id_parametro_remuneracional)}const ambiguo=await modulo.registrarAnticipo({idEmpleado:empleado.id,anio:2097,mes:3,modalidad:'PORCENTAJE',valor:10,codigoBasePorcentaje:codigo,claveIdempotencia:`antv-${sufijo}`},usuario.usuario_id_usuario);ids.periodos.push(ambiguo.periodo.id);assert.equal(ambiguo.estadoValorizacion,'PENDIENTE_VALORIZACION');assert.equal(ambiguo.montoFinal,null);for(const valor of [0,-1])await assert.rejects(modulo.registrarAnticipo({idEmpleado:empleado.id,anio:2097,mes:4,modalidad:'PORCENTAJE',valor,codigoBasePorcentaje:codigo,claveIdempotencia:randomUUID()},usuario.usuario_id_usuario),e=>e.estado===400)});
  await t.test('medios ambiguos y respaldos faltantes bloquean',async()=>{await assert.rejects(modulo.prepararPagoAnticipo(anticipo.id,{monto:100000,idMedioPago:medioPendiente.id_medio_pago,claveIdempotencia:randomUUID()},usuario.usuario_id_usuario),e=>e.estado===409);await assert.rejects(modulo.prepararPagoAnticipo(anticipo.id,{monto:100000,idMedioPago:medioRespaldo.id_medio_pago,claveIdempotencia:randomUUID()},usuario.usuario_id_usuario),e=>e.estado===400)});
  await t.test('CU182 y CU186 concurrentes no reabren una remuneración pagada',async()=>{const calculada=await modulo.calcularRemuneracion({idEmpleado:empleado.id,anio:2096,mes:2},usuario.usuario_id_usuario);ids.periodos.push(calculada.remuneracion.periodo.id);await modulo.cerrarRemuneracion(calculada.remuneracion.id,usuario.usuario_id_usuario);const pago=await modulo.prepararPagoFinal({origenTipo:'REMUNERACION',origenId:calculada.remuneracion.id,monto:500000,idMedioPago:medio.id_medio_pago,claveIdempotencia:`c182-${sufijo}`},usuario.usuario_id_usuario);await modulo.solicitarReaperturaRemuneracion(calculada.remuneracion.id,{motivo:'Carrera controlada'},usuario.usuario_id_usuario);const carrera=await Promise.allSettled([modulo.aprobarReaperturaRemuneracion(calculada.remuneracion.id,usuario2.usuario_id_usuario),modulo.confirmarPagoFinal(pago.id,usuario.usuario_id_usuario)]);assert.equal(carrera.filter(x=>x.status==='fulfilled').length,1);const estado=await modulo.obtenerRemuneracion(calculada.remuneracion.id);if(estado.condicionPago.tienePago)assert.equal(estado.estado,'cerrada');else assert.equal(estado.estado,'reemplazada')});
  await t.test('CU183 y CU186 concurrentes comparten una sola condición económica',async()=>{const calculada=await modulo.calcularRemuneracion({idEmpleado:empleado.id,anio:2096,mes:3},usuario.usuario_id_usuario);ids.periodos.push(calculada.remuneracion.periodo.id);await modulo.cerrarRemuneracion(calculada.remuneracion.id,usuario.usuario_id_usuario);const pago=await modulo.prepararPagoFinal({origenTipo:'REMUNERACION',origenId:calculada.remuneracion.id,monto:500000,idMedioPago:medio.id_medio_pago,claveIdempotencia:`c183-${sufijo}`},usuario.usuario_id_usuario),claveAjuste=`c183-aj-${sufijo}`;await Promise.allSettled([modulo.confirmarPagoFinal(pago.id,usuario.usuario_id_usuario),modulo.crearAjustePosterior(calculada.remuneracion.id,{direccion:'POSITIVO',monto:1000,motivo:'Hallazgo concurrente',fechaHallazgo:'2096-04-01',claveIdempotencia:claveAjuste},usuario.usuario_id_usuario)]);if(!(await modulo.obtenerPagoRemuneracion(pago.id)).confirmadoEn)await modulo.confirmarPagoFinal(pago.id,usuario.usuario_id_usuario);const ajuste=await modulo.crearAjustePosterior(calculada.remuneracion.id,{direccion:'POSITIVO',monto:1000,motivo:'Hallazgo concurrente',fechaHallazgo:'2096-04-01',claveIdempotencia:claveAjuste},usuario.usuario_id_usuario);assert.equal(ajuste.idRemuneracion,calculada.remuneracion.id);assert.equal((await modulo.obtenerRemuneracion(calculada.remuneracion.id)).condicionPago.tienePago,true)});
  await t.test('integridad polimórfica rechaza orígenes inválidos y borrados huérfanos',async()=>{const idOtraTabla=2000000000;await prisma.anticipo_remuneracion.create({data:{id_anticipo:idOtraTabla,id_empleado:empleado.id,id_periodo_remuneracion:anticipo.periodo.id,modalidad:'MONTO',valor_ingresado:1,monto_final:1,estado_valorizacion:'VALORIZADO',clave_idempotencia:`tabla-${sufijo}`,creado_por:usuario.usuario_id_usuario}});const base={monto:1,id_medio_pago:medio.id_medio_pago,clave_idempotencia:randomUUID(),creado_por:usuario.usuario_id_usuario};await assert.rejects(prisma.pago_remuneracion.create({data:{...base,origen_tipo:'DESCONOCIDO',origen_id:historica.id}}));await assert.rejects(prisma.pago_remuneracion.create({data:{...base,clave_idempotencia:randomUUID(),origen_tipo:'REMUNERACION',origen_id:2000000001}}));await assert.rejects(prisma.pago_remuneracion.create({data:{...base,clave_idempotencia:randomUUID(),origen_tipo:'REMUNERACION',origen_id:idOtraTabla}}));await assert.rejects(prisma.remuneracion.delete({where:{id_remuneracion:historica.id}}));await assert.rejects(prisma.anticipo_remuneracion.delete({where:{id_anticipo:anticipo.id}}));await assert.rejects(prisma.regularizacion_extraordinaria.delete({where:{id_regularizacion:regularizacion.id}}))});
  await t.test('persistencia protege CONFIRMADO y permite sólo anulación registral completa',async()=>{const cambios=[{monto:1},{id_medio_pago:medioRespaldo.id_medio_pago},{origen_tipo:'REGULARIZACION',origen_id:regularizacion.id},{respaldo:'alterado'},{referencia:'alterada'},{confirmado_por:usuario2.usuario_id_usuario},{confirmado_en:new Date('2099-01-01')},{estado:'PREPARADO',confirmado_por:null,confirmado_en:null}];for(const data of cambios)await assert.rejects(prisma.pago_remuneracion.update({where:{id_pago_remuneracion:pagoOriginal.id},data}));await assert.rejects(prisma.pago_remuneracion.update({where:{id_pago_remuneracion:pagoOriginal.id},data:{estado:'ANULADO'}}));await assert.rejects(prisma.pago_remuneracion.create({data:{origen_tipo:'REMUNERACION',origen_id:historica.id,monto:500000,id_medio_pago:medio.id_medio_pago,estado:'CONFIRMADO',clave_idempotencia:randomUUID(),creado_por:usuario.usuario_id_usuario,confirmado_por:usuario.usuario_id_usuario,confirmado_en:new Date()}}));await prisma.pago_remuneracion.update({where:{id_pago_remuneracion:pagoOriginal.id},data:{estado:'ANULADO',motivo_anulacion:'Compatibilidad física CU189',anulado_por:usuario2.usuario_id_usuario,anulado_en:new Date()}});assert.equal((await modulo.obtenerRemuneracion(historica.id)).condicionPago.tienePago,false);const reemplazo=await prisma.pago_remuneracion.create({data:{origen_tipo:'REMUNERACION',origen_id:historica.id,monto:500000,id_medio_pago:medio.id_medio_pago,estado:'CONFIRMADO',clave_idempotencia:`rean-${sufijo}`,creado_por:usuario.usuario_id_usuario,confirmado_por:usuario.usuario_id_usuario,confirmado_en:new Date()}});assert.ok(reemplazo.id_pago_remuneracion);await assert.rejects(prisma.pago_remuneracion.update({where:{id_pago_remuneracion:pagoOriginal.id},data:{motivo_anulacion:'No editable'}}))});
  await t.test('permisos CU183-CU186 son específicos y llegan a CU205',()=>{assert.equal(codigosTodosLosCU.length,274);for(let n=183;n<=214;n++)assert.deepEqual(matrizPermisosPorCU[`CU${n}`],[]);assert.equal(operacionesPermiso.crearAjustePosterior,'CU183');assert.equal(operacionesPermiso.crearRegularizacionExtraordinaria,'CU184');assert.equal(operacionesPermiso.prepararPagoAnticipo,'CU185');assert.equal(operacionesPermiso.prepararPagoFinal,'CU186');assert.equal(permiteOperacion('prepararPagoFinal',['CU185']),false);assert.equal(codigosTodosLosCU.includes('CU198'),true);assert.equal(codigosTodosLosCU.includes('CU201'),true);assert.equal(codigosTodosLosCU.includes('CU202'),true);assert.equal(codigosTodosLosCU.includes('CU203'),true);assert.equal(codigosTodosLosCU.includes('CU204'),true);assert.equal(codigosTodosLosCU.includes('CU205'),true);assert.equal(codigosTodosLosCU.includes('CU206'),true);assert.equal(codigosTodosLosCU.includes('CU215'),true)});
  await t.test('modelo evita entidades descartadas y encapsula el origen físico',()=>{const schema=readFileSync(resolve('prisma/schema.prisma'),'utf8'),migracion=readFileSync(resolve('prisma/migrations/033_m6_ajustes_pagos_remuneraciones/migration.sql'),'utf8'),migracion034=readFileSync(resolve('prisma/migrations/034_m6_compatibilidad_anulacion_pago/migration.sql'),'utf8'),controlador=readFileSync(resolve('src/controladores/M6Controller.ts'),'utf8'),repositorio=readFileSync(resolve('src/servicios/RepositorioPagoRemuneracion.ts'),'utf8');const todo=`${schema}\n${migracion}\n${migracion034}\n${controlador}`;assert.match(schema,/ORIGEN FISICO PROVISIONAL/);assert.match(repositorio,/origen_tipo/);assert.doesNotMatch(controlador,/pago_remuneracion\.(find|count|create|update|delete)/);assert.doesNotMatch(todo,/model\s+(obligacion_pago_remuneracion|anulacion_pago_remuneracion|configuracion_anticipo_empleado|regularizacion_version|historial_pago_remuneracion|historial_ajuste_posterior|documento_remuneracional)\s*\{/i);assert.doesNotMatch(controlador,/eval\s*\(|new\s+Function\s*\(/);assert.match(schema,/model\s+boleta_honorarios\s*\{/)});
 }finally{
  await prisma.pago_remuneracion.deleteMany({where:{clave_idempotencia:{contains:sufijo}}});
  await prisma.regularizacion_extraordinaria.deleteMany({where:{ajuste:{clave_idempotencia:{contains:sufijo}}}});await prisma.ajuste_posterior_remuneracion.deleteMany({where:{clave_idempotencia:{contains:sufijo}}});await prisma.anticipo_remuneracion.deleteMany({where:{clave_idempotencia:{contains:sufijo}}});
  const pids=[...new Set(ids.periodos)];const rems=await prisma.remuneracion.findMany({where:{id_periodo_remuneracion:{in:pids}},select:{id_remuneracion:true}});const rids=rems.map(x=>x.id_remuneracion);await prisma.componente_remuneracion.deleteMany({where:{id_remuneracion:{in:rids}}});await prisma.remuneracion.updateMany({where:{id_remuneracion:{in:rids}},data:{reemplaza_a_id:null}});await prisma.remuneracion.deleteMany({where:{id_periodo_remuneracion:{in:pids}}});await prisma.periodo_remuneracion.deleteMany({where:{id_periodo_remuneracion:{in:pids}}});await prisma.parametro_remuneracional.deleteMany({where:{id_parametro_remuneracional:{in:ids.parametros}}});await prisma.tramo_impuesto_renta.deleteMany({where:{id_tramo_impuesto_renta:{in:ids.tramos}}});await prisma.relacion_laboral_empleado.deleteMany({where:{id_relacion_laboral_empleado:{in:ids.relaciones}}});await prisma.usuario.deleteMany({where:{usuario_id_usuario:{in:ids.usuarios}}});await prisma.empleado.deleteMany({where:{id_empleado:{in:ids.empleados}}});await prisma.medio_pago.deleteMany({where:{id_medio_pago:{in:ids.medios}}});
 }
});
