const { test, after } = require('node:test');
const assert = require('node:assert/strict');
const { randomUUID } = require('node:crypto');
const { Prisma } = require('@prisma/client');
const { prisma } = require('../dist/db');
const { M8Controller } = require('../dist/controladores/M8Controller');
const creditoM8 = require('../dist/utilidades/creditoM8');
const { validarCreditoParaFormalizacion, registrarCompromisoCredito, reducirCompromisoPorPago } = creditoM8;
const { M7Controller } = require('../dist/controladores/M7Controller');
const { operacionesPermiso, matrizPermisosPorCU, codigosTodosLosCU } = require('../dist/validaciones/permisos');

const m = new M8Controller();
const ids={clientes:[],fichas:[],cots:[],notas:[],pagos:[],solicitudes:[],condiciones:[],limites:[]};
let actorG,actorS,actorC,b2b,b2c,cot,nota,moneda,medio;
let excepcionAprobada;
const A=(actor,permisos)=>({id:actor.usuario_id_usuario,permisos,configuracion:'prueba'});
const clienteCreditoAislado=(tx,idFicha)=>new Proxy(tx,{get(objeto,propiedad){const delegado=Reflect.get(objeto,propiedad,objeto);if(propiedad==='compromiso_credito_m8')return new Proxy(delegado,{get(modelo,metodo){if(metodo==='aggregate')return argumentos=>modelo.aggregate({...argumentos,where:{...argumentos.where,id_ficha_cliente:idFicha}});return Reflect.get(modelo,metodo,modelo)}});if(propiedad==='limite_global_credito_m8')return new Proxy(delegado,{get(modelo,metodo){if(metodo==='findMany')return async()=>[{id_limite_global:-1,monto_limite:new Prisma.Decimal(5000),vigencia_desde:new Date('2020-01-01'),vigencia_hasta:null}];return Reflect.get(modelo,metodo,modelo)}});return delegado}});
const conExposicionAislada=async accion=>{const exposicionOriginal=creditoM8.exposicionCredito,limiteOriginal=creditoM8.limiteCreditoVigente;try{creditoM8.exposicionCredito=async()=>new Prisma.Decimal(0);creditoM8.limiteCreditoVigente=async()=>({id_limite_global:-1,monto_limite:new Prisma.Decimal(5000)});return await accion()}finally{creditoM8.exposicionCredito=exposicionOriginal;creditoM8.limiteCreditoVigente=limiteOriginal}};
async function preparar(){
 if(b2b)return;actorG=await prisma.usuario.findFirstOrThrow();actorS=actorG;actorC=actorG;
 const tipoB2B=await prisma.tipo_cliente_financiero.findFirst({where:{nombre_tipo_cliente_financiero:{equals:'B2B',mode:'insensitive'}}});
 const tipoB2C=await prisma.tipo_cliente_financiero.findFirst({where:{nombre_tipo_cliente_financiero:{equals:'B2C',mode:'insensitive'}}});
 if(!tipoB2B||!tipoB2C)throw new Error('Catálogos B2B/B2C requeridos');moneda=await prisma.moneda.findUniqueOrThrow({where:{codigo_moneda:'CLP'}});medio=await prisma.medio_pago.findFirstOrThrow({where:{estado_medio_pago:'activo'}});
 for(const [tipo,nombre] of [[tipoB2B,'B2B'],[tipoB2C,'B2C']]){const marca=randomUUID().replaceAll('-','').slice(0,12);const c=await prisma.cliente_financiero.create({data:{id_tipo_cliente_financiero:tipo.id_tipo_cliente_financiero,rut_cliente:`M8${marca}`,nombre_razon_social_referencia:`M8 ${nombre} ${randomUUID()}`,estado_financiero:'activo',nivel_formalizacion:'formal',ficha_cliente:{create:{}}},include:{ficha_cliente:true}});ids.clientes.push(c.id_cliente_financiero);ids.fichas.push(c.ficha_cliente.id_ficha_cliente);if(nombre==='B2B')b2b=c;else b2c=c}
 cot=await prisma.cotizacion.create({data:{id_ficha_cliente:b2b.ficha_cliente.id_ficha_cliente,id_moneda:moneda.id_moneda,fecha_emision:new Date(),fecha_vigencia:new Date('2099-12-31'),monto_total_estimado:1000,estado_cotizacion:'emitida'}});ids.cots.push(cot.id_cotizacion);
 nota=await prisma.nota_venta.create({data:{id_ficha_cliente:b2b.ficha_cliente.id_ficha_cliente,id_cotizacion:cot.id_cotizacion,id_moneda:moneda.id_moneda,numero_nota_venta:`M8-${randomUUID()}`,fecha_emision:new Date(),monto_total:1000,estado_nota_venta:'confirmada'}});ids.notas.push(nota.id_nota_venta);
}
after(async()=>{await prisma.reduccion_compromiso_credito_m8.deleteMany({where:{pago_cliente:{id_pago_cliente:{in:ids.pagos}}}});await prisma.compromiso_credito_m8.deleteMany({where:{id_nota_venta:{in:ids.notas}}});await prisma.pago_cliente.deleteMany({where:{id_pago_cliente:{in:ids.pagos}}});await prisma.evento_credito_m8.deleteMany({where:{id_ficha_cliente:{in:ids.fichas}}});await prisma.resolucion_solicitud_crediticia_m8.deleteMany({where:{solicitud:{id_solicitud_crediticia:{in:ids.solicitudes}}}});await prisma.solicitud_crediticia_m8.deleteMany({where:{id_solicitud_crediticia:{in:ids.solicitudes}}});await prisma.condicion_crediticia_m8.deleteMany({where:{id_ficha_cliente:{in:ids.fichas}}});await prisma.limite_global_credito_m8.deleteMany({where:{id_limite_global:{in:ids.limites}}});await prisma.nota_venta.deleteMany({where:{id_nota_venta:{in:ids.notas}}});await prisma.cotizacion.deleteMany({where:{id_cotizacion:{in:ids.cots}}});await prisma.ficha_cliente.deleteMany({where:{id_ficha_cliente:{in:ids.fichas}}});await prisma.cliente_financiero.deleteMany({where:{id_cliente_financiero:{in:ids.clientes}}});await prisma.$disconnect()});

test('M8 CU260-CU274 núcleo crediticio',async t=>{await preparar();const idFicha=b2b.ficha_cliente.id_ficha_cliente;
 await t.test('01 CU260 sólo Cliente B2B sin Crédito crea borrador',async()=>{const s=await m.crearSolicitud('INICIAL',{idFichaCliente:idFicha,antecedentes:'Antecedentes'},A(actorS,['CU260']));ids.solicitudes.push(s.id);assert.equal(s.estado,'BORRADOR');await assert.rejects(m.crearSolicitud('INICIAL',{idFichaCliente:b2c.ficha_cliente.id_ficha_cliente},A(actorS,['CU260'])),e=>e.estado===409)});
 const inicial=ids.solicitudes[0];
 await t.test('02 borrador inicial se envía y transiciones inválidas se bloquean',async()=>{assert.equal((await m.enviarSolicitud(inicial,A(actorS,['CU260']))).estado_solicitud,'PENDIENTE');await assert.rejects(m.enviarSolicitud(inicial,A(actorS,['CU260'])),e=>e.estado===409)});
 await t.test('03 CU263 rechazo no modifica venta M2',async()=>{const s=await m.crearSolicitud('INICIAL',{idFichaCliente:idFicha},A(actorS,['CU260']));ids.solicitudes.push(s.id);await m.enviarSolicitud(s.id,A(actorS,['CU260']));await m.resolverSolicitud(s.id,{decision:'RECHAZADA',motivo:'Antecedentes insuficientes'},A(actorG,['CU263']));assert.equal((await prisma.nota_venta.findUniqueOrThrow({where:{id_nota_venta:nota.id_nota_venta}})).estado_nota_venta,'confirmada')});
 await t.test('04 CU263 aprobación habilita Crédito con cupo y vigencia definidos',async()=>{await m.resolverSolicitud(inicial,{decision:'APROBADA',motivo:'Aprobación manual',montoCupo:1000,vigenciaDesde:'2026-01-01',vigenciaHasta:'2099-12-31'},A(actorG,['CU263']));const c=await prisma.condicion_crediticia_m8.findUniqueOrThrow({where:{id_ficha_cliente:idFicha}});assert.equal(c.credito_habilitado,true);assert.equal(c.monto_cupo.toNumber(),1000)});
 await t.test('05 nueva solicitud inicial se bloquea con Crédito habilitado',()=>assert.rejects(m.crearSolicitud('INICIAL',{idFichaCliente:idFicha},A(actorS,['CU260'])),e=>e.estado===409));
 await t.test('06 CU261 exige operación y motivo libre',async()=>{await assert.rejects(m.crearSolicitud('EXCEPCION',{idFichaCliente:idFicha,motivo:'x'},A(actorS,['CU261'])),e=>e.estado===400);const s=await m.crearSolicitud('EXCEPCION',{idFichaCliente:idFicha,idCotizacion:cot.id_cotizacion,motivo:'Condición extraordinaria libre',condiciones:'Financiar excedente'},A(actorS,['CU261']));ids.solicitudes.push(s.id);excepcionAprobada=s.id;assert.equal(s.tipo,'EXCEPCION')});
 const ex=()=>ids.solicitudes.at(-1);
 await t.test('07 CU264 aprueba excepción sin modificar cupo ni formalizar M2',async()=>{await m.enviarSolicitud(ex(),A(actorS,['CU261']));await m.resolverSolicitud(ex(),{decision:'APROBADA',motivo:'Autorizada por Gerencia',condiciones:'Sólo esta Cotización'},A(actorG,['CU264']));assert.equal((await prisma.condicion_crediticia_m8.findUniqueOrThrow({where:{id_ficha_cliente:idFicha}})).monto_cupo.toNumber(),1000);assert.equal((await prisma.cotizacion.findUniqueOrThrow({where:{id_cotizacion:cot.id_cotizacion}})).estado_cotizacion,'emitida')});
 await t.test('08 CU262 cancela sólo borrador o pendiente y conserva antecedentes',async()=>{const s=await m.crearSolicitud('EXCEPCION',{idFichaCliente:idFicha,idCotizacion:cot.id_cotizacion,motivo:'Temporal'},A(actorS,['CU261']));ids.solicitudes.push(s.id);assert.equal((await m.cancelarSolicitud(s.id,{motivo:'Desistimiento'},A(actorS,['CU262']))).estado_solicitud,'CANCELADA');await assert.rejects(m.cancelarSolicitud(inicial,{motivo:'x'},A(actorS,['CU262'])),e=>e.estado===409)});
	 await t.test('09 CU268 configura límite y no implementa F047',async()=>{const transaccionOriginal=prisma.$transaction;let l;try{prisma.$transaction=async callback=>callback({limite_global_credito_m8:{findMany:async()=>[],update:async()=>{throw new Error('No corresponde actualizar')},create:async({data})=>({id_limite_global:-1,...data})}});l=await m.configurarLimiteGlobal({montoLimite:5000,vigenciaDesde:'2026-01-01',motivo:'Definición Gerencia'},A(actorG,['CU268']))}finally{prisma.$transaction=transaccionOriginal}assert.equal(Number(l.monto_limite),5000);const r=await conExposicionAislada(()=>m.consultarExposicion());assert.equal(r.capacidadDisponible,5000);assert.equal(r.avisoCapacidadProxima,'CONDICIONADO_F047_NO_IMPLEMENTADO')});
	 await t.test('10 validación ordinaria autoriza dentro de cupo y límite',async()=>{const r=await prisma.$transaction(tx=>validarCreditoParaFormalizacion(clienteCreditoAislado(tx,idFicha),{idFicha,montoFinanciado:new Prisma.Decimal(500),idCotizacion:cot.id_cotizacion}));assert.equal(r.resultado,'AUTORIZADO')});
 await t.test('11 compromiso nace una vez y explica cupo utilizado',async()=>{await prisma.$transaction(async tx=>{await registrarCompromisoCredito(tx,{idFicha,idNota:nota.id_nota_venta,montoFinanciado:new Prisma.Decimal(500)});await registrarCompromisoCredito(tx,{idFicha,idNota:nota.id_nota_venta,montoFinanciado:new Prisma.Decimal(500)})});assert.equal(await prisma.compromiso_credito_m8.count({where:{id_nota_venta:nota.id_nota_venta}}),1);assert.equal((await m.situacionCliente(idFicha,A(actorG,['CU270']))).utilizado,500)});
	 await t.test('12 exceso exige excepción y aprobada se revalida',async()=>{const sin=await prisma.$transaction(tx=>validarCreditoParaFormalizacion(clienteCreditoAislado(tx,idFicha),{idFicha,montoFinanciado:new Prisma.Decimal(800),idCotizacion:cot.id_cotizacion}));assert.equal(sin.resultado,'REQUIERE_EXCEPCION');const conEx=await prisma.$transaction(tx=>validarCreditoParaFormalizacion(clienteCreditoAislado(tx,idFicha),{idFicha,montoFinanciado:new Prisma.Decimal(800),idCotizacion:cot.id_cotizacion,idSolicitudExcepcion:excepcionAprobada}));assert.equal(conEx.resultado,'AUTORIZADO')});
 await t.test('13 CU265 reduce cupo y deja sobre-cupo sin tocar compromiso',async()=>{const r=await m.modificarCupo(idFicha,{montoCupo:100,vigenciaDesde:'2026-01-01',vigenciaHasta:'2099-12-31',motivo:'Reducción controlada'},A(actorG,['CU265']));assert.equal(r.sobreCupo,true);assert.equal((await prisma.compromiso_credito_m8.findUniqueOrThrow({where:{id_nota_venta:nota.id_nota_venta}})).monto_pendiente.toNumber(),500)});
 await t.test('14 CU266/CU267 exigen motivo y pago no reactiva',async()=>{await assert.rejects(m.suspenderCredito(idFicha,{},A(actorG,['CU266'])),e=>e.estado===400);await m.suspenderCredito(idFicha,{motivo:'Riesgo manual'},A(actorG,['CU266']));assert.equal((await prisma.condicion_crediticia_m8.findUniqueOrThrow({where:{id_ficha_cliente:idFicha}})).suspendido,true);await m.reactivarCredito(idFicha,{motivo:'Revisión manual'},A(actorG,['CU267']));assert.equal((await prisma.condicion_crediticia_m8.findUniqueOrThrow({where:{id_ficha_cliente:idFicha}})).suspendido,false)});
 await t.test('15 pago reduce una vez, libera cupo y operación totalmente pagada no consume',async()=>{const p=await prisma.pago_cliente.create({data:{id_ficha_cliente:idFicha,id_moneda:moneda.id_moneda,id_medio_pago:medio.id_medio_pago,fecha_pago:new Date(),monto_pago:500,estado_verificacion:'verificado'}});ids.pagos.push(p.id_pago_cliente);await prisma.$transaction(async tx=>{await reducirCompromisoPorPago(tx,p.id_pago_cliente,nota.id_nota_venta,p.monto_pago);await reducirCompromisoPorPago(tx,p.id_pago_cliente,nota.id_nota_venta,p.monto_pago)});const c=await prisma.compromiso_credito_m8.findUniqueOrThrow({where:{id_nota_venta:nota.id_nota_venta}});assert.equal(c.estado,'LIBERADO');assert.equal(c.monto_pendiente.toNumber(),0);assert.equal(await prisma.reduccion_compromiso_credito_m8.count({where:{id_pago_cliente:p.id_pago_cliente}}),1)});
	 await t.test('16 consultas CU269/CU270 separan dimensiones y costo F038 ausente',async()=>{const e=await conExposicionAislada(()=>m.consultarExposicion()),s=await m.situacionCliente(idFicha,A(actorC,['CU270']));assert.equal(e.exposicionUtilizada,0);assert.equal(s.suspension.suspendido,false);assert.equal(s.costoReal.estado,'FUENTE_NO_DISPONIBLE');assert.equal(s.morosidad.decisionAutomatica,false)});
 await t.test('17 CU271 reconstruye hechos sin historial paralelo',async()=>{const h=await m.historialCliente(idFicha,A(actorG,['CU271']));assert.ok(h.eventos.some(x=>x.tipo==='SUSPENSION'));assert.ok(h.solicitudes.length>=3)});
	 await t.test('18 CU273 distribución y concentración son derivadas',async()=>{const d=await conExposicionAislada(()=>m.distribucion(A(actorG,['CU273'])));assert.ok(d.clientes.some(x=>x.idFicha===idFicha));assert.equal(d.exposicionTotal,0)});
 await t.test('19 CU274 composición conserva operación y reducciones',async()=>{const c=await m.composicionCliente(idFicha,A(actorG,['CU274']));assert.equal(c.compromisos[0].operacion.idNota,nota.id_nota_venta);assert.equal(c.compromisos[0].reducciones.length,1);assert.equal(c.totalPendiente,0)});
 await t.test('20 CU272 exporta scope contextual y conjunto vacío',async()=>{const a=await m.exportar('solicitudes',{estado:'CANCELADA'},A(actorS,['CU272']));assert.match(a.contenido,/data:text\/csv;base64/);const vacio=await m.exportar('solicitudes',{desde:'2099-01-01'},A(actorS,['CU272']));assert.equal(vacio.total,0)});
 await t.test('21 M8→M7 entrega productor real y ausencia sigue segura',async()=>{const m7=new M7Controller(m);assert.equal((await m7.consultarExposicionCreditoM7({})).estado,'VALIDO');assert.equal((await new M7Controller().consultarExposicionCreditoM7({})).estado,'FUENTE_NO_DISPONIBLE')});
 await t.test('22 permisos CU260-CU274 son independientes y actores exactos',()=>{assert.equal(codigosTodosLosCU.length,274);assert.equal(operacionesPermiso.crearSolicitudInicialM8,'CU260');assert.equal(operacionesPermiso.consultarComposicionCreditoM8,'CU274');assert.deepEqual(matrizPermisosPorCU.CU260,['secretaria']);assert.deepEqual(matrizPermisosPorCU.CU270,['gerencia','secretaria','contador']);assert.deepEqual(matrizPermisosPorCU.CU274,['gerencia'])});
 await t.test('23 CU275 no existe y F047 no tiene umbral hardcodeado',()=>{assert.equal(codigosTodosLosCU.includes('CU275'),false);assert.equal(Object.hasOwn(operacionesPermiso,'CU275'),false)});
});
