const test=require('node:test');
const assert=require('node:assert/strict');
const {M9Controller}=require('../dist/controladores/M9Controller');
const {RepositorioAuditoriaM9Memoria}=require('../dist/m9/RepositorioAuditoriaM9');
const {RepositorioPoliticasMemoriaM9,MotorPoliticasM9}=require('../dist/m9/politicas');
const fecha=s=>new Date(s);
const categoria={id:1,codigo:'CONFIGURADA_OWNER',ownership:'M9',descripcion:null};
const politica=(id,version,accion,desde,hasta=null,extra={})=>({id,categoriaId:1,version,accion,modulo:'M1',entidad:'CLIENTE',estrategiaRef:null,permiteCorrelacion:false,preservarMinimo:false,finalidadRef:null,baseRef:null,politicaOwnerRef:null,desde:fecha(desde),hasta:hasta?fecha(hasta):null,...extra});
const entrada=(id,ocurrido='2036-01-01T00:00:00Z')=>({identidadLogica:`policy-${id}`,versionContrato:'1.0',ocurridoEn:ocurrido,zonaHoraria:'UTC',ejecutor:{tipo:'HUMANO',referencia:`persona-${id}`},productor:'M1',modulo:'M1',operacion:'CAMBIO',resultado:'EXITOSO',referencia:{tipo:'CLIENTE',id:`cliente-${id}`},nuevo:{correo:`persona-${id}@invalid.test`},capacidad:'EMITIR_EVENTO_M9'});
const estrategia={nombre:'TEST_SAFE',aplicar:(evento,correlacion)=>({evento:{...evento,ejecutorReferencia:null,entidadReferencia:correlacion?'anon-estable':null,anterior:null,nuevo:null,motivo:null,causa:null,metadatos:null,eventoPrivacidad:true},...(correlacion?{correlacionAnonima:'anon-estable'}:{})})};

test('M9 CUT414-CUT433 motor parametrizable y privacidad de consulta/exportación',async t=>{
 await t.test('sin policy no trata y ownership externo queda DEPENDENCIA_OWNER',async()=>{const motor=new MotorPoliticasM9(new RepositorioPoliticasMemoriaM9());const repo=new RepositorioAuditoriaM9Memoria(),m=new M9Controller({repositorio:repo,politicas:motor});const e=(await m.recibir(entrada('sin'))).evento;assert.equal((await motor.tratar(e,'INEXISTENTE',fecha('2036-01-02'))).estado,'SIN_POLITICA');const externa=new MotorPoliticasM9(new RepositorioPoliticasMemoriaM9([{...categoria,ownership:'OWNER'}],[politica(1,1,'PURGE','2035-01-01')]));assert.equal((await externa.tratar(e,categoria.codigo,fecha('2036-01-02'))).estado,'DEPENDENCIA_OWNER');});
 await t.test('policy versionada afecta sólo su vigencia y universo',async()=>{const repoP=new RepositorioPoliticasMemoriaM9([categoria],[politica(1,1,'NONE','2035-01-01','2035-12-31'),politica(2,2,'BLOCK','2036-01-01')]);const motor=new MotorPoliticasM9(repoP),repo=new RepositorioAuditoriaM9Memoria(),m=new M9Controller({repositorio:repo,politicas:motor});const a=(await m.recibir(entrada('v1','2035-06-01T00:00:00Z'))).evento,b=(await m.recibir(entrada('v2'))).evento;assert.equal((await motor.tratar(a,categoria.codigo,fecha('2035-06-01'))).politica.version,1);assert.equal((await motor.tratar(b,categoria.codigo,fecha('2036-01-01'))).estado,'BLOQUEADO');assert.equal((await motor.proyectar(b)).entidadReferencia,'cliente-v2');});
 await t.test('ANONYMIZE usa strategy explícita y correlación sólo autorizada',async()=>{const repoP=new RepositorioPoliticasMemoriaM9([categoria],[politica(3,1,'ANONYMIZE','2035-01-01',null,{estrategiaRef:'TEST_SAFE',permiteCorrelacion:true,preservarMinimo:true})]);const motor=new MotorPoliticasM9(repoP);motor.registrarEstrategia(estrategia);const repo=new RepositorioAuditoriaM9Memoria(),m=new M9Controller({repositorio:repo,politicas:motor});const e=(await m.recibir(entrada('anon'))).evento;assert.equal((await motor.tratar(e,categoria.codigo,fecha('2036-01-02'))).estado,'APLICADO');const vista=await m.consultar({identidadLogica:e.identidadLogica},{solicitante:'fixture',permitirCambios:true,permitirPrivacidad:true});assert.equal(vista.eventos[0].referencia.id,'anon-estable');assert.equal(vista.eventos[0].cambios.anterior,null);assert.equal(vista.eventos[0].cambios.nuevo,null);assert.equal(JSON.stringify(vista).includes('@invalid.test'),false);});
 await t.test('PURGE excluye de consulta/export y no muta evidencia original',async()=>{const motor=new MotorPoliticasM9(new RepositorioPoliticasMemoriaM9([categoria],[politica(4,1,'PURGE','2035-01-01')]));const repo=new RepositorioAuditoriaM9Memoria(),m=new M9Controller({repositorio:repo,politicas:motor});const e=(await m.recibir(entrada('purge'))).evento;await motor.tratar(e,categoria.codigo,fecha('2036-01-02'));assert.equal((await m.consultar({identidadLogica:e.identidadLogica},{solicitante:'fixture'})).total,0);assert.equal((await m.exportar('CSV',{identidadLogica:e.identidadLogica},{solicitante:'fixture'})).total,0);assert.equal((await repo.porId(e.id)).entidadReferencia,'cliente-purge');});
 await t.test('BLOCK impide tratamiento pero conserva almacenamiento',async()=>{const motor=new MotorPoliticasM9(new RepositorioPoliticasMemoriaM9([categoria],[politica(5,1,'BLOCK','2035-01-01')]));const repo=new RepositorioAuditoriaM9Memoria(),m=new M9Controller({repositorio:repo,politicas:motor});const e=(await m.recibir(entrada('block'))).evento;assert.equal((await motor.tratar(e,categoria.codigo,fecha('2036-01-02'))).estado,'BLOQUEADO');assert.equal((await m.consultar({identidadLogica:e.identidadLogica},{solicitante:'fixture'})).total,1);assert.equal(await repo.cantidad(),2);});
 await t.test('tratamiento deja evidencia terminal y elimina vínculos indirectos reidentificables',async()=>{const motor=new MotorPoliticasM9(new RepositorioPoliticasMemoriaM9([categoria],[politica(6,1,'ANONYMIZE','2035-01-01',null,{estrategiaRef:'TEST_SAFE'})]));motor.registrarEstrategia(estrategia);const repo=new RepositorioAuditoriaM9Memoria(),m=new M9Controller({repositorio:repo,politicas:motor});const origen=(await m.recibir(entrada('origen'))).evento;const derivado=(await m.recibir({...entrada('derivado'),eventoOrigenId:origen.id})).evento;await m.tratarPorPolitica(origen.id,categoria.codigo,fecha('2036-01-02'));const vista=await m.consultar({identidadLogica:derivado.identidadLogica},{solicitante:'fixture'});assert.equal(vista.eventos[0].eventoOrigenId,null);const terminales=(await repo.listar({modulo:'M9'})).eventos;assert.equal(terminales.some(e=>e.operacion==='TRATAMIENTO_PRIVACIDAD'&&e.contextoTerminal),true);});
 await t.test('no existe operación de reconstrucción de identidad',()=>{const motor=new MotorPoliticasM9(new RepositorioPoliticasMemoriaM9());assert.equal(typeof motor.reconstruirIdentidad,'undefined');});
});
