import { useCallback, useEffect, useState } from 'react';
import { AlertTriangle, Download, PauseCircle, PlayCircle, RefreshCw } from 'lucide-react';
import { solicitarFinanzas } from '../../api/finanzas';
import { usarSesion } from '../../seguridad/Sesion';

type Situacion={habilitado:boolean;cupo:number|null;utilizado:number;disponible:number|null;vigencia:{desde:string|null;hasta:string|null};suspension:{suspendido:boolean;motivo:string|null};sobreCupo:boolean;morosidad:{estado:string;cantidad:number};costoReal:{estado:string}};
const json=async(r:string,o?:RequestInit)=>{const x=await solicitarFinanzas(r,o),d=await x.json();if(!x.ok)throw new Error(d.error||'No fue posible completar la operación');return d};
const post=(body:unknown,method='POST'):RequestInit=>({method,headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});
const dinero=(n:number|null)=>n===null?'No disponible':`$${n.toLocaleString('es-CL')}`;

export default function CreditoCliente({idFicha}:{idFicha:number}){
 const {sesion}=usarSesion(),puede=(p:string)=>Boolean(sesion?.permisos.includes(p));
 const [dato,setDato]=useState<Situacion|null>(null),[error,setError]=useState(''),[detalle,setDetalle]=useState<unknown>(null);
 const cargar=useCallback(()=>{if(!puede('CU270'))return;setError('');void json(`/credito/clientes/${idFicha}`).then(setDato).catch(e=>setError(e.message))},[idFicha,sesion]);
 useEffect(cargar,[cargar]);
 const actuar=async(tipo:'cupo'|'suspender'|'reactivar')=>{try{const motivo=window.prompt('Motivo obligatorio');if(!motivo)return;if(tipo==='cupo'){const monto=window.prompt('Nuevo cupo');const desde=window.prompt('Vigencia desde AAAA-MM-DD');const hasta=window.prompt('Vigencia hasta AAAA-MM-DD');if(!monto||!desde||!hasta)return;await json(`/credito/clientes/${idFicha}/cupo`,post({montoCupo:Number(monto),vigenciaDesde:desde,vigenciaHasta:hasta,motivo},'PUT'))}else await json(`/credito/clientes/${idFicha}/${tipo}`,post({motivo}));cargar()}catch(e){setError((e as Error).message)}};
 const consultar=async(tipo:'historial'|'compromisos')=>{try{setDetalle(await json(`/credito/clientes/${idFicha}/${tipo}`))}catch(e){setError((e as Error).message)}};
 const exportar=async()=>{try{const a=await json(`/credito/exportar/cliente?idFicha=${idFicha}`),enlace=document.createElement('a');enlace.href=a.contenido;enlace.download=a.nombre;enlace.click()}catch(e){setError((e as Error).message)}};
 if(!puede('CU270'))return null;
 return <section className="mb-8 border-y border-gray-200 bg-white p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm font-semibold text-primary-600">M8 Crédito</p><h2 className="text-xl font-bold">Situación crediticia</h2></div><button title="Actualizar" onClick={cargar} className="border p-2"><RefreshCw className="h-4 w-4"/></button></div>{error&&<p className="mt-3 border border-red-200 bg-red-50 p-3 text-red-700">{error}</p>}{dato?<><div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><div><span className="text-xs uppercase text-gray-500">Cupo</span><strong className="block">{dinero(dato.cupo)}</strong></div><div><span className="text-xs uppercase text-gray-500">Utilizado</span><strong className="block">{dinero(dato.utilizado)}</strong></div><div><span className="text-xs uppercase text-gray-500">Disponible</span><strong className="block">{dinero(dato.disponible)}</strong></div><div><span className="text-xs uppercase text-gray-500">Vigencia</span><strong className="block">{dato.vigencia.desde||'—'} a {dato.vigencia.hasta||'—'}</strong></div></div><div className="mt-4 flex flex-wrap gap-2 text-sm">{dato.suspension.suspendido&&<span className="inline-flex items-center gap-1 bg-amber-100 px-2 py-1 text-amber-900"><AlertTriangle className="h-4 w-4"/>Suspendido</span>}{dato.sobreCupo&&<span className="bg-red-100 px-2 py-1 text-red-800">Sobre cupo</span>}<span className="bg-gray-100 px-2 py-1">Morosidad informada: {dato.morosidad.cantidad}</span><span className="bg-gray-100 px-2 py-1">Costo real: {dato.costoReal.estado}</span></div><div className="mt-5 flex flex-wrap gap-2">{puede('CU265')&&<button onClick={()=>void actuar('cupo')} className="border px-3 py-2">Modificar cupo/vigencia</button>}{puede('CU266')&&!dato.suspension.suspendido&&<button onClick={()=>void actuar('suspender')} className="inline-flex items-center gap-2 border px-3 py-2"><PauseCircle className="h-4 w-4"/>Suspender</button>}{puede('CU267')&&dato.suspension.suspendido&&<button onClick={()=>void actuar('reactivar')} className="inline-flex items-center gap-2 border px-3 py-2"><PlayCircle className="h-4 w-4"/>Reactivar</button>}{puede('CU271')&&<button onClick={()=>void consultar('historial')} className="border px-3 py-2">Historial</button>}{puede('CU274')&&<button onClick={()=>void consultar('compromisos')} className="border px-3 py-2">Composición</button>}{puede('CU272')&&<button title="Exportar contexto" onClick={()=>void exportar()} className="border p-2"><Download className="h-4 w-4"/></button>}</div>{detalle&&<pre className="mt-4 max-h-72 overflow-auto border bg-gray-50 p-3 text-xs">{JSON.stringify(detalle,null,2)}</pre>}</>:<p className="mt-4 text-gray-500">Cargando situación crediticia…</p>}</section>;
}
