import { useEffect, useState } from 'react';
import { ArrowLeft, ClipboardCheck, ClipboardPlus, History, Ruler, Save, SquarePen } from 'lucide-react';
import { Link, useParams } from 'react-router-dom';
import { usarSesion } from '../../seguridad/Sesion';

type Datos={tarea:{id:string;titulo:string|null;estado:string|null;fechaActualizacion:string|null};visita:{id:string;tipoServicio:string|null};obra:{nombre:string|null;referencia:string|null;direccion:string|null;comuna:string|null;region:string|null;cliente:{rut:string;nombre:string|null}|null;especificacion:{modelo:string|null;zona:string|null}|null};especificacion:Record<string,string|boolean|null>;medidas:Record<string,string|null>|null;historial:Array<{id:string;versionAnterior:string|null;versionNueva:string|null;fecha:string|null;descripcion:string|null}>;ordenTrabajo:{id:string;estado:string|null;fecha:string|null;idEspecificacion:string;proyecto:string|null;area:string|null;usuario:string|null}|null};
const camposEspecificacion=[['modeloPuerta','Modelo de puerta'],['zona','Zona'],['sentidoApertura','Sentido de apertura'],['materialidadVano','Materialidad del vano'],['materialidadMarcoActual','Materialidad del marco actual'],['solucionMarco','Solución de marco'],['hojaPasiva','Hoja pasiva'],['hojaActiva','Hoja activa'],['disenoPuerta','Diseño de puerta'],['bisagras','Bisagras']] as const;
const camposMedidas=[['marcoAncho','Marco ancho'],['marcoAlto','Marco alto'],['marcoEspesor','Marco espesor'],['vanoVerticalAncho','Vano vertical ancho'],['vanoVerticalAlto','Vano vertical alto'],['vanoVerticalEspesor','Vano vertical espesor'],['vanoHorizontalAncho','Vano horizontal ancho'],['vanoHorizontalAlto','Vano horizontal alto'],['vanoHorizontalEspesor','Vano horizontal espesor'],['alojamientoVerticalAlto','Alojamiento vertical alto'],['alojamientoVerticalAncho','Alojamiento vertical ancho'],['alojamientoVerticalEspesor','Alojamiento vertical espesor'],['alojamientoHorizontalAlto','Alojamiento horizontal alto'],['alojamientoHorizontalAncho','Alojamiento horizontal ancho'],['alojamientoHorizontalEspesor','Alojamiento horizontal espesor'],['alojamientoVertical','Alojamiento vertical'],['medidaMarcoAncho','Medida de marco ancho'],['medidaMarcoAlto','Medida de marco alto'],['medidaMarcoEspesor','Medida de marco espesor']] as const;
const json=async(ruta:string,opciones?:RequestInit)=>{const respuesta=await fetch(`/api/finanzas${ruta}`,{...opciones,credentials:'same-origin'});const dato=await respuesta.json();if(!respuesta.ok)throw new Error(dato.error||'No fue posible completar la operación');return dato};

export default function LevantamientoTecnico(){
 const {sesion}=usarSesion(),{id}=useParams();const puedeGuardar=Boolean(sesion?.permisos.includes('CU202')),puedeCorregir=Boolean(sesion?.permisos.includes('CU203')),puedeGenerarOt=Boolean(sesion?.permisos.includes('CU204')),puedeGestionarOt=Boolean(sesion?.permisos.includes('CU205'));
 const [datos,setDatos]=useState<Datos|null>(null),[especificacion,setEspecificacion]=useState<Record<string,string|boolean|null>>({}),[medidas,setMedidas]=useState<Record<string,string>>({}),[error,setError]=useState(''),[mensaje,setMensaje]=useState(''),[guardando,setGuardando]=useState(false),[modoCorreccion,setModoCorreccion]=useState<'levantamiento'|'ot'|null>(null),[motivo,setMotivo]=useState('');
 const cargar=async()=>{setError('');try{const resultado=await json(`/terreno/tareas/${id}/levantamiento`) as Datos;setDatos(resultado);setEspecificacion(resultado.especificacion);setMedidas(Object.fromEntries(Object.entries(resultado.medidas||{}).filter(([clave])=>clave!=='id').map(([clave,valor])=>[clave,valor||''])))}catch(e){setError((e as Error).message)}};
 useEffect(()=>{void cargar()},[id]);
 const guardar=async()=>{setError('');setMensaje('');setGuardando(true);try{const resultado=await json(`/terreno/tareas/${id}/levantamiento`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({especificacion,medidas})}) as Datos;setDatos(resultado);setMensaje('Levantamiento técnico guardado')}catch(e){setError((e as Error).message)}finally{setGuardando(false)}};
 const corregir=async()=>{setError('');setMensaje('');setGuardando(true);try{const ruta=modoCorreccion==='ot'?`/terreno/tareas/${id}/orden-trabajo/ajustes`:`/terreno/tareas/${id}/levantamiento/correcciones`;const resultado=await json(ruta,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({motivo,especificacion,medidas})}) as Datos;setDatos(resultado);setEspecificacion(resultado.especificacion);setMedidas(Object.fromEntries(Object.entries(resultado.medidas||{}).filter(([clave])=>clave!=='id').map(([clave,valor])=>[clave,valor||''])));setMotivo('');setModoCorreccion(null);setMensaje(modoCorreccion==='ot'?'Orden de Trabajo ajustada':'Corrección registrada')}catch(e){setError((e as Error).message)}finally{setGuardando(false)}};
 const generarOt=async()=>{setError('');setMensaje('');setGuardando(true);try{const resultado=await json(`/terreno/tareas/${id}/orden-trabajo`,{method:'POST'}) as Datos;setDatos(resultado);setMensaje(`Orden de Trabajo ${resultado.ordenTrabajo?.id||''} disponible`)}catch(e){setError((e as Error).message)}finally{setGuardando(false)}};
 const liberarOt=async()=>{if(!datos?.ordenTrabajo)return;setError('');setMensaje('');setGuardando(true);try{const resultado=await json(`/terreno/tareas/${id}/orden-trabajo/${datos.ordenTrabajo.id}/liberar`,{method:'POST'}) as Datos;setDatos(resultado);setMensaje(`Orden de Trabajo ${resultado.ordenTrabajo?.id||''} liberada para producción`)}catch(e){setError((e as Error).message)}finally{setGuardando(false)}};
 return <div className="min-h-full bg-gray-50 p-5 lg:p-8"><div className="mx-auto max-w-6xl"><header className="mb-6 flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm font-semibold text-primary-600">Terreno</p><h1 className="flex items-center gap-2 text-2xl font-bold"><Ruler className="h-6 w-6"/>Levantamiento técnico</h1></div><Link title="Volver a mis tareas" to="/terreno/mis-tareas" className="rounded border bg-white p-2.5"><ArrowLeft className="h-4 w-4"/></Link></header>
 {error&&<p className="mb-4 border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</p>}{mensaje&&<p className="mb-4 border border-green-200 bg-green-50 p-3 text-sm text-green-800">{mensaje}</p>}
 {datos&&<><section className="mb-5 border-y bg-white p-5"><h2 className="mb-4 font-bold">{datos.tarea.titulo||`Tarea ${datos.tarea.id}`}</h2><dl className="grid gap-4 text-sm md:grid-cols-2 lg:grid-cols-4"><div><dt className="text-gray-500">Visita</dt><dd>{datos.visita.tipoServicio||datos.visita.id}</dd></div><div><dt className="text-gray-500">Obra</dt><dd>{datos.obra.nombre||datos.obra.referencia||'Sin nombre'}</dd></div><div><dt className="text-gray-500">Cliente</dt><dd>{datos.obra.cliente?.nombre||datos.obra.cliente?.rut||'Sin cliente'}</dd></div><div><dt className="text-gray-500">Puerta</dt><dd>{String(especificacion.modeloPuerta||'Sin modelo')} · {String(especificacion.zona||'Sin zona')}</dd></div><div className="md:col-span-2"><dt className="text-gray-500">Ubicación</dt><dd>{[datos.obra.direccion,datos.obra.comuna,datos.obra.region].filter(Boolean).join(', ')||'Sin ubicación'}</dd></div><div><dt className="text-gray-500">Última actualización</dt><dd>{datos.tarea.fechaActualizacion?new Date(datos.tarea.fechaActualizacion).toLocaleDateString('es-CL'):'Sin registro'}</dd></div></dl></section>
 <section className="border-y bg-white p-5"><h2 className="mb-4 font-bold">Especificación existente</h2><div className="grid gap-3 md:grid-cols-2 lg:grid-cols-3">{camposEspecificacion.map(([campo,etiqueta])=><label key={campo} className="text-sm"><span className="mb-1 block text-gray-600">{etiqueta}</span><input value={String(especificacion[campo]||'')} onChange={e=>setEspecificacion({...especificacion,[campo]:e.target.value})} className="w-full rounded border p-2.5"/></label>)}<label className="text-sm"><span className="mb-1 block text-gray-600">Cubrejuntas</span><select value={especificacion.cubrejuntas===true?'si':especificacion.cubrejuntas===false?'no':''} onChange={e=>setEspecificacion({...especificacion,cubrejuntas:e.target.value===''?null:e.target.value==='si'})} className="w-full rounded border p-2.5"><option value="">Sin información</option><option value="si">Sí</option><option value="no">No</option></select></label><label className="text-sm md:col-span-2 lg:col-span-3"><span className="mb-1 block text-gray-600">Observaciones de diseño</span><textarea value={String(especificacion.observacionesDiseno||'')} onChange={e=>setEspecificacion({...especificacion,observacionesDiseno:e.target.value})} className="w-full rounded border p-2.5"/></label><label className="text-sm md:col-span-2 lg:col-span-3"><span className="mb-1 block text-gray-600">Observaciones</span><textarea value={String(especificacion.observaciones||'')} onChange={e=>setEspecificacion({...especificacion,observaciones:e.target.value})} className="w-full rounded border p-2.5"/></label></div>
 <h2 className="mb-4 mt-7 font-bold">Medidas existentes</h2><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{camposMedidas.map(([campo,etiqueta])=><label key={campo} className="text-sm"><span className="mb-1 block text-gray-600">{etiqueta}</span><input type="number" min="0" step="0.0001" value={medidas[campo]||''} onChange={e=>setMedidas({...medidas,[campo]:e.target.value})} className="w-full rounded border p-2.5"/></label>)}</div><div className="mt-6 flex flex-wrap justify-end gap-2">{puedeCorregir&&<button disabled={guardando} onClick={()=>setModoCorreccion('levantamiento')} className="flex items-center gap-2 rounded border px-4 py-2 font-semibold"><SquarePen className="h-4 w-4"/>Corregir levantamiento</button>}{puedeGuardar&&<button disabled={guardando} onClick={()=>void guardar()} className="flex items-center gap-2 rounded bg-primary-600 px-4 py-2 text-white disabled:opacity-40"><Save className="h-4 w-4"/>Guardar levantamiento</button>}</div>{modoCorreccion&&<div className="mt-5 border-t pt-5"><label className="text-sm"><span className="mb-1 block font-semibold">Motivo del {modoCorreccion==='ot'?'ajuste de OT':'levantamiento'}</span><textarea maxLength={1000} value={motivo} onChange={e=>setMotivo(e.target.value)} className="w-full rounded border p-2.5"/></label><div className="mt-3 flex justify-end gap-2"><button onClick={()=>setModoCorreccion(null)} className="rounded border px-4 py-2">Cancelar</button><button disabled={guardando||!motivo.trim()} onClick={()=>void corregir()} className="rounded bg-primary-600 px-4 py-2 text-white disabled:opacity-40">Registrar {modoCorreccion==='ot'?'ajuste':'corrección'}</button></div></div>}</section>
 <section className="mt-5 border-y bg-white p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="flex items-center gap-2 font-bold"><ClipboardPlus className="h-4 w-4"/>Orden de Trabajo</h2>{datos.ordenTrabajo?<p className="mt-2 text-sm text-gray-700">OT {datos.ordenTrabajo.id} · {datos.ordenTrabajo.estado||'Sin estado'} · {datos.ordenTrabajo.fecha?new Date(datos.ordenTrabajo.fecha).toLocaleString('es-CL'):'Sin fecha'}</p>:<p className="mt-2 text-sm text-gray-500">No existe una Orden de Trabajo abierta para este levantamiento.</p>}</div><div className="flex flex-wrap gap-2">{puedeGestionarOt&&datos.ordenTrabajo&&['pendiente','activa'].includes(datos.ordenTrabajo.estado||'')&&<><button disabled={guardando} onClick={()=>setModoCorreccion('ot')} className="flex items-center gap-2 rounded border px-4 py-2 font-semibold"><SquarePen className="h-4 w-4"/>Ajustar OT</button><button disabled={guardando||!datos.medidas} onClick={()=>void liberarOt()} className="flex items-center gap-2 rounded bg-primary-600 px-4 py-2 font-semibold text-white disabled:opacity-40"><ClipboardCheck className="h-4 w-4"/>Liberar para producción</button></>}{puedeGenerarOt&&!datos.ordenTrabajo&&<button disabled={guardando||!datos.medidas} onClick={()=>void generarOt()} className="flex items-center gap-2 rounded bg-primary-600 px-4 py-2 font-semibold text-white disabled:opacity-40"><ClipboardPlus className="h-4 w-4"/>Generar Orden de Trabajo</button>}</div></div></section>
 <section className="mt-5 border-y bg-white p-5"><h2 className="mb-4 flex items-center gap-2 font-bold"><History className="h-4 w-4"/>Historial de correcciones</h2>{datos.historial.length?<div className="divide-y">{datos.historial.map(cambio=><div key={cambio.id} className="py-3 text-sm"><div className="flex flex-wrap justify-between gap-2"><strong>{cambio.versionAnterior||'Sin versión'} → {cambio.versionNueva||'Sin versión'}</strong><span className="text-gray-500">{cambio.fecha?new Date(cambio.fecha).toLocaleString('es-CL'):'Sin fecha'}</span></div><p className="mt-1 text-gray-700">{cambio.descripcion||'Sin descripción'}</p></div>)}</div>:<p className="text-sm text-gray-500">No existen correcciones registradas.</p>}</section></>}
 </div></div>;
}
