import { useEffect, useState } from 'react';
import { operar, usarSesion } from '../../seguridad/Sesion';
import { entradaClase, botonClase, tarjetaClase } from './Acceso';
interface Usuario {id:string;nombre:string;acceso:string;correo:string;estado:string;configuracion:string;configuracionParticular:boolean;administrador:boolean;original:boolean;bloqueada:boolean;permisos:string[]}
interface Catalogo {empleados:{rut_empleado:string;nombres:string;apellido_paterno:string}[];configuraciones:{codigo_m4:string;perfil_nombre_perfil:string;admite_particulares:boolean}[];permisos:{codigo_m4:string;permiso_descripcion:string;requiere_administrador:boolean}[];dependencias:{permiso:string;requiere:string}[]}
const nombres:Record<string,string>={desactivar:'Desactivar usuario',reactivar:'Reactivar usuario',configuracion:'Cambiar configuración base',asignar:'Asignar permisos',retirar:'Retirar permisos',administrador:'Asignar Administrador','retirar-administrador':'Retirar Administrador',restablecer:'Restablecer contraseña',desbloquear:'Desbloquear cuenta'};
export default function Usuarios() {
 const {sesion}=usarSesion();const [usuarios,cambiarUsuarios]=useState<Usuario[]>([]);const [catalogo,cambiarCatalogo]=useState<Catalogo|null>(null);const [seleccionado,seleccionar]=useState<string>('');const [nuevo,mostrarNuevo]=useState(false);const [mensaje,cambiarMensaje]=useState('');const [temporal,cambiarTemporal]=useState('');const [ocupado,cambiarOcupado]=useState(false);
 const [accion,cambiarAccion]=useState<{nombre:string;cuerpo:Record<string,unknown>}|null>(null);const [permisos,cambiarPermisos]=useState<string[]>([]);const [configuracion,cambiarConfiguracion]=useState('');
 const cuenta=usuarios.find(u=>u.id===seleccionado);const permite=(permiso:string)=>sesion?.permisos.includes(permiso);
 const cargar=async()=>{const resultado=await operar('/usuarios');cambiarUsuarios(resultado);if(permite('CU59'))cambiarCatalogo(await operar('/usuarios/catalogos'));};
 useEffect(()=>{void cargar().catch(e=>cambiarMensaje(e.message));},[]);
 const proponer=(nombre:string,cuerpo:Record<string,unknown>={})=>cambiarAccion({nombre,cuerpo:{id:seleccionado,...cuerpo}});
 return <div className="p-8 max-w-7xl mx-auto"><div className="flex items-center justify-between mb-6"><div><h1 className="text-3xl font-bold">Gestión de Usuarios</h1><p className="text-gray-500 mt-2">Estado de cuentas, configuración y permisos efectivos</p></div>{permite('CU59')&&<button className={botonClase} onClick={()=>{mostrarNuevo(!nuevo);seleccionar('');}}>Nuevo Usuario</button>}</div>
 {mensaje&&<p role="status" className="p-4 mb-4 bg-orange-50 text-orange-900 rounded-lg">{mensaje}</p>}
 {temporal&&<div className={`${tarjetaClase} mb-5`}><h2 className="font-bold">Credencial temporal generada</h2><p className="text-sm text-gray-500 my-2">Entrégala por un canal seguro. Sólo se muestra en esta respuesta y obliga a cambiarla al ingresar.</p><input aria-label="Contraseña temporal" className={entradaClase} value={temporal} readOnly/><button className="mt-3 text-primary-600" onClick={()=>cambiarTemporal('')}>Ocultar credencial</button></div>}
 {nuevo&&catalogo&&<form className={`${tarjetaClase} mb-6 space-y-4`} onSubmit={evento=>{evento.preventDefault();const datos=Object.fromEntries(new FormData(evento.currentTarget));cambiarAccion({nombre:'nuevo',cuerpo:datos});}}><h2 className="text-xl font-bold">Nuevo Usuario</h2><label className="block">Empleado activo<select className={entradaClase} name="rutEmpleado" required><option value="">Seleccionar empleado sin cuenta</option>{catalogo.empleados.map(e=><option key={e.rut_empleado} value={e.rut_empleado}>{e.nombres} {e.apellido_paterno} · {e.rut_empleado}</option>)}</select></label><label className="block">Correo<input className={entradaClase} type="email" name="correo" required/></label><label className="block">Configuración inicial<select className={entradaClase} name="configuracion">{catalogo.configuraciones.map(c=><option key={c.codigo_m4} value={c.codigo_m4}>{c.perfil_nombre_perfil}</option>)}</select></label><button className={botonClase}>Revisar y crear cuenta</button></form>}
 <div className="bg-white border rounded-xl overflow-x-auto shadow-sm mb-6"><table className="w-full text-left text-sm"><thead className="bg-gray-50 text-gray-500"><tr>{['Usuario','Configuración','Estado','Accesos'].map(t=><th className="px-6 py-4" key={t}>{t}</th>)}</tr></thead><tbody>{usuarios.map(u=><tr key={u.id} className="border-t border-gray-100"><td className="px-6 py-4"><strong>{u.nombre}</strong><p className="text-gray-500">{u.acceso}</p></td><td className="px-6 py-4 capitalize">{u.configuracion}{u.configuracionParticular?' · Particular':''}{u.administrador&&<span className="block text-primary-600">Administrador</span>}</td><td className="px-6 py-4"><span className={`px-2 py-1 rounded-full text-xs ${u.estado==='activo'?'bg-green-100 text-green-700':'bg-gray-100 text-gray-600'}`}>{u.estado}</span>{u.bloqueada&&<span className="block text-red-600 mt-2">Bloqueo persistente</span>}</td><td className="px-6 py-4"><button className="text-primary-600 font-semibold" onClick={()=>{seleccionar(u.id);cambiarPermisos([]);cambiarConfiguracion(u.configuracion);mostrarNuevo(false);}}>Ver accesos</button></td></tr>)}</tbody></table></div>
 {cuenta&&<section className="space-y-5"><div className={tarjetaClase}><h2 className="text-xl font-bold">Detalle y accesos — {cuenta.nombre}</h2><p className="text-gray-500 mt-1">{cuenta.correo}</p><div className="flex flex-wrap gap-2 mt-4">{cuenta.permisos.map(p=><span key={p} className="bg-orange-50 text-primary-700 px-3 py-1 rounded-full text-xs">{p}</span>)}</div><div className="flex flex-wrap gap-3 mt-5">{[['desactivar','CU60'],['reactivar','CU61'],['restablecer','CU71'],['desbloquear','CU72']].filter(([a,p])=>permite(p!) && (a==='desactivar'?cuenta.estado==='activo':a==='reactivar'?cuenta.estado==='inactivo':a==='desbloquear'?cuenta.bloqueada:true)).map(([a])=><button key={a} className="px-4 py-2 border rounded-lg text-gray-700 hover:bg-gray-50" onClick={()=>proponer(a!)}>{nombres[a!]}</button>)}</div></div>
 {catalogo&&permite('CU62')&&<div className={tarjetaClase}><h2 className="font-bold text-lg mb-3">Configuración base</h2><p className="text-sm text-gray-500 mb-3">El cambio reemplaza la configuración particular e invalida la sesión de esta cuenta.</p><div className="flex gap-3"><select aria-label="Configuración base" className={entradaClase} value={configuracion} onChange={e=>cambiarConfiguracion(e.target.value)}>{catalogo.configuraciones.map(c=><option key={c.codigo_m4} value={c.codigo_m4}>{c.perfil_nombre_perfil}</option>)}</select><button className={botonClase} onClick={()=>proponer('configuracion',{configuracion})}>Cambiar</button></div></div>}
 {catalogo&&cuenta.configuracion!=='gerencia'&&<div className={tarjetaClase}><h2 className="font-bold text-lg mb-3">Permisos particulares</h2><p className="text-sm text-gray-500 mb-4">Las dependencias se validan antes de guardar. No se editan los perfiles base.</p><div className="grid grid-cols-2 lg:grid-cols-3 gap-3">{catalogo.permisos.filter(p=>Number(p.codigo_m4.slice(2))<59).map(p=><label key={p.codigo_m4} className="flex gap-2 text-sm"><input type="checkbox" checked={permisos.includes(p.codigo_m4)} onChange={e=>cambiarPermisos(e.target.checked?[...permisos,p.codigo_m4]:permisos.filter(v=>v!==p.codigo_m4))}/><span>{p.codigo_m4}<small className="block text-gray-500">{catalogo.dependencias.filter(d=>d.permiso===p.codigo_m4).map(d=>`Requiere ${d.requiere}`).join(', ')}</small></span></label>)}</div><div className="flex gap-3 mt-5">{permite('CU63')&&<button className={botonClase} onClick={()=>proponer('asignar',{permisos})}>Asignar seleccionados</button>}{permite('CU64')&&<button className="border rounded-lg px-4 py-2 text-red-600" onClick={()=>proponer('retirar',{permisos})}>Retirar seleccionados</button>}</div></div>}
 {cuenta.configuracion==='gerencia'&&<div className={tarjetaClase}><h2 className="font-bold text-lg mb-2">Gestión Administrador</h2><p className="text-sm text-gray-500 mb-4">Rol adicional a Gerencia. Se conserva la continuidad administrativa.</p>{!cuenta.administrador&&permite('CU65')&&<button className={botonClase} onClick={()=>proponer('administrador')}>Asignar Administrador</button>}{cuenta.administrador&&permite('CU66')&&<button className="border rounded-lg px-4 py-2 text-red-600" onClick={()=>proponer('retirar-administrador')}>Retirar Administrador</button>}</div>}</section>}
 {accion&&<div className="fixed inset-0 z-50 bg-black/50 flex items-center justify-center p-6"><form className={`${tarjetaClase} w-full max-w-lg space-y-4`} onSubmit={async e=>{e.preventDefault();const datos=Object.fromEntries(new FormData(e.currentTarget));cambiarOcupado(true);try{const resultado=await operar(accion.nombre==='nuevo'?'/usuarios':`/usuarios/${accion.nombre}`,{...accion.cuerpo,...datos,confirmado:true});cambiarMensaje(resultado.mensaje);cambiarTemporal(resultado.claveTemporal || '');cambiarAccion(null);mostrarNuevo(false);await cargar();}catch(error){cambiarMensaje((error as Error).message);cambiarAccion(null);}finally{cambiarOcupado(false);}}}><h2 className="text-xl font-bold">{accion.nombre==='nuevo'?'Confirmar nuevo Usuario':nombres[accion.nombre]}</h2><p className="text-gray-600">{cuenta?.nombre || String(accion.cuerpo.rutEmpleado)}. Revisa la operación antes de confirmar.</p>{accion.nombre==='administrador'&&<label className="block">Tu contraseña actual<input className={entradaClase} name="claveActual" type="password" autoComplete="current-password" required/></label>}<div className="flex justify-end gap-3"><button type="button" className="border rounded-lg px-4 py-2" onClick={()=>cambiarAccion(null)}>Cancelar</button><button disabled={ocupado} className={botonClase}>{ocupado?'Procesando…':'Confirmar'}</button></div></form></div>}
 </div>;
}
