import {useState} from 'react';
import {operar,usarSesion} from '../seguridad/Sesion';
import {entradaClase,botonClase} from '../views/Seguridad/Acceso';
interface Catalogos {medios:{id_medio_pago:number;nombre_medio_pago:string}[];categorias:{id_categoria_pago:number;nombre:string}[];cuotas:{cantidad:number}[];documentos:{id_documento_tributario:number;folio_documento:string;tipo_documento:{nombre_tipo_documento:string}}[]}
export default function OperacionesFinancieras({tipo,documento}:{tipo:string;documento:any}) {
 const {sesion}=usarSesion();const [modo,cambiarModo]=useState('');const [catalogos,cambiarCatalogos]=useState<Catalogos|null>(null);const [mensaje,cambiarMensaje]=useState('');const [ocupado,cambiarOcupado]=useState(false);const [pdf,cambiarPdf]=useState('');
 const nota=tipo==='nota_venta';const permite=(p:string)=>sesion?.permisos.includes(p);const moneda=documento.moneda?.codigo_moneda;
 const iniciar=async(operacion:string)=>{cambiarModo(operacion);cambiarMensaje('');if(operacion!=='reversion')try{cambiarCatalogos(await operar(`/pagos/catalogos?idFicha=${documento.id_ficha_cliente}`));}catch(e){cambiarMensaje((e as Error).message);}};
 return <section className="border-t mt-6 pt-5"><div className="flex gap-3 flex-wrap">
 {nota&&permite('CU43')&&<button className={botonClase} onClick={()=>iniciar('pago')}>Registrar pago</button>}
 {nota&&permite('CU38')&&<button className="px-4 py-2 border rounded-lg text-red-600" onClick={()=>iniciar('reversion')}>Reversión comercial</button>}
 {!nota&&documento.estado_cotizacion==='emitida'&&permite('CU25')&&<button className={botonClase} onClick={()=>iniciar('b2c')}>Consolidar B2C con primer pago</button>}</div>
 {mensaje&&<p role="status" className="mt-4 p-3 bg-orange-50 text-orange-900 rounded-lg">{mensaje}</p>}
 {modo&&<form className="space-y-4 mt-5" onSubmit={async evento=>{evento.preventDefault();if(!window.confirm('¿Confirmas los antecedentes y la operación?'))return;const datos=Object.fromEntries(new FormData(evento.currentTarget));cambiarOcupado(true);try{
 const ruta=modo==='reversion'?`/notas-venta/${documento.id_nota_venta}/revertir`:modo==='b2c'?`/cotizaciones/${documento.id_cotizacion}/consolidar-b2c`:'/pagos';
 const resultado=await operar(ruta,{...datos,idNota:documento.id_nota_venta,respaldoPdf:pdf,confirmacionMontoPdf:datos.confirmacionMontoPdf==='on'});cambiarMensaje(resultado.mensaje || 'Operación realizada');cambiarModo('');window.location.reload();
 }catch(e){cambiarMensaje((e as Error).message);}finally{cambiarOcupado(false);}}}>
 <h3 className="font-bold text-lg">{modo==='reversion'?'Reversión con Nota de Crédito':modo==='b2c'?'Primer pago y consolidación B2C':'Nuevo pago'}</h3>
 <label className="block text-sm">Monto ({moneda})<input className={entradaClase} name="monto" type="number" step="0.01" min="0.01" required/></label>
 {modo==='reversion'?<><label className="block text-sm">Motivo<textarea className={entradaClase} name="motivo" required/></label><label className="block text-sm">Folio Nota de Crédito<input className={entradaClase} name="folio" required/></label><label className="block text-sm">Monto indicado en el documento<input className={entradaClase} name="montoDocumento" type="number" min="0.01" step="0.01" required/></label><label className="block text-sm">Nota de Crédito PDF (máximo 3 MB)<input className={`${entradaClase} mt-1`} type="file" accept="application/pdf" required onChange={e=>{const archivo=e.target.files?.[0];if(!archivo)return;if(archivo.size>3000000){cambiarMensaje('El PDF supera 3 MB');return;}const lector=new FileReader();lector.onload=()=>cambiarPdf(String(lector.result));lector.readAsDataURL(archivo);}}/></label><label className="flex gap-2 text-sm"><input name="confirmacionMontoPdf" type="checkbox" required/>Confirmo que revisé el PDF y que su monto coincide con el indicado.</label><label className="block text-sm">Si aparece un excedente<select className={entradaClase} name="destino"><option value="">Seleccionar tratamiento</option><option value="saldo_favor">Conservar como saldo a favor</option><option value="devolucion">Dejar disponible para devolución posterior</option></select></label></>:catalogos&&<>
 <label className="block text-sm">Documento tributario existente<select className={entradaClase} name="idDocumento" required><option value="">Seleccionar documento del mismo cliente</option>{catalogos.documentos.map(d=><option key={d.id_documento_tributario} value={d.id_documento_tributario}>{d.tipo_documento.nombre_tipo_documento} · {d.folio_documento}</option>)}</select></label>
 <label className="block text-sm">Medio de pago<select className={entradaClase} name="idMedio" required><option value="">Seleccionar</option>{catalogos.medios.map(m=><option key={m.id_medio_pago} value={m.id_medio_pago}>{m.nombre_medio_pago}</option>)}</select></label>
 <label className="block text-sm">Categoría<select className={entradaClase} name="idCategoria"><option value="">Sugerir según saldo y pagos</option>{catalogos.categorias.map(c=><option key={c.id_categoria_pago} value={c.id_categoria_pago}>{c.nombre}</option>)}</select></label>
 <label className="block text-sm">Cuotas (si pagas con tarjeta de crédito)<select className={entradaClase} name="cuotas"><option value="">No aplica</option>{catalogos.cuotas.map(c=><option key={c.cantidad} value={c.cantidad}>{c.cantidad}</option>)}</select></label>
 {moneda==='USD'&&<label className="block text-sm">Tipo de cambio confirmado para este pago<input className={entradaClase} name="tipoCambio" type="number" min="0.0001" step="0.0001" required/><span className="text-xs text-gray-500">Ingreso manual. No se presenta como una consulta al Banco Central.</span></label>}
 <label className="block text-sm">Referencia del respaldo del pago<input className={entradaClase} name="respaldo" required/></label></>}
 <div className="flex gap-3"><button className={botonClase} disabled={ocupado || (modo!=='reversion'&&!catalogos)}>{ocupado?'Procesando…':'Confirmar operación'}</button><button type="button" onClick={()=>cambiarModo('')} className="px-4 py-2 border rounded-lg">Cancelar</button></div>
 </form>}
 </section>;
}
