import { useEffect, useMemo, useState } from 'react';
import { AlertTriangle, ArrowDownUp, Settings2, X } from 'lucide-react';
import { solicitarFinanzas } from '../../api/finanzas';
import { usarSesion } from '../../seguridad/Sesion';

interface Cuenta {id:number;proveedor:{id:number;razonSocial:string;identificadorFiscal:string};documento:{id:number;folio:string;tipo:string};moneda:string;montoOriginal:number;saldoActual:number;fechaEmision:string;fechaVencimiento:string;condicionTemporal:string|null;estadoPago:string;tipoCambio:number|null;requiereAtencion:boolean}
async function api(ruta:string,opciones?:RequestInit){const respuesta=await solicitarFinanzas(ruta,opciones);const resultado=await respuesta.json();if(!respuesta.ok)throw new Error(resultado.error||'No fue posible consultar cuentas por pagar');return resultado}

export default function CuentasPorPagar(){
 const {sesion}=usarSesion();const [cuentas,setCuentas]=useState<Cuenta[]>([]);const [filtros,setFiltros]=useState({estadoTemporal:'todos',estadoPago:'todos',proveedor:'',busqueda:'',ordenar:'fechaVencimiento',direccion:'asc'});const [version,setVersion]=useState(0);const [error,setError]=useState('');const [cargando,setCargando]=useState(true);const [configurar,setConfigurar]=useState(false);const [umbral,setUmbral]=useState('5');const [mensaje,setMensaje]=useState('');
 const puedeConfigurar=!!sesion?.permisos.includes('CU110')&&sesion.configuracion==='gerencia'&&sesion.administrador;
 useEffect(()=>{const espera=window.setTimeout(()=>{const p=new URLSearchParams();Object.entries(filtros).forEach(([k,v])=>{if(v)p.set(k,v)});setCargando(true);api(`/cuentas-por-pagar?${p}`).then(setCuentas).catch(e=>setError(e.message)).finally(()=>setCargando(false));},200);return()=>window.clearTimeout(espera)},[filtros,version]);
 useEffect(()=>{api('/configuracion/umbral-por-vencer-proveedores').then(r=>setUmbral(String(r.diasHabiles))).catch(()=>undefined)},[version]);
 const proveedores=useMemo(()=>[...new Map(cuentas.map(c=>[c.proveedor.id,c.proveedor])).values()].sort((a,b)=>a.razonSocial.localeCompare(b.razonSocial,'es-CL')),[cuentas]);
 const cambiar=(campo:string,valor:string)=>setFiltros(actual=>({...actual,[campo]:valor}));
 const guardarUmbral=async()=>{setError('');const respuesta=await solicitarFinanzas('/configuracion/umbral-por-vencer-proveedores',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({diasHabiles:Number(umbral)})});const resultado=await respuesta.json();if(!respuesta.ok){setError(resultado.error||'No fue posible actualizar el umbral');return}setMensaje(`Umbral actualizado: ${resultado.valorAnterior} → ${resultado.valorNuevo} días hábiles.`);setConfigurar(false);setVersion(v=>v+1)};
 return <div className="min-h-full bg-slate-50 p-5 lg:p-8"><div className="mx-auto max-w-7xl"><header className="mb-6 flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm font-semibold text-primary-600">Proveedores y egresos</p><h1 className="text-2xl font-bold">Cuentas por pagar</h1></div>{puedeConfigurar&&<button onClick={()=>setConfigurar(true)} title="Configurar umbral Por vencer" className="rounded-md border bg-white p-2.5 text-gray-700"><Settings2 className="h-5 w-5"/></button>}</header>{(error||mensaje)&&<div className={`mb-4 rounded-md border p-3 text-sm ${error?'border-red-200 bg-red-50 text-red-700':'border-emerald-200 bg-emerald-50 text-emerald-700'}`}>{error||mensaje}</div>}
 <section className="mb-5 grid gap-3 border-y bg-white p-4 md:grid-cols-3 lg:grid-cols-6"><input aria-label="Buscar" value={filtros.busqueda} onChange={e=>cambiar('busqueda',e.target.value)} placeholder="Proveedor, identificación o folio" className="rounded-md border px-3 py-2 lg:col-span-2"/><select aria-label="Condición temporal" value={filtros.estadoTemporal} onChange={e=>cambiar('estadoTemporal',e.target.value)} className="rounded-md border px-3"><option value="todos">Todos los vencimientos</option><option value="por_pagar">Por pagar</option><option value="por_vencer">Por vencer</option><option value="vencida">Vencida</option></select><select aria-label="Estado de pago" value={filtros.estadoPago} onChange={e=>cambiar('estadoPago',e.target.value)} className="rounded-md border px-3"><option value="todos">Todos los pagos</option><option value="pendiente">Pendiente</option><option value="parcial">Parcial</option><option value="pagada">Pagada</option></select><select aria-label="Proveedor" value={filtros.proveedor} onChange={e=>cambiar('proveedor',e.target.value)} className="rounded-md border px-3"><option value="">Todos los proveedores</option>{proveedores.map(p=><option key={p.id} value={p.id}>{p.razonSocial}</option>)}</select><div className="flex"><select aria-label="Ordenar" value={filtros.ordenar} onChange={e=>cambiar('ordenar',e.target.value)} className="min-w-0 flex-1 rounded-l-md border px-2"><option value="proveedor">Proveedor</option><option value="fechaEmision">Emisión</option><option value="fechaVencimiento">Vencimiento</option><option value="saldoPendiente">Saldo</option><option value="montoOriginal">Monto</option></select><button title="Cambiar dirección" onClick={()=>cambiar('direccion',filtros.direccion==='asc'?'desc':'asc')} className="rounded-r-md border border-l-0 px-2"><ArrowDownUp className="h-4 w-4"/></button></div></section>
 <div className="overflow-hidden rounded-md border bg-white"><div className="overflow-x-auto"><table className="w-full min-w-[1100px] text-left text-sm"><thead className="border-b bg-gray-50"><tr><th className="p-3">Obligación</th><th>Proveedor</th><th>Documento</th><th>Emisión</th><th>Vencimiento</th><th>Condición temporal</th><th>Estado de pago</th><th className="text-right">Monto original</th><th className="pr-4 text-right">Saldo pendiente</th></tr></thead><tbody>{cuentas.map(c=><tr key={c.id} className="border-b"><td className="p-3 font-semibold">OB-{c.id}</td><td><p>{c.proveedor.razonSocial}</p><p className="text-xs text-gray-500">{c.proveedor.identificadorFiscal}</p></td><td>{c.documento.tipo} {c.documento.folio}</td><td>{new Date(c.fechaEmision).toLocaleDateString('es-CL',{timeZone:'UTC'})}</td><td>{new Date(c.fechaVencimiento).toLocaleDateString('es-CL',{timeZone:'UTC'})}</td><td>{c.condicionTemporal||'Sin condición activa'}{c.requiereAtencion&&<AlertTriangle className="ml-2 inline h-4 w-4 text-amber-600"/>}</td><td>{c.estadoPago}</td><td className="text-right">{c.moneda} {c.montoOriginal.toLocaleString('es-CL')}</td><td className="pr-4 text-right font-semibold">{c.moneda} {c.saldoActual.toLocaleString('es-CL')}</td></tr>)}</tbody></table></div>{cargando&&<p className="p-10 text-center text-gray-500">Cargando obligaciones...</p>}{!cargando&&!cuentas.length&&<p className="p-10 text-center text-gray-500">No hay obligaciones para los filtros seleccionados.</p>}</div></div>
 {configurar&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/50 p-4"><div className="w-full max-w-md rounded-md bg-white"><div className="flex justify-between border-b p-4"><h2 className="font-bold">Umbral Por vencer</h2><button title="Cerrar" onClick={()=>setConfigurar(false)}><X/></button></div><label className="block p-5 text-sm font-medium">Días hábiles<input type="number" min="0" step="1" value={umbral} onChange={e=>setUmbral(e.target.value)} className="mt-1 w-full rounded-md border p-2.5"/></label><div className="flex justify-end gap-2 border-t p-4"><button onClick={()=>setConfigurar(false)} className="rounded-md border px-4 py-2">Cancelar</button><button onClick={()=>void guardarUmbral()} className="rounded-md bg-primary-600 px-4 py-2 font-semibold text-white">Guardar</button></div></div></div>}</div>;
}
