import { useEffect, useMemo, useState } from 'react';
import { AlertTriangle, ArrowDownUp, RefreshCw, Scale, Settings2, X } from 'lucide-react';
import { solicitarFinanzas } from '../../api/finanzas';
import { usarSesion } from '../../seguridad/Sesion';

interface Cuenta {id:number;proveedor:{id:number;razonSocial:string;identificadorFiscal:string};documento:{id:number;folio:string;tipo:string};moneda:string;montoOriginal:number;saldoActual:number;fechaEmision:string;fechaVencimiento:string;condicionTemporal:string|null;estadoPago:string;tipoCambio:number|null;requiereAtencion:boolean}
interface Credito {id:number;moneda:string;folio:string;montoDisponible:number;estado:string}
interface Propuesta {idSaldoFavor:number;montoDisponible:number;distribuciones:Array<{idObligacion:number;monto:number;saldoObligacion:number;condicionTemporal:string|null}>}
interface Compensacion {id:number;estado:string;total:number;distribuciones:Array<{id:number;idObligacion:number;monto:number;montoRevertido:number}>}
async function api(ruta:string,opciones?:RequestInit){const respuesta=await solicitarFinanzas(ruta,opciones);const resultado=await respuesta.json();if(!respuesta.ok)throw new Error(resultado.error||'No fue posible consultar cuentas por pagar');return resultado}
const json=(method:string,body?:unknown):RequestInit=>({method,headers:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});
const leerArchivo=async(file:File)=>new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>reject(new Error('No fue posible leer el archivo'));reader.readAsDataURL(file)});

export default function CuentasPorPagar(){
 const {sesion}=usarSesion();const puede=(cu:string)=>!!sesion?.permisos.includes(cu);const [cuentas,setCuentas]=useState<Cuenta[]>([]);const [filtros,setFiltros]=useState({estadoTemporal:'todos',estadoPago:'todos',proveedor:'',busqueda:'',ordenar:'fechaVencimiento',direccion:'asc'});const [version,setVersion]=useState(0);const [error,setError]=useState('');const [cargando,setCargando]=useState(true);const [configurar,setConfigurar]=useState(false);const [umbral,setUmbral]=useState('5');const [mensaje,setMensaje]=useState('');const [proveedorCompensacion,setProveedorCompensacion]=useState<Cuenta['proveedor']|null>(null);const [creditos,setCreditos]=useState<Credito[]>([]);const [propuesta,setPropuesta]=useState<Propuesta|null>(null);const [compensaciones,setCompensaciones]=useState<Compensacion[]>([]);
 const puedeConfigurar=!!sesion?.permisos.includes('CU110')&&sesion.configuracion==='gerencia'&&sesion.administrador;
 useEffect(()=>{const espera=window.setTimeout(()=>{const p=new URLSearchParams();Object.entries(filtros).forEach(([k,v])=>{if(v)p.set(k,v)});setCargando(true);api(`/cuentas-por-pagar?${p}`).then(setCuentas).catch(e=>setError(e.message)).finally(()=>setCargando(false));},200);return()=>window.clearTimeout(espera)},[filtros,version]);
 useEffect(()=>{api('/configuracion/umbral-por-vencer-proveedores').then(r=>setUmbral(String(r.diasHabiles))).catch(()=>undefined)},[version]);
 const proveedores=useMemo(()=>[...new Map(cuentas.map(c=>[c.proveedor.id,c.proveedor])).values()].sort((a,b)=>a.razonSocial.localeCompare(b.razonSocial,'es-CL')),[cuentas]);
 const cambiar=(campo:string,valor:string)=>setFiltros(actual=>({...actual,[campo]:valor}));
 const guardarUmbral=async()=>{setError('');const respuesta=await solicitarFinanzas('/configuracion/umbral-por-vencer-proveedores',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({diasHabiles:Number(umbral)})});const resultado=await respuesta.json();if(!respuesta.ok){setError(resultado.error||'No fue posible actualizar el umbral');return}setMensaje(`Umbral actualizado: ${resultado.valorAnterior} → ${resultado.valorNuevo} días hábiles.`);setConfigurar(false);setVersion(v=>v+1)};
 const abrirCompensacion=async(proveedor:Cuenta['proveedor'])=>{try{setProveedorCompensacion(proveedor);const [saldos,lista]=await Promise.all([api(`/proveedores/${proveedor.id}/saldos-favor`),puede('CU133')?api(`/proveedores/${proveedor.id}/compensaciones`):Promise.resolve([])]);setCreditos(saldos.saldos.filter((s:Credito)=>s.estado==='disponible'&&s.montoDisponible>0));setCompensaciones(lista)}catch(e){setError((e as Error).message)}};
 const proponer=async(idSaldoFavor:number)=>{try{setPropuesta(await api(`/proveedores/${proveedorCompensacion!.id}/compensaciones/propuesta`,json('POST',{idSaldoFavor})))}catch(e){setError((e as Error).message)}};
 const confirmarCompensacion=async()=>{if(!propuesta||!proveedorCompensacion)return;try{await api(`/proveedores/${proveedorCompensacion.id}/compensaciones`,json('POST',{idSaldoFavor:propuesta.idSaldoFavor,distribuciones:propuesta.distribuciones.map(d=>({idObligacion:d.idObligacion,monto:d.monto}))}));setMensaje('Compensación confirmada');setPropuesta(null);setVersion(v=>v+1);await abrirCompensacion(proveedorCompensacion)}catch(e){setError((e as Error).message)}};
 const revertir=async(compensacion:Compensacion,detalle:Compensacion['distribuciones'][number])=>{const monto=Number(window.prompt('Monto a revertir',String(detalle.monto-detalle.montoRevertido)));const motivo=window.prompt('Motivo obligatorio');if(!monto||!motivo)return;const input=document.createElement('input');input.type='file';input.onchange=async()=>{const file=input.files?.[0];if(!file)return;try{await api(`/compensaciones/${compensacion.id}/reversas`,json('POST',{motivo,nombreArchivo:file.name,contenido:await leerArchivo(file),distribuciones:[{idDetalle:detalle.id,monto}]}));setMensaje('Reversa registrada');await abrirCompensacion(proveedorCompensacion!);setVersion(v=>v+1)}catch(e){setError((e as Error).message)}};input.click()};
 return <div className="min-h-full bg-slate-50 p-5 lg:p-8"><div className="mx-auto max-w-7xl"><header className="mb-6 flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm font-semibold text-primary-600">Proveedores y egresos</p><h1 className="text-2xl font-bold">Cuentas por pagar</h1></div>{puedeConfigurar&&<button onClick={()=>setConfigurar(true)} title="Configurar umbral Por vencer" className="rounded-md border bg-white p-2.5 text-gray-700"><Settings2 className="h-5 w-5"/></button>}</header>{(error||mensaje)&&<div className={`mb-4 rounded-md border p-3 text-sm ${error?'border-red-200 bg-red-50 text-red-700':'border-emerald-200 bg-emerald-50 text-emerald-700'}`}>{error||mensaje}</div>}
 <section className="mb-5 grid gap-3 border-y bg-white p-4 md:grid-cols-3 lg:grid-cols-6"><input aria-label="Buscar" value={filtros.busqueda} onChange={e=>cambiar('busqueda',e.target.value)} placeholder="Proveedor, identificación o folio" className="rounded-md border px-3 py-2 lg:col-span-2"/><select aria-label="Condición temporal" value={filtros.estadoTemporal} onChange={e=>cambiar('estadoTemporal',e.target.value)} className="rounded-md border px-3"><option value="todos">Todos los vencimientos</option><option value="por_pagar">Por pagar</option><option value="por_vencer">Por vencer</option><option value="vencida">Vencida</option></select><select aria-label="Estado de pago" value={filtros.estadoPago} onChange={e=>cambiar('estadoPago',e.target.value)} className="rounded-md border px-3"><option value="todos">Todos los pagos</option><option value="pendiente">Pendiente</option><option value="parcial">Parcial</option><option value="pagada">Pagada</option></select><select aria-label="Proveedor" value={filtros.proveedor} onChange={e=>cambiar('proveedor',e.target.value)} className="rounded-md border px-3"><option value="">Todos los proveedores</option>{proveedores.map(p=><option key={p.id} value={p.id}>{p.razonSocial}</option>)}</select><div className="flex"><select aria-label="Ordenar" value={filtros.ordenar} onChange={e=>cambiar('ordenar',e.target.value)} className="min-w-0 flex-1 rounded-l-md border px-2"><option value="proveedor">Proveedor</option><option value="fechaEmision">Emisión</option><option value="fechaVencimiento">Vencimiento</option><option value="saldoPendiente">Saldo</option><option value="montoOriginal">Monto</option></select><button title="Cambiar dirección" onClick={()=>cambiar('direccion',filtros.direccion==='asc'?'desc':'asc')} className="rounded-r-md border border-l-0 px-2"><ArrowDownUp className="h-4 w-4"/></button></div></section>
 <div className="overflow-hidden rounded-md border bg-white"><div className="overflow-x-auto"><table className="w-full min-w-[1180px] text-left text-sm"><thead className="border-b bg-gray-50"><tr><th className="p-3">Obligación</th><th>Proveedor</th><th>Documento</th><th>Emisión</th><th>Vencimiento</th><th>Condición temporal</th><th>Estado de pago</th><th className="text-right">Monto original</th><th className="text-right">Saldo pendiente</th><th/></tr></thead><tbody>{cuentas.map(c=><tr key={c.id} className="border-b"><td className="p-3 font-semibold">OB-{c.id}</td><td><p>{c.proveedor.razonSocial}</p><p className="text-xs text-gray-500">{c.proveedor.identificadorFiscal}</p></td><td>{c.documento.tipo} {c.documento.folio}</td><td>{new Date(c.fechaEmision).toLocaleDateString('es-CL',{timeZone:'UTC'})}</td><td>{new Date(c.fechaVencimiento).toLocaleDateString('es-CL',{timeZone:'UTC'})}</td><td>{c.condicionTemporal||'Sin condición activa'}{c.requiereAtencion&&<AlertTriangle className="ml-2 inline h-4 w-4 text-amber-600"/>}</td><td>{c.estadoPago}</td><td className="text-right">{c.moneda} {c.montoOriginal.toLocaleString('es-CL')}</td><td className="text-right font-semibold">{c.moneda} {c.saldoActual.toLocaleString('es-CL')}</td><td>{puede('CU132')&&<button title="Compensar saldo a favor" onClick={()=>void abrirCompensacion(c.proveedor)} className="p-2 text-primary-700"><Scale className="h-4 w-4"/></button>}</td></tr>)}</tbody></table></div>{cargando&&<p className="p-10 text-center text-gray-500">Cargando obligaciones...</p>}{!cargando&&!cuentas.length&&<p className="p-10 text-center text-gray-500">No hay obligaciones para los filtros seleccionados.</p>}</div></div>
 {proveedorCompensacion&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/50 p-4"><div className="max-h-[90vh] w-full max-w-3xl overflow-y-auto bg-white"><div className="flex justify-between border-b p-4"><div><h2 className="font-bold">Compensaciones</h2><p className="text-sm text-gray-500">{proveedorCompensacion.razonSocial}</p></div><button title="Cerrar" onClick={()=>{setProveedorCompensacion(null);setPropuesta(null)}}><X/></button></div><section className="p-4"><h3 className="mb-2 font-semibold">Créditos disponibles</h3><div className="flex flex-wrap gap-2">{creditos.map(c=><button key={c.id} onClick={()=>void proponer(c.id)} className="border px-3 py-2 text-left"><strong>{c.moneda} {c.montoDisponible.toLocaleString('es-CL')}</strong><small className="block">NC {c.folio}</small></button>)}{!creditos.length&&<p className="text-sm text-gray-500">No hay crédito disponible.</p>}</div></section>{propuesta&&<section className="border-y bg-gray-50 p-4"><h3 className="mb-2 font-semibold">Distribución propuesta</h3>{propuesta.distribuciones.map((d,i)=><label key={d.idObligacion} className="mb-2 grid grid-cols-[1fr_140px] items-center gap-3 text-sm"><span>OB-{d.idObligacion} · {d.condicionTemporal} · saldo {d.saldoObligacion.toLocaleString('es-CL')}</span><input type="number" min="0.01" max={d.saldoObligacion} value={d.monto} onChange={e=>setPropuesta(p=>p?{...p,distribuciones:p.distribuciones.map((x,j)=>j===i?{...x,monto:Number(e.target.value)}:x)}:p)} className="border p-2"/></label>)}<div className="flex justify-end"><button onClick={()=>void confirmarCompensacion()} className="bg-primary-600 px-4 py-2 text-white">Confirmar compensación</button></div></section>}<section className="p-4"><div className="mb-2 flex items-center gap-2"><h3 className="font-semibold">Historial</h3><RefreshCw className="h-4 w-4"/></div>{compensaciones.map(c=><div key={c.id} className="mb-3 border p-3 text-sm"><strong>COMP-{c.id} · {c.estado} · {c.total.toLocaleString('es-CL')}</strong>{c.distribuciones.map(d=><div key={d.id} className="mt-2 flex justify-between"><span>OB-{d.idObligacion}: {d.monto.toLocaleString('es-CL')} · revertido {d.montoRevertido.toLocaleString('es-CL')}</span>{puede('CU133')&&d.montoRevertido<d.monto&&<button onClick={()=>void revertir(c,d)} className="text-amber-700 underline">Revertir</button>}</div>)}</div>)}</section></div></div>}
 {configurar&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/50 p-4"><div className="w-full max-w-md rounded-md bg-white"><div className="flex justify-between border-b p-4"><h2 className="font-bold">Umbral Por vencer</h2><button title="Cerrar" onClick={()=>setConfigurar(false)}><X/></button></div><label className="block p-5 text-sm font-medium">Días hábiles<input type="number" min="0" step="1" value={umbral} onChange={e=>setUmbral(e.target.value)} className="mt-1 w-full rounded-md border p-2.5"/></label><div className="flex justify-end gap-2 border-t p-4"><button onClick={()=>setConfigurar(false)} className="rounded-md border px-4 py-2">Cancelar</button><button onClick={()=>void guardarUmbral()} className="rounded-md bg-primary-600 px-4 py-2 font-semibold text-white">Guardar</button></div></div></div>}</div>;
}
