CREATE TABLE "finanzas"."relacion_laboral_empleado" (
  "id_relacion_laboral_empleado" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_empleado" INTEGER NOT NULL,
  "fecha_inicio" DATE NOT NULL,
  "fecha_termino" DATE,
  "estado" VARCHAR(20) NOT NULL DEFAULT 'vigente',
  "id_tipo_vinculo_laboral" INTEGER,
  "jornada" VARCHAR(80),
  CONSTRAINT "chk_relacion_laboral_estado" CHECK ("estado" IN ('vigente', 'terminada')),
  CONSTRAINT "chk_relacion_laboral_fechas" CHECK ("fecha_termino" IS NULL OR "fecha_termino" >= "fecha_inicio"),
  CONSTRAINT "fk_relacion_laboral_empleado" FOREIGN KEY ("id_empleado") REFERENCES "finanzas"."empleado"("id_empleado") ON DELETE RESTRICT,
  CONSTRAINT "fk_relacion_laboral_tipo_vinculo" FOREIGN KEY ("id_tipo_vinculo_laboral") REFERENCES "finanzas"."tipo_vinculo_laboral"("id_tipo_vinculo_laboral") ON DELETE RESTRICT
);

CREATE INDEX "idx_relacion_laboral_empleado_fecha"
ON "finanzas"."relacion_laboral_empleado" ("id_empleado", "fecha_inicio");

CREATE UNIQUE INDEX "uq_relacion_laboral_vigente_empleado"
ON "finanzas"."relacion_laboral_empleado" ("id_empleado")
WHERE "estado" = 'vigente' AND "fecha_termino" IS NULL;
