import { solicitarTexto } from '../../components/DialogosSistema';
import { useEffect,useState } from 'react';
import { AlertTriangle,Plus,RefreshCw } from 'lucide-react';
type Incidencia={id:string;descripcion:string;causaReferencia:string|null;responsabilidad:string|null;estado:string;ejecucion:{id:string;tarea:{titulo:string|null;idOrdenTrabajo:string|null}|null}};
const api=async(r:string,o?:RequestInit)=>{const x=await fetch(`/api/finanzas${r}`,{...o,credentials:'same-origin'}),d=await x.json();if(!x.ok)throw new Error(d.error||'Error');return d};
export default function IncidenciasTerreno(){
 const [items,setItems]=useState<Incidencia[]>([]),[error,setError]=useState(''),[nueva,setNueva]=useState({idEjecucion:'',descripcion:'',causaReferencia:'',responsabilidad:''});
 const cargar=async()=>setItems(await api('/terreno/incidencias'));useEffect(()=>{void cargar().catch(e=>setError(e.message))},[]);
 const crear=async()=>{try{await api(`/terreno/ejecuciones/${nueva.idEjecucion}/incidencias`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(nueva)});setNueva({idEjecucion:'',descripcion:'',causaReferencia:'',responsabilidad:''});await cargar()}catch(e){setError((e as Error).message)}};
 const actuar=async(i:Incidencia)=>{const accion=i.estado==='pendiente'?'corregir':'cerrar',causa=accion==='corregir'?await solicitarTexto('Causa o contexto',i.causaReferencia||''):i.causaReferencia,responsabilidad=accion==='corregir'?await solicitarTexto('Responsabilidad',i.responsabilidad||''):i.responsabilidad;if(accion==='corregir'&&!causa&&!responsabilidad)return;try{await api(`/terreno/incidencias/${i.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({accion,causaReferencia:causa,responsabilidad,confirmado:accion==='cerrar'})});await cargar()}catch(e){setError((e as Error).message)}};
 return <div className="min-h-full bg-gray-50 p-6"><div className="mx-auto max-w-5xl"><header className="mb-6 flex justify-between"><h1 className="flex items-center gap-2 text-2xl font-bold"><AlertTriangle/>Incidencias y retrabajos</h1><button title="Actualizar" onClick={()=>void cargar()} className="rounded border p-2"><RefreshCw className="h-4 w-4"/></button></header>{error&&<p className="mb-4 bg-red-50 p-3 text-red-700">{error}</p>}<section className="mb-5 grid gap-2 border-y bg-white p-4 md:grid-cols-5"><input placeholder="ID ejecución" value={nueva.idEjecucion} onChange={e=>setNueva({...nueva,idEjecucion:e.target.value})} className="rounded border p-2"/><input placeholder="Descripción" value={nueva.descripcion} onChange={e=>setNueva({...nueva,descripcion:e.target.value})} className="rounded border p-2"/><input placeholder="Causa opcional" value={nueva.causaReferencia} onChange={e=>setNueva({...nueva,causaReferencia:e.target.value})} className="rounded border p-2"/><input placeholder="Responsabilidad opcional" value={nueva.responsabilidad} onChange={e=>setNueva({...nueva,responsabilidad:e.target.value})} className="rounded border p-2"/><button onClick={()=>void crear()} className="flex items-center justify-center gap-2 rounded bg-black px-3 text-white"><Plus className="h-4 w-4"/>Registrar</button></section><div className="border-y bg-white">{items.map(i=><div key={i.id} className="flex items-center justify-between gap-4 border-b p-4"><div><strong>{i.descripcion}</strong><p className="text-sm text-gray-500">{i.ejecucion.tarea?.titulo||`Ejecución ${i.ejecucion.id}`} · OT {i.ejecucion.tarea?.idOrdenTrabajo||'sin vínculo'} · {i.causaReferencia||'sin causa'} · {i.responsabilidad||'sin responsabilidad'}</p></div><div className="flex items-center gap-3"><span className="font-semibold">{i.estado}</span>{i.estado!=='cerrada'&&<button onClick={()=>void actuar(i)} className="rounded border px-3 py-2">{i.estado==='pendiente'?'Marcar corregida':'Validar y cerrar'}</button>}</div></div>)}</div></div></div>;
}
