import { useEffect, useMemo, useState } from 'react';
import { AlertTriangle, Ban, CheckCircle2, FileClock, FileUp, Plus, RefreshCw, RotateCcw, Save, Search, Send, Trash2, WalletCards } from 'lucide-react';
import { solicitarFinanzas } from '../../api/finanzas';
import { usarSesion } from '../../seguridad/Sesion';

interface Obligacion { id:number; moneda:string; saldoActual:number; montoOriginal:number; fechaVencimiento:string }
interface Proveedor { id:number; razonSocial:string; identificadorFiscal:string; obligaciones:Obligacion[] }
interface Medio { id:number; nombre:string }
interface Movimiento {
  id:number; idObligacion:number; idMedioPago:number; medioPago:string; moneda:string; montoAplicado:number; saldoActual:number;
  conflictoSaldo:boolean; tasaReferencia:number|null; fuenteTasa?:string|null; tasaBancariaEfectiva:number|null; equivalenteClp:number|null;
  estado:string; montoAnulado:number; montoRevertido:number; montoNetoVigente:number; tieneRespaldo?:boolean;
  conciliacion:{estado:string;observacion:string|null;usuario:string|null;fecha:string|null}; respaldos:Array<{id:number;nombre:string}>;
  anulacion?:{monto:number;motivo:string;fecha:string;respaldo?:string}|null; reversas?:Array<{id:number;monto:number;motivo:string;fecha:string;respaldo?:string}>;
}
interface Operacion {
  id:number; estado:string; estadoAgregado?:string; fechaEfectivaPago:string|null; proveedor:{id:number;razonSocial:string;identificadorFiscal:string;estado?:string};
  total:number; totalConfirmado?:number|null; tieneRespaldo:boolean; movimientos:Movimiento[]; respaldos?:Array<{id:number;nombre:string}>;
  preparadoPor?:string|null; confirmadoPor?:string|null; fechaConfirmacion?:string|null;
  historialRespaldos?:Array<{id:number;idMovimiento:number|null;anterior:{id:number;nombre?:string};nuevo:{id:number;nombre?:string};motivo:string;usuario:string;fecha:string}>;
}

async function api(ruta:string, opciones?:RequestInit){const respuesta=await solicitarFinanzas(ruta,opciones);const resultado=await respuesta.json();if(!respuesta.ok)throw new Error(resultado.error||'No fue posible completar la operación');return resultado}
const json=(method:string,body?:unknown):RequestInit=>({method,headers:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});
const fechaHoy=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Santiago',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const leerArchivo=async(file:File)=>new Promise<string>((resolver,rechazar)=>{const lector=new FileReader();lector.onload=()=>resolver(String(lector.result));lector.onerror=()=>rechazar(new Error('No fue posible leer el archivo'));lector.readAsDataURL(file)});
const fechaHora=(valor?:string|null)=>valor?new Date(valor).toLocaleString('es-CL'):'No disponible';

export default function PagosProveedores(){
  const {sesion}=usarSesion(); const puede=(cu:string)=>!!sesion?.permisos.includes(cu);
  const [modo,setModo]=useState<'registrar'|'confirmados'>('registrar'); const [busqueda,setBusqueda]=useState(''); const [proveedores,setProveedores]=useState<Proveedor[]>([]); const [medios,setMedios]=useState<Medio[]>([]);
  const [borradores,setBorradores]=useState<Operacion[]>([]); const [confirmados,setConfirmados]=useState<Operacion[]>([]); const [proveedor,setProveedor]=useState<Proveedor|null>(null); const [operacion,setOperacion]=useState<Operacion|null>(null);
  const [fechaPago,setFechaPago]=useState(fechaHoy()); const [movimiento,setMovimiento]=useState({idObligacion:'',idMedioPago:'',montoAplicado:'',tasaBancariaEfectiva:''}); const [archivo,setArchivo]=useState<File|null>(null);
  const [accion,setAccion]=useState<{tipo:'anular-operacion'|'anular'|'revertir'|'conciliar';movimiento?:Movimiento}|null>(null); const [motivo,setMotivo]=useState(''); const [monto,setMonto]=useState(''); const [resultado,setResultado]=useState<'conciliado'|'con_discrepancia'>('conciliado'); const [observacion,setObservacion]=useState(''); const [archivoPost,setArchivoPost]=useState<File|null>(null);
  const [reemplazo,setReemplazo]=useState<{id:number;nombre:string}|null>(null); const [archivoReemplazo,setArchivoReemplazo]=useState<File|null>(null); const [motivoReemplazo,setMotivoReemplazo]=useState('');
  const [error,setError]=useState(''); const [mensaje,setMensaje]=useState(''); const [cargando,setCargando]=useState(false);
  const obligaciones=useMemo(()=>proveedor?.obligaciones||[],[proveedor]);
  const cargarBorradores=()=>api('/pagos-proveedores/borradores').then(setBorradores).catch(e=>setError(e.message));
  const cargarConfirmados=()=>puede('CU123')?api('/pagos-proveedores/confirmados').then(setConfirmados).catch(e=>setError(e.message)):Promise.resolve();
  useEffect(()=>{api('/pagos-proveedores/catalogos').then(r=>setMedios(r.medios)).catch(e=>setError(e.message));void cargarBorradores()},[]);
  useEffect(()=>{const espera=window.setTimeout(()=>api(`/pagos-proveedores/proveedores?busqueda=${encodeURIComponent(busqueda)}`).then(setProveedores).catch(e=>setError(e.message)),200);return()=>window.clearTimeout(espera)},[busqueda]);
  const ejecutar=async(consulta:()=>Promise<Operacion>,textoExito:string)=>{setCargando(true);setError('');setMensaje('');try{const actual=await consulta();setOperacion(actual);setMensaje(textoExito);await Promise.all([cargarBorradores(),cargarConfirmados()])}catch(e){setError(e instanceof Error?e.message:'No fue posible completar la operación')}finally{setCargando(false)}};
  const crear=async(p:Proveedor)=>{setProveedor(p);await ejecutar(()=>api('/pagos-proveedores',json('POST',{idProveedor:p.id,fechaEfectivaPago:fechaPago})),'Borrador creado')};
  const agregar=()=>operacion&&ejecutar(()=>api(`/pagos-proveedores/${operacion.id}/movimientos`,json('POST',{...movimiento,idObligacion:Number(movimiento.idObligacion),idMedioPago:Number(movimiento.idMedioPago),montoAplicado:Number(movimiento.montoAplicado),tasaBancariaEfectiva:movimiento.tasaBancariaEfectiva?Number(movimiento.tasaBancariaEfectiva):undefined})),'Movimiento agregado').then(()=>setMovimiento({idObligacion:'',idMedioPago:'',montoAplicado:'',tasaBancariaEfectiva:''}));
  const adjuntar=async()=>{if(!operacion||!archivo)return;const contenido=await leerArchivo(archivo);await ejecutar(()=>api(`/pagos-proveedores/${operacion.id}/respaldos`,json('POST',{nombreArchivo:archivo.name,contenido,operacion:true,movimientos:operacion.movimientos.map(m=>m.id)})),'Respaldo asociado');setArchivo(null)};
  const retomar=async(borrador:Operacion)=>{setCargando(true);try{const actual=await api(`/pagos-proveedores/${borrador.id}/retomar`,json('POST'));setOperacion(actual);setFechaPago(actual.fechaEfectivaPago?.slice(0,10)||fechaHoy());const lista:Proveedor[]=await api(`/pagos-proveedores/proveedores?busqueda=${encodeURIComponent(actual.proveedor.identificadorFiscal)}`);setProveedor(lista.find(p=>p.id===actual.proveedor.id)||null)}catch(e){setError(e instanceof Error?e.message:'No fue posible retomar el borrador')}finally{setCargando(false)}};
  const abrirDetalle=async(id:number)=>{setCargando(true);setError('');try{setOperacion(await api(`/pagos-proveedores/${id}/detalle`));setModo('confirmados')}catch(e){setError(e instanceof Error?e.message:'No fue posible consultar el pago')}finally{setCargando(false)}};
  const tasaManual=async(m:Movimiento)=>{if(!operacion)return;const tasa=window.prompt('Tasa de referencia manual');if(!tasa)return;const justificacion=window.prompt('Justificación de la tasa manual');if(!justificacion)return;await ejecutar(()=>api(`/pagos-proveedores/${operacion.id}/movimientos/${m.id}/tipo-cambio-manual`,json('POST',{tasaReferencia:Number(tasa),justificacion})),'Tasa manual registrada')};
  const confirmarAccion=async()=>{if(!operacion||!accion)return;let ruta='';let cuerpo:Record<string,unknown>={};if(accion.tipo==='conciliar'){ruta=`/pagos-proveedores/${operacion.id}/movimientos/${accion.movimiento!.id}/conciliar`;cuerpo={resultado,observacion}}else{if(!archivoPost)return setError('Selecciona el respaldo obligatorio');const contenido=await leerArchivo(archivoPost);cuerpo={motivo,nombreArchivo:archivoPost.name,contenido,...(accion.tipo==='revertir'?{monto:Number(monto)}:{})};ruta=accion.tipo==='anular-operacion'?`/pagos-proveedores/${operacion.id}/anular`:`/pagos-proveedores/${operacion.id}/movimientos/${accion.movimiento!.id}/${accion.tipo==='anular'?'anular':'reversas'}`}await ejecutar(()=>api(ruta,json('POST',cuerpo)),accion.tipo==='conciliar'?'Conciliación registrada':accion.tipo==='revertir'?'Devolución registrada':'Anulación registrada');setAccion(null);setMotivo('');setMonto('');setObservacion('');setArchivoPost(null)};
  const confirmarReemplazo=async()=>{if(!operacion||!reemplazo||!archivoReemplazo||!motivoReemplazo)return;const contenido=await leerArchivo(archivoReemplazo);await ejecutar(()=>api(`/pagos-proveedores/${operacion.id}/respaldos/${reemplazo.id}/reemplazar`,json('POST',{nombreArchivo:archivoReemplazo.name,contenido,motivo:motivoReemplazo})),'Respaldo reemplazado con trazabilidad');setReemplazo(null);setArchivoReemplazo(null);setMotivoReemplazo('')};
  const cerrar=()=>{setOperacion(null);setProveedor(null);setMovimiento({idObligacion:'',idMedioPago:'',montoAplicado:'',tasaBancariaEfectiva:''});setMensaje('');setAccion(null)};
  const confirmado=operacion?.estado==='confirmada';
  return <div className="min-h-full bg-slate-50 p-5 lg:p-8"><div className="mx-auto max-w-7xl">
    <header className="mb-5 flex flex-wrap items-center justify-between gap-4"><div className="flex items-center gap-3"><WalletCards className="h-7 w-7 text-primary-600"/><div><p className="text-sm font-semibold text-primary-600">Proveedores y egresos</p><h1 className="text-2xl font-bold">Pagos a proveedores</h1></div></div><div className="inline-flex border bg-white p-1"><button onClick={()=>{setModo('registrar');cerrar()}} className={`px-4 py-2 text-sm font-medium ${modo==='registrar'?'bg-primary-600 text-white':''}`}>Registrar</button>{puede('CU123')&&<button onClick={()=>{setModo('confirmados');cerrar();void cargarConfirmados()}} className={`px-4 py-2 text-sm font-medium ${modo==='confirmados'?'bg-primary-600 text-white':''}`}>Confirmados</button>}</div></header>
    {(error||mensaje)&&<div className={`mb-4 border p-3 text-sm ${error?'border-red-200 bg-red-50 text-red-700':'border-emerald-200 bg-emerald-50 text-emerald-700'}`}>{error||mensaje}</div>}
    {modo==='registrar'&&!operacion&&<div className="grid gap-6 lg:grid-cols-[1.3fr_1fr]"><section className="border bg-white"><div className="flex items-center gap-2 border-b p-4"><Search className="h-4 w-4"/><input value={busqueda} onChange={e=>setBusqueda(e.target.value)} placeholder="Razón social o identificación fiscal" className="w-full border-0 outline-none"/></div><div className="divide-y">{proveedores.map(p=><button key={p.id} onClick={()=>void crear(p)} className="flex w-full items-center justify-between p-4 text-left hover:bg-gray-50"><span><strong className="block">{p.razonSocial}</strong><small className="text-gray-500">{p.identificadorFiscal} · {p.obligaciones.length} obligaciones</small></span><Plus className="h-5 w-5 text-primary-600"/></button>)}{!proveedores.length&&<p className="p-8 text-center text-sm text-gray-500">No hay proveedores elegibles.</p>}</div></section><section className="border bg-white"><div className="flex items-center justify-between border-b p-4"><h2 className="font-semibold">Borradores</h2><button title="Actualizar borradores" onClick={()=>void cargarBorradores()}><RefreshCw className="h-4 w-4"/></button></div><div className="divide-y">{borradores.map(b=><button key={b.id} disabled={b.estado!=='borrador'} onClick={()=>void retomar(b)} className="w-full p-4 text-left disabled:cursor-not-allowed disabled:bg-gray-50"><strong>OP-{b.id} · {b.proveedor.razonSocial}</strong><p className="text-sm text-gray-500">{b.estado} · {b.total.toLocaleString('es-CL')}</p></button>)}{!borradores.length&&<p className="p-8 text-center text-sm text-gray-500">No hay borradores pendientes.</p>}</div></section></div>}
    {modo==='confirmados'&&!operacion&&<section className="border bg-white"><div className="flex items-center justify-between border-b p-4"><h2 className="font-semibold">Operaciones confirmadas</h2><button title="Actualizar operaciones" onClick={()=>void cargarConfirmados()}><RefreshCw className="h-4 w-4"/></button></div><div className="divide-y">{confirmados.map(item=><button key={item.id} onClick={()=>void abrirDetalle(item.id)} className="flex w-full flex-wrap items-center justify-between gap-2 p-4 text-left hover:bg-gray-50"><span><strong className="block">OP-{item.id} · {item.proveedor.razonSocial}</strong><small className="text-gray-500">{fechaHora(item.fechaConfirmacion)} · {item.movimientos.length} movimientos</small></span><span className="font-semibold">{item.estadoAgregado||item.estado}</span></button>)}{!confirmados.length&&<p className="p-8 text-center text-sm text-gray-500">No hay operaciones confirmadas.</p>}</div></section>}
    {operacion&&<div className="space-y-5"><section className="border bg-white p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs uppercase text-gray-500">Operación OP-{operacion.id}</p><h2 className="text-lg font-bold">{operacion.proveedor.razonSocial}</h2><p className="text-sm text-gray-500">{operacion.proveedor.identificadorFiscal} · {operacion.estadoAgregado||operacion.estado}</p></div><label className="text-sm font-medium">Fecha efectiva<input type="date" value={operacion.fechaEfectivaPago?.slice(0,10)||fechaPago} onChange={e=>setFechaPago(e.target.value)} disabled={operacion.estado!=='borrador'} className="ml-2 border p-2"/></label></div>{confirmado&&<div className="mt-4 grid gap-3 border-t pt-4 text-sm sm:grid-cols-3"><p><span className="block text-gray-500">Preparador</span>{operacion.preparadoPor||'No disponible'}</p><p><span className="block text-gray-500">Confirmante</span>{operacion.confirmadoPor||'No disponible'}</p><p><span className="block text-gray-500">Confirmación</span>{fechaHora(operacion.fechaConfirmacion)}</p></div>}</section>
      {operacion.estado==='borrador'&&<section className="grid gap-3 border-y bg-white p-4 md:grid-cols-2 lg:grid-cols-5"><select value={movimiento.idObligacion} onChange={e=>setMovimiento(v=>({...v,idObligacion:e.target.value}))} className="border p-2"><option value="">Obligación</option>{obligaciones.map(o=><option key={o.id} value={o.id}>OB-{o.id} · {o.moneda} {o.saldoActual.toLocaleString('es-CL')}</option>)}</select><select value={movimiento.idMedioPago} onChange={e=>setMovimiento(v=>({...v,idMedioPago:e.target.value}))} className="border p-2"><option value="">Medio de pago</option>{medios.map(m=><option key={m.id} value={m.id}>{m.nombre}</option>)}</select><input type="number" min="0.01" step="0.01" value={movimiento.montoAplicado} onChange={e=>setMovimiento(v=>({...v,montoAplicado:e.target.value}))} placeholder="Monto aplicado" className="border p-2"/><input type="number" min="0.0001" step="0.0001" value={movimiento.tasaBancariaEfectiva} onChange={e=>setMovimiento(v=>({...v,tasaBancariaEfectiva:e.target.value}))} placeholder="Tasa bancaria opcional" className="border p-2"/><button disabled={cargando||!movimiento.idObligacion||!movimiento.idMedioPago||!movimiento.montoAplicado} onClick={()=>void agregar()} className="flex items-center justify-center gap-2 bg-primary-600 px-4 py-2 font-semibold text-white disabled:opacity-40"><Plus className="h-4 w-4"/>Agregar</button></section>}
      <section className="overflow-hidden border bg-white"><div className="overflow-x-auto"><table className="w-full min-w-[1100px] text-left text-sm"><thead className="border-b bg-gray-50"><tr><th className="p-3">Obligación</th><th>Medio</th><th>Moneda</th><th className="text-right">Original</th><th className="text-right">Revertido</th><th className="text-right">Anulado</th><th className="text-right">Neto vigente</th><th>Estado</th><th>Conciliación</th><th className="pr-3">Acciones</th></tr></thead><tbody>{operacion.movimientos.map(m=><tr key={m.id} className={m.conflictoSaldo?'border-b bg-red-50':'border-b'}><td className="p-3 font-semibold">OB-{m.idObligacion}</td><td>{m.medioPago}</td><td>{m.moneda}</td><td className="text-right">{m.montoAplicado.toLocaleString('es-CL')}</td><td className="text-right">{(m.montoRevertido||0).toLocaleString('es-CL')}</td><td className="text-right">{(m.montoAnulado||0).toLocaleString('es-CL')}</td><td className="text-right font-semibold">{(m.montoNetoVigente??m.montoAplicado).toLocaleString('es-CL')}</td><td>{m.estado}</td><td>{m.conciliacion?.estado||'pendiente'}{m.conciliacion?.observacion&&<small className="block max-w-52 text-gray-500">{m.conciliacion.observacion}</small>}</td><td className="pr-3"><div className="flex gap-1">{operacion.estado==='borrador'&&m.moneda!=='CLP'&&!m.tasaReferencia&&puede('CU115')&&<button title="Ingresar tasa" onClick={()=>void tasaManual(m)} className="px-2 text-primary-700 underline">Tasa</button>}{confirmado&&puede('CU124')&&m.montoNetoVigente>0&&<button title="Anular movimiento" onClick={()=>setAccion({tipo:'anular',movimiento:m})} className="p-2 text-red-700"><Ban className="h-4 w-4"/></button>}{confirmado&&puede('CU125')&&m.montoNetoVigente>0&&<button title="Registrar devolución" onClick={()=>setAccion({tipo:'revertir',movimiento:m})} className="p-2 text-amber-700"><RotateCcw className="h-4 w-4"/></button>}{confirmado&&puede('CU126')&&<button title="Conciliar movimiento" onClick={()=>setAccion({tipo:'conciliar',movimiento:m})} className="p-2 text-emerald-700"><CheckCircle2 className="h-4 w-4"/></button>}</div></td></tr>)}</tbody></table></div>{!operacion.movimientos.length&&<p className="p-8 text-center text-sm text-gray-500">Agrega al menos un movimiento.</p>}<div className="flex justify-end border-t p-4 text-lg font-bold">Total original: {operacion.total.toLocaleString('es-CL')}</div></section>
      {operacion.estado==='borrador'&&<section className="flex flex-wrap items-center gap-3 border bg-white p-4"><input type="file" onChange={e=>setArchivo(e.target.files?.[0]||null)} className="min-w-0 flex-1 text-sm"/><button disabled={!archivo||!operacion.movimientos.length} onClick={()=>void adjuntar()} className="flex items-center gap-2 border px-4 py-2 disabled:opacity-40"><FileUp className="h-4 w-4"/>Asociar a operación y movimientos</button></section>}
      {confirmado&&<section className="border bg-white"><div className="flex items-center gap-2 border-b p-4"><FileClock className="h-4 w-4"/><h3 className="font-semibold">Respaldos e historial</h3></div><div className="divide-y text-sm">{[...(operacion.respaldos||[]),...operacion.movimientos.flatMap(m=>m.respaldos||[])].filter((r,i,t)=>t.findIndex(x=>x.id===r.id)===i).map(r=><div key={r.id} className="flex items-center justify-between gap-3 p-3"><span>{r.nombre}</span>{puede('CU127')&&<button onClick={()=>setReemplazo(r)} className="border px-3 py-1.5">Reemplazar</button>}</div>)}{operacion.historialRespaldos?.map(h=><div key={`h-${h.id}`} className="p-3 text-gray-600"><strong>{h.anterior.nombre||`Respaldo ${h.anterior.id}`}</strong> → <strong>{h.nuevo.nombre||`Respaldo ${h.nuevo.id}`}</strong><span className="block text-xs">{h.motivo} · {fechaHora(h.fecha)}</span></div>)}</div></section>}
      {confirmado&&reemplazo&&<section className="border border-amber-300 bg-amber-50 p-4"><h3 className="mb-3 font-semibold">Reemplazar {reemplazo.nombre}</h3><div className="grid gap-3 md:grid-cols-2"><input value={motivoReemplazo} onChange={e=>setMotivoReemplazo(e.target.value)} placeholder="Motivo obligatorio" className="border p-2"/><input type="file" onChange={e=>setArchivoReemplazo(e.target.files?.[0]||null)} className="border bg-white p-2 text-sm"/></div><div className="mt-3 flex justify-end gap-2"><button onClick={()=>setReemplazo(null)} className="border px-4 py-2">Cancelar</button><button disabled={!motivoReemplazo||!archivoReemplazo||cargando} onClick={()=>void confirmarReemplazo()} className="bg-primary-600 px-4 py-2 font-semibold text-white disabled:opacity-40">Confirmar reemplazo</button></div></section>}
      {confirmado&&accion&&<section className="border border-amber-300 bg-amber-50 p-4"><div className="mb-3 flex items-start gap-2"><AlertTriangle className="mt-0.5 h-5 w-5 text-amber-700"/><div><h3 className="font-semibold">{accion.tipo==='conciliar'?'Conciliar movimiento':accion.tipo==='revertir'?'Registrar devolución':'Anular pago'}</h3><p className="text-sm text-gray-600">{accion.tipo==='revertir'?'El pago sí ocurrió y el proveedor devolvió dinero.':'La anulación declara que el pago registrado no ocurrió.'}</p></div></div>{accion.tipo==='conciliar'?<div className="grid gap-3 md:grid-cols-2"><select value={resultado} onChange={e=>setResultado(e.target.value as typeof resultado)} className="border p-2"><option value="conciliado">Conciliado</option><option value="con_discrepancia">Con discrepancia</option></select><input value={observacion} onChange={e=>setObservacion(e.target.value)} placeholder="Observación" className="border p-2"/></div>:<div className="grid gap-3 md:grid-cols-3">{accion.tipo==='revertir'&&<input type="number" min="0.01" max={accion.movimiento?.montoNetoVigente} step="0.01" value={monto} onChange={e=>setMonto(e.target.value)} placeholder="Monto devuelto" className="border p-2"/>}<input value={motivo} onChange={e=>setMotivo(e.target.value)} placeholder="Motivo obligatorio" className="border p-2"/><input type="file" onChange={e=>setArchivoPost(e.target.files?.[0]||null)} className="border bg-white p-2 text-sm"/></div>}<div className="mt-3 flex justify-end gap-2"><button onClick={()=>setAccion(null)} className="border px-4 py-2">Cancelar</button><button disabled={cargando||(accion.tipo==='revertir'&&!monto)||(accion.tipo!=='conciliar'&&(!motivo||!archivoPost))||(accion.tipo==='conciliar'&&resultado==='con_discrepancia'&&!observacion)} onClick={()=>void confirmarAccion()} className="bg-primary-600 px-4 py-2 font-semibold text-white disabled:opacity-40">Confirmar</button></div></section>}
      <div className="flex flex-wrap justify-end gap-2"><button onClick={cerrar} className="border px-4 py-2">Cerrar</button>{operacion.estado==='borrador'&&<><button onClick={()=>void ejecutar(()=>api(`/pagos-proveedores/${operacion.id}/guardar-borrador`,json('POST',{fechaEfectivaPago:fechaPago})),'Borrador guardado')} className="flex items-center gap-2 border px-4 py-2"><Save className="h-4 w-4"/>Guardar</button><button onClick={()=>void ejecutar(()=>api(`/pagos-proveedores/${operacion.id}/descartar`,json('POST')),'Borrador descartado')} className="flex items-center gap-2 border border-red-300 px-4 py-2 text-red-700"><Trash2 className="h-4 w-4"/>Descartar</button><button onClick={()=>void ejecutar(()=>api(`/pagos-proveedores/${operacion.id}/preparar`,json('POST')),'Operación preparada')} className="flex items-center gap-2 bg-primary-600 px-4 py-2 font-semibold text-white"><Send className="h-4 w-4"/>Preparar</button></>}{operacion.estado==='preparada'&&puede('CU120')&&<button onClick={()=>void ejecutar(()=>api(`/pagos-proveedores/${operacion.id}/confirmar`,json('POST')),'Pago confirmado')} className="bg-emerald-700 px-4 py-2 font-semibold text-white">Confirmar pago</button>}{confirmado&&puede('CU124')&&operacion.movimientos.some(m=>m.montoNetoVigente>0)&&<button onClick={()=>setAccion({tipo:'anular-operacion'})} className="flex items-center gap-2 border border-red-300 px-4 py-2 text-red-700"><Ban className="h-4 w-4"/>Anular operación</button>}</div>
    </div>}
  </div></div>;
}
