import { useEffect, useMemo, useState } from 'react';
import { FileUp, Plus, RefreshCw, Save, Search, Send, Trash2, WalletCards } from 'lucide-react';
import { solicitarFinanzas } from '../../api/finanzas';
import { usarSesion } from '../../seguridad/Sesion';

interface Obligacion { id:number; moneda:string; saldoActual:number; montoOriginal:number; fechaVencimiento:string }
interface Proveedor { id:number; razonSocial:string; identificadorFiscal:string; obligaciones:Obligacion[] }
interface Medio { id:number; nombre:string }
interface Movimiento { id:number; idObligacion:number; idMedioPago:number; medioPago:string; moneda:string; montoAplicado:number; saldoActual:number; conflictoSaldo:boolean; tasaReferencia:number|null; tasaBancariaEfectiva:number|null; equivalenteClp:number|null; tieneRespaldo:boolean }
interface Operacion { id:number; estado:string; fechaEfectivaPago:string|null; proveedor:{id:number;razonSocial:string;identificadorFiscal:string}; total:number; tieneRespaldo:boolean; movimientos:Movimiento[] }

async function api(ruta:string, opciones?:RequestInit){
  const respuesta=await solicitarFinanzas(ruta,opciones);const resultado=await respuesta.json();
  if(!respuesta.ok)throw new Error(resultado.error||'No fue posible completar la operación');return resultado;
}
const json=(method:string,body?:unknown):RequestInit=>({method,headers:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});
const fechaHoy=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Santiago',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());

export default function PagosProveedores(){
  const {sesion}=usarSesion();
  const [busqueda,setBusqueda]=useState('');const [proveedores,setProveedores]=useState<Proveedor[]>([]);const [medios,setMedios]=useState<Medio[]>([]);const [borradores,setBorradores]=useState<Operacion[]>([]);
  const [proveedor,setProveedor]=useState<Proveedor|null>(null);const [operacion,setOperacion]=useState<Operacion|null>(null);const [fechaPago,setFechaPago]=useState(fechaHoy());
  const [movimiento,setMovimiento]=useState({idObligacion:'',idMedioPago:'',montoAplicado:'',tasaBancariaEfectiva:''});const [archivo,setArchivo]=useState<File|null>(null);const [error,setError]=useState('');const [mensaje,setMensaje]=useState('');const [cargando,setCargando]=useState(false);
  const puedeConfirmar=sesion?.configuracion==='gerencia'||sesion?.configuracion==='contador';const puedeTasaManual=puedeConfirmar;
  const obligaciones=useMemo(()=>proveedor?.obligaciones||[],[proveedor]);
  const cargarBorradores=()=>api('/pagos-proveedores/borradores').then(setBorradores).catch(e=>setError(e.message));
  useEffect(()=>{api('/pagos-proveedores/catalogos').then(r=>setMedios(r.medios)).catch(e=>setError(e.message));void cargarBorradores()},[]);
  useEffect(()=>{const espera=window.setTimeout(()=>api(`/pagos-proveedores/proveedores?busqueda=${encodeURIComponent(busqueda)}`).then(setProveedores).catch(e=>setError(e.message)),200);return()=>window.clearTimeout(espera)},[busqueda]);
  const ejecutar=async(accion:()=>Promise<Operacion>,textoExito:string)=>{setCargando(true);setError('');setMensaje('');try{const actual=await accion();setOperacion(actual);setMensaje(textoExito);await cargarBorradores()}catch(e){setError(e instanceof Error?e.message:'No fue posible completar la operación')}finally{setCargando(false)}};
  const crear=async(p:Proveedor)=>{setProveedor(p);await ejecutar(()=>api('/pagos-proveedores',json('POST',{idProveedor:p.id,fechaEfectivaPago:fechaPago})),'Borrador creado')};
  const agregar=()=>operacion&&ejecutar(()=>api(`/pagos-proveedores/${operacion.id}/movimientos`,json('POST',{...movimiento,idObligacion:Number(movimiento.idObligacion),idMedioPago:Number(movimiento.idMedioPago),montoAplicado:Number(movimiento.montoAplicado),tasaBancariaEfectiva:movimiento.tasaBancariaEfectiva?Number(movimiento.tasaBancariaEfectiva):undefined})),'Movimiento agregado').then(()=>setMovimiento({idObligacion:'',idMedioPago:'',montoAplicado:'',tasaBancariaEfectiva:''}));
  const leerArchivo=async(file:File)=>new Promise<string>((resolver,rechazar)=>{const lector=new FileReader();lector.onload=()=>resolver(String(lector.result));lector.onerror=()=>rechazar(new Error('No fue posible leer el archivo'));lector.readAsDataURL(file)});
  const adjuntar=async()=>{if(!operacion||!archivo)return;const contenido=await leerArchivo(archivo);await ejecutar(()=>api(`/pagos-proveedores/${operacion.id}/respaldos`,json('POST',{nombreArchivo:archivo.name,contenido,operacion:true,movimientos:operacion.movimientos.map(m=>m.id)})),'Respaldo asociado');setArchivo(null)};
  const retomar=async(borrador:Operacion)=>{setCargando(true);try{const actual=await api(`/pagos-proveedores/${borrador.id}/retomar`,json('POST'));setOperacion(actual);setFechaPago(actual.fechaEfectivaPago?.slice(0,10)||fechaHoy());const lista:Proveedor[]=await api(`/pagos-proveedores/proveedores?busqueda=${encodeURIComponent(actual.proveedor.identificadorFiscal)}`);setProveedor(lista.find(p=>p.id===actual.proveedor.id)||null)}catch(e){setError(e instanceof Error?e.message:'No fue posible retomar el borrador')}finally{setCargando(false)}};
  const tasaManual=async(m:Movimiento)=>{if(!operacion)return;const tasa=window.prompt('Tasa de referencia manual');if(!tasa)return;const justificacion=window.prompt('Justificación de la tasa manual');if(!justificacion)return;await ejecutar(()=>api(`/pagos-proveedores/${operacion.id}/movimientos/${m.id}/tipo-cambio-manual`,json('POST',{tasaReferencia:Number(tasa),justificacion})),'Tasa manual registrada')};
  const cerrar=()=>{setOperacion(null);setProveedor(null);setMovimiento({idObligacion:'',idMedioPago:'',montoAplicado:'',tasaBancariaEfectiva:''});setMensaje('')};
  return <div className="min-h-full bg-slate-50 p-5 lg:p-8"><div className="mx-auto max-w-7xl">
    <header className="mb-6 flex items-center gap-3"><WalletCards className="h-7 w-7 text-primary-600"/><div><p className="text-sm font-semibold text-primary-600">Proveedores y egresos</p><h1 className="text-2xl font-bold">Pagos a proveedores</h1></div></header>
    {(error||mensaje)&&<div className={`mb-4 rounded-md border p-3 text-sm ${error?'border-red-200 bg-red-50 text-red-700':'border-emerald-200 bg-emerald-50 text-emerald-700'}`}>{error||mensaje}</div>}
    {!operacion&&<div className="grid gap-6 lg:grid-cols-[1.3fr_1fr]">
      <section className="border bg-white"><div className="flex items-center gap-2 border-b p-4"><Search className="h-4 w-4"/><input value={busqueda} onChange={e=>setBusqueda(e.target.value)} placeholder="Razón social o identificación fiscal" className="w-full border-0 outline-none"/></div><div className="divide-y">{proveedores.map(p=><button key={p.id} onClick={()=>void crear(p)} className="flex w-full items-center justify-between p-4 text-left hover:bg-gray-50"><span><strong className="block">{p.razonSocial}</strong><small className="text-gray-500">{p.identificadorFiscal} · {p.obligaciones.length} obligaciones</small></span><Plus className="h-5 w-5 text-primary-600"/></button>)}{!proveedores.length&&<p className="p-8 text-center text-sm text-gray-500">No hay proveedores elegibles.</p>}</div></section>
      <section className="border bg-white"><div className="flex items-center justify-between border-b p-4"><h2 className="font-semibold">Borradores</h2><button title="Actualizar borradores" onClick={()=>void cargarBorradores()}><RefreshCw className="h-4 w-4"/></button></div><div className="divide-y">{borradores.map(b=><button key={b.id} disabled={b.estado!=='borrador'} onClick={()=>void retomar(b)} className="w-full p-4 text-left disabled:cursor-not-allowed disabled:bg-gray-50"><strong>OP-{b.id} · {b.proveedor.razonSocial}</strong><p className="text-sm text-gray-500">{b.estado} · {b.total.toLocaleString('es-CL')}</p></button>)}{!borradores.length&&<p className="p-8 text-center text-sm text-gray-500">No hay borradores pendientes.</p>}</div></section>
    </div>}
    {operacion&&<div className="space-y-5"><section className="border bg-white p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs uppercase text-gray-500">Operación OP-{operacion.id}</p><h2 className="text-lg font-bold">{operacion.proveedor.razonSocial}</h2><p className="text-sm text-gray-500">{operacion.proveedor.identificadorFiscal} · {operacion.estado}</p></div><label className="text-sm font-medium">Fecha efectiva<input type="date" value={fechaPago} onChange={e=>setFechaPago(e.target.value)} disabled={operacion.estado!=='borrador'} className="ml-2 rounded-md border p-2"/></label></div></section>
      {operacion.estado==='borrador'&&<section className="grid gap-3 border-y bg-white p-4 md:grid-cols-2 lg:grid-cols-5"><select value={movimiento.idObligacion} onChange={e=>setMovimiento(v=>({...v,idObligacion:e.target.value}))} className="rounded-md border p-2"><option value="">Obligación</option>{obligaciones.map(o=><option key={o.id} value={o.id}>OB-{o.id} · {o.moneda} {o.saldoActual.toLocaleString('es-CL')}</option>)}</select><select value={movimiento.idMedioPago} onChange={e=>setMovimiento(v=>({...v,idMedioPago:e.target.value}))} className="rounded-md border p-2"><option value="">Medio de pago</option>{medios.map(m=><option key={m.id} value={m.id}>{m.nombre}</option>)}</select><input type="number" min="0.01" step="0.01" value={movimiento.montoAplicado} onChange={e=>setMovimiento(v=>({...v,montoAplicado:e.target.value}))} placeholder="Monto aplicado" className="rounded-md border p-2"/><input type="number" min="0.0001" step="0.0001" value={movimiento.tasaBancariaEfectiva} onChange={e=>setMovimiento(v=>({...v,tasaBancariaEfectiva:e.target.value}))} placeholder="Tasa bancaria opcional" className="rounded-md border p-2"/><button disabled={cargando||!movimiento.idObligacion||!movimiento.idMedioPago||!movimiento.montoAplicado} onClick={()=>void agregar()} className="flex items-center justify-center gap-2 rounded-md bg-primary-600 px-4 py-2 font-semibold text-white disabled:opacity-40"><Plus className="h-4 w-4"/>Agregar</button></section>}
      <section className="overflow-hidden border bg-white"><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead className="border-b bg-gray-50"><tr><th className="p-3">Obligación</th><th>Medio</th><th>Moneda</th><th className="text-right">Monto</th><th className="text-right">Saldo actual</th><th className="text-right">Tasa</th><th>Respaldo</th><th></th></tr></thead><tbody>{operacion.movimientos.map(m=><tr key={m.id} className={m.conflictoSaldo?'border-b bg-red-50':'border-b'}><td className="p-3 font-semibold">OB-{m.idObligacion}</td><td>{m.medioPago}</td><td>{m.moneda}</td><td className="text-right">{m.montoAplicado.toLocaleString('es-CL')}</td><td className="text-right">{m.saldoActual.toLocaleString('es-CL')}</td><td className="text-right">{m.tasaReferencia??'Pendiente'}</td><td>{m.tieneRespaldo?'Asociado':'Pendiente'}</td><td>{operacion.estado==='borrador'&&m.moneda!=='CLP'&&!m.tasaReferencia&&puedeTasaManual&&<button onClick={()=>void tasaManual(m)} className="text-primary-700 underline">Ingresar tasa</button>}</td></tr>)}</tbody></table></div>{!operacion.movimientos.length&&<p className="p-8 text-center text-sm text-gray-500">Agrega al menos un movimiento.</p>}<div className="flex justify-end border-t p-4 text-lg font-bold">Total: {operacion.total.toLocaleString('es-CL')}</div></section>
      {operacion.estado==='borrador'&&<section className="flex flex-wrap items-center gap-3 border bg-white p-4"><input type="file" onChange={e=>setArchivo(e.target.files?.[0]||null)} className="min-w-0 flex-1 text-sm"/><button disabled={!archivo||!operacion.movimientos.length} onClick={()=>void adjuntar()} className="flex items-center gap-2 rounded-md border px-4 py-2 disabled:opacity-40"><FileUp className="h-4 w-4"/>Asociar a operación y movimientos</button></section>}
      <div className="flex flex-wrap justify-end gap-2"><button onClick={cerrar} className="rounded-md border px-4 py-2">Cerrar</button>{operacion.estado==='borrador'&&<><button onClick={()=>void ejecutar(()=>api(`/pagos-proveedores/${operacion.id}/guardar-borrador`,json('POST',{fechaEfectivaPago:fechaPago})),'Borrador guardado')} className="flex items-center gap-2 rounded-md border px-4 py-2"><Save className="h-4 w-4"/>Guardar</button><button onClick={()=>void ejecutar(()=>api(`/pagos-proveedores/${operacion.id}/descartar`,json('POST')),'Borrador descartado')} className="flex items-center gap-2 rounded-md border border-red-300 px-4 py-2 text-red-700"><Trash2 className="h-4 w-4"/>Descartar</button><button onClick={()=>void ejecutar(()=>api(`/pagos-proveedores/${operacion.id}/preparar`,json('POST')),'Operación preparada')} className="flex items-center gap-2 rounded-md bg-primary-600 px-4 py-2 font-semibold text-white"><Send className="h-4 w-4"/>Preparar</button></>}{operacion.estado==='preparada'&&puedeConfirmar&&<button onClick={()=>void ejecutar(()=>api(`/pagos-proveedores/${operacion.id}/confirmar`,json('POST')),'Pago confirmado')} className="rounded-md bg-emerald-700 px-4 py-2 font-semibold text-white">Confirmar pago</button>}</div>
    </div>}
  </div></div>;
}
