import { useEffect, useMemo, useState, type ReactNode } from 'react';
import { FileSpreadsheet, X } from 'lucide-react';
import { useLocation } from 'react-router-dom';
import { ControlSegmentado, EncabezadoM7, EstadoDato, PdfDashboard, Periodo, formatearDato, usarConsultaM7 } from './componentes';
import { GraficoDonut, GraficoPeriodosVentas, GraficoRangoVentas } from './graficos';
import type { DatoGrafico } from './graficos';
import { solicitarFinanzas } from '../../api/finanzas';
import { usarSesion } from '../../seguridad/Sesion';
import { NombreProducto, PALETA_PRODUCTOS, limpiarNombreProducto } from './presentacionProductos';
import { FiltroTemporalVentas, leerFiltrosTemporalesVentas, parametrosTemporalesVentas, type FiltrosTemporalesVentas } from './filtrosTemporalesVentas';

type Objeto = Record<string, unknown>;
const esObjeto = (valor: unknown): valor is Objeto => Boolean(valor) && typeof valor === 'object' && !Array.isArray(valor);
const indicador = (valor: unknown) => esObjeto(valor) ? valor : {};
const valorIndicador = (valor: unknown) => indicador(valor).valor;
const numero = (valor: unknown) => typeof valor === 'number' && Number.isFinite(valor) ? valor : null;
const porcentaje = (valor: unknown) => { const base = numero(valor); if (base === null) return 'N/A'; const normalizado = Object.is(base, -0) ? 0 : base; return `${normalizado >= 0 ? '+' : ''}${normalizado.toLocaleString('es-CL', { maximumFractionDigits: 1 })}%`; };

function Tarjeta({ titulo, valor, detalle, estado }: { titulo: string; valor: string; detalle: string; estado?: string }) {
  return <article className="min-w-0 border-t-4 border-[#FE8F01] bg-white p-4 shadow-sm"><div className="flex items-start justify-between gap-2"><p className="text-xs font-black uppercase text-[#676767]">{titulo}</p><EstadoDato estado={estado} compacto /></div><p className="mt-3 break-words text-2xl font-black text-black">{valor}</p><p className="mt-2 text-xs leading-5 text-gray-500">{detalle}</p></article>;
}

function Seccion({ titulo, descripcion, children }: { titulo: string; descripcion: string; children: ReactNode }) {
  return <section className="border border-gray-200 bg-white p-4 shadow-sm sm:p-6"><div className="mb-5"><h2 className="text-lg font-black text-black">{titulo}</h2><p className="mt-1 text-sm text-gray-500">{descripcion}</p></div>{children}</section>;
}

function DetalleComparacion({ periodoA, periodoB }: { periodoA: Objeto | null; periodoB: Objeto | null }) {
  const conversion = (periodo: Objeto | null) => esObjeto(valorIndicador(periodo?.conversion)) ? valorIndicador(periodo?.conversion) as Objeto : {};
  const metricas = [
    { nombre: 'Cotizaciones', valor: (p: Objeto | null) => formatearDato(conversion(p).totalCotizaciones) },
    { nombre: 'Conversiones', valor: (p: Objeto | null) => formatearDato(conversion(p).convertidas) },
    { nombre: 'Tasa de conversión', valor: (p: Objeto | null) => numero(conversion(p).tasaPorcentual) === null ? 'N/A' : formatearDato(conversion(p).tasaPorcentual, 'participacionPorcentual') },
    { nombre: 'Costos directos', valor: (p: Objeto | null) => numero(valorIndicador(p?.costosDirectos)) === null ? 'Sin cobertura' : formatearDato(valorIndicador(p?.costosDirectos), 'monto') },
    { nombre: 'Resultado gerencial', valor: (p: Objeto | null) => numero(valorIndicador(p?.resultadoGerencial)) === null ? 'Sin cobertura' : formatearDato(valorIndicador(p?.resultadoGerencial), 'monto') },
  ];
  const lista = (periodo: Objeto | null, clave: 'concentracionClientes' | 'productos', nombre: string) => {
    const filas = (Array.isArray(valorIndicador(periodo?.[clave])) ? valorIndicador(periodo?.[clave]) as unknown[] : []).filter(esObjeto).slice(0, 5);
    return <div><p className="mb-2 text-xs font-black uppercase text-gray-500">{nombre}</p>{filas.length ? <ol className="space-y-2 text-sm">{filas.map((fila, indice) => <li key={`${String(fila.idCliente || fila.producto)}-${indice}`} className="flex justify-between gap-3 border-b border-gray-100 pb-2"><span className="truncate">{String(fila.cliente || fila.producto)}</span><strong className="shrink-0">{formatearDato(fila.montoClp ?? fila.ventaNetaClp, 'monto')}</strong></li>)}</ol> : <p className="text-sm text-gray-500">Sin datos comparables.</p>}</div>;
  };
  return <div className="mt-5 space-y-5 border-t border-gray-100 pt-5"><div className="overflow-x-auto"><table className="w-full min-w-[520px] text-sm"><thead className="bg-gray-50 text-left text-xs uppercase text-gray-500"><tr><th className="px-3 py-2">Métrica</th><th className="px-3 text-right">Período A</th><th className="px-3 text-right">Período B</th></tr></thead><tbody>{metricas.map(metrica => <tr key={metrica.nombre} className="border-b border-gray-100"><th className="px-3 py-3 text-left font-semibold">{metrica.nombre}</th><td className="px-3 text-right">{metrica.valor(periodoA)}</td><td className="px-3 text-right font-bold">{metrica.valor(periodoB)}</td></tr>)}</tbody></table></div><div className="grid gap-5 lg:grid-cols-2"><div className="rounded-md bg-gray-50 p-4"><p className="mb-4 font-black">Período A</p><div className="grid gap-5 sm:grid-cols-2">{lista(periodoA, 'concentracionClientes', 'Principales clientes')}{lista(periodoA, 'productos', 'Productos')}</div></div><div className="rounded-md bg-orange-50/50 p-4"><p className="mb-4 font-black">Período B</p><div className="grid gap-5 sm:grid-cols-2">{lista(periodoB, 'concentracionClientes', 'Principales clientes')}{lista(periodoB, 'productos', 'Productos')}</div></div></div></div>;
}

function ResumenRangoAnalisis({ filtros, datos }: { filtros: FiltrosTemporalesVentas; datos: Objeto }) {
  const monto = esObjeto(indicador(datos.montoNeto).valor) ? indicador(datos.montoNeto).valor as Objeto : {};
  const ticket = esObjeto(indicador(datos.ticketMedio).valor) ? indicador(datos.ticketMedio).valor as Objeto : {};
  const venta = numero(monto.totalClp); const dias = Math.floor((new Date(`${filtros.hasta}T00:00:00Z`).getTime() - new Date(`${filtros.desde}T00:00:00Z`).getTime()) / 86400000) + 1;
  const serie = (Array.isArray(datos.serieTemporal) ? datos.serieTemporal : []) as DatoGrafico[]; const granularidad = datos.granularidad === 'dia' ? 'dia' : 'mes';
  const item = (etiqueta: string, valor: string) => <div><dt className="text-[10px] font-black uppercase text-gray-500">{etiqueta}</dt><dd className="mt-1 text-sm font-black">{valor}</dd></div>;
  return <Seccion titulo="Evolución dentro del rango" descripcion="Cada punto representa un día en rangos de hasta 62 días; los rangos más extensos se agrupan por mes."><dl className="mb-5 grid gap-4 bg-gray-50 p-4 sm:grid-cols-2 lg:grid-cols-5">{item('Período', `${filtros.desde} → ${filtros.hasta}`)}{item('Venta neta', venta === null ? 'No disponible' : formatearDato(venta, 'monto'))}{item('Ventas', formatearDato(indicador(datos.cantidad).valor))}{item('Ticket promedio', numero(ticket.totalClp) === null ? 'N/A' : formatearDato(ticket.totalClp, 'monto'))}{item('Promedio diario', venta === null ? 'N/A' : formatearDato(venta / dias, 'monto'))}</dl><GraficoRangoVentas datos={serie} granularidad={granularidad}/></Seccion>;
}

function ExportarExcelVentas({ anio, mes, desde, hasta, segmento }: { anio: number; mes: number; desde?: string; hasta?: string; segmento: string }) {
  const { sesion } = usarSesion();
  const opciones = ([
    sesion?.permisos.includes('CU219') && sesion.permisos.includes('CU220') ? 'VENTAS' : null,
    sesion?.permisos.includes('CU218') && sesion.permisos.includes('CU220') ? 'COTIZACIONES' : null,
  ] as const).filter((opcion): opcion is 'VENTAS' | 'COTIZACIONES' => opcion !== null);
  const [abierto, setAbierto] = useState(false);
  const [tipo, setTipo] = useState<'VENTAS' | 'COTIZACIONES'>(opciones[0] || 'VENTAS');
  const [ocupado, setOcupado] = useState(false);
  const [error, setError] = useState('');
  useEffect(() => { if (opciones.length && !opciones.includes(tipo)) setTipo(opciones[0]); }, [opciones, tipo]);
  const cerrar = () => { if (!ocupado) { setAbierto(false); setError(''); } };
  const descargar = async () => {
    setOcupado(true); setError('');
    try {
      const consulta = desde && hasta ? { desde, hasta, segmento } : { anio, mes, segmento };
      const respuesta = await solicitarFinanzas('/dashboard-m7/excel', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ tipo, consulta }) });
      const archivo = await respuesta.json();
      if (!respuesta.ok) throw new Error(archivo.error || 'No fue posible generar el Excel');
      const enlace = document.createElement('a'); enlace.href = archivo.contenido; enlace.download = archivo.nombre; enlace.click();
      setAbierto(false);
    } catch (causa) { setError((causa as Error).message); }
    finally { setOcupado(false); }
  };
  if (!opciones.length) return null;
  return <><button type="button" onClick={() => setAbierto(true)} className="inline-flex items-center gap-2 rounded-md bg-[#FE8F01] px-3 py-2 text-sm font-bold text-black shadow-sm transition hover:bg-orange-400"><FileSpreadsheet className="h-4 w-4" />Exportar Excel</button>{abierto && <div role="dialog" aria-modal="true" aria-labelledby="titulo-exportar-excel" className="fixed inset-0 z-50 flex items-center justify-center bg-black/45 p-4"><div className="w-full max-w-md rounded-lg bg-white p-5 shadow-xl"><div className="flex items-start justify-between gap-3"><div><h2 id="titulo-exportar-excel" className="text-lg font-black text-black">Exportar detalle a Excel</h2><p className="mt-1 text-sm text-gray-500">Se aplicarán el período y segmento activos.</p></div><button type="button" aria-label="Cerrar exportación" onClick={cerrar} disabled={ocupado} className="rounded p-1 text-gray-500 hover:bg-gray-100 disabled:opacity-40"><X className="h-5 w-5" /></button></div><fieldset className="mt-5"><legend className="text-xs font-bold uppercase text-[#676767]">Contenido</legend><div className="mt-2 grid grid-cols-2 gap-2">{opciones.map(opcion => <button key={opcion} type="button" aria-pressed={tipo === opcion} onClick={() => setTipo(opcion)} disabled={ocupado} className={`rounded-md border px-3 py-3 text-sm font-bold ${tipo === opcion ? 'border-[#FE8F01] bg-orange-50 text-black' : 'border-gray-300 text-gray-600'}`}>{opcion === 'VENTAS' ? 'Ventas' : 'Cotizaciones'}</button>)}</div></fieldset>{error && <p role="alert" className="mt-4 rounded border border-red-200 bg-red-50 p-3 text-sm text-red-800">{error}</p>}<div className="mt-6 flex flex-wrap justify-end gap-2"><button type="button" onClick={cerrar} disabled={ocupado} className="rounded-md border border-gray-300 px-4 py-2 text-sm font-semibold text-gray-700 disabled:opacity-40">Cancelar</button><button type="button" onClick={() => void descargar()} disabled={ocupado} className="inline-flex items-center gap-2 rounded-md bg-[#FE8F01] px-4 py-2 text-sm font-bold text-black disabled:opacity-50"><FileSpreadsheet className="h-4 w-4" />{ocupado ? 'Generando Excel…' : 'Descargar .xlsx'}</button></div></div></div>}</>;
}

export default function AnalisisVentasM7() {
  const location = useLocation();
  const parametrosUrl = new URLSearchParams(location.search); const hoy = new Date();
  const anioInicial = Number(parametrosUrl.get('anio')) || hoy.getFullYear(); const mesInicial = Number(parametrosUrl.get('mes')) || hoy.getMonth() + 1;
  const [filtros, setFiltros] = useState<FiltrosTemporalesVentas>(() => leerFiltrosTemporalesVentas(location.search, anioInicial, mesInicial));
  const [metrica, setMetrica] = useState(() => new URLSearchParams(location.search).get('metrica') === 'UNIDADES' ? 'UNIDADES' : 'VALOR');
  const q = usarConsultaM7('/dashboard-m7/ventas', false, parametrosTemporalesVentas(filtros));
  const comparando = filtros.modo === 'comparar'; const respuesta = q.datos || {};
  const datos = comparando && esObjeto(respuesta.periodoB) ? respuesta.periodoB : respuesta;
  const monto = indicador(datos.montoNeto); const montoValor = esObjeto(monto.valor) ? monto.valor : {};
  const cantidad = indicador(datos.cantidad); const conversion = indicador(datos.conversion); const conversionValor = esObjeto(conversion.valor) ? conversion.valor : {};
  const ticket = indicador(datos.ticketMedio); const ticketValor = esObjeto(ticket.valor) ? ticket.valor : {};
  const temporal = esObjeto(datos.resumenTemporal) ? datos.resumenTemporal : null;
  const clientes = (Array.isArray(valorIndicador(datos.concentracionClientes)) ? valorIndicador(datos.concentracionClientes) as unknown[] : []).filter(esObjeto);
  const productos = (Array.isArray(valorIndicador(datos.productos)) ? valorIndicador(datos.productos) as unknown[] : []).filter(esObjeto);
  const participacion = (Array.isArray(datos.participacionSegmentos) ? datos.participacionSegmentos : []).filter(esObjeto);
  const productosPresentacion = useMemo<Array<Objeto & { nombrePresentacion: string; colorPresentacion: string }>>(() => productos.map((item, indice) => ({ ...item, nombrePresentacion: limpiarNombreProducto(item.producto), colorPresentacion: PALETA_PRODUCTOS[indice % PALETA_PRODUCTOS.length] })), [productos]);
  const donutProductos = useMemo(() => productosPresentacion.map(item => ({ nombre: item.nombrePresentacion, valor: numero(metrica === 'VALOR' ? item.ventaNetaClp : item.unidades) || 0, color: item.colorPresentacion, porcentaje: numero(metrica === 'VALOR' ? item.participacionValorPorcentual : item.participacionUnidadesPorcentual) })).filter(item => item.valor > 0), [productosPresentacion, metrica]);
  const totalDonutProductos = donutProductos.reduce((total, item) => total + item.valor, 0);
  const productosConFxFaltante = productos.some(item => numero(item.unidades) !== null && numero(item.ventaNetaClp) === null);
  const donutSegmentos = participacion.map(item => ({ nombre: String(item.segmento), valor: numero(item.montoClp) || 0 })).filter(item => item.valor > 0);
  const cambiarPeriodo = (anio: number, mes: number) => { const mensual = leerFiltrosTemporalesVentas('', anio, mes); setFiltros(mensual); q.cambiar(anio, mes, ['modo', 'desde', 'hasta', 'desdeA', 'hastaA', 'desdeB', 'hastaB']); };
  const cambiarFiltros = (siguiente: FiltrosTemporalesVentas) => { setFiltros(siguiente); q.reemplazarParametros({ ...parametrosTemporalesVentas(siguiente), metrica }, ['modo', 'desde', 'hasta', 'desdeA', 'hastaA', 'desdeB', 'hastaB']); };
  const cambiarMetrica = (valor: string) => { setMetrica(valor); q.actualizarParametros({ metrica: valor }); };
  const rangoActivo = filtros.modo === 'rango' ? filtros : null;
  const resumenComparacion = comparando && esObjeto(respuesta.resumen) ? respuesta.resumen : null; const periodoA = comparando && esObjeto(respuesta.periodoA) ? respuesta.periodoA : null; const periodoB = comparando && esObjeto(respuesta.periodoB) ? respuesta.periodoB : null;
  const promedioDiarioComparacion = resumenComparacion?.granularidad === 'dia';
  const resumenPeriodo = (titulo: string, periodo: Objeto | null, clase: string) => {
    const pMonto = esObjeto(indicador(periodo?.montoNeto).valor) ? indicador(periodo?.montoNeto).valor as Objeto : {};
    const pTicket = esObjeto(indicador(periodo?.ticketMedio).valor) ? indicador(periodo?.ticketMedio).valor as Objeto : {};
    const fechas = esObjeto(periodo?.periodo) ? periodo?.periodo as Objeto : {};
    const periodoEsA = titulo === 'Período A'; const dias = resumenComparacion?.[periodoEsA ? 'diasA' : 'diasB']; const promedio = resumenComparacion?.[periodoEsA ? 'promedioA' : 'promedioB'];
    return <><article className={`border-t-4 bg-white p-4 shadow-sm ${clase}`}><p className="text-xs font-black uppercase text-gray-500">{titulo}</p><p className="mt-1 text-xs text-gray-500">{String(fechas.desde || '')} → {String(fechas.hasta || '')} · {String(dias || '—')} días</p><p className="mt-3 text-2xl font-black">{numero(pMonto.totalClp) === null ? 'No disponible' : formatearDato(pMonto.totalClp, 'monto')}</p><p className="mt-1 text-xs text-gray-600">Promedio {promedioDiarioComparacion ? 'diario' : 'mensual'}: <strong>{formatearDato(promedio, 'monto')}</strong></p><div className="mt-3 grid grid-cols-2 gap-3 text-sm"><div><span className="text-gray-500">Ventas</span><strong className="block">{formatearDato(indicador(periodo?.cantidad).valor)}</strong></div><div><span className="text-gray-500">Ticket medio</span><strong className="block">{numero(pTicket.totalClp) === null ? 'N/A' : formatearDato(pTicket.totalClp, 'monto')}</strong></div></div><p className="mt-3 text-xs text-amber-800">{formatearDato(pMonto.ventasExcluidasSinTipoCambio)} venta(s) sin FX histórico.</p></article>{titulo === 'Período B' && <div className="lg:col-span-2"><DetalleComparacion periodoA={periodoA} periodoB={periodoB}/></div>}</>;
  };
  return <div className="min-h-full bg-gray-100"><EncabezadoM7 titulo="Análisis de Ventas" descripcion="Ventas definitivas, clientes y productos con segmentación definida en la ficha del cliente" regreso={q.global}/><Periodo anio={q.anio} mes={q.mes} cambiar={cambiarPeriodo} cargando={q.cargando} recargar={q.recargar}/><div className="mx-auto mt-3 max-w-7xl space-y-3 px-5 sm:px-8"><div className="rounded-lg border border-gray-200 bg-white p-4 shadow-sm"><ControlSegmentado etiqueta="Segmento comercial" valor={q.segmento} cambiar={q.cambiarSegmento} opciones={[{ valor: 'TODOS', etiqueta: 'Todos' }, { valor: 'B2B', etiqueta: 'B2B' }, { valor: 'B2C', etiqueta: 'B2C' }]} /></div><div className="rounded-lg border border-gray-200 bg-white p-4 shadow-sm"><FiltroTemporalVentas valor={filtros} cambiar={cambiarFiltros} cargando={q.cargando}/></div></div><PdfDashboard origen="ventas" anio={q.anio} mes={q.mes} desde={rangoActivo?.desde} hasta={rangoActivo?.hasta} segmento={q.segmento} acciones={<ExportarExcelVentas anio={q.anio} mes={q.mes} desde={rangoActivo?.desde} hasta={rangoActivo?.hasta} segmento={q.segmento}/>}/>{q.error && <p role="alert" className="mx-auto mt-4 max-w-7xl border border-red-200 bg-red-50 px-5 py-3 text-red-800">{q.error}</p>}
    <main className="mx-auto max-w-7xl space-y-5 px-5 py-6 sm:px-8">
      {filtros.modo === 'rango' && <ResumenRangoAnalisis filtros={filtros} datos={datos}/>}
      {comparando && <Seccion titulo="Período B vs Período A" descripcion="Comparación de ventas netas con idénticas reglas de definitividad, segmento y tipo de cambio histórico.">
        <div className="grid gap-3 lg:grid-cols-2">{resumenPeriodo('Período A', periodoA, 'border-[#676767]')}{resumenPeriodo('Período B', periodoB, 'border-[#FE8F01]')}</div>
        {resumenComparacion && <div className="mt-4 grid gap-3 rounded-lg bg-gray-50 p-4 sm:grid-cols-2 lg:grid-cols-4"><div><p className="text-xs font-bold text-gray-500">Diferencia absoluta</p><strong>{formatearDato(esObjeto(resumenComparacion.total) ? resumenComparacion.total.diferenciaAbsoluta : null, 'monto')}</strong></div><div><p className="text-xs font-bold text-[#9a4f00]">Variación total B vs A</p><strong>{porcentaje(esObjeto(resumenComparacion.total) ? resumenComparacion.total.variacionPorcentual : null)}</strong></div><div><p className="text-xs font-bold text-gray-500">Promedio {promedioDiarioComparacion ? 'diario' : 'mensual'} A / B</p><strong>{formatearDato(resumenComparacion.promedioA, 'monto')} / {formatearDato(resumenComparacion.promedioB, 'monto')}</strong></div><div><p className="text-xs font-bold text-gray-500">Variación promedio {promedioDiarioComparacion ? 'diario' : 'mensual'}</p><strong>{porcentaje(esObjeto(resumenComparacion.promedio) ? resumenComparacion.promedio.variacionPorcentual : null)}</strong></div></div>}
        {resumenComparacion?.duracionComparable === false && <p className="mt-3 rounded-md bg-amber-50 p-3 text-sm text-amber-900">Los períodos tienen distinta duración ({String(resumenComparacion.diasA)} vs {String(resumenComparacion.diasB)} días). La variación total se conserva como referencia; compara también el promedio {promedioDiarioComparacion ? 'diario' : 'mensual'}.</p>}
        <div className="mt-5"><GraficoPeriodosVentas datos={(Array.isArray(respuesta.serieComparativa) ? respuesta.serieComparativa : []) as DatoGrafico[]}/></div>
      </Seccion>}
      <Seccion titulo={comparando ? 'Resumen del Período B' : 'Resumen'} descripcion={`${filtros.modo === 'rango' ? `Rango activo: ${filtros.desde} → ${filtros.hasta}` : 'Período seleccionado'} · segmento ${q.segmento}`}><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Tarjeta titulo="Venta neta" valor={numero(montoValor.totalClp) === null ? 'No disponible' : formatearDato(montoValor.totalClp, 'monto')} detalle={`${formatearDato(montoValor.ventasExcluidasSinTipoCambio)} venta(s) excluida(s) por falta de tipo de cambio histórico.`} estado={String(monto.estado || '')}/><Tarjeta titulo="Ventas" valor={formatearDato(cantidad.valor)} detalle="Notas de Venta definitivas." estado={String(cantidad.estado || '')}/><Tarjeta titulo="Ticket medio" valor={numero(ticketValor.totalClp) === null ? 'No disponible' : formatearDato(ticketValor.totalClp, 'monto')} detalle="Neto comparable dividido por cantidad de ventas." estado={String(ticket.estado || '')}/><Tarjeta titulo="Conversión" valor={numero(conversionValor.tasaPorcentual) === null ? 'N/A' : formatearDato(conversionValor.tasaPorcentual, 'participacionPorcentual')} detalle={`${formatearDato(conversionValor.convertidas)} de ${formatearDato(conversionValor.totalCotizaciones)} cotizaciones.`} estado={String(conversion.estado || '')}/></div>{!comparando && temporal && <div className="mt-4 grid gap-3 rounded-lg bg-gray-50 p-4 sm:grid-cols-3"><div><p className="text-xs font-bold text-gray-500">MoM</p><strong>{porcentaje(temporal.mom)}</strong></div><div><p className="text-xs font-bold text-[#b85e00]">YoY</p><strong>{porcentaje(temporal.yoy)}</strong></div><div><p className="text-xs font-bold text-gray-500">Variación YTD</p><strong>{porcentaje(temporal.variacionYtd)}</strong></div></div>} {donutSegmentos.length > 0 && <div className="mt-5 grid items-center gap-5 lg:grid-cols-2"><GraficoDonut datos={donutSegmentos}/><div>{participacion.map(item => <div key={String(item.segmento)} className="flex justify-between border-b border-gray-100 py-3 text-sm"><span className="font-bold">{String(item.segmento)}</span><span className="text-right">{formatearDato(item.montoClp, 'monto')}<strong className="ml-3 text-[#b85e00]">{formatearDato(item.participacionPorcentual, 'participacionPorcentual')}</strong></span></div>)}</div></div>}</Seccion>
      <Seccion titulo="Clientes" descripcion="Participación sobre el total comparable consolidado en CLP."><div className="overflow-x-auto"><table className="w-full min-w-[620px] text-left text-sm"><thead className="bg-gray-50 text-xs uppercase text-gray-500"><tr><th className="px-3 py-3">Posición</th><th className="px-3">Cliente</th><th className="px-3 text-right">Venta neta</th><th className="px-3 text-right">Participación</th></tr></thead><tbody>{clientes.map(item => <tr key={String(item.idCliente)} className="border-b border-gray-100"><td className="px-3 py-3">{formatearDato(item.posicion)}</td><td className="px-3 font-semibold">{String(item.cliente)}</td><td className="px-3 text-right">{formatearDato(item.montoClp, 'monto')}</td><td className="px-3 text-right font-bold text-[#b85e00]">{formatearDato(item.participacionPorcentual, 'participacionPorcentual')}</td></tr>)}</tbody></table>{!q.cargando && !clientes.length && <p className="py-8 text-center text-sm text-gray-500">No hay clientes comparables para el período y segmento.</p>}</div></Seccion>
      <Seccion titulo="Productos" descripcion="Producto registrado, unidades reales y neto prorrateado sin duplicar la Nota de Venta."><div className="mb-5"><ControlSegmentado etiqueta="Métrica" valor={metrica} cambiar={cambiarMetrica} opciones={[{ valor: 'VALOR', etiqueta: 'Valor' }, { valor: 'UNIDADES', etiqueta: 'Unidades' }]} /></div><div className="grid items-center gap-6 md:grid-cols-[minmax(260px,.8fr)_minmax(0,1.2fr)]"><div className="flex justify-center"><GraficoDonut datos={donutProductos} metrica={metrica === 'VALOR' ? 'VALOR' : 'UNIDADES'} mostrarLeyenda={false} alto={300} radioInterior={76} radioExterior={112} centroEtiqueta={metrica === 'VALOR' ? 'Total vendido' : 'Unidades'} centroValor={metrica === 'VALOR' ? formatearDato(totalDonutProductos, 'monto') : formatearDato(totalDonutProductos)}/></div><div className="overflow-x-auto"><table className="w-full min-w-[620px] table-fixed text-left text-sm"><thead className="bg-gray-50 text-xs uppercase text-gray-500"><tr><th className="w-[34%] px-3 py-3">Producto/modelo</th><th className="w-[14%] px-3">Segmento</th><th className="w-[15%] px-3 text-right">Unidades</th><th className="w-[22%] px-3 text-right">Venta neta</th><th className="w-[15%] px-3 text-right">Participación</th></tr></thead><tbody>{productosPresentacion.map(item => <tr key={`${String(item.segmento)}-${String(item.producto)}`} className="border-b border-gray-100"><td className="px-3 py-3"><NombreProducto nombre={item.nombrePresentacion} color={item.colorPresentacion}/></td><td className="px-3">{String(item.segmento || 'Sin clasificar')}</td><td className="px-3 text-right tabular-nums">{formatearDato(item.unidades)}</td><td className="px-3 text-right tabular-nums">{item.ventaNetaClp === null ? 'Sin tipo de cambio' : formatearDato(item.ventaNetaClp, 'monto')}</td><td className="px-3 text-right font-bold tabular-nums text-[#9a4f00]">{formatearDato(metrica === 'VALOR' ? item.participacionValorPorcentual : item.participacionUnidadesPorcentual, 'participacionPorcentual')}</td></tr>)}</tbody></table>{!q.cargando && !productos.length && <p className="py-8 text-center text-sm text-gray-500">No hay detalle comercial estructurado para el período y segmento.</p>}</div></div><p className="mt-4 text-xs leading-5 text-gray-500">{productosConFxFaltante ? 'Algunas ventas no pudieron incluirse en el valor consolidado por falta de tipo de cambio histórico.' : 'Información disponible'}</p></Seccion></main></div>;
}
