import { useEffect, useMemo, useState, type FormEvent, type ReactNode } from 'react';
import { CalendarDays, FileSpreadsheet, X } from 'lucide-react';
import { useLocation } from 'react-router-dom';
import { ControlSegmentado, EncabezadoM7, EstadoDato, PdfDashboard, Periodo, formatearDato, usarConsultaM7 } from './componentes';
import { GraficoDonut } from './graficos';
import { solicitarFinanzas } from '../../api/finanzas';
import { usarSesion } from '../../seguridad/Sesion';

type Rango = { desde: string; hasta: string };
type Objeto = Record<string, unknown>;
const esObjeto = (valor: unknown): valor is Objeto => Boolean(valor) && typeof valor === 'object' && !Array.isArray(valor);
const indicador = (valor: unknown) => esObjeto(valor) ? valor : {};
const valorIndicador = (valor: unknown) => indicador(valor).valor;
const numero = (valor: unknown) => typeof valor === 'number' && Number.isFinite(valor) ? valor : null;
const porcentaje = (valor: unknown) => { const base = numero(valor); if (base === null) return 'N/A'; const normalizado = Object.is(base, -0) ? 0 : base; return `${normalizado >= 0 ? '+' : ''}${normalizado.toLocaleString('es-CL', { maximumFractionDigits: 1 })}%`; };
const rangoDesdeBusqueda = (busqueda: string): Rango | null => { const parametros = new URLSearchParams(busqueda); const desde = parametros.get('desde') || ''; const hasta = parametros.get('hasta') || ''; return /^\d{4}-\d{2}-\d{2}$/.test(desde) && /^\d{4}-\d{2}-\d{2}$/.test(hasta) && desde <= hasta ? { desde, hasta } : null; };

function Tarjeta({ titulo, valor, detalle, estado }: { titulo: string; valor: string; detalle: string; estado?: string }) {
  return <article className="min-w-0 border-t-4 border-[#FE8F01] bg-white p-4 shadow-sm"><div className="flex items-start justify-between gap-2"><p className="text-xs font-black uppercase text-[#676767]">{titulo}</p><EstadoDato estado={estado} compacto /></div><p className="mt-3 break-words text-2xl font-black text-black">{valor}</p><p className="mt-2 text-xs leading-5 text-gray-500">{detalle}</p></article>;
}

function Seccion({ titulo, descripcion, children }: { titulo: string; descripcion: string; children: ReactNode }) {
  return <section className="border border-gray-200 bg-white p-4 shadow-sm sm:p-6"><div className="mb-5"><h2 className="text-lg font-black text-black">{titulo}</h2><p className="mt-1 text-sm text-gray-500">{descripcion}</p></div>{children}</section>;
}

function ExportarExcelVentas({ anio, mes, desde, hasta, segmento }: { anio: number; mes: number; desde?: string; hasta?: string; segmento: string }) {
  const { sesion } = usarSesion();
  const opciones = ([
    sesion?.permisos.includes('CU219') && sesion.permisos.includes('CU220') ? 'VENTAS' : null,
    sesion?.permisos.includes('CU218') && sesion.permisos.includes('CU220') ? 'COTIZACIONES' : null,
  ] as const).filter((opcion): opcion is 'VENTAS' | 'COTIZACIONES' => opcion !== null);
  const [abierto, setAbierto] = useState(false);
  const [tipo, setTipo] = useState<'VENTAS' | 'COTIZACIONES'>(opciones[0] || 'VENTAS');
  const [ocupado, setOcupado] = useState(false);
  const [error, setError] = useState('');
  useEffect(() => { if (opciones.length && !opciones.includes(tipo)) setTipo(opciones[0]); }, [opciones, tipo]);
  const cerrar = () => { if (!ocupado) { setAbierto(false); setError(''); } };
  const descargar = async () => {
    setOcupado(true); setError('');
    try {
      const consulta = desde && hasta ? { desde, hasta, segmento } : { anio, mes, segmento };
      const respuesta = await solicitarFinanzas('/dashboard-m7/excel', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ tipo, consulta }) });
      const archivo = await respuesta.json();
      if (!respuesta.ok) throw new Error(archivo.error || 'No fue posible generar el Excel');
      const enlace = document.createElement('a'); enlace.href = archivo.contenido; enlace.download = archivo.nombre; enlace.click();
      setAbierto(false);
    } catch (causa) { setError((causa as Error).message); }
    finally { setOcupado(false); }
  };
  if (!opciones.length) return null;
  return <><button type="button" onClick={() => setAbierto(true)} className="inline-flex items-center gap-2 rounded-md bg-[#FE8F01] px-3 py-2 text-sm font-bold text-black shadow-sm transition hover:bg-orange-400"><FileSpreadsheet className="h-4 w-4" />Exportar Excel</button>{abierto && <div role="dialog" aria-modal="true" aria-labelledby="titulo-exportar-excel" className="fixed inset-0 z-50 flex items-center justify-center bg-black/45 p-4"><div className="w-full max-w-md rounded-lg bg-white p-5 shadow-xl"><div className="flex items-start justify-between gap-3"><div><h2 id="titulo-exportar-excel" className="text-lg font-black text-black">Exportar detalle a Excel</h2><p className="mt-1 text-sm text-gray-500">Se aplicarán el período y segmento activos.</p></div><button type="button" aria-label="Cerrar exportación" onClick={cerrar} disabled={ocupado} className="rounded p-1 text-gray-500 hover:bg-gray-100 disabled:opacity-40"><X className="h-5 w-5" /></button></div><fieldset className="mt-5"><legend className="text-xs font-bold uppercase text-[#676767]">Contenido</legend><div className="mt-2 grid grid-cols-2 gap-2">{opciones.map(opcion => <button key={opcion} type="button" aria-pressed={tipo === opcion} onClick={() => setTipo(opcion)} disabled={ocupado} className={`rounded-md border px-3 py-3 text-sm font-bold ${tipo === opcion ? 'border-[#FE8F01] bg-orange-50 text-black' : 'border-gray-300 text-gray-600'}`}>{opcion === 'VENTAS' ? 'Ventas' : 'Cotizaciones'}</button>)}</div></fieldset>{error && <p role="alert" className="mt-4 rounded border border-red-200 bg-red-50 p-3 text-sm text-red-800">{error}</p>}<div className="mt-6 flex flex-wrap justify-end gap-2"><button type="button" onClick={cerrar} disabled={ocupado} className="rounded-md border border-gray-300 px-4 py-2 text-sm font-semibold text-gray-700 disabled:opacity-40">Cancelar</button><button type="button" onClick={() => void descargar()} disabled={ocupado} className="inline-flex items-center gap-2 rounded-md bg-[#FE8F01] px-4 py-2 text-sm font-bold text-black disabled:opacity-50"><FileSpreadsheet className="h-4 w-4" />{ocupado ? 'Generando Excel…' : 'Descargar .xlsx'}</button></div></div></div>}</>;
}

export default function AnalisisVentasM7() {
  const location = useLocation();
  const inicialRango = rangoDesdeBusqueda(location.search);
  const [borrador, setBorrador] = useState<Rango>(inicialRango || { desde: '', hasta: '' });
  const [rango, setRango] = useState<Rango | null>(inicialRango);
  const [errorRango, setErrorRango] = useState('');
  const [metrica, setMetrica] = useState(() => new URLSearchParams(location.search).get('metrica') === 'UNIDADES' ? 'UNIDADES' : 'VALOR');
  const q = usarConsultaM7('/dashboard-m7/ventas', false, rango || {});
  const datos = q.datos || {};
  const monto = indicador(datos.montoNeto); const montoValor = esObjeto(monto.valor) ? monto.valor : {};
  const cantidad = indicador(datos.cantidad); const conversion = indicador(datos.conversion); const conversionValor = esObjeto(conversion.valor) ? conversion.valor : {};
  const ticket = indicador(datos.ticketMedio); const ticketValor = esObjeto(ticket.valor) ? ticket.valor : {};
  const temporal = esObjeto(datos.resumenTemporal) ? datos.resumenTemporal : null;
  const clientes = (Array.isArray(valorIndicador(datos.concentracionClientes)) ? valorIndicador(datos.concentracionClientes) as unknown[] : []).filter(esObjeto);
  const productos = (Array.isArray(valorIndicador(datos.productos)) ? valorIndicador(datos.productos) as unknown[] : []).filter(esObjeto);
  const participacion = (Array.isArray(datos.participacionSegmentos) ? datos.participacionSegmentos : []).filter(esObjeto);
  const donutProductos = useMemo(() => productos.map(item => ({ nombre: String(item.producto || 'Sin producto'), valor: numero(metrica === 'VALOR' ? item.ventaNetaClp : item.unidades) || 0 })).filter(item => item.valor > 0), [productos, metrica]);
  const donutSegmentos = participacion.map(item => ({ nombre: String(item.segmento), valor: numero(item.montoClp) || 0 })).filter(item => item.valor > 0);
  const cambiarPeriodo = (anio: number, mes: number) => { setRango(null); setBorrador({ desde: '', hasta: '' }); setErrorRango(''); q.cambiar(anio, mes, ['desde', 'hasta']); };
  const aplicarRango = (evento: FormEvent) => { evento.preventDefault(); if (!borrador.desde || !borrador.hasta || borrador.desde > borrador.hasta) { setErrorRango('Selecciona un rango válido: desde debe ser anterior o igual a hasta.'); return; } setErrorRango(''); setRango(borrador); q.actualizarParametros({ desde: borrador.desde, hasta: borrador.hasta, metrica }); };
  const volverMensual = () => { setRango(null); setBorrador({ desde: '', hasta: '' }); setErrorRango(''); q.limpiarParametros(['desde', 'hasta']); };
  const cambiarMetrica = (valor: string) => { setMetrica(valor); q.actualizarParametros({ metrica: valor }); };
  return <div className="min-h-full bg-gray-100"><EncabezadoM7 titulo="Análisis de Ventas" descripcion="Ventas definitivas, clientes y productos con segmentación definida en la ficha del cliente" regreso={q.global}/><Periodo anio={q.anio} mes={q.mes} cambiar={cambiarPeriodo} cargando={q.cargando} recargar={q.recargar}/><div className="mx-auto mt-3 max-w-7xl px-5 sm:px-8"><div className="rounded-lg border border-gray-200 bg-white p-4 shadow-sm"><ControlSegmentado etiqueta="Segmento comercial" valor={q.segmento} cambiar={q.cambiarSegmento} opciones={[{ valor: 'TODOS', etiqueta: 'Todos' }, { valor: 'B2B', etiqueta: 'B2B' }, { valor: 'B2C', etiqueta: 'B2C' }]} /></div><form onSubmit={aplicarRango} className="mt-3 rounded-lg border border-gray-200 bg-white p-4 shadow-sm"><div className="flex flex-wrap items-end gap-3"><CalendarDays className="mb-2 h-5 w-5 text-[#FE8F01]" /><label className="min-w-0 flex-1 text-xs font-semibold uppercase text-gray-500 sm:max-w-48">Desde<input aria-label="Rango desde" type="date" value={borrador.desde} onChange={evento => setBorrador(actual => ({ ...actual, desde: evento.target.value }))} className="mt-1 block w-full rounded-md border border-gray-300 px-3 py-2 text-sm font-normal text-gray-900" /></label><label className="min-w-0 flex-1 text-xs font-semibold uppercase text-gray-500 sm:max-w-48">Hasta<input aria-label="Rango hasta" type="date" value={borrador.hasta} onChange={evento => setBorrador(actual => ({ ...actual, hasta: evento.target.value }))} className="mt-1 block w-full rounded-md border border-gray-300 px-3 py-2 text-sm font-normal text-gray-900" /></label><button type="submit" disabled={q.cargando} className="rounded-md bg-[#FE8F01] px-4 py-2 text-sm font-bold text-black transition hover:bg-orange-400 disabled:opacity-50">Aplicar rango</button>{rango && <button type="button" onClick={volverMensual} className="rounded-md border border-gray-300 px-4 py-2 text-sm font-semibold text-gray-700 hover:border-[#FE8F01]">Usar mes seleccionado</button>}</div>{errorRango && <p role="alert" className="mt-3 text-sm text-red-700">{errorRango}</p>}{rango && <p role="status" className="mt-3 inline-flex rounded-full bg-orange-50 px-3 py-1 text-xs font-bold text-[#9a4f00]">Rango activo: {rango.desde} → {rango.hasta}</p>}</form></div><PdfDashboard origen="ventas" anio={q.anio} mes={q.mes} desde={rango?.desde} hasta={rango?.hasta} segmento={q.segmento} acciones={<ExportarExcelVentas anio={q.anio} mes={q.mes} desde={rango?.desde} hasta={rango?.hasta} segmento={q.segmento}/>}/>{q.error && <p role="alert" className="mx-auto mt-4 max-w-7xl border border-red-200 bg-red-50 px-5 py-3 text-red-800">{q.error}</p>}
    <main className="mx-auto max-w-7xl space-y-5 px-5 py-6 sm:px-8"><Seccion titulo="Resumen" descripcion={`Período seleccionado · segmento ${q.segmento}`}><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Tarjeta titulo="Venta neta" valor={numero(montoValor.totalClp) === null ? 'No disponible' : formatearDato(montoValor.totalClp, 'monto')} detalle={`${formatearDato(montoValor.ventasExcluidasSinTipoCambio)} venta(s) excluida(s) por falta de tipo de cambio histórico.`} estado={String(monto.estado || '')}/><Tarjeta titulo="Ventas" valor={formatearDato(cantidad.valor)} detalle="Notas de Venta definitivas." estado={String(cantidad.estado || '')}/><Tarjeta titulo="Ticket medio" valor={numero(ticketValor.totalClp) === null ? 'No disponible' : formatearDato(ticketValor.totalClp, 'monto')} detalle="Neto comparable dividido por cantidad de ventas." estado={String(ticket.estado || '')}/><Tarjeta titulo="Conversión" valor={numero(conversionValor.tasaPorcentual) === null ? 'N/A' : formatearDato(conversionValor.tasaPorcentual, 'participacionPorcentual')} detalle={`${formatearDato(conversionValor.convertidas)} de ${formatearDato(conversionValor.totalCotizaciones)} cotizaciones.`} estado={String(conversion.estado || '')}/></div>{temporal && <div className="mt-4 grid gap-3 rounded-lg bg-gray-50 p-4 sm:grid-cols-3"><div><p className="text-xs font-bold text-gray-500">MoM</p><strong>{porcentaje(temporal.mom)}</strong></div><div><p className="text-xs font-bold text-[#b85e00]">YoY</p><strong>{porcentaje(temporal.yoy)}</strong></div><div><p className="text-xs font-bold text-gray-500">Variación YTD</p><strong>{porcentaje(temporal.variacionYtd)}</strong></div></div>} {donutSegmentos.length > 0 && <div className="mt-5 grid items-center gap-5 lg:grid-cols-2"><GraficoDonut datos={donutSegmentos}/><div>{participacion.map(item => <div key={String(item.segmento)} className="flex justify-between border-b border-gray-100 py-3 text-sm"><span className="font-bold">{String(item.segmento)}</span><span className="text-right">{formatearDato(item.montoClp, 'monto')}<strong className="ml-3 text-[#b85e00]">{formatearDato(item.participacionPorcentual, 'participacionPorcentual')}</strong></span></div>)}</div></div>}</Seccion>
      <Seccion titulo="Clientes" descripcion="Participación sobre el total comparable consolidado en CLP."><div className="overflow-x-auto"><table className="w-full min-w-[620px] text-left text-sm"><thead className="bg-gray-50 text-xs uppercase text-gray-500"><tr><th className="px-3 py-3">Posición</th><th className="px-3">Cliente</th><th className="px-3 text-right">Venta neta</th><th className="px-3 text-right">Participación</th></tr></thead><tbody>{clientes.map(item => <tr key={String(item.idCliente)} className="border-b border-gray-100"><td className="px-3 py-3">{formatearDato(item.posicion)}</td><td className="px-3 font-semibold">{String(item.cliente)}</td><td className="px-3 text-right">{formatearDato(item.montoClp, 'monto')}</td><td className="px-3 text-right font-bold text-[#b85e00]">{formatearDato(item.participacionPorcentual, 'participacionPorcentual')}</td></tr>)}</tbody></table>{!q.cargando && !clientes.length && <p className="py-8 text-center text-sm text-gray-500">No hay clientes comparables para el período y segmento.</p>}</div></Seccion>
      <Seccion titulo="Productos" descripcion="Producto registrado, unidades reales y neto prorrateado sin duplicar la Nota de Venta."><div className="mb-4"><ControlSegmentado etiqueta="Métrica" valor={metrica} cambiar={cambiarMetrica} opciones={[{ valor: 'VALOR', etiqueta: 'Valor' }, { valor: 'UNIDADES', etiqueta: 'Unidades' }]} /></div><div className="grid gap-5 lg:grid-cols-[minmax(0,1fr)_minmax(0,1.2fr)]"><GraficoDonut datos={donutProductos}/><div className="overflow-x-auto"><table className="w-full min-w-[620px] text-left text-sm"><thead className="bg-gray-50 text-xs uppercase text-gray-500"><tr><th className="px-3 py-3">Producto/modelo</th><th className="px-3">Segmento</th><th className="px-3 text-right">Unidades</th><th className="px-3 text-right">Venta neta</th><th className="px-3 text-right">Participación</th></tr></thead><tbody>{productos.map(item => <tr key={`${String(item.segmento)}-${String(item.producto)}`} className="border-b border-gray-100"><td className="px-3 py-3 font-semibold">{String(item.producto)}</td><td className="px-3">{String(item.segmento || 'Sin clasificar')}</td><td className="px-3 text-right">{formatearDato(item.unidades)}</td><td className="px-3 text-right">{item.ventaNetaClp === null ? 'Excluido por falta de tipo de cambio' : formatearDato(item.ventaNetaClp, 'monto')}</td><td className="px-3 text-right font-bold text-[#b85e00]">{formatearDato(metrica === 'VALOR' ? item.participacionValorPorcentual : item.participacionUnidadesPorcentual, 'participacionPorcentual')}</td></tr>)}</tbody></table>{!q.cargando && !productos.length && <p className="py-8 text-center text-sm text-gray-500">No hay detalle comercial estructurado para el período y segmento.</p>}</div></div><p className="mt-4 text-xs leading-5 text-gray-500">{String(indicador(datos.productos).detalle || '')}</p></Seccion></main></div>;
}
