import { ExternalLink } from 'lucide-react';
import { Link, useParams } from 'react-router-dom';
import { ContenidoIndicadores, EncabezadoM7, Periodo, estadoHumano, usarConsultaM7 } from './componentes';

type Cliente={idCliente:number;nombre:string;identificador:string|null;tipoCliente:string;estado:string};
export default function ContextoClienteM7(){
 const {id}=useParams();const q=usarConsultaM7(`/dashboard-m7/clientes/${id}`);const cliente=q.datos?.cliente as Cliente|undefined;const bloques=(q.datos?.bloques as Record<string,Record<string,unknown>>)||{};const destinos=Object.entries(bloques).filter(([,bloque])=>typeof bloque.destino==='string').map(([clave,bloque])=>({clave,destino:String(bloque.destino)}));const datos=q.datos?Object.fromEntries(Object.entries(bloques).map(([clave,bloque])=>{const {destino: _destino,...contenido}=bloque;return [clave,contenido];})):null;
 return <div className="min-h-full bg-gray-50"><EncabezadoM7 titulo="Contexto de Cliente" descripcion="Resumen autorizado; los datos maestros permanecen en Clientes" regreso={q.global}/><Periodo anio={q.anio} mes={q.mes} cambiar={q.cambiar} cargando={q.cargando} recargar={q.recargar}/>{cliente&&<section className="mx-auto mt-5 max-w-7xl px-5 sm:px-8"><div className="flex flex-wrap items-center justify-between gap-4 rounded-lg border border-gray-200 bg-white p-5 shadow-sm"><div><h2 className="text-lg font-bold">{cliente.nombre}</h2><p className="text-sm text-gray-500">{cliente.tipoCliente} · {cliente.identificador||'Sin identificador'} · {estadoHumano(cliente.estado)}</p></div><div className="flex flex-wrap items-center gap-4"><Link to={String(q.datos?.destinoCliente||'/clientes')} className="inline-flex items-center gap-2 text-sm font-semibold text-primary-700">Abrir ficha del cliente<ExternalLink className="h-4 w-4"/></Link>{destinos.map(item=><Link key={item.clave} to={item.destino} className="inline-flex items-center gap-2 text-sm font-semibold text-primary-700">Abrir {item.clave==='ventas'?'Ventas':'Cuentas por cobrar'}<ExternalLink className="h-4 w-4"/></Link>)}</div></div></section>}<ContenidoIndicadores datos={datos} error={q.error} cargando={q.cargando}/></div>;
}
