import React from 'react';
import { BanknoteArrowDown, BanknoteArrowUp, BellRing, ChartNoAxesCombined, CircleAlert, FileClock, Gauge, Scale, Wallet } from 'lucide-react';
import { Link } from 'react-router-dom';
import { EncabezadoM7, EstadoDato, PdfDashboard, Periodo, estadoHumano, formatearDato, usarConsultaM7 } from './componentes';
import type { RespuestaM7 } from './componentes';

const destinos: Record<string, { titulo: string; ruta: string; icono: React.ComponentType<{ className?: string }> }> = {
  centroAtencion: { titulo: 'Centro de Atención', ruta: '/dashboard-m7/centro-atencion', icono: BellRing }, cotizacionesPendientes: { titulo: 'Cotizaciones pendientes', ruta: '/dashboard-m7/cotizaciones-pendientes', icono: FileClock },
  ventas: { titulo: 'Ventas', ruta: '/dashboard-m7/ventas', icono: ChartNoAxesCombined }, cuentasCobrar: { titulo: 'Cuentas por cobrar', ruta: '/dashboard-m7/cuentas-cobrar', icono: BanknoteArrowUp }, cuentasPagar: { titulo: 'Cuentas por pagar', ruta: '/dashboard-m7/cuentas-pagar', icono: BanknoteArrowDown }, liquidez: { titulo: 'Liquidez y flujo', ruta: '/dashboard-m7/liquidez', icono: Wallet },
  riesgoDeficit: { titulo: 'Riesgo de déficit', ruta: '/dashboard-m7/riesgo-deficit', icono: CircleAlert }, exposicionProyectos: { titulo: 'Exposición de Proyectos', ruta: '/dashboard-m7/proyectos/exposicion', icono: Gauge },
  margenProyectos: { titulo: 'Margen por proyecto', ruta: '/dashboard-m7/margen-proyectos', icono: Gauge }, resumenResultados: { titulo: 'Resumen de resultados', ruta: '/dashboard-m7/resumenes', icono: ChartNoAxesCombined }, situacionFinanciera: { titulo: 'Situación financiera', ruta: '/dashboard-m7/resumenes', icono: Scale },
  costoRemuneraciones: { titulo: 'Costo de remuneraciones', ruta: '/dashboard-m7/operacion', icono: Scale }, ordenesTrabajo: { titulo: 'Órdenes de Trabajo', ruta: '/dashboard-m7/operacion', icono: Gauge }, cargaOperacional: { titulo: 'Carga operacional', ruta: '/dashboard-m7/operacion', icono: Gauge }, instalaciones: { titulo: 'Instalaciones', ruta: '/dashboard-m7/operacion', icono: ChartNoAxesCombined }, atrasosInstalaciones: { titulo: 'Atrasos de instalaciones', ruta: '/dashboard-m7/operacion', icono: FileClock }, incidenciasRetrabajos: { titulo: 'Incidencias y retrabajos', ruta: '/dashboard-m7/operacion', icono: CircleAlert },
  exposicionCredito: { titulo: 'Exposición crediticia', ruta: '/dashboard-m7/control', icono: Gauge }, alertasCredito: { titulo: 'Alertas de crédito', ruta: '/dashboard-m7/control', icono: CircleAlert }, resumenIva: { titulo: 'IVA estimado', ruta: '/dashboard-m7/control', icono: Scale }, costosFabricacion: { titulo: 'Costos de fabricación', ruta: '/dashboard-m7/control', icono: Scale }, bloqueosEconomicos: { titulo: 'Bloqueos económicos', ruta: '/dashboard-m7/control', icono: CircleAlert }, margenInstalaciones: { titulo: 'Margen de instalaciones', ruta: '/dashboard-m7/control', icono: Gauge }, inventarioValorizado: { titulo: 'Inventario valorizado', ruta: '/dashboard-m7/control', icono: Scale }, materialesProyectoOt: { titulo: 'Materiales por Proyecto y OT', ruta: '/dashboard-m7/control', icono: Gauge }, riesgoStock: { titulo: 'Riesgo de stock', ruta: '/dashboard-m7/control', icono: CircleAlert }, rotacionInventario: { titulo: 'Rotación de inventario', ruta: '/dashboard-m7/control', icono: ChartNoAxesCombined }, comprasRecepciones: { titulo: 'Compras y recepciones', ruta: '/dashboard-m7/control', icono: FileClock },
};
const clavesEjecutivas = ['liquidez', 'cuentasCobrar', 'cuentasPagar', 'ventas', 'cotizacionesPendientes'];
const clavesContextuales = ['centroAtencion', 'riesgoDeficit', 'margenProyectos', 'exposicionProyectos', 'exposicionCredito', 'resumenIva'];
const entradaIndicador = (bloque: RespuestaM7) => Object.entries(bloque).find(([, valor]) => valor && typeof valor === 'object' && 'estado' in (valor as object)) as [string, { estado?: string; valor?: unknown; detalle?: string }] | undefined;
const primerIndicador = (bloque: RespuestaM7) => entradaIndicador(bloque)?.[1];
const valorResumen = (bloque: RespuestaM7) => {
  const entrada = entradaIndicador(bloque); const indicador = entrada?.[1]; const valor = indicador?.valor;
  if (typeof valor === 'number') return formatearDato(valor, entrada?.[0] || 'valor');
  if (Array.isArray(valor) && valor.length) { const fila = valor[0] as Record<string, unknown>; const campo = ['liquidez', 'monto', 'saldo', 'cantidad'].find(clave => typeof fila?.[clave] === 'number'); return campo ? `${fila.moneda ? `${fila.moneda} ` : ''}${formatearDato(fila[campo], campo)}` : `${valor.length} registros`; }
  if (valor && typeof valor === 'object') { const objeto = valor as Record<string, unknown>; const campo = ['totalClp', 'cantidad', 'monto', 'saldo'].find(clave => typeof objeto[clave] === 'number'); if (campo) return formatearDato(objeto[campo], campo); const porMoneda = objeto.porMoneda as Array<Record<string, unknown>> | undefined; if (porMoneda?.length) return `${porMoneda[0].moneda || ''} ${formatearDato(porMoneda[0].monto, 'monto')}`.trim(); }
  return estadoHumano(indicador?.estado || bloque.estado);
};

export default function PanelGeneralM7({ compacto = false }: { compacto?: boolean }) {
  const consulta = usarConsultaM7('/dashboard-m7', true); const bloques = (consulta.datos?.bloques || {}) as Record<string, RespuestaM7>;
  const disponibles = Object.entries(bloques).filter(([clave]) => destinos[clave]);
  const destacadas = compacto ? clavesEjecutivas.flatMap(clave => bloques[clave] ? [[clave, bloques[clave]] as [string, RespuestaM7]] : []) : [];
  const detalle = compacto ? clavesContextuales.flatMap(clave => bloques[clave] ? [[clave, bloques[clave]] as [string, RespuestaM7]] : []) : disponibles;
  const Tarjeta = ({ clave, bloque, principal = false }: { clave: string; bloque: RespuestaM7; principal?: boolean }) => { const destino = destinos[clave]; const Icono = destino.icono; const resumen = primerIndicador(bloque); return <Link to={`${destino.ruta}?anio=${consulta.anio}&mes=${consulta.mes}`} className={`group rounded-lg border border-gray-200 bg-white p-5 shadow-sm transition hover:border-primary-300 hover:shadow-md ${principal ? 'min-h-40' : ''}`}><div className="flex items-center justify-between"><span className="rounded-lg bg-orange-50 p-2.5 text-primary-700"><Icono className="h-5 w-5" /></span><EstadoDato estado={bloque.estado || resumen?.estado} compacto /></div><h2 className="mt-4 text-base font-bold text-gray-950 group-hover:text-primary-700">{destino.titulo}</h2>{principal && <p className="mt-2 text-2xl font-bold text-gray-950">{valorResumen(bloque)}</p>}<p className="mt-1 line-clamp-2 text-sm leading-5 text-gray-500">{resumen?.detalle || 'Abrir análisis del período'}</p><span className="mt-4 inline-block text-sm font-semibold text-primary-700">Ver detalle</span></Link>; };
  return <div className="min-h-full bg-gray-50"><EncabezadoM7 titulo={compacto ? 'Dashboard Financiero' : 'Resumen financiero'} descripcion={compacto ? 'Visión ejecutiva de liquidez, cartera, ventas y riesgos' : 'Indicadores y análisis disponibles para el período seleccionado'} /><Periodo anio={consulta.anio} mes={consulta.mes} cambiar={consulta.cambiar} cargando={consulta.cargando} recargar={consulta.recargar} />
    <PdfDashboard origen="panel" anio={consulta.anio} mes={consulta.mes}/>
    {consulta.error && <div className="border-y border-red-200 bg-red-50 px-5 py-4 text-red-800">{consulta.error}</div>}
    <main className="mx-auto max-w-7xl px-5 py-6 sm:px-8">{compacto && destacadas.length > 0 && <section><h2 className="mb-4 text-lg font-bold text-gray-950">Indicadores principales</h2><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{destacadas.map(([clave, bloque]) => <Tarjeta key={clave} clave={clave} bloque={bloque} principal />)}</div></section>}<section className={compacto && destacadas.length ? 'mt-8' : ''}><div className="mb-4 flex items-center justify-between"><h2 className="text-lg font-bold text-gray-950">{compacto ? 'Riesgos y análisis' : 'Análisis disponibles'}</h2>{compacto && <Link to={`/dashboard-m7?anio=${consulta.anio}&mes=${consulta.mes}`} className="text-sm font-semibold text-primary-700 hover:underline">Ver todos los análisis</Link>}</div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{detalle.map(([clave, bloque]) => <Tarjeta key={clave} clave={clave} bloque={bloque} />)}{!consulta.cargando && !Object.keys(bloques).length && !consulta.error && <p className="col-span-full rounded-lg border border-dashed border-gray-300 bg-white py-10 text-center text-sm text-gray-500">No hay bloques habilitados para esta cuenta.</p>}</div></section></main>
  </div>;
}
