import { useEffect, useState } from 'react';
import { Factory, RefreshCw, UserCheck } from 'lucide-react';
import { usarSesion } from '../../seguridad/Sesion';

type Usuario={id:string;nombre:string};
type Tarea={id:string;titulo:string|null;estado:string|null;prioridad:string|null;idOrdenTrabajo:string|null;asignados:Usuario[]};
type Ejecucion={id:string;fecha:string;cantidad:string|null;unidad:string|null;tarea:{titulo:string|null;idOrdenTrabajo:string|null};ejecutor:Usuario|null};
const api=async(ruta:string,opciones?:RequestInit)=>{const r=await fetch(`/api/finanzas${ruta}`,{...opciones,credentials:'same-origin'});const d=await r.json();if(!r.ok)throw new Error(d.error||'No fue posible completar la operación');return d};

export default function ProduccionTerreno(){
 const {sesion}=usarSesion();const puede207=Boolean(sesion?.permisos.includes('CU207')),puede209=Boolean(sesion?.permisos.includes('CU209'));
 const [orden,setOrden]=useState(''),[tareas,setTareas]=useState<Tarea[]>([]),[usuarios,setUsuarios]=useState<Usuario[]>([]),[seleccion,setSeleccion]=useState<Record<string,string>>({}),[ejecuciones,setEjecuciones]=useState<Ejecucion[]>([]),[error,setError]=useState(''),[mensaje,setMensaje]=useState('');
 const cargarPendientes=async()=>{if(puede209)setEjecuciones(await api('/terreno/ejecuciones/pendientes'))};
 useEffect(()=>{void Promise.all([puede207?api('/terreno/usuarios').then(setUsuarios):Promise.resolve(),cargarPendientes()]).catch(e=>setError(e.message))},[puede207,puede209]);
 const cargarTareas=async()=>{if(!orden)return;setError('');try{setTareas(await api(`/terreno/ordenes-trabajo/${orden}/tareas-produccion`))}catch(e){setError((e as Error).message)}};
 const asignar=async(tarea:Tarea)=>{const id=seleccion[tarea.id];if(!id){setError('Seleccione un trabajador');return}try{await api(`/terreno/tareas-produccion/${tarea.id}/asignaciones`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({idsUsuarios:[id],prioridad:tarea.prioridad})});setMensaje('Asignación actualizada');await cargarTareas()}catch(e){setError((e as Error).message)}};
 const validar=async(id:string,decision:string)=>{try{await api(`/terreno/ejecuciones/${id}/validacion`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({decision})});setMensaje('Ejecución revisada');await cargarPendientes()}catch(e){setError((e as Error).message)}};
 return <div className="min-h-full bg-gray-50 p-5 lg:p-8"><div className="mx-auto max-w-6xl"><header className="mb-6 flex items-center justify-between"><div><p className="text-sm font-semibold text-primary-600">Terreno</p><h1 className="flex items-center gap-2 text-2xl font-bold"><Factory className="h-6 w-6"/>Producción</h1></div><button title="Actualizar" onClick={()=>void Promise.all([cargarTareas(),cargarPendientes()])} className="rounded border bg-white p-2.5"><RefreshCw className="h-4 w-4"/></button></header>{error&&<p className="mb-4 border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</p>}{mensaje&&<p className="mb-4 border border-green-200 bg-green-50 p-3 text-sm text-green-800">{mensaje}</p>}{puede207&&<section className="mb-6 border-y bg-white p-4"><h2 className="mb-3 font-bold">Asignar tareas operacionales</h2><div className="mb-4 flex gap-2"><input value={orden} onChange={e=>setOrden(e.target.value)} placeholder="ID Orden de Trabajo" className="rounded border p-2.5"/><button onClick={()=>void cargarTareas()} className="rounded bg-black px-4 py-2 text-white">Consultar</button></div>{tareas.map(t=><div key={t.id} className="flex flex-wrap items-center justify-between gap-3 border-t py-3"><div><strong>{t.titulo||`Tarea ${t.id}`}</strong><div className="text-sm text-gray-500">{t.asignados.map(u=>u.nombre).join(', ')||'Sin asignar'} · {t.prioridad||'Sin prioridad'}</div></div><div className="flex gap-2"><select value={seleccion[t.id]||''} onChange={e=>setSeleccion({...seleccion,[t.id]:e.target.value})} className="rounded border p-2"><option value="">Trabajador</option>{usuarios.map(u=><option key={u.id} value={u.id}>{u.nombre}</option>)}</select><button title="Reemplazar asignación" onClick={()=>void asignar(t)} className="rounded border p-2"><UserCheck className="h-4 w-4"/></button></div></div>)}</section>}{puede209&&<section className="border-y bg-white p-4"><h2 className="mb-3 font-bold">Validación productiva pendiente</h2>{ejecuciones.map(e=><div key={e.id} className="flex flex-wrap items-center justify-between gap-3 border-t py-3"><div><strong>{e.tarea?.titulo||`Ejecución ${e.id}`}</strong><div className="text-sm text-gray-500">{e.ejecutor?.nombre||'Sin ejecutor'} · {e.cantidad===null?'Sin cantidad':`${e.cantidad} ${e.unidad}`}</div></div><div className="flex gap-2">{['validada','devuelta','rechazada'].map(d=><button key={d} onClick={()=>void validar(e.id,d)} className="rounded border px-3 py-2 capitalize">{d}</button>)}</div></div>)}{!ejecuciones.length&&<p className="text-sm text-gray-500">No hay ejecuciones pendientes.</p>}</section>}</div></div>;
}
