import { useEffect, useState } from 'react';
import { BadgeDollarSign, BriefcaseBusiness, Layers3, Plus, RefreshCw } from 'lucide-react';
import { solicitarFinanzas } from '../../api/finanzas';
import { usarSesion } from '../../seguridad/Sesion';

type Esquema = { id:number; codigo:string; nombre:string; descripcion:string|null; estado:string; vigenciaDesde:string; vigenciaHasta:string|null; cargos:Array<{cargo:string; activa:boolean}> };
type Haber = { id:number; codigo:string|null; nombre:string; estado:string; configuraciones:Array<{id:number; modalidad:string; valor:number|null; vigenciaDesde:string; vigenciaHasta:string|null; esExcepcion:boolean}> };
type Tarifa = { id:number; modalidad:string; valor:number|null; reglaTipo:string|null; referencia:string|null; unidad:string|null; tipoAplicacion:'global'|'por_unidad'|null; vigenciaDesde:string; vigenciaHasta:string|null; esExcepcion:boolean; estadoRevision:string; causaBloqueo:string|null };
type Catalogo = { id:number; nombre:string };

async function json(ruta:string, opciones?:RequestInit) { const respuesta=await solicitarFinanzas(ruta,opciones); const cuerpo=await respuesta.json(); if(!respuesta.ok) throw new Error(cuerpo.error||'No fue posible completar la operación'); return cuerpo; }

export default function EsquemasRemuneracionales() {
  const { sesion }=usarSesion();
  const puede=(cu:string)=>Boolean(sesion?.permisos.includes(cu));
  const puedeCU162=puede('CU162');
  const puedeTarifas=puede('CU163')||puede('CU164');
  const puedeEsquemas=['CU162','CU163','CU164'].some(puede);
  const puedeHaberes=['CU165','CU166'].some(puede);
  const [esquemas,setEsquemas]=useState<Esquema[]>([]); const [haberes,setHaberes]=useState<Haber[]>([]); const [cargos,setCargos]=useState<Catalogo[]>([]); const [tarifas,setTarifas]=useState<Tarifa[]>([]);
  const [seleccionado,setSeleccionado]=useState(''); const [version,setVersion]=useState(0); const [mensaje,setMensaje]=useState(''); const [error,setError]=useState('');
  const [esquema,setEsquema]=useState({codigo:'',nombre:'',descripcion:'',vigenciaDesde:'',vigenciaHasta:''});
  const [cargo,setCargo]=useState({idCargo:'',vigenciaDesde:'',vigenciaHasta:''});
  const [tarifa,setTarifa]=useState({modalidad:'FIJO',valor:'',reglaTipo:'',referencia:'',tipoAplicacion:'',unidad:'',vigenciaDesde:'',vigenciaHasta:'',esExcepcion:false});
  const [haber,setHaber]=useState({codigo:'',nombre:'',descripcion:'',modalidad:'FIJO',valor:'',reglaTipo:'',vigenciaDesde:'',vigenciaHasta:''});
  const [config,setConfig]=useState({modalidad:'FIJO',valor:'',reglaTipo:'',vigenciaDesde:'',vigenciaHasta:'',esExcepcion:false});

  useEffect(()=>{ const controlador=new AbortController(); const tareas:Promise<void>[]=[]; if(puedeEsquemas)tareas.push(json('/esquemas-remuneracionales',{signal:controlador.signal}).then(setEsquemas)); if(puedeHaberes)tareas.push(json('/haberes',{signal:controlador.signal}).then(setHaberes)); if(puedeCU162)tareas.push(json('/esquemas-remuneracionales/catalogos/cargos',{signal:controlador.signal}).then(setCargos)); Promise.all(tareas).catch(causa=>{if(!controlador.signal.aborted)setError(causa.message)}); return()=>controlador.abort(); },[puedeCU162,puedeEsquemas,puedeHaberes,version]);
  useEffect(()=>{ if(!seleccionado||!puedeTarifas)return; json(`/esquemas-remuneracionales/${seleccionado}/tarifas`).then(setTarifas).catch(causa=>setError(causa.message)); },[puedeTarifas,seleccionado,version]);
  const enviar=async(ruta:string,body:unknown,method='POST')=>{setError('');setMensaje('');try{await json(ruta,{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});setMensaje('Cambios guardados.');setVersion(v=>v+1);}catch(causa){setError((causa as Error).message)}};

  return <div className="min-h-full bg-slate-50 p-5 lg:p-8"><div className="mx-auto max-w-7xl">
    <header className="mb-6 flex items-center justify-between gap-4"><div><p className="text-sm font-semibold text-primary-600">Remuneraciones</p><h1 className="text-2xl font-bold text-gray-900">Esquemas, Tarifas y Haberes</h1></div><button onClick={()=>setVersion(v=>v+1)} title="Actualizar" className="rounded-md border bg-white p-2.5"><RefreshCw className="h-4 w-4"/></button></header>
    {error&&<div className="mb-4 border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}{mensaje&&<div className="mb-4 border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-700">{mensaje}</div>}

    {puedeEsquemas&&<section className="border-y bg-white px-5 py-5"><div className="mb-4 flex items-center gap-2"><Layers3 className="h-5 w-5 text-primary-600"/><h2 className="font-bold">Esquemas y defaults por Cargo</h2></div>
      {puede('CU162')&&<div className="mb-5 grid gap-3 border-b pb-5 md:grid-cols-6"><input placeholder="Código" value={esquema.codigo} onChange={e=>setEsquema({...esquema,codigo:e.target.value})} className="rounded-md border p-2.5"/><input placeholder="Nombre" value={esquema.nombre} onChange={e=>setEsquema({...esquema,nombre:e.target.value})} className="rounded-md border p-2.5 md:col-span-2"/><input type="date" value={esquema.vigenciaDesde} onChange={e=>setEsquema({...esquema,vigenciaDesde:e.target.value})} className="rounded-md border p-2.5"/><input type="date" value={esquema.vigenciaHasta} onChange={e=>setEsquema({...esquema,vigenciaHasta:e.target.value})} className="rounded-md border p-2.5"/><button onClick={()=>void enviar('/esquemas-remuneracionales',esquema)} className="flex items-center justify-center gap-2 rounded-md bg-primary-600 px-4 text-sm font-semibold text-white"><Plus className="h-4 w-4"/>Crear</button></div>}
      {!esquemas.length?<p className="py-8 text-center text-sm text-gray-500">No existen esquemas remuneracionales.</p>:<div className="overflow-x-auto"><table className="w-full min-w-[760px] text-sm"><thead className="border-b bg-gray-50 text-left"><tr><th className="p-3">Código</th><th>Nombre</th><th>Vigencia</th><th>Estado</th><th>Defaults Cargo</th><th></th></tr></thead><tbody>{esquemas.map(e=><tr key={e.id} className="border-b"><td className="p-3 font-mono">{e.codigo}</td><td>{e.nombre}</td><td>{e.vigenciaDesde.slice(0,10)} → {e.vigenciaHasta?.slice(0,10)||'abierta'}</td><td className="capitalize">{e.estado}</td><td>{e.cargos.map(c=>c.cargo).join(', ')||'Sin default'}</td><td><button onClick={()=>setSeleccionado(String(e.id))} className="font-semibold text-primary-700">Tarifas</button></td></tr>)}</tbody></table></div>}
      {puede('CU162')&&seleccionado&&<div className="mt-5 grid gap-3 border-t pt-5 md:grid-cols-4"><select value={cargo.idCargo} onChange={e=>setCargo({...cargo,idCargo:e.target.value})} className="rounded-md border p-2.5"><option value="">Cargo para default</option>{cargos.map(c=><option key={c.id} value={c.id}>{c.nombre}</option>)}</select><input type="date" value={cargo.vigenciaDesde} onChange={e=>setCargo({...cargo,vigenciaDesde:e.target.value})} className="rounded-md border p-2.5"/><input type="date" value={cargo.vigenciaHasta} onChange={e=>setCargo({...cargo,vigenciaHasta:e.target.value})} className="rounded-md border p-2.5"/><button onClick={()=>void enviar(`/esquemas-remuneracionales/${seleccionado}/cargos`,cargo)} className="rounded-md bg-gray-900 text-sm font-semibold text-white">Asignar default</button></div>}
    </section>}

    {(puede('CU163')||puede('CU164'))&&<section className="mt-6 border-y bg-white px-5 py-5"><div className="mb-4 flex items-center gap-2"><BriefcaseBusiness className="h-5 w-5 text-primary-600"/><h2 className="font-bold">Tarifas, reglas y revisión inicial</h2></div>
      {!seleccionado?<p className="py-6 text-sm text-gray-500">Selecciona un esquema para administrar sus configuraciones.</p>:<>{puede('CU163')&&<div className="mb-5 grid gap-3 border-b pb-5 md:grid-cols-9"><select value={tarifa.modalidad} onChange={e=>setTarifa({...tarifa,modalidad:e.target.value})} className="rounded-md border p-2.5"><option>FIJO</option><option>PORCENTAJE</option><option>REGLA</option></select><input type="number" min="0" placeholder="Valor" value={tarifa.valor} onChange={e=>setTarifa({...tarifa,valor:e.target.value})} className="rounded-md border p-2.5"/><select value={tarifa.tipoAplicacion} onChange={e=>setTarifa({...tarifa,tipoAplicacion:e.target.value,unidad:e.target.value==='global'?'':tarifa.unidad})} className="rounded-md border p-2.5"><option value="">Aplicación pendiente</option><option value="global">Global</option><option value="por_unidad">Por unidad</option></select><input disabled={tarifa.tipoAplicacion!=='por_unidad'} placeholder="Unidad" value={tarifa.unidad} onChange={e=>setTarifa({...tarifa,unidad:e.target.value})} className="rounded-md border p-2.5 disabled:bg-gray-100"/><input placeholder="Tipo regla" value={tarifa.reglaTipo} onChange={e=>setTarifa({...tarifa,reglaTipo:e.target.value})} className="rounded-md border p-2.5"/><input placeholder="Referencia" value={tarifa.referencia} onChange={e=>setTarifa({...tarifa,referencia:e.target.value})} className="rounded-md border p-2.5"/><input type="date" value={tarifa.vigenciaDesde} onChange={e=>setTarifa({...tarifa,vigenciaDesde:e.target.value})} className="rounded-md border p-2.5"/><input type="date" value={tarifa.vigenciaHasta} onChange={e=>setTarifa({...tarifa,vigenciaHasta:e.target.value})} className="rounded-md border p-2.5"/><button onClick={()=>void enviar(`/esquemas-remuneracionales/${seleccionado}/tarifas`,tarifa)} className="rounded-md bg-gray-900 text-sm font-semibold text-white">Agregar</button></div>}
      <div className="space-y-2">{tarifas.map(t=><div key={t.id} className="grid gap-2 border-b py-3 text-sm md:grid-cols-[1fr_1fr_1fr_auto]"><span>{t.modalidad} {t.valor??t.reglaTipo??'incompleta'} · {t.tipoAplicacion==='global'?'Global':t.tipoAplicacion==='por_unidad'?`Por ${t.unidad}`:'Aplicación pendiente'}</span><span>{t.vigenciaDesde.slice(0,10)} → {t.vigenciaHasta?.slice(0,10)||'abierta'}</span><span className={t.estadoRevision==='bloqueada'?'text-red-700':'capitalize'}>{t.estadoRevision}{t.causaBloqueo?`: ${t.causaBloqueo}`:''}</span>{puede('CU164')&&t.estadoRevision==='pendiente'&&<button onClick={()=>void enviar(`/esquemas-remuneracionales/${seleccionado}/tarifas/${t.id}/revisar`,{})} className="font-semibold text-primary-700">Revisar</button>}</div>)}</div></>}
    </section>}

    {puedeHaberes&&<section className="mt-6 border-y bg-white px-5 py-5"><div className="mb-4 flex items-center gap-2"><BadgeDollarSign className="h-5 w-5 text-primary-600"/><h2 className="font-bold">Haberes</h2></div>
      {puede('CU165')&&<div className="mb-5 grid gap-3 border-b pb-5 md:grid-cols-7"><input placeholder="Código" value={haber.codigo} onChange={e=>setHaber({...haber,codigo:e.target.value})} className="rounded-md border p-2.5"/><input placeholder="Nombre" value={haber.nombre} onChange={e=>setHaber({...haber,nombre:e.target.value})} className="rounded-md border p-2.5"/><select value={haber.modalidad} onChange={e=>setHaber({...haber,modalidad:e.target.value})} className="rounded-md border p-2.5"><option>FIJO</option><option>PORCENTAJE</option><option>REGLA</option></select><input type="number" min="0" placeholder="Valor" value={haber.valor} onChange={e=>setHaber({...haber,valor:e.target.value})} className="rounded-md border p-2.5"/><input type="date" value={haber.vigenciaDesde} onChange={e=>setHaber({...haber,vigenciaDesde:e.target.value})} className="rounded-md border p-2.5"/><input type="date" value={haber.vigenciaHasta} onChange={e=>setHaber({...haber,vigenciaHasta:e.target.value})} className="rounded-md border p-2.5"/><button onClick={()=>void enviar('/haberes',haber)} className="rounded-md bg-primary-600 text-sm font-semibold text-white">Crear HABER</button></div>}
      {!haberes.length?<p className="py-8 text-center text-sm text-gray-500">No existen conceptos HABER.</p>:<div className="space-y-3">{haberes.map(h=><div key={h.id} className="border-b pb-3"><div className="flex justify-between text-sm"><strong>{h.codigo} · {h.nombre}</strong><span className="capitalize">{h.estado}</span></div><p className="mt-1 text-xs text-gray-500">{h.configuraciones.length} configuración(es) conservadas</p>{puede('CU166')&&<div className="mt-3 grid gap-2 md:grid-cols-6"><select value={config.modalidad} onChange={e=>setConfig({...config,modalidad:e.target.value})} className="rounded-md border p-2"><option>FIJO</option><option>PORCENTAJE</option><option>REGLA</option></select><input type="number" min="0" placeholder="Valor" value={config.valor} onChange={e=>setConfig({...config,valor:e.target.value})} className="rounded-md border p-2"/><input type="date" value={config.vigenciaDesde} onChange={e=>setConfig({...config,vigenciaDesde:e.target.value})} className="rounded-md border p-2"/><input type="date" value={config.vigenciaHasta} onChange={e=>setConfig({...config,vigenciaHasta:e.target.value})} className="rounded-md border p-2"/><label className="flex items-center gap-2 text-xs"><input type="checkbox" checked={config.esExcepcion} onChange={e=>setConfig({...config,esExcepcion:e.target.checked})}/>Excepción</label><button onClick={()=>void enviar(`/haberes/${h.id}/configuraciones`,config)} className="rounded-md bg-gray-900 text-xs font-semibold text-white">Nueva vigencia</button></div>}</div>)}</div>}
    </section>}
  </div></div>;
}
