-- TEMPORAL_M5_DB_PATCH
-- Soporte mínimo para CU91-CU94. No registra documentos, obligaciones ni aprobaciones de excedentes.

ALTER TABLE finanzas.orden_compra_servicio_m5
  ADD COLUMN monto_autorizado_original numeric(14,2);

UPDATE finanzas.orden_compra_servicio_m5
SET monto_autorizado_original = monto_autorizado;

ALTER TABLE finanzas.orden_compra_servicio_m5
  ALTER COLUMN monto_autorizado_original SET NOT NULL,
  ADD CONSTRAINT chk_ocs_m5_monto_original CHECK (monto_autorizado_original > 0);

ALTER TABLE finanzas.historial_orden_compra_servicio_m5
  ADD COLUMN motivo text;

CREATE TABLE finanzas.ajuste_orden_compra_servicio_m5 (
  id_ajuste_ocs_m5 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_ocs_m5 integer NOT NULL,
  campo character varying(80) NOT NULL,
  valor_anterior text,
  valor_propuesto text,
  motivo text NOT NULL,
  solicitado_por bigint NOT NULL,
  fecha_solicitud timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  estado character varying(20) NOT NULL DEFAULT 'pendiente',
  confirmado_por bigint,
  fecha_confirmacion timestamp with time zone,
  CONSTRAINT chk_ajuste_ocs_m5_estado CHECK (estado IN ('pendiente', 'confirmado')),
  CONSTRAINT fk_ajuste_ocs_m5_ocs FOREIGN KEY (id_ocs_m5)
    REFERENCES finanzas.orden_compra_servicio_m5(id_orden_compra_servicio_m5) ON DELETE RESTRICT,
  CONSTRAINT fk_ajuste_ocs_m5_solicitante FOREIGN KEY (solicitado_por)
    REFERENCES terreno.usuario(usuario_id_usuario) ON DELETE RESTRICT,
  CONSTRAINT fk_ajuste_ocs_m5_confirmante FOREIGN KEY (confirmado_por)
    REFERENCES terreno.usuario(usuario_id_usuario) ON DELETE RESTRICT
);

CREATE INDEX idx_ajuste_ocs_m5_ocs_estado
  ON finanzas.ajuste_orden_compra_servicio_m5 (id_ocs_m5, estado);

CREATE TABLE finanzas.efecto_financiero_ocs_m5 (
  id_efecto_financiero_ocs_m5 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_ocs_m5 integer NOT NULL,
  tipo_efecto character varying(40) NOT NULL,
  referencia character varying(150),
  monto_documentado numeric(14,2) NOT NULL DEFAULT 0,
  fecha_registro timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT chk_efecto_ocs_m5_tipo CHECK (tipo_efecto IN ('documento_definitivo', 'obligacion', 'otro')),
  CONSTRAINT chk_efecto_ocs_m5_monto CHECK (monto_documentado >= 0),
  CONSTRAINT fk_efecto_ocs_m5_ocs FOREIGN KEY (id_ocs_m5)
    REFERENCES finanzas.orden_compra_servicio_m5(id_orden_compra_servicio_m5) ON DELETE RESTRICT
);

CREATE INDEX idx_efecto_ocs_m5_ocs
  ON finanzas.efecto_financiero_ocs_m5 (id_ocs_m5);

COMMENT ON COLUMN finanzas.orden_compra_servicio_m5.monto_autorizado_original IS
  'TEMPORAL_M5_DB_PATCH: monto inicial inmutable para trazabilidad CU91';
COMMENT ON TABLE finanzas.ajuste_orden_compra_servicio_m5 IS
  'TEMPORAL_M5_DB_PATCH: preparación y confirmación acotada de ajustes OCS CU91';
COMMENT ON TABLE finanzas.efecto_financiero_ocs_m5 IS
  'TEMPORAL_M5_DB_PATCH: marcador de efectos para integrar documentos y obligaciones desde CU97+';
