import { useEffect, useState } from 'react';
import { ClipboardPenLine, ListTodo, PlayCircle, RefreshCw } from 'lucide-react';
import { Link } from 'react-router-dom';
import { usarSesion } from '../../seguridad/Sesion';

type Tarea={id:string;titulo:string|null;descripcion:string|null;estado:string|null;urgencia:string|null;fecha:string|null;bloqueHorario:string|null;visita:{id:string;tipoServicio:string|null;obra:{nombre:string|null;referencia:string|null;cliente:{rut:string;nombre:string|null}|null;especificacion:{modelo:string|null;zona:string|null}|null}|null}|null;especificacion:{modelo:string|null;zona:string|null}|null};
const json=async(ruta:string,opciones?:RequestInit)=>{const respuesta=await fetch(`/api/finanzas${ruta}`,{...opciones,credentials:'same-origin'});const dato=await respuesta.json();if(!respuesta.ok)throw new Error(dato.error||'No fue posible completar la operación');return dato};

export default function MisTareasTerreno(){
 const {sesion}=usarSesion();const puedeLevantar=Boolean(sesion?.permisos.some(permiso=>['CU202','CU203','CU204'].includes(permiso))),puedeEjecutar=Boolean(sesion?.permisos.includes('CU208'));
 const [tareas,setTareas]=useState<Tarea[]>([]),[error,setError]=useState(''),[mensaje,setMensaje]=useState('');
 const cargar=async()=>{setError('');try{setTareas(await json('/terreno/mis-tareas'))}catch(e){setError((e as Error).message)}};
 useEffect(()=>{void cargar()},[]);
 const ejecutar=async(id:string)=>{setError('');setMensaje('');try{await json(`/terreno/tareas-produccion/${id}/ejecuciones`,{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});setMensaje('Ejecución registrada y enviada a validación')}catch(e){setError((e as Error).message)}};
 return <div className="min-h-full bg-gray-50 p-5 lg:p-8"><div className="mx-auto max-w-6xl"><header className="mb-6 flex items-center justify-between gap-3"><div><p className="text-sm font-semibold text-primary-600">Terreno</p><h1 className="flex items-center gap-2 text-2xl font-bold"><ListTodo className="h-6 w-6"/>Mis tareas asignadas</h1></div><button title="Actualizar" onClick={()=>void cargar()} className="rounded border bg-white p-2.5"><RefreshCw className="h-4 w-4"/></button></header>{error&&<p className="mb-4 border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</p>}{mensaje&&<p className="mb-4 border border-green-200 bg-green-50 p-3 text-sm text-green-800">{mensaje}</p>}<div className="overflow-x-auto border-y bg-white"><table className="w-full min-w-[920px] text-left text-sm"><thead className="border-b text-xs uppercase text-gray-500"><tr><th className="p-3">Tarea</th><th className="p-3">Estado</th><th className="p-3">Fecha</th><th className="p-3">Visita</th><th className="p-3">Obra / cliente / puerta</th><th className="p-3 text-right">Acción</th></tr></thead><tbody>{tareas.map(t=><tr key={t.id} className="border-b"><td className="p-3"><strong>{t.titulo||`Tarea ${t.id}`}</strong><div className="text-gray-500">{t.descripcion||t.urgencia||'Sin detalle'}</div></td><td className="p-3 font-semibold">{t.estado||'Sin estado'}</td><td className="p-3">{t.fecha?new Date(t.fecha).toLocaleDateString('es-CL'):'Sin fecha'}</td><td className="p-3">{t.visita?.tipoServicio||'Producción'}</td><td className="p-3">{t.visita?.obra?.nombre||t.visita?.obra?.referencia||'Sin obra'}<div className="text-gray-500">{t.visita?.obra?.cliente?.nombre||t.visita?.obra?.cliente?.rut||'Sin cliente'} · {t.visita?.obra?.especificacion?.modelo||t.especificacion?.modelo||'Sin puerta'}</div></td><td className="p-3 text-right"><div className="flex justify-end gap-2">{puedeEjecutar&&<button title="Registrar ejecución terminada" onClick={()=>void ejecutar(t.id)} className="inline-flex items-center gap-2 rounded border px-3 py-2 font-semibold"><PlayCircle className="h-4 w-4"/>Ejecutar</button>}{puedeLevantar&&t.visita&&<Link title="Levantamiento técnico" to={`/terreno/tareas/${t.id}/levantamiento`} className="inline-flex items-center gap-2 rounded border px-3 py-2 font-semibold"><ClipboardPenLine className="h-4 w-4"/>Levantamiento</Link>}</div></td></tr>)}</tbody></table>{!tareas.length&&<p className="p-6 text-center text-sm text-gray-500">No tiene tareas asignadas.</p>}</div></div></div>;
}
