import { confirmarAccion, solicitarTexto } from '../../components/DialogosSistema';
import { useEffect, useState } from 'react';
import { ClipboardCheck, ClipboardPlus, Eye, MapPinned, RefreshCw, UserCheck, X } from 'lucide-react';
import { usarSesion } from '../../seguridad/Sesion';

type Usuario={id:string;acceso:string|null;nombre:string};
type Obra={id:string;nombre:string|null;referencia:string|null;direccion:string|null;comuna:string|null;region:string|null;cliente:{rut:string;nombre:string|null}|null;especificacion:{id:string;modelo:string|null;zona:string|null;observaciones:string|null}|null};
type Visita={id:string;tipoServicio:string|null;fecha:string|null;bloqueHorario:string|null;prioridad:string|null;estado:string|null;observaciones:string|null;responsable:Usuario|null;obra:Obra|null};
type Preparacion={visita:Visita;checklist:{id:string;item:string|null;marcado:boolean|null;noMarcado:boolean|null}|null;ordenesTrabajo:Array<{id:string;estado:string|null;reservas:Array<{id:string;materialSku:string|null;cantidad:string|null;estado:string|null}>}>};
const vacio={idObra:'',tipoServicio:'',fecha:'',bloqueHorario:'',prioridad:'',observaciones:''};
const json=async(ruta:string,opciones?:RequestInit)=>{const respuesta=await fetch(`/api/finanzas${ruta}`,{...opciones,credentials:'same-origin'});const dato=await respuesta.json();if(!respuesta.ok)throw new Error(dato.error||'No fue posible completar la operación');return dato};

export default function GestionTerreno(){
 const {sesion}=usarSesion();const puede199=Boolean(sesion?.permisos.includes('CU199')),puede200=Boolean(sesion?.permisos.includes('CU200')),puede210=Boolean(sesion?.permisos.includes('CU210')),puede211=Boolean(sesion?.permisos.includes('CU211'));
 const [visitas,setVisitas]=useState<Visita[]>([]),[obras,setObras]=useState<Obra[]>([]),[usuarios,setUsuarios]=useState<Usuario[]>([]),[detalle,setDetalle]=useState<Visita|null>(null);
 const [formulario,setFormulario]=useState(vacio),[asignaciones,setAsignaciones]=useState<Record<string,string>>({}),[mostrarAlta,setMostrarAlta]=useState(false),[preparacion,setPreparacion]=useState<Preparacion|null>(null),[error,setError]=useState(''),[mensaje,setMensaje]=useState(''),[ocupado,setOcupado]=useState(false);
 const cargar=async()=>{const tareas:Promise<unknown>[]=[json('/terreno/visitas').then(setVisitas)];if(puede199)tareas.push(json('/terreno/obras').then(setObras));if(puede200)tareas.push(json('/terreno/usuarios').then(setUsuarios));await Promise.all(tareas)};
 useEffect(()=>{void cargar().catch(e=>setError(e.message))},[puede199,puede200]);
 const crear=async()=>{setError('');setMensaje('');setOcupado(true);try{await json('/terreno/visitas',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(formulario)});setFormulario(vacio);setMostrarAlta(false);setMensaje('Visita creada');await cargar()}catch(e){setError((e as Error).message)}finally{setOcupado(false)}};
 const asignar=async(id:string)=>{const idUsuario=asignaciones[id];if(!idUsuario){setError('Seleccione un responsable');return}setError('');setMensaje('');setOcupado(true);try{await json(`/terreno/visitas/${id}/responsable`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({idUsuario})});setMensaje('Responsable actualizado');await cargar()}catch(e){setError((e as Error).message)}finally{setOcupado(false)}};
 const abrir=async(id:string)=>{setError('');try{setDetalle(await json(`/terreno/visitas/${id}`))}catch(e){setError((e as Error).message)}};
 const preparar=async(id:string)=>{setError('');try{setPreparacion(await json(`/terreno/visitas/${id}/preparacion-salida`))}catch(e){setError((e as Error).message)}};
 const registrarResultado=async(id:string)=>{const resultado=await solicitarTexto('Resultado real del servicio');if(!resultado)return;const observaciones=await solicitarTexto('Observaciones')||'';const finalizada=await confirmarAccion('¿El servicio quedó finalizado?');try{await json(`/terreno/visitas/${id}/resultado`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({resultado,observaciones,finalizada})});setMensaje(finalizada?'Visita cerrada':'Visita mantenida pendiente');await cargar()}catch(e){setError((e as Error).message)}};
 return <div className="min-h-full bg-gray-50 p-4 sm:p-6 lg:p-8"><div className="mx-auto max-w-7xl">
  <header className="mb-6 flex flex-col items-stretch justify-between gap-4 sm:flex-row sm:items-center"><div className="min-w-0"><p className="text-sm font-semibold text-primary-600">Terreno</p><h1 className="flex items-center gap-2 break-words text-2xl font-bold"><MapPinned className="h-6 w-6 shrink-0"/>Gestor de visitas</h1></div><div className="flex w-full gap-2 sm:w-auto">{puede199&&<button onClick={()=>setMostrarAlta(true)} className="flex min-w-0 flex-1 items-center justify-center gap-2 rounded bg-black px-4 py-2 text-white sm:flex-none"><ClipboardPlus className="h-4 w-4 shrink-0"/>Nueva visita</button>}<button title="Actualizar" onClick={()=>void cargar()} className="shrink-0 rounded border bg-white p-2.5"><RefreshCw className="h-4 w-4"/></button></div></header>
  {error&&<p className="mb-4 border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</p>}{mensaje&&<p className="mb-4 border border-green-200 bg-green-50 p-3 text-sm text-green-800">{mensaje}</p>}
  {mostrarAlta&&<section className="mb-5 rounded-lg border bg-white p-4 sm:p-5"><div className="mb-4 flex items-center justify-between gap-3"><h2 className="break-words font-bold">Crear visita/ticket</h2><button title="Cerrar" onClick={()=>setMostrarAlta(false)} className="shrink-0 rounded border p-2"><X className="h-4 w-4"/></button></div><div className="grid gap-3 md:grid-cols-2 lg:grid-cols-3"><select aria-label="Obra" value={formulario.idObra} onChange={e=>setFormulario({...formulario,idObra:e.target.value})} className="min-w-0 rounded border p-2.5"><option value="">Seleccionar obra</option>{obras.map(o=><option key={o.id} value={o.id}>{o.nombre||o.referencia||`Obra ${o.id}`} · {o.cliente?.nombre||o.cliente?.rut||'Sin cliente'}</option>)}</select><input placeholder="Tipo de servicio" maxLength={50} value={formulario.tipoServicio} onChange={e=>setFormulario({...formulario,tipoServicio:e.target.value})} className="min-w-0 rounded border p-2.5"/><input aria-label="Fecha" type="date" value={formulario.fecha} onChange={e=>setFormulario({...formulario,fecha:e.target.value})} className="min-w-0 rounded border p-2.5"/><input aria-label="Bloque horario" type="time" value={formulario.bloqueHorario} onChange={e=>setFormulario({...formulario,bloqueHorario:e.target.value})} className="min-w-0 rounded border p-2.5"/><input placeholder="Prioridad" value={formulario.prioridad} onChange={e=>setFormulario({...formulario,prioridad:e.target.value})} className="min-w-0 rounded border p-2.5"/><textarea placeholder="Observaciones" maxLength={1000} value={formulario.observaciones} onChange={e=>setFormulario({...formulario,observaciones:e.target.value})} className="min-w-0 rounded border p-2.5 md:col-span-2"/><button disabled={ocupado||!formulario.idObra||!formulario.tipoServicio} onClick={()=>void crear()} className="rounded bg-primary-600 px-4 py-2 text-white disabled:opacity-40">Crear visita</button></div></section>}
  <div className="max-w-full overflow-x-auto rounded-lg border bg-white"><table className="w-full min-w-[900px] text-left text-sm"><thead className="border-b text-xs uppercase text-gray-500"><tr><th className="p-3">Visita</th><th className="p-3">Obra / cliente</th><th className="p-3">Fecha</th><th className="p-3">Estado</th><th className="p-3">Responsable</th><th className="p-3 text-right">Acciones</th></tr></thead><tbody>{visitas.map(v=><tr key={v.id} className="border-b"><td className="p-3"><strong>{v.tipoServicio||`Visita ${v.id}`}</strong><div className="text-gray-500">{v.prioridad||'Sin prioridad'}</div></td><td className="p-3">{v.obra?.nombre||v.obra?.referencia||'Sin obra'}<div className="text-gray-500">{v.obra?.cliente?.nombre||v.obra?.cliente?.rut||'Sin cliente derivable'}</div></td><td className="p-3">{v.fecha?new Date(v.fecha).toLocaleDateString('es-CL'):'Sin fecha'}</td><td className="p-3 font-semibold">{v.estado||'Sin estado'}</td><td className="p-3">{puede200?<div className="flex gap-2"><select aria-label={`Responsable visita ${v.id}`} value={asignaciones[v.id]||v.responsable?.id||''} onChange={e=>setAsignaciones({...asignaciones,[v.id]:e.target.value})} className="min-w-44 rounded border p-2"><option value="">Seleccionar</option>{usuarios.map(u=><option key={u.id} value={u.id}>{u.nombre}</option>)}</select><button title="Asignar responsable" disabled={ocupado} onClick={()=>void asignar(v.id)} className="rounded border p-2"><UserCheck className="h-4 w-4"/></button></div>:v.responsable?.nombre||'Sin asignar'}</td><td className="whitespace-nowrap p-3 text-right"><div className="flex justify-end gap-2"><button title="Ver detalle" onClick={()=>void abrir(v.id)} className="rounded border p-2"><Eye className="h-4 w-4"/></button>{puede210&&<button title="Preparar salida" onClick={()=>void preparar(v.id)} className="rounded border p-2"><ClipboardCheck className="h-4 w-4"/></button>}{puede211&&<button title="Registrar resultado" onClick={()=>void registrarResultado(v.id)} className="rounded border px-3 py-2 text-sm font-semibold">Resultado</button>}</div></td></tr>)}</tbody></table>{!visitas.length&&<p className="p-6 text-center text-sm text-gray-500">No existen visitas registradas.</p>}</div>
  {detalle&&<section className="mt-5 rounded-lg border bg-white p-4 sm:p-5"><div className="mb-4 flex items-center justify-between gap-3"><h2 className="break-all font-bold">Detalle visita {detalle.id}</h2><button title="Cerrar detalle" onClick={()=>setDetalle(null)} className="shrink-0 rounded border p-2"><X className="h-4 w-4"/></button></div><dl className="grid gap-4 text-sm md:grid-cols-2 lg:grid-cols-4"><div><dt className="text-gray-500">Servicio</dt><dd>{detalle.tipoServicio}</dd></div><div><dt className="text-gray-500">Responsable</dt><dd>{detalle.responsable?.nombre||'Sin asignar'}</dd></div><div><dt className="text-gray-500">Obra</dt><dd>{detalle.obra?.nombre||detalle.obra?.referencia}</dd></div><div><dt className="text-gray-500">Ubicación</dt><dd>{[detalle.obra?.direccion,detalle.obra?.comuna,detalle.obra?.region].filter(Boolean).join(', ')||'Sin ubicación'}</dd></div><div><dt className="text-gray-500">Cliente</dt><dd>{detalle.obra?.cliente?.nombre||detalle.obra?.cliente?.rut||'Sin cliente'}</dd></div><div><dt className="text-gray-500">Puerta</dt><dd>{detalle.obra?.especificacion?`${detalle.obra.especificacion.modelo||'Sin modelo'} · ${detalle.obra.especificacion.zona||'Sin zona'}`:'Sin especificación'}</dd></div><div className="md:col-span-2"><dt className="text-gray-500">Observaciones</dt><dd>{detalle.observaciones||'Sin observaciones'}</dd></div></dl></section>}
  {preparacion&&<section className="mt-5 rounded-lg border bg-white p-4 sm:p-5"><div className="mb-4 flex items-center justify-between gap-3"><h2 className="min-w-0 break-words font-bold">Preparación de salida · visita {preparacion.visita.id}</h2><button title="Cerrar preparación" onClick={()=>setPreparacion(null)} className="shrink-0 rounded border p-2"><X className="h-4 w-4"/></button></div><p className="mb-3 break-words text-sm">{preparacion.visita.obra?.nombre||'Sin obra'} · {preparacion.visita.responsable?.nombre||'Sin responsable'} · {preparacion.visita.fecha?new Date(preparacion.visita.fecha).toLocaleDateString('es-CL'):'Sin fecha'}</p><div className="mb-4 border p-3 text-sm"><strong>Checklist:</strong> {preparacion.checklist?.item||'No disponible'}</div>{preparacion.ordenesTrabajo.map(ot=><div key={ot.id} className="border-t py-3 text-sm"><strong>OT {ot.id} · {ot.estado}</strong>{ot.reservas.map(r=><div key={r.id} className="break-words text-gray-600">{r.materialSku||'Material sin SKU'} · {r.cantidad||'Cantidad no informada'} · {r.estado||'Sin estado'}</div>)}</div>)}{!preparacion.ordenesTrabajo.length&&<p className="text-sm text-gray-500">No existe OT ni preparación de inventario asociada a esta puerta.</p>}</section>}
 </div></div>;
}
