import { useEffect, useState } from 'react';
import { Anchor, CheckCircle2, Link2, LockKeyhole, PackagePlus, Pencil, Plus, RefreshCw, RotateCcw } from 'lucide-react';
import { solicitarFinanzas } from '../../api/finanzas';
import { usarSesion } from '../../seguridad/Sesion';

interface Costo {id:number;tipo:string;fuente:string;monto:number;moneda:string;descripcion:string|null}
interface Envio {id:number;referencia:string;fecha:string;descripcion:string|null;estado:string;ordenes:Array<{id:number;tipo:string;idOcs:number|null}>;costos:Costo[];costoFinanciero:{totalesPorMoneda:Array<{moneda:string;monto:number}>;totalClp:number|null;conversionPendiente:boolean};historial:Array<{id:number;evento:string;detalle:string;usuario:string;fecha:string}>}
interface Catalogos {monedas:Array<{id:number;codigo:string}>;ordenes:Array<{id:number;referencia:string|null;monto:number}>}
const hoy=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Santiago',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
async function api(ruta:string,opciones?:RequestInit){const respuesta=await solicitarFinanzas(ruta,opciones);const resultado=await respuesta.json();if(!respuesta.ok)throw new Error(resultado.error||'No fue posible completar la operación');return resultado}
const json=(method:string,body?:unknown):RequestInit=>({method,headers:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});
const leerArchivo=async(file:File)=>new Promise<string>((resolver,rechazar)=>{const lector=new FileReader();lector.onload=()=>resolver(String(lector.result));lector.onerror=()=>rechazar(new Error('No fue posible leer el archivo'));lector.readAsDataURL(file)});
const etiquetaEstado=(estado:string)=>({abierto:'Abierto',en_revision:'En revisión',cerrado_financieramente:'Cerrado financieramente'}[estado]||estado);

export default function EnviosImportaciones(){
 const {sesion}=usarSesion();const puede=(cu:string)=>!!sesion?.permisos.includes(cu);const [envios,setEnvios]=useState<Envio[]>([]);const [seleccionado,setSeleccionado]=useState<Envio|null>(null);const [catalogos,setCatalogos]=useState<Catalogos>({monedas:[],ordenes:[]});const [nuevo,setNuevo]=useState({referencia:'',fecha:hoy(),descripcion:''});const [costo,setCosto]=useState({tipoCosto:'flete',fuente:'directo',idMoneda:'',monto:'',idFuente:'',descripcion:''});const [archivo,setArchivo]=useState<File|null>(null);const [error,setError]=useState('');const [mensaje,setMensaje]=useState('');
 const cargar=async(id?:number)=>{try{const lista:Envio[]=await api('/envios-importaciones');setEnvios(lista);const objetivo=id||seleccionado?.id;if(objetivo)setSeleccionado(lista.find(item=>item.id===objetivo)||null);setError('')}catch(e){setError((e as Error).message)}};
 useEffect(()=>{let activo=true;void Promise.all([api('/envios-importaciones'),api('/documentos-proveedor-catalogos')]).then(([lista,catalogosIniciales])=>{if(activo){setEnvios(lista);setCatalogos(catalogosIniciales)}}).catch(e=>{if(activo)setError(e.message)});return()=>{activo=false}},[]);
 const ejecutar=async(ruta:string,cuerpo:unknown={},method='POST')=>{try{const resultado=await api(ruta,json(method,cuerpo));setMensaje('Operación completada.');setError('');await cargar(resultado.id||seleccionado?.id);return resultado}catch(e){setError((e as Error).message)}};
 const crear=async()=>{const resultado=await ejecutar('/envios-importaciones',nuevo);if(resultado){setNuevo({referencia:'',fecha:hoy(),descripcion:''});setSeleccionado(resultado)}};
 const asociar=()=>{if(!seleccionado)return;const idOcs=Number(window.prompt(`ID OCS (${catalogos.ordenes.map(o=>o.id).join(', ')})`));if(idOcs)void ejecutar(`/envios-importaciones/${seleccionado.id}/ordenes-compra`,{tipoOrden:'OCS',idOcs})};
 const registrarCosto=async()=>{if(!seleccionado)return;const cuerpo:Record<string,unknown>={tipoCosto:costo.tipoCosto,fuente:costo.fuente,descripcion:costo.descripcion};if(costo.fuente==='directo'){if(!archivo)return setError('Selecciona el respaldo del costo directo');Object.assign(cuerpo,{idMoneda:Number(costo.idMoneda),monto:Number(costo.monto),nombreArchivo:archivo.name,contenido:await leerArchivo(archivo)})}else if(costo.fuente==='obligacion')cuerpo.idObligacion=Number(costo.idFuente);else cuerpo.idComision=Number(costo.idFuente);const resultado=await ejecutar(`/envios-importaciones/${seleccionado.id}/costos`,cuerpo);if(resultado){setCosto({tipoCosto:'flete',fuente:'directo',idMoneda:'',monto:'',idFuente:'',descripcion:''});setArchivo(null)}};
 const editarCosto=(item:Costo)=>{if(!seleccionado||item.fuente!=='directo')return;const monto=Number(window.prompt('Monto corregido',String(item.monto)));const motivo=window.prompt('Motivo obligatorio');if(monto&&motivo)void ejecutar(`/envios-importaciones/${seleccionado.id}/costos/${item.id}`,{monto,motivo},'PUT')};
 const transicion=(accion:string)=>{if(!seleccionado)return;const cuerpo=accion==='reabrir'?{motivo:window.prompt('Motivo obligatorio de reapertura')}:{};if(accion==='reabrir'&&!cuerpo.motivo)return;void ejecutar(`/envios-importaciones/${seleccionado.id}/${accion}`,cuerpo)};
 const editable=seleccionado&&['abierto','en_revision'].includes(seleccionado.estado);
 return <div className="min-h-full bg-slate-50 p-5 lg:p-8"><div className="mx-auto max-w-7xl"><header className="mb-6 flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-3"><Anchor className="h-7 w-7 text-primary-600"/><div><p className="text-sm font-semibold text-primary-600">Proveedores y egresos</p><h1 className="text-2xl font-bold">Envíos e importaciones</h1></div></div><button title="Actualizar" onClick={()=>void cargar()} className="border p-2"><RefreshCw className="h-5 w-5"/></button></header>{(error||mensaje)&&<div className={`mb-4 border p-3 text-sm ${error?'border-red-200 bg-red-50 text-red-700':'border-emerald-200 bg-emerald-50 text-emerald-700'}`}>{error||mensaje}</div>}
 {puede('CU143')&&<section className="mb-6 grid gap-3 border-y bg-white p-4 md:grid-cols-[1fr_180px_1.5fr_auto]"><input value={nuevo.referencia} onChange={e=>setNuevo({...nuevo,referencia:e.target.value})} placeholder="Referencia" className="border p-2"/><input type="date" value={nuevo.fecha} onChange={e=>setNuevo({...nuevo,fecha:e.target.value})} className="border p-2"/><input value={nuevo.descripcion} onChange={e=>setNuevo({...nuevo,descripcion:e.target.value})} placeholder="Descripción" className="border p-2"/><button disabled={!nuevo.referencia||!nuevo.fecha} onClick={()=>void crear()} className="flex items-center justify-center gap-2 bg-primary-600 px-4 py-2 text-white disabled:opacity-40"><PackagePlus className="h-4 w-4"/>Crear</button></section>}
 <div className="grid gap-6 lg:grid-cols-[320px_1fr]"><section className="border bg-white"><h2 className="border-b p-4 font-semibold">Registros</h2><div className="divide-y">{envios.map(item=><button key={item.id} onClick={()=>setSeleccionado(item)} className={`w-full p-4 text-left ${seleccionado?.id===item.id?'bg-primary-50':''}`}><strong>{item.referencia}</strong><p className="text-sm text-gray-500">{new Date(item.fecha).toLocaleDateString('es-CL')} · {etiquetaEstado(item.estado)}</p></button>)}{!envios.length&&<p className="p-8 text-center text-gray-500">No hay envíos registrados.</p>}</div></section>
 {seleccionado?<div className="space-y-5"><section className="border bg-white p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs uppercase text-gray-500">Envío {seleccionado.id}</p><h2 className="text-xl font-bold">{seleccionado.referencia}</h2><p className="text-sm text-gray-500">{seleccionado.descripcion||'Sin descripción'} · {etiquetaEstado(seleccionado.estado)}</p></div><div className="flex flex-wrap gap-2">{editable&&puede('CU144')&&<button onClick={asociar} className="flex items-center gap-2 border px-3 py-2"><Link2 className="h-4 w-4"/>Asociar OCS</button>}{seleccionado.estado==='abierto'&&puede('CU146')&&<button onClick={()=>transicion('pasar-revision')} className="flex items-center gap-2 border px-3 py-2"><CheckCircle2 className="h-4 w-4"/>Pasar a revisión</button>}{seleccionado.estado==='en_revision'&&puede('CU147')&&<button onClick={()=>transicion('cerrar-financieramente')} className="flex items-center gap-2 bg-primary-600 px-3 py-2 text-white"><LockKeyhole className="h-4 w-4"/>Cerrar financieramente</button>}{seleccionado.estado==='cerrado_financieramente'&&puede('CU148')&&<button onClick={()=>transicion('reabrir')} className="flex items-center gap-2 border px-3 py-2"><RotateCcw className="h-4 w-4"/>Reabrir</button>}</div></div><div className="mt-4 flex flex-wrap gap-4 border-t pt-4 text-sm">{seleccionado.costoFinanciero.totalesPorMoneda.map(t=><strong key={t.moneda}>{t.moneda} {t.monto.toLocaleString('es-CL')}</strong>)}<span>Total CLP: {seleccionado.costoFinanciero.totalClp?.toLocaleString('es-CL')||'no disponible'}</span></div></section>
 <section className="border bg-white"><h3 className="border-b p-4 font-semibold">Órdenes asociadas</h3><div className="flex flex-wrap gap-2 p-4">{seleccionado.ordenes.map(o=><span key={o.id} className="border px-3 py-2 text-sm">{o.tipo}-{o.idOcs}</span>)}{!seleccionado.ordenes.length&&<span className="text-sm text-gray-500">Sin órdenes asociadas.</span>}</div></section>
 {editable&&puede('CU145')&&<section className="grid gap-3 border-y bg-white p-4 md:grid-cols-3"><select value={costo.tipoCosto} onChange={e=>setCosto({...costo,tipoCosto:e.target.value})} className="border p-2"><option value="flete">Flete</option><option value="seguro">Seguro</option><option value="aduana">Aduana</option><option value="agente_aduanas">Agente de aduanas</option><option value="arancel">Arancel</option><option value="otro">Otro</option></select><select value={costo.fuente} onChange={e=>setCosto({...costo,fuente:e.target.value})} className="border p-2"><option value="directo">Costo directo</option><option value="obligacion">Obligación existente</option><option value="comision">Comisión bancaria</option></select>{costo.fuente==='directo'?<><select value={costo.idMoneda} onChange={e=>setCosto({...costo,idMoneda:e.target.value})} className="border p-2"><option value="">Moneda</option>{catalogos.monedas.map(m=><option key={m.id} value={m.id}>{m.codigo}</option>)}</select><input type="number" min="0.01" value={costo.monto} onChange={e=>setCosto({...costo,monto:e.target.value})} placeholder="Monto" className="border p-2"/><input type="file" onChange={e=>setArchivo(e.target.files?.[0]||null)} className="border p-2 text-sm"/></>:<input type="number" value={costo.idFuente} onChange={e=>setCosto({...costo,idFuente:e.target.value})} placeholder={costo.fuente==='obligacion'?'ID obligación':'ID comisión'} className="border p-2"/>}<input value={costo.descripcion} onChange={e=>setCosto({...costo,descripcion:e.target.value})} placeholder="Descripción" className="border p-2"/><button onClick={()=>void registrarCosto()} className="flex items-center justify-center gap-2 bg-primary-600 px-4 py-2 text-white"><Plus className="h-4 w-4"/>Agregar costo</button></section>}
 <section className="border bg-white"><h3 className="border-b p-4 font-semibold">Costos</h3><div className="divide-y">{seleccionado.costos.map(item=><div key={item.id} className="flex flex-wrap items-center justify-between gap-3 p-4 text-sm"><span><strong className="capitalize">{item.tipo}</strong> · {item.fuente} · {item.moneda} {item.monto.toLocaleString('es-CL')}</span>{item.fuente==='directo'&&editable&&puede('CU145')&&<button title="Corregir costo" onClick={()=>editarCosto(item)} className="p-2"><Pencil className="h-4 w-4"/></button>}</div>)}</div></section>
 <section className="border bg-white"><h3 className="border-b p-4 font-semibold">Historial de estados y operaciones</h3><div className="divide-y">{seleccionado.historial.map(item=><div key={item.id} className="p-4 text-sm"><strong>{item.evento.replaceAll('_',' ')}</strong><span className="ml-2 text-gray-500">{new Date(item.fecha).toLocaleString('es-CL')}</span><p className="mt-1 break-words text-gray-600">{item.detalle}</p></div>)}</div></section></div>:<section className="border bg-white p-10 text-center text-gray-500">Selecciona un envío.</section>}</div></div></div>;
}
