import { useEffect, useState } from 'react';
import { Check, Pencil, Plus, RefreshCw, Settings2, X } from 'lucide-react';
import { solicitarFinanzas } from '../../api/finanzas';
import { usarSesion } from '../../seguridad/Sesion';

interface Categoria {id:number;nombre:string;activo:boolean;historial:Array<{id_historial_categoria_m5:number;nombre_anterior:string|null;nombre_nuevo:string|null;activo_anterior:boolean|null;activo_nuevo:boolean|null;fecha_hora:string}>}
interface Reclasificacion {id:number;idDocumento:number;estado:string;montoTotal:number;montoReferenciaClp:number;umbralSnapshotClp:number;motivo:string;solicitadoPor:string;fecha:string}
async function api(ruta:string,opciones?:RequestInit){const r=await solicitarFinanzas(ruta,opciones);const j=await r.json();if(!r.ok)throw new Error(j.error||'No fue posible completar la operación');return j}
const json=(method:string,body?:unknown):RequestInit=>({method,headers:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});

export default function CategoriasEgreso(){
 const {sesion}=usarSesion();const puede=(cu:string)=>!!sesion?.permisos.includes(cu);const puedeAprobar=puede('CU136');const puedeConfigurar=puede('CU137');const [categorias,setCategorias]=useState<Categoria[]>([]);const [solicitudes,setSolicitudes]=useState<Reclasificacion[]>([]);const [nombre,setNombre]=useState('');const [umbral,setUmbral]=useState('0');const [error,setError]=useState('');const [mensaje,setMensaje]=useState('');
 const cargar=async()=>{try{const tareas=[api('/categorias-egreso').then(setCategorias)];if(puede('CU136'))tareas.push(api('/reclasificaciones').then(setSolicitudes));if(puede('CU137'))tareas.push(api('/configuracion/umbral-reclasificacion').then(r=>setUmbral(String(r.montoClp))));await Promise.all(tareas)}catch(e){setError((e as Error).message)}};
 useEffect(()=>{let activo=true;const tareas=[api('/categorias-egreso').then(r=>{if(activo)setCategorias(r)})];if(puedeAprobar)tareas.push(api('/reclasificaciones').then(r=>{if(activo)setSolicitudes(r)}));if(puedeConfigurar)tareas.push(api('/configuracion/umbral-reclasificacion').then(r=>{if(activo)setUmbral(String(r.montoClp))}));void Promise.all(tareas).catch(e=>{if(activo)setError((e as Error).message)});return()=>{activo=false}},[puedeAprobar,puedeConfigurar]);
 const ejecutar=async(ruta:string,opciones:RequestInit,exito:string)=>{try{await api(ruta,opciones);setMensaje(exito);setError('');await cargar()}catch(e){setError((e as Error).message)}};
 const crear=()=>{if(nombre.trim())void ejecutar('/categorias-egreso',json('POST',{nombre}),'Categoría creada').then(()=>setNombre(''))};
 const editar=(categoria:Categoria)=>{const nuevo=window.prompt('Nuevo nombre',categoria.nombre);if(nuevo&&nuevo.trim()!==categoria.nombre)void ejecutar(`/categorias-egreso/${categoria.id}`,json('PUT',{nombre:nuevo,motivo:'Actualización de catálogo'}),'Categoría actualizada')};
 const resolver=(item:Reclasificacion,aprobar:boolean)=>{const motivo=aprobar?undefined:window.prompt('Motivo del rechazo');if(!aprobar&&!motivo)return;void ejecutar(`/reclasificaciones/${item.id}/${aprobar?'aprobar':'rechazar'}`,json('POST',{motivo}),aprobar?'Reclasificación aprobada':'Reclasificación rechazada')};
 return <div className="min-h-full bg-slate-50 p-5 lg:p-8"><div className="mx-auto max-w-7xl"><header className="mb-6 flex items-center justify-between"><div><p className="text-sm font-semibold text-primary-600">Proveedores y egresos</p><h1 className="text-2xl font-bold">Categorías y reclasificaciones</h1></div><button title="Actualizar" onClick={()=>void cargar()} className="border p-2"><RefreshCw className="h-5 w-5"/></button></header>{(error||mensaje)&&<div className={`mb-4 border p-3 text-sm ${error?'border-red-200 bg-red-50 text-red-700':'border-emerald-200 bg-emerald-50 text-emerald-700'}`}>{error||mensaje}</div>}
 {puede('CU134')&&<section className="mb-6 border bg-white"><div className="flex flex-wrap gap-3 border-b p-4"><input value={nombre} onChange={e=>setNombre(e.target.value)} placeholder="Nueva categoría" className="min-w-56 flex-1 border p-2"/><button disabled={!nombre.trim()} onClick={crear} className="flex items-center gap-2 bg-primary-600 px-4 py-2 text-white disabled:opacity-40"><Plus className="h-4 w-4"/>Crear</button></div><div className="divide-y">{categorias.map(c=><div key={c.id} className="flex items-center justify-between gap-3 p-4"><div><strong>{c.nombre}</strong><p className="text-xs text-gray-500">{c.activo?'Activa':'Inactiva'} · {c.historial.length} cambios</p></div><div className="flex gap-1"><button title="Renombrar" onClick={()=>editar(c)} className="p-2"><Pencil className="h-4 w-4"/></button><button title={c.activo?'Desactivar':'Activar'} onClick={()=>void ejecutar(`/categorias-egreso/${c.id}/${c.activo?'desactivar':'activar'}`,json('POST',{motivo:c.activo?'Desactivación de catálogo':'Reactivación de catálogo'}),c.activo?'Categoría desactivada':'Categoría reactivada')} className={c.activo?'p-2 text-red-700':'p-2 text-emerald-700'}>{c.activo?<X className="h-4 w-4"/>:<Check className="h-4 w-4"/>}</button></div></div>)}</div></section>}
 {puede('CU137')&&<section className="mb-6 flex flex-wrap items-end gap-3 border bg-white p-4"><label className="min-w-60 flex-1 text-sm font-medium">Umbral de reclasificación CLP<input type="number" min="0" step="0.01" value={umbral} onChange={e=>setUmbral(e.target.value)} className="mt-1 w-full border p-2"/></label><button onClick={()=>void ejecutar('/configuracion/umbral-reclasificacion',json('PUT',{montoClp:Number(umbral)}),'Umbral actualizado')} className="flex items-center gap-2 bg-primary-600 px-4 py-2 text-white"><Settings2 className="h-4 w-4"/>Guardar</button></section>}
 {puede('CU136')&&<section className="border bg-white"><h2 className="border-b p-4 font-semibold">Solicitudes de reclasificación</h2><div className="divide-y">{solicitudes.map(s=><div key={s.id} className="flex flex-wrap items-center justify-between gap-3 p-4 text-sm"><div><strong>Solicitud {s.id} · Documento {s.idDocumento}</strong><p className="text-gray-500">CLP {s.montoReferenciaClp.toLocaleString('es-CL')} · umbral {s.umbralSnapshotClp.toLocaleString('es-CL')} · {s.estado}</p><p>{s.motivo}</p></div>{s.estado==='pendiente'&&<div className="flex gap-2"><button onClick={()=>resolver(s,false)} className="border border-red-300 px-3 py-2 text-red-700">Rechazar</button><button onClick={()=>resolver(s,true)} className="bg-emerald-700 px-3 py-2 text-white">Aprobar</button></div>}</div>)}{!solicitudes.length&&<p className="p-8 text-center text-gray-500">No hay solicitudes.</p>}</div></section>}
 </div></div>;
}
