import { useEffect, useState } from 'react';
import { BookOpenCheck, Calculator, FileClock, Landmark, Plus, RefreshCw, WalletCards } from 'lucide-react';
import { solicitarFinanzas } from '../../api/finanzas';
import { usarSesion } from '../../seguridad/Sesion';

type Parametro={id:number;codigo:string;tipo:string;nombre:string;valor:number|null;unidad:string|null;vigenciaDesde:string;vigenciaHasta:string|null;fuente:string|null;referencia:string|null;estado:string};
type Tramo={id:number;orden:number;limiteDesde:number;limiteHasta:number|null;factor:number;rebaja:number;unidad:string;vigenciaDesde:string;vigenciaHasta:string|null};
type Concepto={id:number;codigo:string|null;nombre:string;naturaleza:string;estado:string;configuraciones:unknown[]};
type Politica={id:number;estado:string;criterioDescriptivo:string|null;vigenciaDesde:string;vigenciaHasta:string|null;ejecutaTratamiento:boolean};
type Medio={id:number;codigo:string|null;nombre:string;descripcion:string|null;estado:string;requiereRespaldo:boolean|null};

async function json(ruta:string,opciones?:RequestInit){const respuesta=await solicitarFinanzas(ruta,opciones);const cuerpo=await respuesta.json();if(!respuesta.ok)throw new Error(cuerpo.error||'No fue posible completar la operación');return cuerpo;}
const hoy=()=>new Date().toISOString().slice(0,10);

export default function MantenedorParametros(){
 const {sesion}=usarSesion();const puede=(cu:string)=>Boolean(sesion?.permisos.includes(cu));
 const puede167=puede('CU167'),puede168=puede('CU168'),puede169=puede('CU169'),puede170=puede('CU170'),puede171=puede('CU171');
 const [parametros,setParametros]=useState<Parametro[]>([]),[tramos,setTramos]=useState<Tramo[]>([]),[conceptos,setConceptos]=useState<Concepto[]>([]),[prorrateos,setProrrateos]=useState<Parametro[]>([]),[politicas,setPoliticas]=useState<Politica[]>([]),[medios,setMedios]=useState<Medio[]>([]);
 const [version,setVersion]=useState(0),[error,setError]=useState(''),[mensaje,setMensaje]=useState('');
 const [parametro,setParametro]=useState({codigo:'',tipo:'LEGAL',nombre:'',valor:'',unidad:'',vigenciaDesde:hoy(),vigenciaHasta:'',fuente:'',referencia:'',estado:'pendiente'});
 const [tramo,setTramo]=useState({orden:'1',limiteDesde:'',limiteHasta:'',factor:'',rebaja:'',unidad:'',vigenciaDesde:hoy(),vigenciaHasta:'',fuente:'',referencia:''});
 const [concepto,setConcepto]=useState({codigo:'',nombre:'',naturaleza:'DEDUCCION',modalidad:'',valor:'',reglaTipo:'',vigenciaDesde:hoy(),vigenciaHasta:''});
 const [prorrateo,setProrrateo]=useState({codigo:'',nombre:'',valor:'',unidad:'',vigenciaDesde:hoy(),vigenciaHasta:'',fuente:'',referencia:'',estado:'pendiente'});
 const [politica,setPolitica]=useState({estado:'pendiente',criterioDescriptivo:'',vigenciaDesde:hoy(),vigenciaHasta:'',fuente:'',referencia:''});
 const [medio,setMedio]=useState({codigo:'',nombre:'',descripcion:'',requiereRespaldo:false});
 const [configuracionLegacy,setConfiguracionLegacy]=useState<Record<number,{codigo:string;requiereRespaldo:boolean}>>({});
 const enviar=async(ruta:string,cuerpo:unknown,method='POST')=>{setError('');setMensaje('');try{await json(ruta,{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(cuerpo)});setMensaje('Cambios guardados.');setVersion(v=>v+1);}catch(causa){setError((causa as Error).message)}};
 useEffect(()=>{const controlador=new AbortController();const tareas:Promise<void>[]=[];if(puede167){tareas.push(json('/parametros-remuneracionales',{signal:controlador.signal}).then(setParametros));tareas.push(json('/tramos-impuesto-renta',{signal:controlador.signal}).then(setTramos));}if(puede168)tareas.push(json('/conceptos-deduccion-aporte',{signal:controlador.signal}).then(setConceptos));if(puede169)tareas.push(json('/configuracion-prorrateo',{signal:controlador.signal}).then(setProrrateos));if(puede170)tareas.push(json('/politica-conservacion',{signal:controlador.signal}).then(setPoliticas));if(puede171)tareas.push(json('/medios-pago-remuneraciones',{signal:controlador.signal}).then(setMedios));Promise.all(tareas).catch(causa=>{if(!controlador.signal.aborted)setError(causa.message)});return()=>controlador.abort();},[version,puede167,puede168,puede169,puede170,puede171]);
 const bloque='border-y border-gray-200 bg-white px-5 py-5';const campo='rounded-md border p-2.5 text-sm';
 return <div className="min-h-full bg-slate-50 p-5 lg:p-8"><div className="mx-auto max-w-7xl">
  <header className="mb-6 flex items-center justify-between"><div><p className="text-sm font-semibold text-primary-600">Remuneraciones</p><h1 className="text-2xl font-bold">Mantenedor de Parámetros</h1></div><button title="Actualizar" onClick={()=>setVersion(v=>v+1)} className="rounded-md border bg-white p-2.5"><RefreshCw className="h-4 w-4"/></button></header>
  {error&&<p className="mb-4 border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</p>}{mensaje&&<p className="mb-4 border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-700">{mensaje}</p>}
  {puede167&&<><section className={bloque}><h2 className="mb-4 flex items-center gap-2 font-bold"><Landmark className="h-5 w-5 text-primary-600"/>Parámetros legales, previsionales y tributarios</h2><div className="grid gap-2 md:grid-cols-5"><input className={campo} placeholder="Código" value={parametro.codigo} onChange={e=>setParametro({...parametro,codigo:e.target.value})}/><select className={campo} value={parametro.tipo} onChange={e=>setParametro({...parametro,tipo:e.target.value})}><option>LEGAL</option><option>PREVISIONAL</option><option>TRIBUTARIO</option></select><input className={campo} placeholder="Nombre" value={parametro.nombre} onChange={e=>setParametro({...parametro,nombre:e.target.value})}/><input className={campo} type="number" min="0" placeholder="Valor pendiente permitido" value={parametro.valor} onChange={e=>setParametro({...parametro,valor:e.target.value})}/><input className={campo} placeholder="Unidad" value={parametro.unidad} onChange={e=>setParametro({...parametro,unidad:e.target.value})}/><input className={campo} type="date" value={parametro.vigenciaDesde} onChange={e=>setParametro({...parametro,vigenciaDesde:e.target.value})}/><input className={campo} type="date" value={parametro.vigenciaHasta} onChange={e=>setParametro({...parametro,vigenciaHasta:e.target.value})}/><input className={campo} placeholder="Fuente" value={parametro.fuente} onChange={e=>setParametro({...parametro,fuente:e.target.value})}/><input className={campo} placeholder="Referencia" value={parametro.referencia} onChange={e=>setParametro({...parametro,referencia:e.target.value})}/><button className="flex items-center justify-center gap-2 rounded-md bg-primary-600 text-sm font-semibold text-white" onClick={()=>void enviar('/parametros-remuneracionales',parametro)}><Plus className="h-4 w-4"/>Registrar</button></div><div className="mt-4 space-y-2">{!parametros.length?<p className="text-sm text-gray-500">No existen parámetros configurados.</p>:parametros.map(p=><div key={p.id} className="grid items-center gap-2 border-b py-2 text-sm md:grid-cols-5"><strong>{p.codigo} · {p.nombre}</strong><span>{p.tipo}</span><span>{p.valor??'Pendiente'} {p.unidad}</span><span>{p.vigenciaDesde.slice(0,10)} → {p.vigenciaHasta?.slice(0,10)||'abierta'}</span><button className="rounded-md border px-2 py-1" onClick={()=>void enviar(`/parametros-remuneracionales/${p.id}`,{estado:p.estado==='inactivo'?'activo':'inactivo'},'PATCH')}>{p.estado==='inactivo'?'Activar':'Desactivar'}</button></div>)}</div></section>
  <section className={`${bloque} mt-6`}><h2 className="mb-4 flex items-center gap-2 font-bold"><BookOpenCheck className="h-5 w-5 text-primary-600"/>Tramos tributarios</h2><div className="grid gap-2 md:grid-cols-6"><input className={campo} type="number" min="1" value={tramo.orden} onChange={e=>setTramo({...tramo,orden:e.target.value})}/><input className={campo} type="number" min="0" placeholder="Límite desde" value={tramo.limiteDesde} onChange={e=>setTramo({...tramo,limiteDesde:e.target.value})}/><input className={campo} type="number" min="0" placeholder="Límite hasta" value={tramo.limiteHasta} onChange={e=>setTramo({...tramo,limiteHasta:e.target.value})}/><input className={campo} type="number" min="0" placeholder="Factor" value={tramo.factor} onChange={e=>setTramo({...tramo,factor:e.target.value})}/><input className={campo} type="number" min="0" placeholder="Rebaja" value={tramo.rebaja} onChange={e=>setTramo({...tramo,rebaja:e.target.value})}/><input className={campo} placeholder="Unidad" value={tramo.unidad} onChange={e=>setTramo({...tramo,unidad:e.target.value})}/><input className={campo} type="date" value={tramo.vigenciaDesde} onChange={e=>setTramo({...tramo,vigenciaDesde:e.target.value})}/><input className={campo} type="date" value={tramo.vigenciaHasta} onChange={e=>setTramo({...tramo,vigenciaHasta:e.target.value})}/><input className={campo} placeholder="Fuente" value={tramo.fuente} onChange={e=>setTramo({...tramo,fuente:e.target.value})}/><input className={campo} placeholder="Referencia" value={tramo.referencia} onChange={e=>setTramo({...tramo,referencia:e.target.value})}/><button className="rounded-md bg-gray-900 text-sm font-semibold text-white md:col-span-2" onClick={()=>void enviar('/tramos-impuesto-renta',tramo)}>Agregar tramo</button></div><p className="mt-4 text-sm text-gray-500">{tramos.length?`${tramos.length} tramo(s) configurados.`:'No existen tramos configurados.'}</p></section></>}
  {puede168&&<section className={`${bloque} mt-6`}><h2 className="mb-4 flex items-center gap-2 font-bold"><Calculator className="h-5 w-5 text-primary-600"/>Deducciones y aportes</h2><div className="grid gap-2 md:grid-cols-7"><input className={campo} placeholder="Código" value={concepto.codigo} onChange={e=>setConcepto({...concepto,codigo:e.target.value})}/><input className={campo} placeholder="Nombre" value={concepto.nombre} onChange={e=>setConcepto({...concepto,nombre:e.target.value})}/><select className={campo} value={concepto.naturaleza} onChange={e=>setConcepto({...concepto,naturaleza:e.target.value})}><option>DEDUCCION</option><option>APORTE_EMPLEADOR</option></select><select className={campo} value={concepto.modalidad} onChange={e=>setConcepto({...concepto,modalidad:e.target.value})}><option value="">Pendiente / sin tasa configurada</option><option>FIJO</option><option>PORCENTAJE</option><option>REGLA</option></select><input className={campo} type="number" min="0" placeholder="Valor" value={concepto.valor} onChange={e=>setConcepto({...concepto,valor:e.target.value})}/><input className={campo} placeholder="Referencia de regla" value={concepto.reglaTipo} onChange={e=>setConcepto({...concepto,reglaTipo:e.target.value})}/><button className="rounded-md bg-primary-600 text-sm font-semibold text-white" onClick={()=>void enviar('/conceptos-deduccion-aporte',concepto)}>Crear concepto</button></div><div className="mt-4 space-y-2">{!conceptos.length?<p className="text-sm text-gray-500">No existen deducciones ni aportes configurados.</p>:conceptos.map(c=><div key={c.id} className="grid items-center gap-2 border-b py-2 text-sm md:grid-cols-4"><strong>{c.codigo} · {c.nombre}</strong><span>{c.naturaleza}</span><span>{c.configuraciones.length?'Configurado':'Pendiente de tasa'} · {c.estado}</span><button className="rounded-md border px-2 py-1" onClick={()=>void enviar(`/conceptos-deduccion-aporte/${c.id}`,{estado:c.estado==='inactivo'?'activo':'inactivo'},'PATCH')}>{c.estado==='inactivo'?'Activar':'Desactivar'}</button></div>)}</div></section>}
  {puede169&&<section className={`${bloque} mt-6`}><h2 className="mb-4 font-bold">Configuración de prorrateo</h2><div className="grid gap-2 md:grid-cols-7"><input className={campo} placeholder="Código" value={prorrateo.codigo} onChange={e=>setProrrateo({...prorrateo,codigo:e.target.value})}/><input className={campo} placeholder="Nombre" value={prorrateo.nombre} onChange={e=>setProrrateo({...prorrateo,nombre:e.target.value})}/><input className={campo} type="date" value={prorrateo.vigenciaDesde} onChange={e=>setProrrateo({...prorrateo,vigenciaDesde:e.target.value})}/><input className={campo} placeholder="Fuente o fundamento" value={prorrateo.fuente} onChange={e=>setProrrateo({...prorrateo,fuente:e.target.value})}/><input className={campo} placeholder="Referencia" value={prorrateo.referencia} onChange={e=>setProrrateo({...prorrateo,referencia:e.target.value})}/><select className={campo} value={prorrateo.estado} onChange={e=>setProrrateo({...prorrateo,estado:e.target.value})}><option value="pendiente">Pendiente / no configurada</option><option value="activo">Configurada sin fórmula congelada</option></select><button className="rounded-md bg-gray-900 text-sm font-semibold text-white" onClick={()=>void enviar('/configuracion-prorrateo',prorrateo)}>Guardar configuración</button></div><p className="mt-4 text-sm text-gray-500">{prorrateos.length?`${prorrateos.length} configuración(es) conservadas.`:'Prorrateo pendiente / no configurado.'}</p></section>}
  {puede170&&<section className={`${bloque} mt-6`}><h2 className="mb-4 flex items-center gap-2 font-bold"><FileClock className="h-5 w-5 text-primary-600"/>Conservación documental</h2><div className="grid gap-2 md:grid-cols-5"><select className={campo} value={politica.estado} onChange={e=>setPolitica({...politica,estado:e.target.value})}><option value="pendiente">Pendiente</option><option value="configurada">Configurada</option></select><input className={`${campo} md:col-span-2`} placeholder="Criterio descriptivo, sin ejecución automática" value={politica.criterioDescriptivo} onChange={e=>setPolitica({...politica,criterioDescriptivo:e.target.value})}/><input className={campo} type="date" value={politica.vigenciaDesde} onChange={e=>setPolitica({...politica,vigenciaDesde:e.target.value})}/><button className="rounded-md bg-gray-900 text-sm font-semibold text-white" onClick={()=>void enviar('/politica-conservacion',politica)}>Guardar política</button></div><p className="mt-4 text-sm text-gray-500">{politicas.length?`${politicas.length} política(s) registradas; ninguna ejecuta tratamiento.`:'No existe política configurada.'}</p></section>}
  {puede171&&<section className={`${bloque} mt-6`}><h2 className="mb-4 flex items-center gap-2 font-bold"><WalletCards className="h-5 w-5 text-primary-600"/>Medios de pago y respaldo</h2><div className="grid gap-2 md:grid-cols-5"><input className={campo} placeholder="Código" value={medio.codigo} onChange={e=>setMedio({...medio,codigo:e.target.value})}/><input className={campo} placeholder="Nombre" value={medio.nombre} onChange={e=>setMedio({...medio,nombre:e.target.value})}/><input className={campo} placeholder="Descripción" value={medio.descripcion} onChange={e=>setMedio({...medio,descripcion:e.target.value})}/><label className="flex items-center gap-2 rounded-md border px-3 text-sm"><input type="checkbox" checked={medio.requiereRespaldo} onChange={e=>setMedio({...medio,requiereRespaldo:e.target.checked})}/>Requiere respaldo</label><button className="rounded-md bg-primary-600 text-sm font-semibold text-white" onClick={()=>void enviar('/medios-pago-remuneraciones',medio)}>Crear medio</button></div><div className="mt-4 space-y-2">{!medios.length?<p className="text-sm text-gray-500">No existen medios de pago configurados.</p>:medios.map(m=>{const pendiente=m.codigo===null||m.requiereRespaldo===null;const edicion=configuracionLegacy[m.id]||{codigo:m.codigo||'',requiereRespaldo:false};return <div key={m.id} className="grid items-center gap-2 border-b py-2 text-sm md:grid-cols-4"><span>{m.codigo||'Legacy sin código M6'} · {m.nombre}</span><span>{m.requiereRespaldo===null?'Requisito pendiente':m.requiereRespaldo?'Con respaldo':'Sin respaldo'} · {m.estado}</span>{pendiente?<><input className={campo} placeholder="Código M6" value={edicion.codigo} onChange={e=>setConfiguracionLegacy({...configuracionLegacy,[m.id]:{...edicion,codigo:e.target.value}})}/><div className="flex gap-2"><label className="flex items-center gap-2"><input type="checkbox" checked={edicion.requiereRespaldo} onChange={e=>setConfiguracionLegacy({...configuracionLegacy,[m.id]:{...edicion,requiereRespaldo:e.target.checked}})}/>Requiere respaldo</label><button className="rounded-md border px-2 py-1" onClick={()=>void enviar(`/medios-pago-remuneraciones/${m.id}`,edicion,'PATCH')}>Configurar</button></div></>:<><button className="rounded-md border px-2 py-1" onClick={()=>void enviar(`/medios-pago-remuneraciones/${m.id}`,{requiereRespaldo:!m.requiereRespaldo},'PATCH')}>Cambiar requisito</button><button className="rounded-md border px-2 py-1" onClick={()=>void enviar(`/medios-pago-remuneraciones/${m.id}`,{estado:m.estado==='inactivo'?'activo':'inactivo'},'PATCH')}>{m.estado==='inactivo'?'Activar':'Desactivar'}</button></>}</div>})}</div></section>}
 </div></div>;
}
